### ISSUE TITLE
Checks as pure metric emitters

### ISSUE THREAD

**Issue by uppfinnarn** [loadimpact/k6#100]
Right now, we have two ways to decide if a tests is tainted: Thresholds, and Checks. The latter is rather blunt: there's a global acceptance rate (`-a`/`--acceptance`) for all checks, which defaults to 0%, and failures beyond that threshold mark the test as failed.

With #63 implemented, checks now seem rather… redundant, because you can define a threshold on the `checks` metric to do the exact same thing, with more flexibility. Unless there are any complaints, I'm just going to remove `--acceptance` along with checks' own taint logic.

**Comment by aidylewis** [comment]
Does this mean remove checks in favour or thresholds? If this is the case how would I ensure that 100% of responses === 200?

**Comment by uppfinnarn** [comment]
I'm just gonna remove non-threshold taints entirely.

**Comment by ppcano** [comment]
@uppfinnarn @ragnarlonn 

I think the guide or documentation should specifically highlight the threshold on all the `checks` case. I have always found this to be a general case. Users configure many checks but they assume a % of error to mark the test as a failure.
