### ISSUE TITLE
Allow access to "who am I" context

### ISSUE THREAD

**Issue by micsjo** [loadimpact/k6#101]
Allow the script to access context about

- vu# (or vu id)
- iteration#
- current source IP

Other relevant context data?

The reason being you can use vu# and iteration# to generate and control test data sequences. There are possibly other as well (debugging of nothing else).

**Comment by uppfinnarn** [comment]
Definitely want VU ID and iteration counter, but source IP is a deceptively difficult thing to deduce. Unless you're in a setting such as DigitalOcean where eth0's IP = public IP, you basically need to ping a server on startup and have it tell you what your source IP is…
