### ISSUE TITLE
Make absolute paths relative to main script.

### ISSUE THREAD

**Issue by ArjanvHugten** [loadimpact/k6#1026]
Might be an idea to make the absolute paths in the script relative to the main script instead of pointing to the root directory. This can be backward incompatible.

**Comment by paralectvkomodey** [comment]
Hi!

Is there any progress on this?

**Comment by MStoykov** [comment]
There has been zero work on this ... as I don't know how to make this backward compatible. As the person who has probably fixed most bugs in that area and the random amount of problems that exist there (mostly Windows centered :facepalm: ), I do think that this was probably what should've been done from the beginning. But given that this hasn't been done, and ... my work on fixing issues has shown that people do use absolute paths (again :facepalm: ) I don't think it's likely we are just going to break it.

**Comment by na--** [comment]
I agree with @MStoykov, unfortunately there's no way to implement something like this without it being a major breaking change. As a compromise, we'll likely implement functions that return the CWD and path to the executed script file: https://github.com/loadimpact/k6/issues/1320#issuecomment-767478977. Using those and [k6's `require()`](https://k6.io/docs/using-k6/javascript-compatibility-mode#%E2%9A%A0%EF%B8%8F-about-require), it should be possible to have helpers that treat absolute paths as relative from the script.
