### ISSUE TITLE
Chrome detect virus in release page

### ISSUE THREAD

**Issue by alfeg** [loadimpact/k6#1029]
Unable to download latest 0.24 release of win-x64 binary https://github.com/loadimpact/k6/releases/download/v0.24.0/k6-v0.24.0-win64.zip

Browser: Version 74.0.3729.169 (Official Build) (64-bit)
OS: Windows 10 Pro 1809 [17763.503]

Windows detect following threats:
![image](https://user-images.githubusercontent.com/118516/58202346-e438f500-7cdf-11e9-8d99-670ed1d2a94a.png)

![image](https://user-images.githubusercontent.com/118516/58202518-75a86700-7ce0-11e9-81ee-1c9fb34819ec.png)

This issue is reproduced on seveal PC that I have access to.

**Comment by na--** [comment]
What's the antivirus used on those PC? I'm a linux user, so I'd need some time to reproduce this, but VirusTotal gives clean results from most of the popular anti-virus software packages :confused: 

This is for the win64 zip file: https://www.virustotal.com/#/file/a6dc7c6fb594431d0f6819654db9e6dcb6b97b55aa3dea60610560c5fa38cd2b/detection
And this is for the exe: https://www.virustotal.com/#/file/cf173b79b1c45de483c4e8947c1c2d93574f1f549d7d321efba665c6fc080950/detection

**Comment by na--** [comment]
I was the one who built these k6 binaries for the v0.24.0 release, and I located the original files on my machine. I just compared them and they are identical to the ones in the GitHub release, so the files haven't been modified between then and now.

**Comment by alfeg** [comment]
@na-- there is no 3rd party antivirus software - only Windows Defender with latest updates.
One PC that I have access to (home one) is on Insider builds.

It's only Win-X64 version that cannot be downloaded. 

As for my opinioun - this is totally false alarm. It's seems that AI stuff is overreating on some bits in URL 

Also found a link in Defender on threat details: https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fForetype.A!ml&threatid=2147724345

**Comment by na--** [comment]
I submitted the file to Microsoft as an incorrect detection:
![Screenshot_2019-05-23 Submission details (124ac83b-193c-4301-87d7-8d34ed2c9ffa) - Microsoft Security Intelligence](https://user-images.githubusercontent.com/3336773/58236024-b341da00-7d4a-11e9-94ed-56df919bad35.png)
their online windows defender doesn't seem to consider it an issue... :confused: in any case, I'll update this issue when they update they publish their final determination

**Comment by na--** [comment]
Microsoft published their final determination, the files are clean. Here's the page:
![Screenshot_2019-05-24 Submission details (124ac83b-193c-4301-87d7-8d34ed2c9ffa) - Microsoft Security Intelligence](https://user-images.githubusercontent.com/3336773/58310739-0336a480-7e10-11e9-903d-eba754efb8e3.jpg)
@alfeg, can you update your definitions for Windows Defender like they suggest in the comments and share if the problem persists?

**Comment by alfeg** [comment]
@na--  - Confirm. 

Succesfully downloaded archive without complain from Windows Defender. Thanks.

Everything worked out without manual steps to update definitions (seems that they were uddated automatically this night)
