### ISSUE TITLE
Error when retrieving gzip encoded response

### ISSUE THREAD

**Issue by soemeier** [loadimpact/k6#1030]
I am trying to write a test that queries an url that returns gzip encoded content. Unfortunately I receive the following error:

GoError: gzip: invalid header\n\tat native\n\tat get

The response headers that my application returns are
```
Response:
HTTP/2.0 200 OK
Connection: close
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Encoding: gzip
Content-Type: application/json;charset=UTF-8
Date: Mon, 27 May 2019 09:07:44 GMT
Server: nginx/1.15.3
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Vary: accept-encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
```

Is this a bug or am I doing sth. wrong?

**Comment by MStoykov** [comment]
in this case `header` refers to the gzip header not the http one. I think you are missing some part of the error, but usually this is due to ... the body not being gzip compressed :). Can you test that you are actually getting gzip compressed body? You can use `curl` for example like:

```
$ curl --output test.gzip -X GET "https://httpbin.org/gzip"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   166  100   166    0     0     29      0  0:00:05  0:00:05 --:--:--    29
$ cat test.gzip | gunzip
{
  "gzipped": true,
  "headers": {
    "Accept": "application/json",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.61.1"
  },
  "method": "GET",
  "origin": "<removed>"
}

```
The following script shows how it works with httpbin gziped bodies
```js
import http from "k6/http";

export default function() {
    var res = http.get("https://httpbin.org/gzip");
    console.log(res.body);
    console.log(JSON.stringify(res, null, '\t'));
};
```

**Comment by soemeier** [comment]
I have to admit that the body is not gzip compressed but the header is sent. Thanks for the fast response anyway.
