### ISSUE TITLE
metrics show incorrect timings

### ISSUE THREAD

**Issue by kkeranen** [loadimpact/k6#1041]
Response.timings.receiving show unbelievably low values, like 0.05 (ms). In my tests, when receiving content of 2-3 MB, duration is typically 700ms and waiting time is (almost) the same with 1 ms accuracy, sending and receiving taking together about 0.1 ms. Tested with k6 v0.24.0.

I can't believe the numbers and I have double-checked my code (and also timings.duration = timings.sending + timings.waiting + timings.receiving), so I'm quite sure there must be a bug in k6 metrics code.

**Comment by kkeranen** [comment]
OTOH, maybe the figures are correct, but misleading. E.g. receiving time might mean how long it took to handle the response in local computer, and not how it is usually understood: how long it took to transfer the message from server to client.

**Comment by na--** [comment]
Looking at [how it's calculated](https://github.com/loadimpact/k6/blob/607b63c4400c8b6852c7f51a0a6151f0bb8ec6b7/lib/netext/httpext/tracer.go#L335), `http_req_receiving` should mean the duration between the time we got the first response byte back and the time the request was finished... :confused: You might be right, depending on how things are handled in the Go stdlib and the network/OS stack, those callbacks might be triggered when the response has already been received, but something smells fishy here. This definitely needs more investigation, and if that's the case, it should be properly documented, as you mentioned.

**Comment by na--** [comment]
Potentially connected issue: https://github.com/loadimpact/k6/issues/925#issuecomment-463568571

**Comment by na--** [comment]
This is definitely a bug :disappointed: 

If I execute this script:
```js
import http from 'k6/http';
import { Trend } from "k6/metrics";

export let options = {
    vus: 10,
    iterations: 20,
    summaryTimeUnit: "ms",
};

var totalTimeTrend = new Trend("total_time", true);
var totalTimeDiffTrend = new Trend("total_time_diff", true);

export default function () {
    let startTime = Date.now();
    let resp = http.get("https://httpbin.test.loadimpact.com/stream-bytes/100000");
    let totalTime = Date.now() - startTime;

    totalTimeTrend.add(totalTime);
    totalTimeDiffTrend.add(Math.abs(totalTime - resp.timings.duration - resp.timings.blocked));
};
```

With k6 v0.24.0, I get the following results:
```
    data_received..............: 2.1 MB 378 kB/s
    data_sent..................: 14 kB  2.6 kB/s
    http_req_blocked...........: avg=285.43ms  min=0.00ms   med=277.13ms  max=626.09ms  p(90)=566.67ms  p(95)=624.89ms 
    http_req_connecting........: avg=68.77ms   min=0.00ms   med=62.91ms   max=169.48ms  p(90)=136.03ms  p(95)=168.34ms 
    http_req_duration..........: avg=1522.50ms min=149.97ms med=1537.81ms max=3071.46ms p(90)=2289.72ms p(95)=3057.44ms
    http_req_receiving.........: avg=0.06ms    min=0.03ms   med=0.05ms    max=0.11ms    p(90)=0.08ms    p(95)=0.11ms   
    http_req_sending...........: avg=0.11ms    min=0.03ms   med=0.06ms    max=0.38ms    p(90)=0.29ms    p(95)=0.30ms   
    http_req_tls_handshaking...: avg=153.71ms  min=0.00ms   med=149.44ms  max=330.92ms  p(90)=306.84ms  p(95)=330.26ms 
    http_req_waiting...........: avg=1522.33ms min=149.62ms med=1537.68ms max=3071.37ms p(90)=2289.60ms p(95)=3057.37ms
    http_reqs..................: 20     3.655567/s
    iteration_duration.........: avg=2190.23ms min=643.92ms med=2367.55ms max=3364.22ms p(90)=3271.33ms p(95)=3349.37ms
    iterations.................: 20     3.655567/s
    total_time.................: avg=2190.15ms min=644.00ms med=2367.50ms max=3364.00ms p(90)=3271.60ms p(95)=3349.75ms
    total_time_diff............: avg=382.22ms  min=290.50ms med=374.80ms  max=514.46ms  p(90)=494.32ms  p(95)=512.86ms 
    vus........................: 10     min=10 max=10
    vus_max....................: 10     min=10 max=10
```

Which don't look realistic at all. Especially telling are the huge values in `total_time_diff` - that one should normally be very close to zero... If I execute the same script with k6 v0.22.1, I get this:
```
    data_received..............: 2.1 MB 384 kB/s
    data_sent..................: 14 kB  2.5 kB/s
    http_req_blocked...........: avg=262.55ms  min=0.00ms   med=254.44ms  max=570.20ms  p(90)=522.09ms  p(95)=561.53ms 
    http_req_connecting........: avg=68.93ms   min=0.00ms   med=63.44ms   max=164.76ms  p(90)=137.45ms  p(95)=164.00ms 
    http_req_duration..........: avg=1861.81ms min=637.26ms med=1835.42ms max=3437.64ms p(90)=2755.32ms p(95)=3002.00ms
    http_req_receiving.........: avg=460.97ms  min=300.33ms med=483.46ms  max=655.57ms  p(90)=528.90ms  p(95)=638.94ms 
    http_req_sending...........: avg=0.11ms    min=0.03ms   med=0.10ms    max=0.26ms    p(90)=0.20ms    p(95)=0.23ms   
    http_req_tls_handshaking...: avg=156.10ms  min=0.00ms   med=153.39ms  max=330.84ms  p(90)=311.33ms  p(95)=322.69ms 
    http_req_waiting...........: avg=1400.74ms min=147.96ms med=1345.78ms max=3053.25ms p(90)=2127.82ms p(95)=2628.53ms
    http_reqs..................: 20     3.717214/s
    iteration_duration.........: avg=2124.60ms min=749.71ms med=2272.29ms max=3437.79ms p(90)=3092.92ms p(95)=3307.59ms
    iterations.................: 20     3.717214/s
    total_time.................: avg=2124.50ms min=750.00ms med=2272.00ms max=3438.00ms p(90)=3093.10ms p(95)=3307.85ms
    total_time_diff............: avg=0.34ms    min=0.07ms   med=0.32ms    max=0.89ms    p(90)=0.68ms    p(95)=0.70ms   
    vus........................: 10     min=10 max=10
    vus_max....................: 10     min=10 max=10
```

Which seems much more realistic - `http_req_receiving` is plausible and `total_time_diff` is below a millisecond, which can be attributed to JS execution and measurement delays of `totalTime`. So, it seems like either we've broken the `http_req_receiving` measurement somehow in the last few versions, or something has changed in how the [`httptrace`](https://golang.org/pkg/net/http/httptrace/) callbacks work in the last Go versions.

**Comment by na--** [comment]
And it seems like the bug is on the k6 side, since compiling the `v0.22.1` code with the latest Go 1.12.5 still produces correct results, but compiling the latest `master` code produces buggy results.

**Comment by na--** [comment]
After some `git bisect` work, this seems to be the commit that has broken the `http_req_receiving` measurement, which somewhat makes sense, given how many HTTP-related things it touches: https://github.com/loadimpact/k6/commit/9405ba29c68ced92c6b96974485d1541a8807f23

**Comment by MStoykov** [comment]
Found it ... Okay so ... `receiving` is basically [measuring](https://github.com/loadimpact/k6/blob/607b63c4400c8b6852c7f51a0a6151f0bb8ec6b7/lib/netext/httpext/tracer.go#L335) from the time we [get the first byte](https://github.com/loadimpact/k6/blob/607b63c4400c8b6852c7f51a0a6151f0bb8ec6b7/lib/netext/httpext/tracer.go#L274-L280) to time we call [Done](https://github.com/loadimpact/k6/blob/607b63c4400c8b6852c7f51a0a6151f0bb8ec6b7/lib/netext/httpext/tracer.go#L283-L284) on the tracer ... which we previously did after we [read the body](https://github.com/loadimpact/k6/commit/9405ba29c68ced92c6b96974485d1541a8807f23#diff-37ac318df24f95fc3aadf765a5cfa593L500). Now we do ... [after the response has went through the transport](https://github.com/loadimpact/k6/blob/master/lib/netext/httpext/transport.go#L99), at which point a lot of the body is probably not read, unless it is tiny ;(

So now the question is how to fix this ... and properly test for it ...

**Comment by na--** [comment]
Testing for this would be somewhat tricky, especially since I desperately don't want to introduce new flaky tests, but we definitely should have a test for it ([prev. mention](https://github.com/loadimpact/k6/issues/925#issuecomment-463589690)), so we don't introduce regressions like this again...

As for fixing it, it seems to me that we should read the response body in our tracing RoundTripper and either discard it, or save it as a `bytes.Buffer` so that it can be read from the HTTP client. Basically, move to [here](https://github.com/loadimpact/k6/blob/master/lib/netext/httpext/transport.go#L98-L99) this code (with the appropriate adjustments, of course): https://github.com/loadimpact/k6/blob/607b63c4400c8b6852c7f51a0a6151f0bb8ec6b7/lib/netext/httpext/request.go#L358-L385

**Comment by MStoykov** [comment]
I would consider something like ... having a http server which writes some amount of data, [flush](https://golang.org/pkg/net/http/#Flusher), sleep a second (we can have this be parallel and slow I think ;) and than writes the other part of the data. We should expect that the receiving is at least half a second ;)

**Comment by kkeranen** [comment]
Thank you **na--** for taking so much attention with this. I found something else in the timings I don't understand. The timings example you shared look much more different than what I have found. For me _connecting_ and _looking_up_ are always zero, and _blocked_ very close to zero. The tests are done at my home office, via VPN, using Ubuntu Linux subsystem of Windows 10. See below:

```
blocked......................: avg=0.008925   min=0.0042   med=0.0047    max=0.0302    p(90)=0.01921   p(95)=0.01973   
connecting...................: avg=0          min=0        med=0         max=0         p(90)=0         p(95)=0         
looking_up...................: avg=0          min=0        med=0         max=0         p(90)=0         p(95)=0         
receiving....................: avg=0.062331   min=0.0334   med=0.05525   max=0.2387    p(90)=0.08464   p(95)=0.101655  
sending......................: avg=0.115969   min=0.0759   med=0.1156    max=0.1802    p(90)=0.14475   p(95)=0.15006   
waiting......................: avg=803.7078   min=621.8174 med=813.2571  max=971.6918  p(90)=866.73862 p(95)=878.557775
duration.....................: avg=803.8861   min=621.9987 med=813.41205 max=971.9089  p(90)=866.91363 p(95)=878.713445
```

These are measured using custom trend metrics, e.g.:
1) Initialization:
`http_req_connecting = new Trend("connecting");`
2) Update after HTTP response:
`http_req_connecting.add(response.timings.connecting);`

**Comment by na--** [comment]
It's normal for `blocked` to be near-zero, actually having it high would probably mean that the machine is struggling to make the number of HTTP requests that you've specified.

The DNS `looking_up` metric was removed from k6 in k6 0.13, but there was a place in the docs where it wasn't properly removed up until recently. You can find more information about that [here](https://github.com/loadimpact/k6/issues/1011#issuecomment-487831326), and use that issue to track when we bring back the DNS metrics. I now see that `timings.looking_up` is also [present](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3620be6751c532f1c3ce08d03554ee273fa14f70/types/k6/http.d.ts#L65) in the user-contributed k6 type definitions, so I'll add a note in that issue to remove it in https://github.com/loadimpact/k6/issues/929.

Finally, regarding `connecting` - I have no idea why it would always be 0. It's normal to have min=0, since the value is 0 for requests where k6 reuses a previously opened connection, but you should have max, avg, etc. be above 0 :confused:

**Comment by na--** [comment]
@kkeranen, I can't reproduce the `connecting` issue you've experienced. Did you add the `response.timings.connecting` values for *all* HTTP responses in your custom metric, or only some of them? Also, if you add `noConnectionReuse: true` to the k6 options, does the problem disappear?

**Comment by kkeranen** [comment]
Right, that must be it. I didn't add `response.timings.connecting` into handshaking messages, but only to the actual "beef".

**Comment by kkeranen** [comment]
The incorrect `receiving` timing seems to affect the `duration` timing, too. Current k6 results in our test: If data is well compressible (from 3 MB down to 36 kB),  the duration of compressed and non-compressed HTTP API calls are about the same. But if data is not so compressible ("only" from 3 MB to 1.5 MB), the duration of compressed HTTP API call goes from 600ms (non-compressed) up to 800 ms. This is quite misleading.
