### ISSUE TITLE
Update CONTRIBUTING.md, add issue/PR templates, etc.

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#1063]
Basically, we probably should improve the developer experience - both for the main k6 developers (  :innocent: :grinning: ) and for people contributing issues or pull requests. Things we can do:
- Update [CONTRIBUTING.md](https://github.com/loadimpact/k6/blob/master/CONTRIBUTING.md)
  - Add a note that changes in the k6 JS API necessitate updates of the type definitions (from https://github.com/loadimpact/k6/issues/929)
  - Read through the whole document carefully and see if anything else needs updating. I recently had to update a lot of things related to versions and CI checks that were obsolete, but I probably missed some stuff...
- Update/create the [other community health files](https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization#about-default-community-health-files). `SUPPORT` is probably the most important one of those, since we want users to use the Discourse forum for support, not GitHub issues.
- Add [issue and pull request templates](https://help.github.com/en/articles/about-issue-and-pull-request-templates)

Anything else? I don't think we need a custom GitHub bot at this stage, but maybe we lack something simple and helpful :smile: Open to suggestions and links to good repositories we can use for inspiration.

**Comment by MStoykov** [comment]
I propose that we specify that the issues are for bug reports and feature requests and point people to the [community forum](https://github.com/loadimpact/k6/issues/1101). Also probably add a note that says that if they are not sure they should write to the community forum not in the issues ..

**Comment by na--** [comment]
This is not quite closed, `CONTRIBUTING.md` could still use some improvements, as per the original issue description

**Comment by imiric** [comment]
Ugh, sorry about that. Apparently [GH doesn't recognize 'Partially fixes'](https://github.com/kubernetes/test-infra/issues/3857) :(

I'll use "Part of" from now on, as suggested in that issue.

**Comment by na--** [comment]
I think this should be closed after https://github.com/loadimpact/k6/pull/1598...
