### ISSUE TITLE
Adopt Go modules

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#1070]
After Go 1.13 comes out, likely sometime next month, we should probably replace [dep](https://github.com/golang/dep/) with the official Go modules:
- https://github.com/golang/go/wiki/Modules
- https://blog.golang.org/modules2019
- https://blog.golang.org/using-go-modules
- https://blog.golang.org/migrating-to-go-modules

**Comment by wingyplus** [comment]
I would like to help this issue if nobody working on it. :D

**Comment by cuonglm** [comment]
@wingyplus Thanks.

If you want to work on it, consider to update CI/CD, too.

**Comment by na--** [comment]
For posterity, it turns out that there are some serious deficiencies regarding vendoring support with Go modules that I didn't expect at all... I've collected a summary here: https://github.com/loadimpact/k6/pull/1150#issuecomment-530256215

**Comment by na--** [comment]
Something else we should adopt when we switch to Go modules: https://golang.org/pkg/runtime/debug/#ReadBuildInfo

Basically, it would be very useful to have the exact commit ID in each k6 binary, as part of `k6 version` and/or as a `debug` console message.
