### ISSUE TITLE
Improve auto-import in the k6 type definitions

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#1071]
As noted in https://github.com/loadimpact/k6/issues/929#issuecomment-508676629 and https://github.com/loadimpact/k6/issues/929#issuecomment-508873173, we can probably improve developer UX by having our types auto-import the correct modules.

**Comment by ppcano** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45259 solves this issue.
