### ISSUE TITLE
 how  redirect post tracing ? 

### ISSUE THREAD

**Issue by hgkiller** [loadimpact/k6#1078]
```javascript
import http from "k6/http";
import { sleep } from "k6";


let file = open("/nxfile/h2spec","b");

export default function() {
          var data = {
                      field: "this is a standard form field",
                      uploaded_file: http.file(file, "h2spec")
                    };
          var res = http.post("http://www.test.com/upload.php", {redirects: 3}, data);
          sleep(3)
}
```

**Comment by MStoykov** [comment]
Hi, can you elaborate? I can't figure out what exactly you are asking ...

Also if this isn't a bug report or a proposal for a feature/enhancement you should probably use the [community forum](https://community.k6.io/)

**Comment by MStoykov** [comment]
I still don't know what you are asking, but you have reversed the position of `body` and `params` in the `http.post` call, it should be :
```javascript
          var res = http.post("http://www.test.com/upload.php", data, {redirects: 3});
```

p.s. FYI I also wrapped your code in order to be better formatted

**Comment by hgkiller** [comment]
if i write like  this   " var res = http.post("http://www.test.com/upload.php", data, {redirects: 3});" , it can't  redirect,   
           and if  i  wirte like this " var res = http.post("http://www.test.com/upload.php", {redirects: 3});" ,it can't flow  307
          so ,  i only write like this 
           "var res = http.post("http://www.test.com/upload.php", {redirects: 3});
             res = http.post("http://www.test.com/upload.php", data); "  only like this,i can redirect 307 and  upload sucess

**Comment by na--** [comment]
I still have no idea what you mean, sorry. As we show in the docs, the order of parameters to `http.post()` is `url, body, options`: https://docs.k6.io/docs/post-url-body-params
In the example above `{redirects: 3}` means "restrict k6 to follow only up to 3 redirects"

**Comment by na--** [comment]
Closing this, since this seems like either a mistaken API usage, or something that should have been fixed by https://github.com/loadimpact/k6/pull/1093. Please, if that isn't the case, feel free to reopen the issue or open a new one, with a full code example (preferably using a public service like https://httpbin.org/) that demonstrates the problem.
