### ISSUE TITLE
Drop or deprecate SSLv3 support

### ISSUE THREAD

**Issue by cuonglm** [loadimpact/k6#1083]
[go 1.13 will deprecate SSLv3 support and it will be removed in go1.14](https://github.com/golang/go/commit/a6a7b148f874b32a34e833893971b471cd9cdeb7)

Should we do the same?

**Comment by na--** [comment]
Yeah, thanks for notifying us of this. We should follow Go's lead on this - if someone is still using SSLv3 in 2019, I'd say that it's unlikely that they need much load testing :smile:... k6 v0.25.0, which should be released in a few days, would likely be the last k6 version that supports SSLv3.
