### ISSUE TITLE
Enforce style of commit messages? 

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#1086]
@imiric mentioned [Conventional Commits](https://www.conventionalcommits.org/) in https://github.com/loadimpact/k6/pull/1082#issuecomment-512576735, and at a first glance they seem very sensible. It may be worth it to switch to using them (or another convention) for k6 commits, though I'm not sure if we should be super strict and actually enforce these styles with commit checks.

**Comment by bookmoons** [comment]
It's an interesting format. I also like [the 7 rules](https://chris.beams.io/posts/git-commit/#seven-rules). They seem mostly compatible.

1. Separate subject from body with a blank line
1. Limit the subject line to 50 characters
1. Capitalize the subject line
1. Do not end the subject line with a period
1. Use the imperative mood in the subject line
1. Wrap the body at 72 characters
1. Use the body to explain what and why vs. how

**Comment by na--** [comment]
@bookmoons :+1: I think I mostly follow those, except the one to "limit the subject line to 50 characters". I try, but my actual hard limit for the subject line is ~70, so that GitHub doesn't wrap it on multiple lines

**Comment by imiric** [comment]
As discussed internally, we won't be adopting a more elaborate convention than the standard imperative guidelines.

And as we won't be enforcing it either, especially on external contributors, we're closing this issue for now.
