### ISSUE TITLE
 wsarecv: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by choungchamnab** [loadimpact/k6#1090]
When I trying to test, I always get this message
` wsarecv: An existing connection was forcibly closed by the remote host.`

**Comment by MStoykov** [comment]
Hi @choungchamnab, this looks like a docker on windows issue. There are some proposed solution at the docker github [here](https://github.com/docker/machine/issues/2318). You can try the [**not** dockerized version of k6](https://github.com/loadimpact/k6/releases/download/v0.24.0/k6-v0.24.0-win64.zip) if none of the solutions work for you. 

I am closing this though, as this is not an issue in k6 and I don't see anything we can do.

**Comment by mstoykov** [comment]
@armelo24 I would recommend opening a new issue or even better asking in the [forums](https://community.grafana.com/c/grafana-k6/70), instead of on a 4y+ old issue.
