### ISSUE TITLE
Full k6 control from API

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#11]
After playing around with remote controlling k6 from another process I've discovered some things that's missing or would ease the integration considerably. 

- I'd like to be able to start k6 in some kind of "slave mode" where it only spins up the API. From there on I want to interact with k6 via the API only. I plan to start k6 with standard in, out and err bound to /dev/null and detached from any shell. 
- I'd like to have a "self destruct" API endpoint (`v1/quit`?) to kill speedboat when it's time to stop the test and tear down output plugins and similar.
- To even get the test going, I need a `v1/run` endpoint that would work as we discussed earlier. This would be the way to send the javascript scenario + config in a POST-request to a process started in a way as described above.

These are thoughts based on last weeks testing/discovery coding and are not finalized suggestions. Hoping for a good discussion.

*Imported from https://trello.com/c/G5sdTlC4/86-full-k6-control-from-api*

**Comment by ppcano** [comment]
@ragnarlonn Could we close this issue?

**Comment by liclac** [comment]
This should just be a part of #140
