### ISSUE TITLE
Fix line numbers in imports

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#1107]
Because of the way we [wrap imports](https://github.com/loadimpact/k6/blob/8e932587c51de324adc52da5bcbf75b217ea26c7/js/initcontext.go#L183), we add an additional 1 to all line numbers. (this is not true for the main script because it special ... for now). This is somewhat annoying and definitely problematic in big scripts when the error is cryptic to begin with. 
We should be able to utilize [sourcemaps](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?hl=en_US&pli=1&pli=1) given that [goja supports](https://godoc.org/github.com/dop251/goja#NewSrcFile) them and we already have some code that [reads them](https://github.com/loadimpact/k6/blob/8e932587c51de324adc52da5bcbf75b217ea26c7/js/compiler/compiler.go#L115-L121) even though they were [disabled](https://github.com/loadimpact/k6/commit/31819e6ffe966fc247f58d3e717e41037068747a) and I can't find them ever being used ... ;(

**Comment by na--** [comment]
Closing this in favor of https://github.com/loadimpact/k6/issues/1804, since it's more detailed
