### ISSUE TITLE
Support all http verbs

### ISSUE THREAD

**Issue by micsjo** [loadimpact/k6#112]
Does not support (or at least fails) with 'options' method.

Preferable if k6 can support all http verbs.

**Comment by uppfinnarn** [comment]
Oh, right, OPTIONS exists.

Can I have a list of all of them, for reference?

**Comment by micsjo** [comment]
Ok, then it's a bug related to the "options" request I am doing. I will isolate and and file a separate issue as a bug.

For reference; all http verbs https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

GET, PUT, HEAD, OPTIONS, POST, PATCH, DELETE, TRACE, CONNECT

**Comment by uppfinnarn** [comment]
d6eaadb90ade8a5a4c5e7c45729b081654f15cc5 adds accessors for PATCH, CONNECT, OPTIONS and TRACE, [godoc](https://godoc.org/net/http#pkg-constants) says net/http should support all of them.

**Comment by micsjo** [comment]
Ah, 4 minutes ago - my build is older than that :-) [gotta go fast!]
