### ISSUE TITLE
Add a set of APIs to give access to current test execution metadata

### ISSUE THREAD

**Issue by markjmeier** [loadimpact/k6#1128]
This would need to come in a post #1007 world, but being able to get some information about the current test in progress can expand flexibility and give more control over the test itself.  Foremost, getting some type `TimeSinceStart`.  For reference, v3.0 of LoadImpact has `client.get_time_since_start()` which can be useful when timing things, dealing with custom timers, etc. 

Further expanding this conversation with @na--, he came up with some other ideas based on #1007: 

- `execution.GetCurrentExecutorID()` to get the ID of the executor that's responsible for the current iteration
- `execution.GetExecutionSegment()` - to get the execution segment (maybe tying in somehow with data partitioning)
- `execution.GetTimeSinceExecutorStart()` - elapsed time for this particular executor
- `execution.GetTimeSinceTestStart()` - time since the global start time of the whole test

**Comment by na--** [comment]
https://github.com/loadimpact/k6/issues/1320 is the same issue with more details, so I consolidated this one in it: https://github.com/loadimpact/k6/issues/1320#issuecomment-767728442

We're probably going to implement all of the various aspects of that new API in multiple PRs, but I think it'd be best if the overall design and consideration happens in a single place.
