### ISSUE TITLE
Continuous fuzzing

### ISSUE THREAD

**Issue by bookmoons** [loadimpact/k6#1135]
What would you guys think about automated fuzzing for k6? Fuzzit can run every push and email you if it finds bugs. It's free for open source:
https://fuzzit.dev/

They use go-fuzz. I guess we'd have to decide the major input channels / components that should be hit and write a target for each one. I've done a few integrations so I know what the setup looks like. If it's interesting maybe I could get into after the current work.

Related to #1023.

**Comment by na--** [comment]
Seems like a good idea, and they seem to have a free/OSS tier. AFAIK we don't use any `unsafe` code in k6, so I doubt we'll catch anything truly scary, but hopefully it will help us prevent things like some of the panics that we've had.

**Comment by bookmoons** [comment]
Alright, I'll add it to my list to look over after the resolver.
