### ISSUE TITLE
Request k6 GitHub Username

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#1161]
Recently, we have discussed to create a dedicated Github organization for the [k6](https://github.com/loadimpact/k6) project.

I am creating this issue to ask @k6 for the possibility to transfer its Github Username to become the k6 organization.

@k6 does not have public activity, but as per GitHub, the account is active. If @k6 could kindly transfer its username to the k6 project, the [k6](https://github.com/loadimpact/k6) project could be located under:

https://github.com/k6/k6

Otherwise, the options for the new GitHub organization name could be: 

https://github.com/k6-io/k6
https://github.com/k6io/k6

**Comment by simskij** [comment]
Apparently, the account is being used, or at least GitHub Staff is not willing to accommodate our requests for taking over the account name. For now, we'll have to settle with https://github.com/k6io
