### ISSUE TITLE
Use RWMutexes

### ISSUE THREAD

**Issue by uppfinnarn** [loadimpact/k6#119]
They're neat and allow concurrent reads, but not writes. I can think of a few uses.

**Comment by ragnarlonn** [comment]
Meta-comment: While new tech is always cool, I think it is useful to describe an actual issue when creating issues :)  If we don't, it gets harder for others to relate to the issue or know how to contribute. Maybe this should be in the CONTRIBUTING.md doc?  I.e. suggestions on how to write an issue?  @uppfinnarn
