### ISSUE TITLE
Maintain consistent units in CLI output

### ISSUE THREAD

**Issue by mcandre** [loadimpact/k6#1191]
Please display consistent units, e.g. deci-second precision, in order to reduce visual jitter during performance runs.

**Comment by na--** [comment]
You can change the time unit with `summaryTimeUnit` / `--summary-time-unit` / `K6_SUMMARY_TIME_UNIT` option, for example `k6 run --summary-time-unit=ms script.js`. That should help somewhat, even though there are no deci-seconds (only `s`, `ms` and `us` for now). You also currently can't specify the decimal precision or the left padding of the numbers, so alignment may still not be perfect if you have high variability. 

Improving the alignment of the end-of-test summary in general is tracked in https://github.com/loadimpact/k6/issues/1024. Also, we're currently working on a way to export the end-of-test summary in a JSON format, so follow https://github.com/loadimpact/k6/pull/1168 if you want to know when you'd be able to do it and format it however it works for you.

All of that said, I don't know if we should just always use milliseconds by default when displaying the metric values in the end-of-test summary... It will probably be a better UX to not mix `µs` and `ms` values at least, that's the most annoying part for me personally. But some metrics like `iteration_duration` and `group_duration` will likely have much larger values than the `http_req_*` metrics, sometimes in the tens or hundreds of seconds, which doesn't make sense to display as milliseconds... :confused: So, maybe we should just stick to having a mix of `ms` and `s` values, unless the user explicitly requests microseconds by `--summary-time-unit=us`?

**Comment by na--** [comment]
I'm closing this issue, now that we have [`handleSummary()` in k6 v0.30.0](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.30.0.md#support-a-handlesummary-callback-at-the-end-of-the-test-1768) (https://github.com/loadimpact/k6/pull/1768), this can be left entirely at the discretion of the user.

An in any case, as I mentioned in https://github.com/loadimpact/k6/issues/1806, in k6 v0.31.0 we'll adopt the latest version of the JS-based summary generation code from [jslib.k6.io](https://jslib.k6.io/), originally submitted in https://github.com/loadimpact/jslib.k6.io/pull/20. So any change requests for the default text summary k6 outputs should be opened in https://github.com/loadimpact/jslib.k6.io/issues now.
