### ISSUE TITLE
Calculate requests per second from json report

### ISSUE THREAD

**Issue by Paxa** [loadimpact/k6#1194]
I would like to get req/sec value from json report, I try to run script for 10 seconds and check difference between first time and last time in json report, I get 7847 ms, and I got very different result then terminal output

```
http_reqs..................: 38            3.799899/s
```

From my script
```
Total requests: 38
exec time: 7847 ms
req/sec: 4.842615012106537
```

Then I try to save start time and end time in my benchmark:
```js
import { Gauge } from "k6/metrics";
var startCounter = new Gauge("start_counter");
var endCounter = new Gauge("end_counter");

export default function() {
  startCounter.add(Date.now());
  // my bench code
  endCounter.add(Date.now());
};
```

And I got better results:
```
exec time: 9890
req/sec: 3.8422649140546006 <-- almost good
```

Is there a better way to do it?

**Comment by na--** [comment]
@Paxa, I'm not completely sure what you're trying to do, can you explain in some more detail?

Regarding the metric timestamps when you output them to a JSON file, they represent the times when the response was received and processed. So, even if you make an HTTP request at t=0, if it takes 2 seconds to receive its response, you're going to see t=2s as the JSON metric timestamp. So, to calculate the req/s, you probably just need to divide the number of request metrics in that JSON file by the duration you specified for the test run.

If you just need the requests per second in a machine readable format, you might want to follow https://github.com/loadimpact/k6/pull/1168. This PR would allow the exporting of all of the metrics you see in the end-of-test summary as a JSON file, so you don't need to process each individual metric to get the summary.
