### ISSUE TITLE
Issues using k6/html

### ISSUE THREAD

**Issue by MMartyn** [loadimpact/k6#1195]
I am having a lot of trouble using the k6/html module where the documentation doesn't seem to match reality. 

A couple of examples of issues:

1) Using the .attr (https://docs.k6.io/docs/selectionattrname) says that it should return a string but actually returns an array

2) Attempting to reading the data from an item says that the method doesn't exist, yet is listed in the docs https://docs.k6.io/docs/selectiondatakey

Are those not the correct docs?

Thanks.

**Comment by cuonglm** [comment]
> Using the .attr (https://docs.k6.io/docs/selectionattrname) says that it should return a string but actually returns an array

Can you post the code that you use? With `k6 v0.25.1`, I tried with the example in doc, and it returns a string as expected.
