### ISSUE TITLE
ERRO[0001] GoError: open() can't be used with directories 

### ISSUE THREAD

**Issue by cdimascio** [loadimpact/k6#1234]
I have a load test script that references a few local modules. It runs successfully on MacOS, however when i run on CentOS 7 the following error is output.
```
DEBU[0000] Loading...                                    moduleSpecifier="file:///load-test/load_test.js" original moduleSpecifier=load_test.js
DEBU[0000] Babel: Transformed                            t=58.637536ms
DEBU[0000] Loading...                                    moduleSpecifier="file:///load-test/config.js" original moduleSpecifier=./config.js
DEBU[0000] Babel: Transformed                            t=60.04885ms
DEBU[0000] Loading...                                    moduleSpecifier="file:///load-test/lib/geo.js" original moduleSpecifier=./lib/geo.js
DEBU[0000] Babel: Transformed                            t=346.938559ms
DEBU[0000] Loading...                                    moduleSpecifier="file:///load-test/lib/util.js" original moduleSpecifier=./util.js
DEBU[0001] Babel: Transformed                            t=332.284008ms
ERRO[0001] GoError: open() can't be used with directories 
```

**Comment by cdimascio** [comment]
the above error occurs because in the main script file i attempt to open a file (outside vu code), but the path did not exist. all in all, my error. that being said, the message was not very helpful.

ultimately, this is a minor issue, if one at all.

**Comment by na--** [comment]
Thanks for reporting this, we definitely need to improve the error message, especially since this is a k6 error, not a Go stdlib one: https://github.com/loadimpact/k6/blob/9d9bc4b155d1210a02d2a6da5725ee0699588487/js/initcontext.go#L205-L207

At the very least, the path of the directory should be shown, for easier debugging in complex scripts...

**Comment by MStoykov** [comment]
I couldn't reproduce it with a file that isn't a director, but not existant .. so I just added the path to the message. 
If the path you were having problems with, @cdimascio , wasn't actually a directory, but not existant, can you please provide me with some additional information on how to reproduce it :)

**Comment by cdimascio** [comment]
This path i was using was not a directory it was a file that i tried to open in the options section

```
for example
```javascript
export let options = {
  stages: config.stages,
  tlsAuth: [
    {
      domains: config.client_cert.domains,
      cert: open(config.client_cert.cert),
      key: open(config.client_cert.key),
    },
  ],
};
```

**Comment by cdimascio** [comment]
basically i had an incorrect path to `config.client_cert.cert`

**Comment by cdimascio** [comment]
can't remember what in the path was wrong. it may have been that one of the subdirs in the path was incorrect

**Comment by MStoykov** [comment]
Sorry @cdimascio, I did just retry to get that error for a non-existent file/dir but all i get is the correct message that such a file just doesn't exist ... I even tried on windows (as we do have some problems sometimes :( ), but there it works as expected as well and the message is slightly different as we return the original underlying error as well.

All in all I think you made a lucky mistake and was actually pointing at another directory ... I guess ... no idea. 

If you or anyone else ever manage to reproduce it I will gladly fix it ;) 

And thanks for reporting it :tada:
