### ISSUE TITLE
k6 run -o cloud does not work with scripts from shortcut URLs

### ISSUE THREAD

**Issue by Menda** [loadimpact/k6#1236]
Given I logged in to the cloud successfully, when I run:

`k6 run -u 1 -d 10s github.com/loadimpact/k6/samples/http_get.js` it works well.

But when I run:
`k6 run -o cloud -u 1 -d 10s github.com/loadimpact/k6/samples/http_get.js`, it returns the following error message:

```
Output: ERRO[0002] (422/E2)
Validation failed
name: Shorter than minimum length 2
```

Extra info:

```
$ k6 version
k6 v0.25.1

$ cat /proc/version
Linux version 4.15.0-65-generic (buildd@lgw01-amd64-006) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019
```

Thank you.

**Comment by cuonglm** [comment]
This seems to be the error from cloud API, not k6 itself.

**Comment by na--** [comment]
@cuonglm, you're technically correct, but see the discussion in Slack. In summary, this is most likely caused by a regression introduced in https://github.com/loadimpact/k6/pull/1059. For one, this is broken in k6 v0.25.1 and v0.25.0, but works with k6 v0.24.0.

**Comment by na--** [comment]
And it's indeed an issue with the "magic" shortcut URLs, since running `k6-0.25.1 run -o cloud -u 1 -d 10s raw.githubusercontent.com/loadimpact/k6/master/samples/http_get.js` works even with the latest k6 versions.
