### ISSUE TITLE
Can I import packages from a custom npm repository?

### ISSUE THREAD

**Issue by goncer** [loadimpact/k6#1251]
Hi, 
I can not fetch a package with the syntax:
import blabla  from '@awesomeRepo/lib/blabla';
neither with:
const blabla = require( '@awesomeRepo/lib/blabla');
Actually I have an npm link, but in the future, it will be required to log in on such npm repository.

**Comment by goncer** [comment]
is there a way to import an npm package?

**Comment by cuonglm** [comment]
> is there a way to import an npm package?

You can read more details at https://docs.k6.io/docs/modules#section-npm-modules

**Comment by na--** [comment]
Like the link @cuonglm posted says, k6 is not based on node.js. So for some modules, you **may** be able to make them work by _manually_ transforming them with browserify of webpack (see demo code in https://github.com/MStoykov/k6-es6), it's not something that is automatically supported by k6.
