### ISSUE TITLE
OpenId Connect authentication flow, cookie issues

### ISSUE THREAD

**Issue by johnkors** [loadimpact/k6#1254]
_Using k6 via docker, using `loadimpact/k6: latest`_

It looks like the cookies are set on the wrong domain when redirects are involved.

In an OpenId Connect authentication flow, the following redirects & cookies are involved:

1. User browses directly to a site behind auth. The auth triggers an OIDC auth flow, meaning it sets two cookies on the site domain (a nonce, and a correlation cookie).
2. Site redirects to the OIDC login provider via a redirect to the `authorize` endpoint of OpenId Connect, including the nonce value set in a cookie at the site.
3. The OIDC login provider validates and renders the login view
4. After login, the OIDC provider redirects back to a configured signin-callback endpoint at the site, including the nonce and correlation values.
5. At the callback, the site validates the nonce and correlation values sent back against the value stored in the nonce cookie and correlation cookie.

Sample showing requests up to the login UI being rendered:
```
GET /some-path-behind-auth HTTP/1.1
Host: www.mydomain.com

Response:
HTTP/1.1 302 Found
Date: Tue, 26 Nov 2019 18:32:23 GMT
Location: https://id.mydomain.com/oauth2/connect/authorize?<queryparams>
Set-Cookie: .AspNetCore.OpenIdConnect.Nonce=N; expires=Tue, 26 Nov 2019 18:47:23 GMT; path=/signin-callback; secure; httponly
Set-Cookie: .AspNetCore.Correlation.OpenIdConnect=N; expires=Tue, 26 Nov 2019 18:47:23 GMT; path=/signin-callback; secure; httponly

Request:
GET /oauth2/connect/authorize?<queryparams>
Host: id.mydomain.com
Referer: https://www.mydomain.com/some-path-behind-auth

Response:
HTTP/1.1 302 Found
Date: Tue, 26 Nov 2019 18:31:40 GMT
Location: https://id.mydomain.com/oauth2/account/login?<query-params>

Request:
GET /oauth2/account/login?<query-params>
Host: id.mydomain.com
Referer: https://id.mydomain.com/oauth2/connect/authorize?<query-params>

Response:
HTTP/1.1 200 OK
Set-Cookie: .AspNetCore.Antiforgery=<value>; path=/oauth2; samesite=strict; httponly

<html>
login ui
</html>
```

At this point, when I check the `http.cookieJar()`,

Expected:
`jar.cookiesForURL('https://www.mydomain.com/signin-callback')` => to have the nonce/correlation cookies, 

but instead, the actual behaviour is that it sets the cookies on the right _path_ , but on the wrong domain:

`jar.cookiesForURL('https://id.mydomain.com/signin-callback')` => has the nonce/correlation cookies.

**Comment by johnkors** [comment]
It looks like the cookies are set on the wrong domain when redirects are involved.

The flow below is

1. User browses directly to a site behind auth. The auth triggers an OIDC auth flow, meaning it sets two cookies on the site domain (a nonce, and a correlation cookie).
2. Site redirects to the OIDC login provider via a redirect to the `authorize` endpoint of OpenId Connect, including the nonce value set in a cookie at the site.
3. The OIDC login provider validates and renders the login view
4. After login, the OIDC provider redirects back to a configured signin-callback endpoint at the site, including the nonce and correlation values.
5. At the callback, the site validates the nonce and correlation values against the value stored in the nonce cookie and correlation cookie.


Sample showing requests up to the login UI being rendered:
```
GET /some-path-behind-auth HTTP/1.1
Host: www.mydomain.com

Response:
HTTP/1.1 302 Found
Date: Tue, 26 Nov 2019 18:32:23 GMT
Location: https://id.mydomain.com/oauth2/connect/authorize?<queryparams>
Set-Cookie: .AspNetCore.OpenIdConnect.Nonce=N; expires=Tue, 26 Nov 2019 18:47:23 GMT; path=/signin-callback; secure; httponly
Set-Cookie: .AspNetCore.Correlation.OpenIdConnect=N; expires=Tue, 26 Nov 2019 18:47:23 GMT; path=/signin-callback; secure; httponly

Request:
GET /oauth2/connect/authorize?<queryparams>
Host: id.mydomain.com
Referer: https://www.mydomain.com/some-path-behind-auth

Response:
HTTP/1.1 302 Found
Date: Tue, 26 Nov 2019 18:31:40 GMT
Location: https://id.mydomain.com/oauth2/account/login?<query-params>

Request:
GET /oauth2/account/login?<query-params>
Host: id.mydomain.com
Referer: https://id.mydomain.com/oauth2/connect/authorize?<query-params>

Response:
HTTP/1.1 200 OK
Set-Cookie: .AspNetCore.Antiforgery=<value>; path=/oauth2; samesite=strict; httponly

<html>
login ui
</html>
```

At this point:

Expected:
`jar.cookiesForURL('https://www.mydomain.com/signin-callback')` => to have the nonce/correlation cookies, 

but instead, the actual behaviour is that it sets the cookies on the right _path_ , but on the wrong domain:

`jar.cookiesForURL('https://id.mydomain.com/signin-callback')` => has the nonce/correlation cookies.

**Comment by johnkors** [comment]
Update: Seems to be fixed in `loadimpact/k6:master` :)

**Comment by sneko** [comment]
@johnkors I'm looking to pass through my OIDC flow with k6 to reach my API endpoints for load testing.

Could you please share an example of what you set up to init the "client", then triggering an authentication flow...?

Thank you,

**Comment by 303sunnyjoy** [comment]
315137ae19d2ff8ec8b126bd07e93ec25166681a/csh.cshrc

**Comment by johnkors** [comment]
No, sorry.
