### ISSUE TITLE
Config/options file composition

### ISSUE THREAD

**Issue by brodul** [loadimpact/k6#1277]
I noticed that configuration in k6 can be quite tricky ( #883 ). Consider this ticket more as an idea how to configure options in more advanced cases. Feel free to close the issue.

## Our use-case

In our case we define the "user" setting (endpoints URL, ...) in a setup function.
The functions (e.g. `testing`) the create a `setting` object that is then referenced by `scenario` function.

```
export function setup () {
  switch (__ENV.ENV) {
    case 'staging':
      return staging()
    case 'testing':
      return testing()
    case 'local':
      return local()
    case 'docker':
      return docker()
    default:
      return testing()
  }
}

export default scenario
```

We could do similar logic for option and create an `options` object dynamical and then export it.
We need to have different stages objects, depending on what/which env we test.

## Something to think about

But I wonder if composition of config JSON files would be an option. e.g.

`ramp_up_to_40.json`
```json
{
  "stages": [
    { "duration": "0m", "target": 0 },
    { "duration": "10s", "target": 5 },
    { "duration": "10s", "target": 10 },
    { "duration": "10s", "target": 15 },
    { "duration": "10s", "target": 20 },
    { "duration": "10s", "target": 25 },
    { "duration": "10s", "target": 30 },
    { "duration": "10s", "target": 35 },
    { "duration": "10s", "target": 40 },
    { "duration": "3m", "target": 0 }
  ]
}
```

`stats_type_A.json`
```json
{
    "summaryTrendStats": [
        "min",
        "max",
        "med",
        "p(70)",
        "p(90)",
        "p(95)",
        "p(99)"
    ]
}
```

Currently you can not specify multiple config files e.g. (`... -c configs/ramp_up_to_40.json -c configs/stats_type_A.json`). Maybe merging json files and overriding the first level key/value pair would add better options management for K6 ... maybe not.

**Comment by na--** [comment]
@brodul, sorry for the late answer. Have a look at this example script I gave a few months ago: https://github.com/loadimpact/k6/issues/1101#issuecomment-518172431

In essence, you can encode all sorts of different options in one or more `.json` files. Then you can just give the file name as an environment variable to k6, and just `open()` and `JSON.parse()` the contents of these files to get the options you want. With this approach, you should be able to implement any merging strategy you want... Would something like this be sufficient for you?

**Comment by brodul** [comment]
That will do it. I have never thought of it. Tnx @na--
