### ISSUE TITLE
error building Dockerfile

### ISSUE THREAD

**Issue by NatashaKramarenko** [loadimpact/k6#1297]
Hi Team,

I need to customise Dockerfile to install aws client, so I added a couple lines to the Dockerfile:

```
FROM golang:1.13-alpine as builder
WORKDIR $GOPATH/src/github.com/loadimpact/k6
ADD . .
RUN apk --no-cache add git
RUN CGO_ENABLED=0 go install -a -trimpath -ldflags "-s -w -X github.com/loadimpact/k6/lib/consts.VersionDetails=$(date -u +"%FT%T%z")/$(git describe --always --long --dirty)"

FROM alpine:3.10
RUN apk add --update --no-cache ca-certificates python py-pip
 # Install AWS CLI
RUN  pip install --upgrade awscli
 # Basic check it works
RUN  aws --version

COPY --from=builder /go/bin/k6 /usr/bin/k6
ENTRYPOINT ["k6"]
```

When building the image I get the error:
**fatal: not a git repository (or any of the parent directories): .git
can't load package: package github.com/loadimpact/k6: no Go files in /go/src/github.com/loadimpact/k6**

Please advise how to fix it.

Note: running prebuilt image works fine
docker run -i loadimpact/k6 run - <script.js

**Comment by cuonglm** [comment]
Hi @NatashaKramarenko, did you run it inside root `k6` cloned repo?

**Comment by NatashaKramarenko** [comment]
No, and I would like to be able to run it anywhere

**Comment by cuonglm** [comment]
@NatashaKramarenko 

> No, and I would like to be able to run it anywhere

We can't get this thing at this moment. If you look at `Dockerfile`, you can see `ADD . .` step, which will add `k6` source code to the container, then we can start build `k6` from there.

**Comment by NatashaKramarenko** [comment]
@cuonglm , can't that be something like

```
...
WORKDIR $GOPATH/src/github.com/loadimpact/k6
RUN apk --no-cache add git
RUN git clone https://github.com/loadimpact/k6.git
...
```

instead?

**Comment by cuonglm** [comment]
> @cuonglm , can't that be something like
> 
> ```
> ...
> WORKDIR $GOPATH/src/github.com/loadimpact/k6
> RUN apk --no-cache add git
> RUN git clone https://github.com/loadimpact/k6.git
> ...
> ```
> 
> instead?

Maybe, but it defeats the purpose of `Dockerfile`, since when it's for you to quickly testing your current *local* development, or building new release.

We can add another docker file to always clone from remote repo. Any idea @na-- ?

**Comment by na--** [comment]
@NatashaKramarenko, do you actually need to customize our `Dockerfile`? Can't you just build your custom image on top of our official Docker image? Like this:
```dockerfile
FROM loadimpact/k6:latest
RUN apk add --update --no-cache ca-certificates python py-pip
RUN pip install --upgrade awscli
RUN aws --version
```

Or, build your Docker image on top of some other image, and just copy the k6 binary from the official image in your own:
```dockerfile
FROM whatever:latest
# ...
COPY --from=loadimpact/k6:latest /usr/bin/k6 /usr/bin/k6
RUN k6 version
# ...
RUN apk add --update --no-cache ca-certificates python py-pip
RUN pip install --upgrade awscli
RUN aws --version
```

In any case, I'm firmly against us adding a separate `Dockerfile` to the k6 repo. If you need to build the k6 docker image yourself, you obviously need to have the k6 code there, so I don't see the need to change our current `Dockerfile` in such a way or add a separate one. If both of the alternative options I presented above don't suffice, and you **need** to build k6 yourself, I think it's fair that you'd have to maintain your own copy of the custom `Dockerfile`.
