### ISSUE TITLE
Windows not so pretty-printed

### ISSUE THREAD

**Issue by micsjo** [loadimpact/k6#131]
We will need to un-pretty cmd line output from the windows build.

![image](https://cloud.githubusercontent.com/assets/9320411/23298760/2a75dfc8-fa7f-11e6-9b0a-27c338ba460b.png)

**Comment by uppfinnarn** [comment]
Does this fix it? 003d13ace7b01d1b40f0df32072cdc9bfa8ce9de

**Comment by micsjo** [comment]
Yes but logging still has the same problem.

**Comment by uppfinnarn** [comment]
You're getting control characters in log messages? Could you try updating `github.com/Sirupsen/logrus`, because that shouldn't happen…

**Comment by micsjo** [comment]
Same thing, no difference. Cleaned out, got everything fresh, still the same.

![image](https://cloud.githubusercontent.com/assets/9320411/23609715/a0dfd2c0-026f-11e7-8940-a4aca25f7400.png)

**Comment by liclac** [comment]
Is this still an issue?

**Comment by ppcano** [comment]
Old ticket, a8265cb1b20feeda9bf6d00e75d36dcbeeb36d9c could have solved the same issue on the latest version. Closing it.

Reopen if necessary.
