### ISSUE TITLE
Ability to set LoadImpact "Test Run Note" through "options.ext.loadimpact"

### ISSUE THREAD

**Issue by SteveLeach-Keytree** [loadimpact/k6#1330]
## Feature Description
You can currently set the LoadImpact project ID with options.ext.loadimpact.projectID, and you can manually add a test run note to the test using the LoadImpact web user interface.
It would be really helpful if we could also set the test run note using something like "options.ext.loadimpact.note".

**Comment by MStoykov** [comment]
Hi, this sounds like a good idea, but technically `options.ext.loadimpact` is something that `loadimpact.com` parses, so not a k6 feature request ;).

Load Impact does have an [idea board](https://loadimpact.ideas.aha.io/) so you can propose it there :D 

I am closing this as this is not a k6 issue :D
