### ISSUE TITLE
Remove BBC site from samples

### ISSUE THREAD

**Issue by aidylewis** [loadimpact/k6#1334]
We have the BBC main URL on the HTTP/2 sample https://github.com/loadimpact/k6/blob/cd557cf73410be31e0ab68cce2ad0f71d3fb9137/samples/http_2.js

Can we have that URL removed please?

**Comment by MStoykov** [comment]
Hi, I took a look around and it looks like [you added it](https://github.com/loadimpact/k6/pull/319) a couple of years ago?
I don't get that PR but in all cases, if you can make a PR changing the BBC URL to be 'k6.io' for example that will be great ;)

**Comment by aidylewis** [comment]
Do you want me to add to your main site? Have you not got a noddy site, to exercise some k6 features against which will not affect your business?

**Comment by MStoykov** [comment]
I highly doubt that someone running this script will affect the site ... and if it does we have much bigger problems :wink: . But if you so want there is https://test.loadimpact.com :)

**Comment by safebear** [comment]
I've found this test site to be really useful: https://test-api.loadimpact.com/ and use it when training people. Is it ok to still use that one?

**Comment by simskij** [comment]
> I've found this test site to be really useful: https://test-api.loadimpact.com/ and use it when training people. Is it ok to still use that one?

Sure, go for it! That's why it's there! 😄

**Comment by na--** [comment]
Closed by https://github.com/loadimpact/k6/pull/1337
