### ISSUE TITLE
HTTP API route for aborting execution

### ISSUE THREAD

**Issue by hynd** [loadimpact/k6#1352]
I run load tests on a remote instance(s) with no SSH access.  If a test goes awry, i'd like to be able to terminate it as quickly as possible and shutting down the instance can sometimes take several seconds/minutes.  The HTTP API is great for pausing/resuming tests quickly - it would be nice and tidy if i could also abort a test in the same way (which in my case leads to the output being saved and the instance terminated).

## Suggested Solution (optional)
I see the various `context`s in play, but no easy path to cancel the parent created in the run cmd from the http API.  The existing OS interrupt/term signal handling is graceful enough, but forcing a signal back into the process from the API feels wrong, and (i think) lacks some support on Windows.

Would simply adding a bool to the Engine struct and testing for it at the end of the `select` in Engine.Run() (https://github.com/loadimpact/k6/blob/new-schedulers/core/engine.go#L222) be an option you'd consider?

If so, any suggestions for the HTTP route (ie; adding to the `/status` PATCH, or a new route/different verb?)

**Comment by na--** [comment]
> Would simply adding a bool to the Engine struct and testing for it at the end of the `select` in Engine.Run() (https://github.com/loadimpact/k6/blob/new-schedulers/core/engine.go#L222) be an option you'd consider?

hmm... that could work, though yous shouldn't add a `bool`, as that wouldn't be thread safe. You can create a [signal channel](https://medium.com/@matryer/golang-advent-calendar-day-two-starting-and-stopping-things-with-a-signal-channel-f5048161018) in `NewEngine()` and a new `Engine.Stop()` method that closes that channel.

**Comment by hynd** [comment]
Great, that seems to work as expected...
Any preference for the API route? (i added it to the `/status` PATCH route for now).

**Comment by na--** [comment]
Closed by https://github.com/loadimpact/k6/pull/1355 (wasn't auto-closed, because the PR was merged in #1007, not `master`)
