### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#1357]
Just a list of tests we have noticed are flaky in CI runs, so we don't forget to fix/refactor them before merging #1007 in `master`:

`TestVariableLoopingVUsRun` - https://ci.appveyor.com/project/robingustafsson/k6/builds/31408611

**Comment by na--** [comment]
`TestVariableLoopingVUsRampDownNoWobble` - https://circleci.com/gh/loadimpact/k6/9110

**Comment by imiric** [comment]
I refactored these two tests and they seem more stable, but while stress testing `lib/executor`, I've also seen these fail occasionally:

- `TestPerVUIterationsRunVariableVU`
- `TestConstantArrivalRateRunCorrectRate`
- `TestExternallyControlledRun`

Will look into them next before creating a PR for this.

**Comment by MStoykov** [comment]
they will probably get changed with the striping algorithm and rewrite so maybe just wait until then ?

**Comment by imiric** [comment]
Another one :disappointed:: `core.TestMetricsEmission`: https://circleci.com/gh/loadimpact/k6/9243

**Comment by na--** [comment]
Another `TestConstantArrivalRateRunCorrectRate` failure: https://circleci.com/gh/loadimpact/k6/9464

**Comment by na--** [comment]
`TestExternallyControlledRun` flakiness: https://circleci.com/gh/loadimpact/k6/9530

**Comment by na--** [comment]
Food for thought: https://dmitryfrank.com/articles/mocking_time_in_go (from https://news.ycombinator.com/item?id=23292215)

**Comment by imiric** [comment]
I'm exploring that article and the `time` mocking packages, but one thing concerns me, mentioned in https://github.com/golang/go/issues/8869:

> The benbjohnson clock package attempts to make Ticker and Timer calls (as well as their
> related AfterFunc and Sleep methods) work against a fake time that can be set and
> updated in tests. _However, it relies on some micro-sleeps and runtime.Gosched calls that
> are obviously going to be flaky._

It would be a substantial effort to convert the entire codebase to use this `Clock` interface. Is that really worth it if it doesn't guarantee deterministic tests?

Also see https://github.com/grafana/metrictank/pull/342, where they abandon it altogether.

The article author uses a [fork](https://github.com/dimonomid/clock) where this might not be an issue(?), but not sure if this can be fixed outside of the stdlib.
So I think the way forward will be much harder: rewriting tests to ensure they rely on timing as little as possible or not at all, which might be impossible in some cases. I'll take a look at some of the current ones and see what can be done.

**Comment by imiric** [comment]
A recently added one: `TestConstantArrivalRateDroppedIterations`, seems to fail frequently:

https://ci.appveyor.com/project/robingustafsson/k6/builds/33999101
https://ci.appveyor.com/project/robingustafsson/k6/builds/33998965

**Comment by na--** [comment]
I'm closing this, since most, if not all, of these tests should have been fixed by now. We can make new issues for every new flaky test we find.
