### ISSUE TITLE
Filesystem abstraction

### ISSUE THREAD

**Issue by uppfinnarn** [loadimpact/k6#136]
Look at [afero](https://github.com/spf13/afero) for instance. This will not only make unit testing a lot easier and cleaner, but also give us flexibility to load from other sources than the local filesystem (such as for distributed execution).

This would deprecate the SourceData struct.

**Comment by adr0sen** [comment]
@uppfinnarn - just to clarify, this would allow for passing in e.g. HTTP-hosted script-files to k6, as we discussed last week?

**Comment by adr0sen** [comment]
@uppfinnarn - ping on above question. Can you pls confirm? If this is not the case, I will create separate issue.

**Comment by uppfinnarn** [comment]
Sorry, I missed this. Yes, it will allow us to pass in files from anywhere, as long as there is a corresponding filesystem backend (a simple interface implementation) or it can be put on an in-memory filesystem. Filesystem compositing is also possible, eg. overlaying the contents of multiple filesystems.

There's no support in the application *yet* for importing files from the internet though, I believe the cleanest point of integration is after I finish #137; my local code already has an import system designed with virtual filesystems and remote sources in mind.
