### ISSUE TITLE
Improve windows automatic builds 

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#1360]
Currently, the AppVeyor windows build doesn't tag the executable properly: https://github.com/loadimpact/k6/blob/eebe92dbf587f81d057663cd6a17b607c1144682/appveyor.yml#L55
so the full version info will feature `dev build`. 

Also, the way the Go version is specified, we wouldn't get the latest minor release for the specified version, but this exact minor version, which is probably not what we want... https://github.com/loadimpact/k6/blob/eebe92dbf587f81d057663cd6a17b607c1144682/appveyor.yml#L33-L34

**Comment by MStoykov** [comment]
I think this was fixed when we moved to github actions?
