### ISSUE TITLE
JUnit Results Output

### ISSUE THREAD

**Issue by simskij** [loadimpact/k6#1366]
## Feature Description

There is currently [a community provided tool](https://github.com/Mattihew/k6-to-junit) that converts k6 output to JUnit result files. It would likely be a lot more convenient, less error-prone, and future proof if this was an actual result output of the k6 tool instead.

Further, this would be a nice addition to the tool as it would allow us to visualize test results in codacy, sonarqube, etc. just as we do with unit tests.

**Comment by na--** [comment]
This is somewhat of a duplicate for https://github.com/loadimpact/k6/issues/1120, if more concisely stated. Also, regarding actually implementing this, https://github.com/loadimpact/k6/issues/1319#issuecomment-600785814 seems like a nice way to go about it.

**Comment by simskij** [comment]
Agreed. Seems like the most straightforward way to do it.

**Comment by simskij** [comment]
Closing this in favor of #1120
