### ISSUE TITLE
Reworked JS runner

### ISSUE THREAD

**Issue by liclac** [loadimpact/k6#137]
I have a couple of design goals for this:

* Based on [goja](https://github.com/dop251/goja), which gives us better optimization options than otto.
* Remove the confusing Runtime/Runner distinction.
* Split the monolithic `API` object, it should in itself deal only with core behavior such as groups and checks, everything else should be in subpackages and registered with a module registry.
* You should be able to PR new modules with only a single-line modification to the `js` package, and everything else self-contained.

I'm doing some preliminary work on this right now, putting this out here for discussion.

**Comment by diego-plan9** [comment]
Once the reworked JS runner is in place, would one of the side effects be that `goja` would completely replace `otto` in `k6`, or would `otto` still be a dependency?

I'm asking from the point of view of planning the debian packaging - neither of them are on the repositories and would need to be packaged, and if `otto` is to be removed in the future (whenever that future is!) it would help me with prioritizing the tasks involved.

**Comment by uppfinnarn** [comment]
Yeah! Using goja is way faster for what we're using it for, so I want to move everything to it. ES6 compilation is already on goja (as otto's regex implementation run Babel), the remaining bits of otto code are the JS runner and thresholds.
