### ISSUE TITLE
k6 cloud --quiet exits immediately after the test run starts

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#1371]
This check: https://github.com/loadimpact/k6/blob/4c7c4bf135a8b68a77549484d2a627fee4128570/cmd/cloud.go#L191-L193

causes `--quiet` to exit the `k6 cloud` process prematurely. This may sometimes be useful, but we have another option that is specifically meant for that, `k6 cloud --exit-on-running`, so we should fix this.

**Comment by qcastel** [comment]
To give a bit more context on why I was trying to use this option and hit that bug:

When you run K6 cloud from a CI, the progression bar is spamming the CI log. As we are limited on the number of logs we can do in CI, I was interested to avoid having those progressing logs.

![Screenshot 2020-10-30 at 11 22 54](https://user-images.githubusercontent.com/3748231/97699661-6ff0ac80-1aa2-11eb-8b9c-1156d1a1c03b.png)
