### ISSUE TITLE
http.request/http.batch don't check the method string

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#1378]
if you run 
```
  const response = http.request("get", url);
```
you will either:
1. if http1 - get 400 (probably dependant on the implementation
2. if http2 - get `WARN[0001] Request Failed                                error="get \"https://test-api.k6.io/\": stream error: stream ID 1; PROTOCOL_ERROR"`

This is easily fixed by uppercasing get to GET :smile:, but I would argue that we probably don't want to proceed if the method is one we don't recognize either way ...

**Comment by na--** [comment]
hmm I think I remember seeing custom HTTP methods a long time ago for HTTP 1.1, so I'm not sure if we should only allow a certain set of valid methods... :confused: I have nothing against converting the supplied method to uppercase though, honestly I'm a bit surprised that Go doesn't do it automatically. In any case, some RFC reading is probably required here.

**Comment by asettouf** [comment]
@na--  That's the closest I could find: https://tools.ietf.org/html/rfc7231#section-4

I think the most interesting part is `Additional methods, outside the scope of this specification, have been standardized for use in HTTP.` So I guess keeping the way it is, and perhaps having a clearer error message would make sense?

**Comment by imiric** [comment]
Also note the continuation to that:

> All such methods ought to be registered within the "Hypertext Transfer Protocol (HTTP) Method Registry" maintained by IANA, as defined in Section 8.1.

"Ought" is very vague in an RFC, so I doubt most implementations bother. But [the registry](http://www.iana.org/assignments/http-methods/http-methods.xhtml) has a bunch of other methods, all uppercase.

And also according to the RFC (paragraph below), the server should either respond with `501 Not Implemented` or `405 Method Not Allowed`, so I don't think we should do anything about this. It's up to the client/user to use the correct method, including casing, and up to the server to respond accordingly.

**Comment by asettouf** [comment]
@imiric Indeed, I was mostly arguing for the "standard cases" to have a message `You used 'get', did you mean 'GET' ?` which could be useful (a bit like git)

**Comment by na--** [comment]
hmm I don't have the time to delve into this issue right now, but it seems to me that `stream error: stream ID 1; PROTOCOL_ERROR` is an error from the Go standard library, not from the remote server. So... if the Go stdlib can't handle lowercase methods, we probably should automatically uppercase them, since they'd never reach any remote server anyway? So maybe we can allow any strange method name, as long as we upper-case it? Or am I completely wrong or missing something here?

**Comment by asettouf** [comment]
@na--  I quite agree with @imiric  where it's up to the client to decide on the method, including the casing. If the remote server for whatever reason accepts lower case methods (whether `get` or `foo`), I don't think we should impose upon clients to upper case the method name used.

**Comment by na--** [comment]
I'm sorry, from just reading the issue I was under the impression that this was a client error, i.e. the request never reached the remote server. But now I actually tried it and remote servers just return 400 when a lower-case method name is used... :blush: Which is fine, and I agree, we shouldn't enforce anything on the k6 side. So... we should just close this issue? @MStoykov, as the one who opened this, please close it if you agree :smile:

**Comment by na--** [comment]
Closing because of no response...  :stuck_out_tongue_closed_eyes: @MStoykov, please reopen if you disagree :rofl:
