### ISSUE TITLE
Refactor/rename lib.ExecutionTuple

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#1379]
The name is ... not very helpful but is a lot shorted then `lib.ExecutionSegmentAndSequence`, which I would argue is nearly as useless as a description :rofl: 
I would argue some additional refactor can be done once it has been used everywhere it needs to be and we know what the actual use cases for it are ...
The same goes for the `lib.sortInterfaceWrapper`

**Comment by na--** [comment]
Something else we should look into is refactoring the segmented iteration from https://github.com/loadimpact/k6/pull/1392 into its own thing, probably somewhat connected to the execution tuple, so we can reuse it for striped iteration over data arrays/streams.

**Comment by MStoykov** [comment]
I am closing this as things have changed and I consider this done
