### ISSUE TITLE
performance.now() resets on every script iteration

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#138]
Having a default function that just prints out the value returned by performance.now() results in output like this:

```
INFO[0003] 0.008104                                     
INFO[0003] 0.008502                                     
INFO[0003] 0.007793                                     
INFO[0003] 0.008227                                     
INFO[0003] 0.007951                                     
INFO[0003] 0.008384
```

For my particular use-case, this is bad. I want to use performance.now() to regulate the RPS rate of my load test - specifically how much time the VU should be sleeping in each script iteration, before executing an HTTP request. The only way I can use performance.now() as it is, is to let my default function contain an infinite loop, which means I will only ever run one iteration (that doesn't complete). Feels wrong, somehow!

My spontaneous thought is that it makes more sense to keep performance.now() state in between iterations.

**Comment by uppfinnarn** [comment]
This is entirely by design, as it mimics how `performance.now` counts in a browser (from the time of the page load). I can see what you're doing, but a JS hack is really not the way to do it.

**Comment by uppfinnarn** [comment]
I realize that there's some internal context I didn't communicate properly here. RPS steering will be part of the core soon, and implementing that seems like it'd be more productive than changing `performance.now()`'s behavior to allow hacking it into a script.

I'm not a huge fan of the idea of making this sticky throughout the whole test, because what that would allow is persisting a reference point outside of the VU context and comparing durations between iterations. This will bite you if you remove some VUs, then add them back. VUs are recycled, and if one has been sleeping for an arbitrary amount of time, you'll end up with a very big time step that will likely mess up your calculation.

**Comment by ragnarlonn** [comment]
Point 1 is taken (though it would be nice to understand roughly what "soon" means here).

On the second point, however, I'd like to just figure out if the current behaviour of performance.now() is desirable. Is it intuitive and useful?  Because if it isn't, then we should at the very least make a note (issue) about wanting to change it. Also, I didn't know that VU state was kept when recycling VUs - that is interesting and maybe not so intuitive to users (I would at least have expected a newly added VU to start its first iteration, not continue on iteration X from a previous time when it was active).

**Comment by uppfinnarn** [comment]
You were the one who asked for it, so you could use it to measure how long things took for which metrics weren't emitted.

Also yeah, it specifically resets the VU ID and the iteration counter, but keeps the rest around for performance reasons; if we initialize all our VUs upfront and recycle, we precompute a lot of CPU-bound work and don't get spikes in response times at the start of the test or when scaling up.

**Comment by micsjo** [comment]
If VU state is kept between iterations it makes very interesting things
like obeying cache directives possible! Highly desireable.

/Michael

Den 7 mars 2017 10:13 em skrev "ragnarlonn" <notifications@github.com>:

**Comment by ragnarlonn** [comment]
@micsjo most VU state is already kept between iterations of course, but I guess you meant the state of the performance.now() counter?  Would persisting it between iterations help obey cache directives?  Do you need a high-resolution clock for that?

@uppfinnarn Did I ask for it to start at zero at each iteration?  Or actually, don't answer that - I wouldn't be surprised if I did ;) but it is beside the point. I have been wrong before and I will be wrong many times in the future. It has no bearing on what the best solution is - and that is the only thing I want to figure out. My feeling is that a high-resolution clock like performance.now(), but which counts elapsed time since the VU was "started", persisting across script iterations, is more intuitive and useful than a clock that resets every script iteration (but it is not unlikely that both types of clocks would be useful).

**Comment by ragnarlonn** [comment]
Here is another use case for a state-keeping performance.now(): a user would like to control the RPS rate for a certain HTTP request, while executing a user scenario that performs many HTTP requests. This is not possible with a global RPS controlling mechanism, which will affect all transactions. 

My guess is that if we can find a couple of use cases for keeping state of the perf counter, there are probably several more out there.

**Comment by uppfinnarn** [comment]
RPS limiting should be implemented in a way that flexibly deal with this, I think - maybe a threshold-like syntax?

```js
export let options = {
    limits: {
        http_reqs: "300/s",
        "http_reqs{kind:static}": "5000/s",
    }
}
```

**Comment by ragnarlonn** [comment]
Sure, if there is a way to implement that without spending a ton of work on it. It (i.e. being able to limit RPS rates granularly, per URL) is not a feature that will be used by a majority of people, and I think it might be quite tricky to do a generic implementation for it. How do you handle this:
```
export let options = {
   limits: {
      "http_reqs{url:http://loadimpact.com}": "300/s",
      "http_reqs{url:http://loadimpact.com/bohoo}": "50/s"
   }
}
export default function() {
   http.get("http://loadimpact.com");
   http.get("http://loadimpact.com/bohoo");
}
```

How would you handle that case in the engine?   Maybe you already have some clever scheme thought out, but I would go for the simpler option of letting the user do this type of RPS limiting themselves, if they want it, in JS code. I would just provide a generic RPS rate limiter that guaranteed not to generate transactions above a certain rate and which blocked any http.x calls until the accepted inter-request interval time has passed since the last request was made.
