### ISSUE TITLE
Move util functions implemented in k6-util jslib to the built-in modules.

### ISSUE THREAD

**Issue by simskij** [loadimpact/k6#1384]
https://github.com/loadimpact/jslib.k6.io/pull/3#event-3195259212 adds `randomInBetween`, `randomItem` and `uuidv4` as a utility lib implemented in javascript. This should be implemented as a built-in module instead, preferably `k6/util` or similar.

## Feature Description
As these functions, according to @sniku, are commonly used by users who just copy-paste the code between different test scripts, I think it would make sense if they instead were part of the k6 API and implemented in go.

**Comment by na--** [comment]
Hmm while @robingustafsson convinced me that we need a URL API built into k6 yesterday (https://github.com/loadimpact/k6/issues/991#issuecomment-767572138), I am far from convinced we need this baked into k6.

Taking stock of the functions (https://github.com/loadimpact/jslib.k6.io/blob/master/lib/k6-utils/1.0.0/index.js), we have:
- 3-line generation of UUIDv4 that I'm not sure is actually correct
- 1-line opinionated (`min and max included`) helper
- 1-line helper that most people just manually inline...

If someone is behind a firewall or can't make network requests to [jslib.k6.io](https://jslib.k6.io/) to `import "https://jslib.k6.io/k6-utils/1.0.0/index.js"` for some reason, they can trivially copy-paste (or `git clone` and import locally) these or write them from scratch in under a minute... So, as things stand, :-1: for bundling them. @MStoykov, @imiric, thoughts?

**Comment by MStoykov** [comment]
I have always been, and if anything I have only started being more, for only the things that *MUST* be in k6 to be in k6 ;)

**Comment by imiric** [comment]
Agree with @na--, these are trivial to inline or import from jslib if needed. Including them in k6 core would open the door for more of jslib to creep into k6, and we have to draw the line somewhere.

It might make sense for big libs like the URL parsing one that are crucial in some situations, and even then we should try to trim them down or re-implement them in Go.
