### ISSUE TITLE
I want to change the PORT that grafana uses - I already have 3000 port where my app UI is running. 

### ISSUE THREAD

**Issue by pawansinha0612** [loadimpact/k6#1388]
I want to change the PORT that grafana uses - I already have 3000 port where my app UI is running. 
How can I change the port for grafana to use 3002 while integrating with GRAFANA and InfluxDB.

Where should i change in the code to run this.

**Comment by imiric** [comment]
If you're using Docker, you can change the host port for Grafana in the [`docker-compose.yml`](https://github.com/loadimpact/k6/blob/dfefce7dbdf7a42ff2c1599df95bc055441341b3/docker-compose.yml#L23) to e.g. `3002:3000`.

Closing this is as it's not a k6 feature. For support, please use the [community forum](https://community.k6.io/).
