### ISSUE TITLE
Update example scripts for new test.k6.io site

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#1400]
The old 90s test.loadimpact.com site has been updated, and now lives at https://test.k6.io, so we have to update our example scripts (including the README)

**Comment by ppcano** [comment]
I think we should remove the `samples` folder and move the focus to https://k6.io/docs/examples

We ported a few of these examples on the `samples` folder to the `examples` page of the documentation. Not sure if we should port more of them.

**Comment by na--** [comment]
I personally like to have the samples in the k6 repo. Maybe we can prune some of them, and improve others, but I don't see a huge issue of having a few simple scripts. We can always add a `README.md` in the `samples/` folder that points to the big list in https://k6.io/docs/examples

Having them in the k6 repo allows simple `k6 run github.com/loadimpact/k6/samples/whatever.js` demos, is personally useful for me when developing k6, and would also probably be useful for https://github.com/loadimpact/k6/issues/625.
