### ISSUE TITLE
http-debug enabled shouldn't exit the script on errors ... ever 

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#1402]
Currently, if http-debug is set and the dumping of the [request](https://github.com/loadimpact/k6/blob/7e4309c3e77f2d196628d6f440da14a44a9a796c/lib/netext/httpext/httpdebug_transport.go#L53) or [response](https://github.com/loadimpact/k6/blob/7e4309c3e77f2d196628d6f440da14a44a9a796c/lib/netext/httpext/httpdebug_transport.go#L62) results in an error k6 will exit with status code 1 ... which is unlikely to be what anyone wants ...

**Comment by berndhartzer** [comment]
Is there some specific functionality needed to fix this, or is it just a matter of swapping `Fatal()` (which calls `os.Exit(1)`) with a different log level, such as `Error()` or `Warn()`?

**Comment by MStoykov** [comment]
No, it is just swapping it, I think. I don't know whether Error or Warn is better though :man_shrugging: 

You are welcome to make a PR, but we are currently working on PR 1007 (not linking it as it is huge as it is) and given that this bug has been this way for way too long, it seems unlikely we will once again stop working on 1007 to fix it, release it and then go back, as I've explained in other currently open PRs :(.

**Comment by berndhartzer** [comment]
Ok cool, thanks. Well I made a PR. In the end I thought `Error()` is a better choice because it is dumping out an error. Happy for any feedback of course!
