### ISSUE TITLE
Improve synchronization around VU reuse and interruption

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#1404]
This example Go code tries to emulate what we'll do with VU reuse after https://github.com/loadimpact/k6/pull/1368

```go
package main

import (
	"context"
	"fmt"
	"log"
	"math/rand"
	"os"
	"sync"
	"sync/atomic"
	"time"
)

const concurrentVUs = 1000

func VUEmulation(logger *log.Logger, r *rand.Rand) {
	runMutex := sync.Mutex{}
	interrupted := new(int32)
	returned := new(int32)

	ctx, cancel := context.WithTimeout(context.Background(), time.Duration(r.Intn(1000))*time.Millisecond)
	defer cancel()

	go func() { // activation function
		<-ctx.Done()
		logger.Print("Context expired, interrupting the execution")
		atomic.StoreInt32(interrupted, 1) // simulate u.Runtime.Interrupt()

		runMutex.Lock()
		atomic.StoreInt32(returned, 1) // simulate params.DeactivateCallback(), i.e. returned to VU pool
		runMutex.Unlock()
	}()

	// looping vu emulation
	for i := 0; ; i++ {
		runMutex.Lock()
		logger.Printf("Running iteration %d...", i)
		if atomic.LoadInt32(returned) > 0 {
			logger.Fatalf("Running an iteration on an already returned VU")
		}
		select { // pretend interruptible work
		case <-time.After(time.Duration(r.Intn(1000)) * time.Microsecond):
		case <-ctx.Done():
		}
		runMutex.Unlock()

		if atomic.LoadInt32(interrupted) > 0 {
			logger.Print("VU was interrupted, stop looping")
			return
		}
	}
}

func main() {
	wg := sync.WaitGroup{}
	wg.Add(concurrentVUs)
	seedBase := time.Now().UnixNano()

	for i := int64(1); i <= concurrentVUs; i++ {
		logger := log.New(os.Stdout, fmt.Sprintf("[VU %05d] ", i), log.Lmicroseconds)

		logger.Printf("Seeding random source with %d", seedBase+i)
		r := rand.New(rand.NewSource(seedBase + i))

		go func() {
			VUEmulation(logger, r)
			wg.Done()
		}()
	}
	wg.Wait()
}
```

It's a somewhat naive, but, I hope, roughly accurate, representation of the current code logic, without any JS runtimes to complicate things. And from my testing, I managed to reach the fatal case, `Running an iteration on an already returned VU`, only a few times out of a few dozen executions. But it's still not 0, so my suspicions that a simple mutex would be insufficient for proper synchronization, appear to be true. 

(hint: to make it fail very often, and for easier running, remove all `logger` invocations except the `logger.Fatalf()` one and increase `concurrentVUs` to 50000)

In any case, we can come back and fix this properly after everything else is ready. Probably using a `select` with a channel, to represent the fact that a VU might or might not be running when the context is done.

**Comment by MStoykov** [comment]
Increasing `GOMAXPROCS` a lot (512 on 8 core machines works great :) ) also increase the chance

**Comment by na--** [comment]
Closed by https://github.com/loadimpact/k6/pull/1424
