### ISSUE TITLE
k6 "native" mode for performance testing/modeling around r/s

### ISSUE THREAD

**Issue by adr0sen** [loadimpact/k6#141]
Modeling of testing and load generation in k6 is currently based on the concept of virtual users (vu), i.e. concurrent simulated users. Once a vu is instantiated with a given script, it will run to completion and then re-instantiate another iteration, until duration of test is complete. This allows for users to assess and validate their system scalability based on how many concurrent users it can handle.

A similar but also very different mode of modeling performance testing and quantifying scalability of a system is in terms of throughput, or rather requests/second (r/s). This is very commonly used and referenced in scope of e.g. API-testing.

There are _"clunky"_ ways to model r/s-based testing using vus, by dynamically sleeping in script relative to response times and desired throughput. See e.g. http://support.loadimpact.com/knowledgebase/articles/861396-how-to-load-test-an-api for a less than desired example of how we currently solve this for our Lua-based infrastructure.

Other aspects worth considering with respect to r/s-based testing is the problem of Coordinated Omission, see https://groups.google.com/forum/#!msg/mechanical-sympathy/icNZJejUHfE/BfDekfBEs_sJ. It would be desired if the capability to model testing by throughput and r/s in k6 would solve or at least attempt to mitigate the Coordinated Omission problem.

For k6, ideally we'd want a "native" CLI/scripting-interface and output that supports modeling around r/s, rather than vus (cli-options, scripting-options e.g. stages, REST API endpoint). In essence, this means we need supporting infrastructure to dynamically scale the number of concurrently executing scripts to constantly satisfy the desired generated throughput. 

Internal to Load Impact, this will have an effect on k6 cloud services, result management, presentation and cloud execution. Once we have made progress on the k6 design for r/s-based testing, we will need to align and plan for appropriate actions in the cloud service infrastructure.

**Comment by ppcano** [comment]
Duplicated of #211
