### ISSUE TITLE
K6 cloud doesn't run if config.json does not have a token

### ISSUE THREAD

**Issue by gpguerra** [loadimpact/k6#1417]
I'm trying to run tests in the cloud using a config.json.
So I already have logged using "k6 login cloud".
But when I run k6 cloud -c config.json script.js K6 prompts:

> "ERRO[0011] Not logged in, please use `k6 login cloud`.  -"

## Environment
- k6 version: 0.26.1
- OS and version: Windows 10

## Expected Behavior
I would like to keep my config.json without the cloud token. So I would use a Enviroment variable (to use K6 with docker in Jenkins) or
be logged in cli before (ie. k6 login cloud)

## Actual Behavior
Token needs to be in config.json

## Steps to Reproduce the Problem
Create

1. Login in K6 on the cli
2. Try to run a test in the cloud using a config.json without a token
3. Execution fails asking to login

**Comment by na--** [comment]
There is another way to log in into the cloud besides having `collectors.cloud.token` in a `config.json` file (either the default one, which is what `k6 login cloud` does, or a custom one you specify with `-c`/`--config`). 

If you save your token in the `K6_CLOUD_TOKEN` environment variable, k6 will use that instead. More details in:
- https://k6.io/docs/using-k6/cloud-execution#getting-started
- https://k6.io/docs/cloud/integrations/token#api-token-as-an-environment-variables
