### ISSUE TITLE
Present check results in chronological order

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#143]
```
k6 run pantheontest.js
...
   ✓ 100.00% - 9: checkout succeeded
    ✗ 0.00% - 11: checkout complete
    ✓ 100.00% - 12: logout succeeded
    ✓ 100.00% - 3: login succeeded
    ✓ 100.00% - 4: carry page OK
    ✓ 100.00% - 8: cart submit succeeded
    ✓ 100.00% - 6: add to cart succeeded
    ✓ 100.00% - 7: shopping cart page OK
    ✓ 100.00% - 10: select shipping succeeded
    ✓ 100.00% - 1: first page content OK
    ✓ 100.00% - 2: login page OK
    ✓ 100.00% - 5: drupal bag page OK
```

The above checks were added in the order their numbers hint at (i.e. "1: first page content OK" was added/executed first). It would be nicer if they were presented in the same order, or perhaps in alphabetical/numerical order, sorting on their text string names because then it would be easy for the user to choose the presentation order.

**Comment by caalle** [comment]
If the execution order could be embedded in the `path` or as a `tag` that would be super( and this would also be nice to have on groups).

When trying to rebuild the hierarchy from the `JSON`-output the order cannot be guaranteed atm.

**Comment by uppfinnarn** [comment]
Hm, the catch here is that Go `map`s don't preserve insertion order… I'm not actually sure how to solve this.

**Comment by micsjo** [comment]
Dictionary rather than map?

**Comment by uppfinnarn** [comment]
JS `{}` literals are parsed as a `map[string]interface{}`. Actually, does JS guarantee the order of items in an object? Because in that case, we could open an issue on goja and ask for it.

**Comment by caalle** [comment]
Order in an Object is not guaranteed. To preserve order I think Map is recommended: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

**Comment by uppfinnarn** [comment]
Hmm… we may have to change the syntax for checks, I'm just not sure what to. I'm going to ask for ordered objects in goja, but I kinda doubt it'd get traction.

This looks kinda dumb to me:

```js
check(http.get("http://example.com/", [
    ["status is 200", (r) => r.status == 200],
    ["body length is 1234", (r) => r.body.length == 1234],
]);
```

This would maybe an acceptable substitute, but it feels like it reads much worse…

```js
let res = http.get("http://example.com/");
check("status is 200", res.status == 200);
check("body length is 1234", res.body.length == 1234);
```

Any other ideas?

**Comment by micsjo** [comment]
This
```check("status is 200", res.status == 200);```
just looks like this but different order of parameters
```assert(res.status == 200, "status is 200");```

Why then would "check" be needed at all? 

Assertions are common terminology in most languages - remind me why "check" was chosen rather than "assert"?

**Comment by micsjo** [comment]
If it's the Go map non-ordering that can be solved by managing keys in a slice.

Sample:

import "sort"

```var m map[int]string
var keys []int
for k := range m {
    keys = append(keys, k)
}
sort.Ints(keys)
for _, k := range keys {
    fmt.Println("Key:", k, "Value:", m[k])
}```

**Comment by uppfinnarn** [comment]
The ordering would have to be preserved by the JS runtime, because otherwise it'll be lost by the time we get them - I just opened [an issue](https://github.com/dop251/goja/issues/22) asking for this.

As I've explained several times (…this needs to be in the docs…), the difference between a check and an assert is that an assert is fatal - a failure will terminate the script - while a check simply notes its result, regardless of what it is. In a load test, this is typically a more desirable behavior, and you can always throw an error yourself if you want one to be fatal.

**Comment by uppfinnarn** [comment]
Ah, the goja author responded: "Hm... I thought it was already preserving the order. It is indeed not part of ES5.1, but since it's common behaviour goja should conform. I'll take a look a bit later."

**Comment by robingustafsson** [comment]
Since https://github.com/dop251/goja/issues/22 has been closed is this issue considered fixed, or do we still want to change the check syntax?

**Comment by liclac** [comment]
Fixed with `-t js2` (which will become the default soon)
