### ISSUE TITLE
Summary export JSON only store the default metrics

### ISSUE THREAD

**Issue by xyngfei** [loadimpact/k6#1433]
Summary export JSON only store the default statistic and can not store the define parameters from summaryTrendStats

## Environment

- k6 version: v0.26.1
- OS and version: MacOS 10.15.3

## Expected Behavior
If I define summaryTrendStats with the own custom define metrics, summary export JSON function does not store those metrics as per defined. 
> summaryTrendStats: [“min”, “max”, “avg”, “p(90)”, “p(95)”, “**p(99)**”, “**count**”]

## Actual Behavior
Custom metrics only store default parameters

**Comment by na--** [comment]
Closing this in favor of https://github.com/loadimpact/k6/issues/1611, since that one has slightly more details, but appears to be the same issue.
