### ISSUE TITLE
End-of-test summary sometimes not shown

### ISSUE THREAD

**Issue by imiric** [loadimpact/k6#1434]
Sometimes on very quick localhost tests (see example below) the end-of-test summary is not outputted.

This issue might've been introduced in #1390, as I wasn't able to reproduce it on the commit before it was merged (a8d1085f).

## Environment

- k6 version: Built on current `new-schedulers` (7dcbfe1f). Note that this does *not* happen on `master`.
- OS and version: Linux
- Docker version and image, if applicable: N/A

## Expected Behavior
The end-of-test summary is always shown.

## Actual Behavior
Sometimes it's not :)

## Steps to Reproduce the Problem

1. Start local httpbin server:
```docker run --rm -it -p 8080:80 kennethreitz/httpbin```
2. Use a slightly modified [`samples/localhost.js`](https://github.com/loadimpact/k6/blob/7dcbfe1f053d3a7115507112efba073c68fdc359/samples/localhost.js) script:
```js
import { group, check } from "k6";
import http from "k6/http";

export let options = {
	thresholds: {
		'http_req_duration{kind:html}': ["avg<=10"],
		'http_req_duration{kind:img}': ["avg<=100"],
		'http_reqs': ["rate>100"],
	}
};

export default function() {
	group("front page", function() {
		check(http.get("http://localhost:8080/", {
			tags: {'kind': 'html' },
		}), {
			"status is 200": (res) => res.status === 200,
		});
	});
	group("image", function() {
		check(http.get("http://localhost:8080/static/favicon.ico", {
			tags: {'kind': 'img' },
		}), {
			"status is 200": (res) => res.status === 200,
		});
	});
}
```
3. Run with `k6 run samples/localhost.js`.

- Example wrong output:
```
> ./k6-new-exec-7dcbfe1f run samples/localhost.js

          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |      |  /  ‾‾\
   /          \   |  |‾\  \ | (_) |
  / __________ \  |__|  \__\ \___/ .io

   executor: local
     output: -
     script: samples/localhost.js

  execution: (100.00%) 1 executors, 1 max VUs, 10m30s max duration (incl. graceful stop):
           * default: 1 iterations for each of 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)


running (00m00.0s), 0/1 VUs, 1 complete and 0 interrupted iterations
default ✓ [======================================] 1 VUs  00m00.0s/10m0s  1/1 iters, 1 per VU


    █ front page

      ✓ status is 200

    █ image

      ✓ status is 200


ERRO[0000] some thresholds have failed
```

- Example correct output (from `master` (8d1a038d)):
```
> ./k6-master-8d1a038d run samples/localhost.js

          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |      |  /  ‾‾\
   /          \   |  |‾\  \ | (_) |
  / __________ \  |__|  \__\ \___/ .io

  execution: local
     output: -
     script: samples/localhost.js

    duration: -,  iterations: 1
         vus: 1, max: 1

    done [==========================================================] 1 / 1

    █ front page

      ✓ status is 200

    █ image

      ✓ status is 200

    checks.....................: 100.00% ✓ 2   ✗ 0
    data_received..............: 33 kB   8.0 MB/s
    data_sent..................: 178 B   44 kB/s
    group_duration.............: avg=2.23ms   min=1.25ms  med=2.23ms   max=3.21ms   p(90)=3.01ms   p(95)=3.11ms
    http_req_blocked...........: avg=164.31µs min=2.28µs  med=164.31µs max=326.34µs p(90)=293.93µs p(95)=310.13µs
    http_req_connecting........: avg=56.95µs  min=0s      med=56.95µs  max=113.91µs p(90)=102.51µs p(95)=108.21µs
    http_req_duration..........: avg=1.94ms   min=1.17ms  med=1.94ms   max=2.7ms    p(90)=2.54ms   p(95)=2.62ms
    ✓ { kind:html }............: avg=2.7ms    min=2.7ms   med=2.7ms    max=2.7ms    p(90)=2.7ms    p(95)=2.7ms
    ✓ { kind:img }.............: avg=1.17ms   min=1.17ms  med=1.17ms   max=1.17ms   p(90)=1.17ms   p(95)=1.17ms
    http_req_receiving.........: avg=73.51µs  min=63.88µs med=73.51µs  max=83.15µs  p(90)=81.23µs  p(95)=82.19µs
    http_req_sending...........: avg=36.8µs   min=10.85µs med=36.8µs   max=62.76µs  p(90)=57.57µs  p(95)=60.16µs
    http_req_tls_handshaking...: avg=0s       min=0s      med=0s       max=0s       p(90)=0s       p(95)=0s
    http_req_waiting...........: avg=1.83ms   min=1.1ms   med=1.83ms   max=2.55ms   p(90)=2.41ms   p(95)=2.48ms
  ✓ http_reqs..................: 2       489.342248/s
    iteration_duration.........: avg=4.53ms   min=4.53ms  med=4.53ms   max=4.53ms   p(90)=4.53ms   p(95)=4.53ms
    iterations.................: 1       244.671124/s
    vus........................: 1       min=1 max=1
    vus_max....................: 1       min=1 max=1
```

Also note that when it is actually output on `new-schedulers`:
```
    checks.....................: 100.00% ✓ 2 ✗ 0
    data_received..............: 33 kB   570 kB/s
    data_sent..................: 178 B   3.1 kB/s
    group_duration.............: avg=2.36ms   min=1.41ms  med=2.36ms   max=3.32ms   p(90)=3.12ms   p(95)=3.22ms
    http_req_blocked...........: avg=185.55µs min=2.69µs  med=185.55µs max=368.42µs p(90)=331.84µs p(95)=350.13µs
    http_req_connecting........: avg=52.36µs  min=0s      med=52.36µs  max=104.73µs p(90)=94.26µs  p(95)=99.49µs
    http_req_duration..........: avg=2.01ms   min=1.31ms  med=2.01ms   max=2.7ms    p(90)=2.56ms   p(95)=2.63ms
      { kind:html }............: avg=2.7ms    min=2.7ms   med=2.7ms    max=2.7ms    p(90)=2.7ms    p(95)=2.7ms
      { kind:img }.............: avg=1.31ms   min=1.31ms  med=1.31ms   max=1.31ms   p(90)=1.31ms   p(95)=1.31ms
    http_req_receiving.........: avg=82.03µs  min=61.18µs med=82.03µs  max=102.89µs p(90)=98.72µs  p(95)=100.8µs
    http_req_sending...........: avg=36.66µs  min=11.1µs  med=36.66µs  max=62.22µs  p(90)=57.11µs  p(95)=59.66µs
    http_req_tls_handshaking...: avg=0s       min=0s      med=0s       max=0s       p(90)=0s       p(95)=0s
    http_req_waiting...........: avg=1.89ms   min=1.24ms  med=1.89ms   max=2.53ms   p(90)=2.41ms   p(95)=2.47ms
    http_reqs..................: 2       34.905221/s
    iteration_duration.........: avg=4.78ms   min=4.78ms  med=4.78ms   max=4.78ms   p(90)=4.78ms   p(95)=4.78ms
    iterations.................: 1       17.45261/s

ERRO[0000] some thresholds have failed
```
1. There are no `✓`/`✗` marks next to the thresholds.
2. More surprisingly though, the `http_reqs` threshold consistently fails (regardless of whether the summary is shown or not). I've noticed the rate always being lower than `100`, compared to when run on `master` where it's consistently over `300` in my tests and no thresholds fail. This implies something changed in this metric calculation, or the worse scenario that the performance actually decreased. :-/

Let me know if I should create separate issues for these last two points.

**Comment by MStoykov** [comment]
Hm looking at the numbers ... I would guess new-schedulers thinks the test ran for longer then it did... as all non `quantity/time` numbers look similar

**Comment by na--** [comment]
not sure why the summary doesn't show, probably forgot to synchronize something and there's a race :disappointed:
regarding `http_reqs`, you should be checking for `count`, not `rate`, given that `http_reqs` is a `Counter`: https://github.com/loadimpact/k6/blob/7dcbfe1f053d3a7115507112efba073c68fdc359/lib/metrics/metrics.go#L42

**Comment by imiric** [comment]
The missing summary and marks should be fixed in #1437, but re: `http_reqs`, the threshold works fine with `rate` though. That is, the [sample script](https://github.com/loadimpact/k6/blob/7dcbfe1f053d3a7115507112efba073c68fdc359/samples/localhost.js) uses it, and I think it's a valid check to have, i.e. to fail if the rate is below a certain threshold. If it's wrong, then we should fix the sample script, but I'd leave it as is.

The problem is that the same script passes the threshold on `master`, but fails on `new-schedulers`, because of the -10x change of rate for all metrics. This seems like a regression we should fix, so should I open a new issue and look into it?

**Comment by na--** [comment]
That sample script seems wrong to me :confused: `rate` supposes `A/B`, but for `Counter` we only have a single number, the `count`. I'm very confused how this can work, but I don't have time to get into it right now :confused:

**Comment by na--** [comment]
Looking into https://github.com/loadimpact/k6/pull/1437, isn't the whole issue the fact that, for fast tests, this ticker doesn't have a chance to tick even once? https://github.com/loadimpact/k6/blob/e0ddf5d3d2440b17ef530ad6d494ab86077efb47/core/engine.go#L266-L275

So, by the time the `run()` method has finished, its metrics are sitting in `sampleContainers`, and haven't been processed for metrics or thresholds. Actually, this isn't going to be an issue only for fast tests - the metrics generated in the last [50 milliseconds](https://github.com/loadimpact/k6/blob/e0ddf5d3d2440b17ef530ad6d494ab86077efb47/core/engine.go#L39) of any test wouldn't be processed either. So, I think the solution here should be to force k6 to process all outstanding metrics before the `run()` method finishes, no?

**Comment by na--** [comment]
argh, the whole way metrics and thresholds are processed is just... :expressionless: I should have just re-written things from scratch, instead of the cosmetic changes I did in https://github.com/loadimpact/k6/pull/1390 :sob:

**Comment by na--** [comment]
https://github.com/loadimpact/k6/pull/1460 :nauseated_face:

**Comment by na--** [comment]
Closed by https://github.com/loadimpact/k6/pull/1460
