### ISSUE TITLE
String interpolation broken for http.batch()

### ISSUE THREAD

**Issue by d-lilja** [loadimpact/k6#1444]
## Environment

- k6 version: Latest, using the web interface

## Expected Behavior

Should work?

## Actual Behavior

Error details: unsupported protocol scheme ""

## Steps to Reproduce the Problem

Works: `http.batch([["GET", baseUrl+"/appshell/data"]]);`
Doesn't work (used to work): `http.batch([["GET", "$(baseUrl)/appshell/data"]]);`
Doesn't work: `http.batch([["GET", "${baseUrl}/appshell/data"]]);`

Still works for http.post and get

**Comment by MStoykov** [comment]
Hi @d-lilja , [string interpolation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) actually requires that the string uses \` instead of " or ' ;)
