### ISSUE TITLE
Die on SIGINT in windows too?

### ISSUE THREAD

**Issue by micsjo** [loadimpact/k6#145]
Could we honor CTRL-C (SIGINT) and die on windows and not only the *nix build?

**Comment by uppfinnarn** [comment]
Should be the case already, though I'm not sure how windows handles signals…

Does it quit properly if you change [this part here](https://github.com/loadimpact/k6/blob/e3d5b95610c5081bc869085469780fb1958918ea/run.go#L434) to just `signal.Notify(signals)`? That should catch any signal, not just the listed ones. Run with `-v` and it will log when a signal is received.

**Comment by micsjo** [comment]
If I do set it to catch any signal it works better. It will actually die immediately during startup with this setting.

It will also die when running but not immediately. There is a delay (couple of seconds) but it does work.

-v says it's signal=interrupt but when limiting the code to os.Interrupt and syscall.SIGTERM it doesn't work.

Just adding syscall.SIGINT to the list of interrupts also works fine (SIGINT would then be what it gets for CTRL-C even if the debug output simply says "interrupt")

**Comment by uppfinnarn** [comment]
That's… interesting, `os.Interrupt` is supposed to be a portable interrupt signal, could be a cygwin thing maybe?
