### ISSUE TITLE
401 Unauthorized Response on Post Request using Bearer Token Authorization type

### ISSUE THREAD

**Issue by LearningNeverEnds** [loadimpact/k6#1451]
## Environment
- k6 version:  k6/0.26.2 (https://k6.io/)
- OS and version:  Windows 10

## Expected Behavior
Post request should create a data with provided extracted Bearer token and payload data

## Actual Behavior
401 Unauthorized Response 

## Steps to Reproduce the Problem
1. `k6Perf.js:

<img width="451" alt="K6_1" src="https://user-images.githubusercontent.com/47758079/82081151-d7ad6980-96b3-11ea-9b66-2cb932de7da3.png">

2.  In first function I am extracting the Bearer token and storing it in var token and passing the var onto second function that will create a data.

3. K6 response Log:
<img width="951" alt="K6_2" src="https://user-images.githubusercontent.com/47758079/82081343-20fdb900-96b4-11ea-9d62-2be3a731a8ae.png">

<img width="958" alt="K6_3" src="https://user-images.githubusercontent.com/47758079/82081356-23f8a980-96b4-11ea-9e74-d3a7de210806.png">

Please let me know what am I doing wrong. I was able to send the same post request using JMeter, Postman and Rest Assured....I been trying to get this done and add this script as my Load Test Stage into my GitLab CI Pipelines. But I am struck :(

Thank you in advance!

**Comment by paulloh3n** [comment]
The parameters used in the post method are in the wrong order, the correct order would be:
 
![image](https://user-images.githubusercontent.com/14806151/82093044-bdce4f80-96d0-11ea-8c9e-bcbbe3b84d52.png)

```js
  let res = http.post(`${API_SERVER}/api/donors`, {
    ...body
  }, {
    headers
  });
```

**Comment by LearningNeverEnds** [comment]
It is working now :) Thank you so much!

**Comment by MichelCorreaDaLuz** [comment]
@gomespauloho 4 years has passed, and today you saved me as well.
Thanks a lot for making me read the documentation properly hahaha

God bless u
