### ISSUE TITLE
Command-line activity progress, and less verbose configurable summary output

### ISSUE THREAD

**Issue by adr0sen** [loadimpact/k6#146]
We want additional activity progress output when running k6 from command line, e.g.:

change
`running [================>=========================================] 3s/10s`

into e.g.
```
running [================>=========================================] 3s/10s
         8/20 active vus, 3/4 checks passed, 2/3 thresholds passed
```

Also, we want the summary output generated at completion of test to be less verbose, and configurable. Proposed change:
```
    default metrics: 
        checks................: 61.11%
      ✓ http_req_duration.....: avg=340.82ms, max=1.14s, med=106.8ms, min=4.62ms, stddev=<60.2ms>, p95=1.14s
        http_reqs.............: 4
        iterations............: 2
        vus...................: 1
        vus_max...............: 1
    custom metrics: 
        my_counter............: 2
      ✓ my_rate...............: 50.00%
```
* note removal of `p90` and addition of `stddev` to the default output of http_req_duration metric. 
* the submetrics of `http_*` is configurable via command-line or options, and allows for inclusion/exclusion of avg/max/med/min/stddev/var/pXX
* is `metrics` the correct terminology for default/custom above?

**Comment by uppfinnarn** [comment]
Managing multiple lines of dynamic output in a portable way is difficult; it's fiddly on POSIX and breaks if you print anything else (such as logs, or just the user hitting a button), and I have no idea how it works on Windows. What we're doing now is just `\r` to set the cursor back to the start of the line, while log messages overwrite it.

If there's a better way to do it that would allow us to do this, I'm all ears, I'm just not aware of one.

For the metrics output, I'm not sure if I see the benefit in hiding data from the user and make them dig for it - clearly communicating the available metrics means there's a canonical reference when writing thresholds, there are no docs that can go out of sync, and you don't need to pipe data into InfluxDB just to see what's there.

**Comment by micsjo** [comment]
Currently the signal/noise ratio is very low. It's way too much _data_ and way too little _information_.

**Comment by micsjo** [comment]
pdcurses seem to do the trick, on Sourceforge somewhere. Old stuff but no need for new stuff.

**Comment by adr0sen** [comment]
@uppfinnarn - to solve the one-liner dynamic outout issue, perhaps we could remove the progress bar, replacing with a running %? So the one-liner would look something like:

```
30% (3s/10s): 8/20 active vus, 3/4 checks passed, 2/3 thresholds passed
```

For the configurable amount of output, does it make sense to adjust the verbosity-level option, where e.g. `-v` would generate all default summary metrics, `-vv` show info messages (if makes sense), and `-vvv` show debug messages?

**Comment by uppfinnarn** [comment]
I do like the idea of replacing the progress bar with something more useful, but I'm not sold on the output idea. The current output is verbose, but very transparent; you can just copypaste the relevant metric names and dimension names when making thresholds or querying the output data.

**Comment by ppcano** [comment]
Closing this old ticket. Please, reopen if necessary.

I think having the ability to write your own console output is the way to accomplish everyone needs
https://github.com/loadimpact/k6/issues/299#issuecomment-325639377
