### ISSUE TITLE
https://github.com/loadimpact/k6/issues/220

### ISSUE THREAD

**Issue by pawansinha0612** [loadimpact/k6#1463]
I have exactly the same issue with this one - 
https://github.com/loadimpact/k6/issues/220

I am not able to understand where should i write that code so that it will run the http request using my proxy.

**Comment by na--** [comment]
Closing this, since it seems like you got your answer in one of the other (closed...) issues you posted in https://github.com/loadimpact/k6/issues/797#issuecomment-632827776

Also, as mentioned when you open an issue, the community forum is a better place to ask questions... https://community.k6.io
