### ISSUE TITLE
K6 - error="Post \"{URL}": context deadline exceeded"

### ISSUE THREAD

**Issue by pawansinha0612** [loadimpact/k6#1466]
This error comes exactly after 1min, can someone help, please. 
Already used below but still it gives error after exactly 1minute which is K6 by default timeout.

The response comes after 1.5min, so i need to increase the K6 timeout, please help. 
what should I include in my code? I have recent version installed 0.26..

## Environment

- k6 version: - 0.26..
- OS and version: MAC
- Docker version and image, if applicable:

## Actual Behavior

This error comes exactly after 1min, can someone help, please. 
Already used below but still it gives error after exactly 1minute which is K6 by default timeout.

Response comes after 1.5min, so i need to increase the K6 timeout, please help. 
what should I include in my code? I have recent version installed 0.26..

## Steps to Reproduce the Problem

let params = {
        timeout: 180000
};
{ "http.rw_timeout": "180s" }
setupTimeout: '180s'
K6_SETUP_TIMEOUT: '180s'
"tcp.connection_timeout":"180s",
"http.rw_timeout": "180s",
"log": "true",

**Comment by na--** [comment]
As shown in the [documentation](https://k6.io/docs/javascript-api/k6-http/params-k6-http), you have to pass `params` in your HTTP calls... So something like
```js
import http from 'k6/http';

export default function () {
    http.get('https://test-api.k6.io', {
        timeout: 180000, // 180 seconds
    });
};
```

Also, as mentioned before, please ask such questions in the community forum https://community.k6.io/

**Comment by pawansinha0612** [comment]
Still i am getting this error - Request Failed                                error="Post \"***\": context deadline exceeded"..

function PostWithValidJwt(endpoint, body, env) {
    let res = http.post(endpoint, JSON.stringify(body), {headers: headers}, {
        timeout: 180000, // 180 seconds
    })
    return res
}
