### ISSUE TITLE
Collect timing for groups

### ISSUE THREAD

**Issue by micsjo** [loadimpact/k6#147]
Would like to have timing for groups collected by default as a metric.

One of the main reasons to use groups is to measure duration of grouped transaction(s). To do this manually is a pain for longer scripts since it needs manual implementation of timers and metrics collection. Doable, yes, but lot's of work for "plumbing".

**Comment by liclac** [comment]
I wonder if this is still relevant now that all normal metrics are tagged with their group.

**Comment by micsjo** [comment]
Maybe as a simplification? Else it means you have to calculate sums of groups when charting. Which would be just fine of course. Much lesser priority but as a "heller" for lazy people (like me...)?

**Comment by micsjo** [comment]
Not "heller", helper!

**Comment by liclac** [comment]
I'm just, gonna close this, because it'd introduce a metric in the CLI output that makes no sense unless filtered…
