### ISSUE TITLE
Clean up the terminal/move the caret when k6 is stopped 

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#1471]
with the current changes in the new-schedulers branch if you ^C to stop k6 things look like this 
![image](https://user-images.githubusercontent.com/312246/83141686-ca06d380-a0f8-11ea-8bad-9edcf1831c0a.png)
It would be better if write that message after all the progressbar and stuff instead of in the middle.

**Comment by na--** [comment]
This seems to have been fixed at some point, so I'm closing this issue... Please reopen if I was wrong and it was a case of "works on my machine" :sweat_smile:
