### ISSUE TITLE
Variable-looping-vus/stages is a start/stopping instances a little flaky

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#1473]
It seems like sometimes variable looping vus will gracefully stop a VU while ramping up and then just start it again. After some additional logs, it is easy to spot 
![image](https://user-images.githubusercontent.com/312246/83159157-5cfe3880-a10e-11ea-9a92-1839f9a3da6b.png)
As is seen `rawStep` goes a little faster sometimes and gets 2-3 steps ahead of `gracefulLimit` and when we get a `gracefulLimit` that is basically for some steps ago and we stop a VU or two... gracefully :D. 

This (at least for me) only happens if the machine is under load which is not all that hard especially when ramping up so ...
The code in question reads from two different channels that get events every time something needs to happen.
https://github.com/loadimpact/k6/blob/83d0fcf2ecf44db27275cdf7ea887c05edf9bd06/lib/executor/variable_looping_vus.go#L638-L673
I do think it will be much simpler and easier if we zip (combine) the two giving `gracefulLimit` the preference and just go through the new slice ... 

This also will definitely be more performant, not that 2 goroutines and 2 channels are too much ... but we can skip them :D

**Comment by na--** [comment]
Resolved by https://github.com/loadimpact/k6/pull/1496 and https://github.com/loadimpact/k6/pull/1506
