### ISSUE TITLE
Loaded external module return s undefined

### ISSUE THREAD

**Issue by zanonnicola** [loadimpact/k6#1482]
Hi,
I'm trying to generate `UUID` as described in this guide https://k6.io/docs/examples/generating-uuids but the generated module return undefined when used.

Thanks,

## Environment

- k6 version: **k6 v0.26.2 (dev build, go1.14, darwin/amd64)**
- OS and version: **Mac (Darwin -19.4.0)**
- browserify: **16.5.1**

## Expected Behavior
Should be able to use `uuid` module

## Actual Behavior

```
INFO[0002] undefined                                    
ERRO[0002] TypeError: Cannot read property 'v4' of undefined
        at generateCorrelationId (file:///Users/1111/repos/k6-bug/test.js:13:246(14))
        at file:///Users/1111/repos/k6-bug/test.js:12:26(3) 
    done [==========================================================] 1 / 1
```

## Steps to Reproduce the Problem

Described in this repo https://github.com/zanonnicola/k6-bug

**Comment by imiric** [comment]
It seems this example only works for older versions of the `uuid` package. E.g. `npm install uuid@3.4.0` works as expected, so please use that version.

Also note that you can use the `uuidv4` function from the [k6 JS lib repository](https://jslib.k6.io/), which has a few curated and often used helpers.

**Comment by zanonnicola** [comment]
Didn't know about JS libs! 
Thanks for the quick reply and explanation @imiric!
