### ISSUE TITLE
Look into whether we should rename "context cancelled"

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#1485]
In the js package we have an [errInterrupted](https://github.com/loadimpact/k6/blob/master/js/runner.go#L52) it is used to signal that we interrupted the iteratiosn. Unfortunately sometimes we get "context canceled"(one `l` not two) which is from when a[ context gets canceled](https://golang.org/pkg/context/#pkg-variables)

```
=== RUN   TestVURunInterruptDoesntPanic/Archive
    TestVURunInterruptDoesntPanic/Archive: assertions.go:247: ^M                          ^M    Error Trace:    runner_test.go:625
        ^M                      ^M                      asm_amd64.s:1373
        ^M      Error:          "context canceled" does not contain "context cancelled"
        ^M      Test:           TestVURunInterruptDoesntPanic/Archive
--- FAIL: TestVURunInterruptDoesntPanic (10.22s)
```

This seems like a slight race .. but ultimately I think it doesn't matter it will just be better if we make ours be single `l` as well but this needs more investigation I think :D

**Comment by na--** [comment]
is anything going to break if we fix the spelling of our error? if not, we should just do it :)

**Comment by MStoykov** [comment]
No idea, no time to check it all .. just I got it the second time today and decided to write it down while not trying to fix that as well :D
