### ISSUE TITLE
k6 doesn't display all cloud test run statuses as expected

### ISSUE THREAD

**Issue by mpandurovic** [loadimpact/k6#1488]
## Expected Behavior

![Screenshot from 2020-06-05 14-06-54](https://user-images.githubusercontent.com/2479123/83874670-28a20200-a736-11ea-9e09-050367bfc790.png)

`k6` should display cloud statuses according to response received from `/test-progress/ID` endpoint. This works as expected in `0.26`.

## Actual Behavior

![Screenshot from 2020-06-05 14-07-36](https://user-images.githubusercontent.com/2479123/83874684-2dff4c80-a736-11ea-8e09-fbe722c282d4.png)

Test run statuses like `INITIALIZING` and `QUEUED` are skipped and progress bar shows `Run ...` throughout several stages of test run's setup in cloud.

## Steps to Reproduce the Problem

1. Run `new-executors` build with `k6 cloud`.

**Comment by na--** [comment]
@imiric, just noticed a somewhat connected issue, while fixing something else - in `cmd/run.go`, the right text in the `printBar()` invocations is very sparse, such print calls are very rarely called, the `initBar.Modify(pb.WithConstProgress(0, "<some-text>"))` calls seem to be completely ignored... Not urgent, but we'll have to revisit how and what we print in all of these progressbars before v0.27.0 comes out...

**Comment by imiric** [comment]
@na-- Hhmm yeah, the right side text set in the progress bar is ignored by `printBar()`, and we're not calling it everywhere it should be. I'll look into it.

**Comment by imiric** [comment]
@na-- Let me know if 6df9b4bb is what you had in mind. I opted for removing the `rightText` arg from `printBar()`, which is not as convenient as before, but it forces the use of the PB API, so I think it's cleaner.

There's still some inconsistencies between `run` and `cloud` (and a few [`TODO`s](https://github.com/loadimpact/k6/blob/6df9b4bb8b79113e178f21dd9e0890614b492714/cmd/cloud.go#L203)), but the rendering should be better aligned now.

**Comment by imiric** [comment]
Closed by #1490.

@mpandurovic Let us know if it works better now. :)
