### ISSUE TITLE
Library of k6 sample scripts exercising full feature-set, easily accessible while centrally maintained 

### ISSUE THREAD

**Issue by adr0sen** [loadimpact/k6#149]
We want to improve the getting started experience of k6 by managing a library of k6 sample scripts, exercising the full feature-set of k6. These scripts should then be very easy for new users of k6 to access and run, e.g. by them being hosted somewhere via the web and k6 having the ability to be fed with scripts via HTTP (as potentially solved by #136?).

Ideally, the library of scripts should offer both real-world end-to-end test implementations (e.g. as in PR #135 for an e-commerce store/checkout example), as well as smaller instructive snippets of working sample code where focus is on single features and scripting capabilities.

All these samples in the library can then be used throughout our documentation and guidelines, e.g. in installation/getting-started instructions as well as in API-references etc.

**Comment by uppfinnarn** [comment]
Gonna work on #152 once I have #137 done, there's #135 in the works and I'd love to see some more contributed code samples (@robingustafsson). I'll take care of writing more long-form documentation once I've got those two down.

**Comment by robingustafsson** [comment]
Yeah, I'll work on producing code samples to showcase k6 features. Will create a PR when I have something to show, or should we put them in a separate repo right away, something like loadimpact/k6-samples?

**Comment by micsjo** [comment]
Have some but need to know where to put them.

**Comment by uppfinnarn** [comment]
Please PR them to /samples!

**Comment by liclac** [comment]
We need more samples, but let's open smaller issues for individual ones instead of this.
