### ISSUE TITLE
too many i/o timeout

### ISSUE THREAD

**Issue by guawazi-glitch** [loadimpact/k6#1495]
## Environment

- k6 version: k6-v0.26.2-linux64
- OS and version: linux version 3.10.0-514.el7.x86__64  red hat 4.8.5 20150623
- Docker version and image, if applicable:

## Expected Behavior

Should work well

## Actual Behavior

The terminal output many error like :
WARN[0182]  error="Get http://xxx.xxx.xxx.xxx:port  dial tcp xxx.xxx.xxx.xxx:port i/o timeout

## Steps to Reproduce the Problem

The command is
./k6 run --vus=5000 --duration=3m --no-thresholds --compatibility-mode=base --discard-response-bodies test.en5.js

Hi, I reopened the issue again. After my investigation, when after started generating loading about 20-30s, the i/o timeout occurred. But when I use top command to see the memory and cpu usage, everything is fine. The cpu usage is 30%  and memory usage is 80%
My server is 8 cores and 16G memory. 
And additional information please ask me. Thanks.

**Comment by MStoykov** [comment]
You should've reopened the OLD issue ... not open a new one .... 

What is the CPU/MEM usage on the system under tests?
How much bandwidth is utilized by the test? How much do you have between the two systems?

**Comment by guawazi-glitch** [comment]
@MStoykov hi，as I know, f you are not a collaborator of a repo, then (in regards to issues)，you cannot re-open your own issues if a repo collaborator closed them。So I opened a new one...

For your question, my test env like this:
220: load generate server, 8core,16memory

219: nginx, use load balance, in the back, there are four server running : 217,218,221,223, the  nginx configuration is:
upstream webhost {
        server 192.168.0.217:9003 ;
        server 192.168.0.218:9003 ;
        server 192.168.0.221:9003 ;
        server 192.168.0.223:9003 ;
    }

Each server under test is:
217 : 4 core 8 G memory
218: 4 core 8G memory
221: 8core 16G memory
223: 8 core 16 G memory

The test script is very simple:

import http from 'k6/http';
export default function() {
  http.get('http://172.17.193.219/auth/test');
}

the /auth/test just return a string "good" and do nothing else.


When doing test, each server CPU/MEM usage is:
217 : cpu 100%-130%  mem 6.7
218:  cpu 100%-110%  mem 8.5
221:  cpu 150%  mem 6.8
223: cpu 45%-50%  mem 3.1

**Comment by MStoykov** [comment]
Again `dial tcp xxx.xxx.xxx.xxx:port i/o timeout` literally means we asked the OS to make us a tcp connection and it didn't manage to make it before it's timeout expired. Why? something in your system isn't configured in a way to support it. 

You can look at the [OS tuning guide](https://k6.io/docs/misc/fine-tuning-os) for some ideas, but ultimately this is not a k6 bug. 


Please if you have any more questions, ask them at the [community forum](https://community.k6.io/), where other people can give you some advice, as these issues are only about actual problems with k6, not for guides or discussions on how to run k6 or tune machines. 

Additional notes:

- the script you've posted, won't work with `--compatibility-mode=base` which you posted as the cli command that you use.
- Also, you decided to skip over how the Nginx performance was
- Nginx has very bad defaults ... for some reason, so tweaking it is probably a good idea
- On related to the above, you are using `http` and Nginx by default doesn't support reusing http connections if I remember correctly, which means that on each iteration we need to redial, which might be what you want, might not be.

**Comment by guawazi-glitch** [comment]
@MStoykov Hi, thanks your quick reply. I'd like to know, for a 8 core 16G memory server, can it generate more than 20k RPS using k6? Is it possible for such a hardware configuration??
