### ISSUE TITLE
Threshold results on summary export are reversed

### ISSUE THREAD

**Issue by kingwill27** [loadimpact/k6#1498]
On the summary export, the boolean result of the threshold evaluations are reversed (i.e. the value is true when the threshold fails, and false when it is passes). This is the case for overall and group thresholds.

## Environment
- k6 version: k6 v0.26.2 (dev build, go1.14, darwin/amd64)
- OS and version: MacOS Mojave
- Docker version and image, if applicable: N/A (native local)

## Expected Behavior
If the threshold passes, the value associated should be true. If not, it should be false

## Actual Behavior
e.g.
```
"http_req_duration{group:::pending}": {
            "avg": 3899.925589285715,
            "max": 7133.369,
            "med": 3993.647,
            "min": 2414.586,
            "p(90)": 5856.789,
            "p(95)": 6083.4515,
            "thresholds": {
                "p(95)<5000": true
            }
        },
```

## Steps to Reproduce the Problem
1. Run k6 with summary export enabled (e.g. `k6 run --summary-export=k6/results.json k6/test.js`)

**Comment by MStoykov** [comment]
Hi @kingwill27 , 

I made an [issue](https://github.com/loadimpact/k6-docs/issues/30) for this to be documented, as I am don't want to break this now that this has been out for over 6 months ...
