### ISSUE TITLE
Installers / packaging

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#15]
Create installers and packages that make it simple to install k6 for a large set of users

*Imported from https://trello.com/c/rrMtv2Op/92-installers-packaging*

**Comment by uppfinnarn** [comment]
Could someone get on this?

At the very least, I want a Homebrew tap:

```bash
brew tap loadimpact/k6
brew install k6
```

**Comment by diego-plan9** [comment]
I have some Debian packaging familiarity (as I'm currently the maintainer of a small package with sporadic releases under the Debian Python Modules Team umbrella) that I'd be more than happy to put to good use for `k6`! 

My main concern is about the timing, as I'd need to combine getting more familiar with go+k6 with the rest of my duties, and I'm not sure how well it would play into the release plans. Still, the main effort might not be on the purely technical front but on following the Debian packaging procedures, so maybe that concern about the time is not so pressing.

**Comment by uppfinnarn** [comment]
I'd love that! I'll gladly help out any way I can, but my experience with Debian packaging is limited to packaging another project as a PPA years ago…

**Comment by diego-plan9** [comment]
An update on the Debian packaging - as of today, the following libraries (either direct dependencies of `k6` or second-level dependencies) on [RFS](https://mentors.debian.net/sponsor/rfs-howto) status:

`api2go`, `goja`, `goquery`, `null.v3`, `regexp2`, `null.v2`, `inflector`, `cascadia`, `dnscache`, `snaker`

In practice it means that the core of the packaging work and procedures have been done, and the packages are awaiting to be reviewed and eventually uploaded (provided no further adjustments are required to conform to the Debian guidelines, etc) to the repository by a Debian developer.

The next steps will happen once #195 is completed and the dependency on `otto` is dropped, as that is when I will proceed with finally packaging `k6`. Unfortunately I can't give an exact timeline on when all the process would be completed, as it depends on the reviews and the Debian volunteers, but we are getting closer!

**Comment by ragnarlonn** [comment]
@liclac @diego-plan9 Shall we rename this issue so it only concerns the debian packaging?  We already have a homebrew package, and I think it might be a good idea to create a new issue for the Windows installer, and then place a bounty on it.

**Comment by liclac** [comment]
👍

**Comment by bradley3313** [comment]
Network Cell Info (v.3.35.1)

Device: HTC 0PGQ1
Hardware: Htc_a12
Radio: 01.01_U113251042_32.06.50731G_F
Android: 5.1 (API 22)
Android image: LMY47O release-keys
RAM total: 887 MB
RAM avail: 177 MB
RAM thres: 144 MB
RAM is low: false
Screen size type: normal
Screen Real Size (px): 480x854
Screen Real Size (dp): 320 x 569
Screen Size (px): 480x782
Screen Size (dp): 320 x 521
Screen Size (in): 4.4
DPI: 240 (hdpi)
Density: 1.5
Scaled density: 1.5
Navigation keys: false
Soft keys ON: true

==========================

The following cell/signal/android information may help us improve further the response of the app for your device (if there are any issues).

Android API : 22
Location access : true / enabled : true
Phone State access : true
Write access : true

Agree to save Map state : true
Agree to allow saving Logs : true
Agree to connect to DB : true
Show dialog again : false

Phone Type : GSM
World phone : false
Telephony: Yes
Voice call capable : true
VoLTE available : -
IWLAN (WiFi calling) available : false
Video call available : false

Airplane Mode : false
Network : true-true / Type = 13 (LTE) / 13 (LTE)
Data : WiFi

Scheduler : false (false/false) :: 4 / 4 / 4 // 0

Cell (API 1) : [xxx,xxx,xxx]
-- N size: 2
-- #1: [] > Unknown, -1, -1, -1, 64
-- #2: [] > Unknown, -1, -1, -1, 73

tmMTK: null (API 22)

Cell (API 17) : 2

--------------1---------------
noNetwork = false
Operator : YES OPTUS (api: YES OPTUS)
operatorID : 50502 / 50502
SIM1 state : 5 (Ready)
SIM1 service state : 0 (In-Service)

cellInfoList : 2 / 2

nNeighbors : 1
nNeighbors same : 1
nNeighbors wdata : 1
isCDMA : false
isLTECDMA : false

S (0: 0) - LTE/LTE (0): 1 4 (4) 49 -91 [25] -7 -1000 -1 -1 | 105 146 -1 -1 | Cell: 57506 / 23214345 / 244 | CellSignalStrengthLte: ss=25 rsrp=-91 rsrq=-7 rssnr=2147483647 cqi=2147483647 ta=2147483647 || CellIdentityLte:{ mMcc=xxx mMnc=xxx mCi=xxx mPci=xxx mTac=xxx} || [ Lte : 50502, 57506, 23214345, 244 ] ||
isRegistered: true

N (0: #1) - null/LTE (1): 1 3 (3) 40 -100 [20] -17 -1000 -1 -1 | orig. type 1 null || 105 -1000 -1 -1 | Cell: -1 / -1 / 75 | CellSignalStrengthLte: ss=20 rsrp=-100 rsrq=-17 rssnr=2147483647 cqi=2147483647 ta=2147483647 || CellIdentityLte:{ mMcc=xxx mMnc=xxx mCi=xxx mPci=xxx mTac=xxx} || [ Lte : null, -1, -1, 75 ] ||
isRegistered: false

--------------2---------------
cellInfoList2 = null

nNeighbors2 : 0
nNeighbors same2 : 0
nNeighbors wdata2 : -
isCDMA2 : false
isLTECDMA : false

--------------sim(s)---------------

HTC 0PGQ1, en/en, tmMTK: null, API 22, Cell (API 17) : 2
Operator IDs: 50502,

A: nSIMS(22) = 1, F: 1 >> SIM: true
B: nSIMS(22) = 1, F: 1 >> SIM: true
isMultiSimEnabled = false (function: true)
numServingCells(List) = 1

Single SIM Android: Yes
--show SIM: #1
Use WiFi Mode: true

SIM(tm): YES OPTUS, 50502, networkType: 13 (LTE)
SIM state : 5 (Ready) -- Ready
SIM roaming : false
SIM data state : 0 (Data DISCONNECTED)

SIM1 state : 5 (Ready)
SIM1 service state : 0 (In-Service) | (R) : 0
SIM1 roaming : false
SIM1 active : true
SIM1 (0, 1): SignalStrength: 99 99 -120 -160 -120 -1 -1 29 -88 -12 146 2147483647 -1 gsm|lte
SIM1 VU: SIGL = 4, ASU = 49, dBm = -91, MCC = 505, MNC = 2, area = 57506, cellid = 23214345, unit = 244
GsmCellLocation1: (505/2) 57506, 23214345, -1 -- [xxx,xxx,xxx]
SIM1(r): YES OPTUS, 50502 (MCC/MNC: 505/2), NW: 13 (LTE) /p13, sigstr: LTE
SIM1(p): YES OPTUS [YES OPTUS], 50502 (MCC/MNC: 505/2), NW: 13 (LTE), Voice: 13 (LTE), Data: 13 (LTE)
SIM1(n): YES OPTUS, 50502 (MCC/MNC: 505/2), Australia, NW: 13 (LTE), sigstr: LTE
SIM1(f): YES OPTUS, 50502 (MCC/MNC: 505/2), Australia
*SubInfo SIM1: OK, Slot: 0, Carrier Disp: YES OPTUS, Carrier: YES OPTUS (AU), Data Roaming: 0, MCC/MNC: 505 / 2
SS: YES OPTUS, 50502 (505,2), roaming: false, serv state: 0 -- [0 0 voice home data home YES OPTUS YES OPTUS 50502 YES OPTUS YES OPTUS 50502 (manual) LTE LTE CSS not supported -1 -1 RoamInd=-1 DefRoamInd=-1EriInd= -1EriMode= -1RadioPowerSv: false EmergOnly=false PhoneType: 1 VoiceRoaming: false DataRoaming: false IMSRegState: -1]
SIM1 data state : 0 (Data DISCONNECTED)

nSIMS(22) = 1, F: 1
SIM2: ph null
SIM2 VU: null
xxxCellLocation2: null
SIM2(r): empty list
SIM2(n,f): no phone info
*SubInfo SIM2: null
sSS: ph null

--------------Graphs---------------

LTE Thresholds Type: 4

--------------wifi---------------

Wifi enabled: true
Wifi connected: true
Wifi state: enabled
Wifi 5GHz band support: false

SSID: gold...
connected: true
RSSI: -55 dBm, level: 4 [0-4]
channel: 6, frequency: 2437 MHz
linkSpeed: 72 Mbps
encryption: [WPA2-PSK-CCMP][WPS][ESS]

SSID: Belo...
connected: false
RSSI: -91 dBm, level: 1 [0-4]
channel: 12, frequency: 2467 MHz
encryption: [WPA2-PSK-CCMP][WPS][ESS]

SSID: KOOR...
connected: false
RSSI: -95 dBm, level: 1 [0-4]
channel: 1, frequency: 2412 MHz
encryption: [WPA2-PSK-CCMP][WPS][ESS]


==========================

If your device doesn't show any signal in the Gauge tab, or it shows erroneous info, the following extra cell/signal/android information may help us extracting the signal (if possible) in future release.

public int getAsuLevel()	= 52
public int getCdmaAsuLevel()	= 99
public int getCdmaDbm()	= -120
public int getCdmaEcio()	= -160
public int getCdmaLevel()	= 0
public int getDbm()	= -88
public int getEvdoAsuLevel()	= 99
public int getEvdoDbm()	= -120
public int getEvdoEcio()	= -1
public int getEvdoLevel()	= 0
public int getEvdoSignalBar()	= -1
public int getEvdoSnr()	= -1
public int getGsmAsuLevel()	= 99
public int getGsmBitErrorRate()	= 99
public int getGsmDbm()	= -1
public int getGsmEcno()	= -1
public int getGsmLevel()	= 0
public int getGsmSignalDbm()	= -1
public int getGsmSignalStrength() = 99
public int getHtcCdmaLevel()	= 0
public int getHtcCdmaMaxLevel() = 5
public int getHtcEvdoLevel()	= 0
public int getHtcGsmLevel(int)	= [0 0 0 5 5 5 5 5 5 5 ]
public int getHtcGsmMaxLevel()	= 5
getHtcLevel(android.content.Context)
getHtcLevel(android.content.Context,int)
public int getHtcLteLevel()	= 5
public int getHtcLteRsrp()	= 88
public int getHtcLteRsrq()	= 12
public int getLevel()	= 4
public int getLteAsuLevel()	= 52
public int getLteCqi()	= 2147483647
public int getLteDbm()	= -88
public int getLteLevel()	= 4
public int getLteRsrp()	= -88
public int getLteRsrq()	= -12
public int getLteRssnr()	= 146
public int getLteSignalStrength()	= 29
public int getTDRscp()	= -1
public boolean isGsm()	= true
public boolean isInvalidLteSignalStrength()	= false
public boolean isInvalidTDSignalStrength()	= true

(#)
public int getAppendixType()	= 0
public int getCdmaDefaultRoamingIndicator()	= -1
public int getCdmaEriIconIndex()	= -1
public int getCdmaEriIconMode()	= -1
public int getCdmaRoamingIndicator()	= -1
public int getCombinedRadioTechnology()	= 14
public int getCombinedRegState() = 0
public boolean getCombinedRoaming()	= false
public int getCssIndicator()	= 0
public int getDataNetworkType()	= 13
public String getDataOperatorAlphaLong()	= YES OPTUS
public String getDataOperatorAlphaShort()	= YES OPTUS
public String getDataOperatorNumeric()	= 50502
public int getDataRegState()	= 0
public boolean getDataRoaming() = false
public int getDataRoamingType()	= 0
public int getIMSRegState()	= -1
public boolean getIsManualSelection()	= true
public int getNetworkId()	= -1
public int getNetworkType()	= 13
public int getNetwrorkType()	= 0
public String getOperatorAlphaLong()	= YES OPTUS
public String getOperatorAlphaShort()	= YES OPTUS
public String getOperatorNumeric()	= 50502
public int getPhoneType()	= 1
public int getRadioTechnology()	= 14
public int getRilDataRadioTechnology()	= 14
public int getRilVoiceRadioTechnology()	= 14
public boolean getRoaming()	= false
public static final String getRoamingLogString(int)
public int getState()	= 0
public int getSystemId()	= -1
public int getVoiceNetworkType() = 13
public String getVoiceOperatorAlphaLong()	= YES OPTUS
public String getVoiceOperatorAlphaShort()	= YES OPTUS
public String getVoiceOperatorNumeric()	= 50502
public int getVoiceRegState()	= 0
public boolean getVoiceRoaming()		 = false
public int getVoiceRoamingType() = 0
public static boolean is3GPP(int)	= [false true true true false false false false false true true true false false false ]
public static boolean is4G(int)	= [false false false false false false false false false false false false false true true ]
public static boolean isCdma(int)	= [false false false false true true true true true false false false true true false ]
public boolean isEmergencyOnly() = false
public static boolean isEvdo(int)	= [false false false false false false false true true false false false true false false ]
public static boolean isGsm(int)	= [false true true true false false false false false true true true false false true ]

(x)
public [I getActiveSubscriptionIdList()	= [1 ]
public android.telephony.SubscriptionInfo getActiveSubscriptionInfo(int)
public int getActiveSubscriptionInfoCount() = 1
public int getActiveSubscriptionInfoCountMax()	= 1
public android.telephony.SubscriptionInfo getActiveSubscriptionInfoForIccIndex(java.lang.String)
public android.telephony.SubscriptionInfo getActiveSubscriptionInfoForSimSlotIndex(int)
public java.util.List getActiveSubscriptionInfoList()
public int getAllSubscriptionInfoCount()	= 4
public java.util.List getAllSubscriptionInfoList()
public int getDefaultDataPhoneId()		 = 0
public static int getDefaultDataSubId()	= 1
public android.telephony.SubscriptionInfo getDefaultDataSubscriptionInfo()
public int getDefaultSmsPhoneId() = 0
public static int getDefaultSmsSubId()	= 1
public android.telephony.SubscriptionInfo getDefaultSmsSubscriptionInfo()
public static int getDefaultSubId() = 1
public static int getDefaultVoicePhoneId()	= 0
public static int getDefaultVoiceSubId()	= 1
public android.telephony.SubscriptionInfo getDefaultVoiceSubscriptionInfo()
public static int getPhoneId(int)	= [2147483647 0 2147483647 2147483647 2147483647 2147483647 2147483647 2147483647 2147483647 2147483647 ]
public static int getSimStateForSubscriber(int)	= [5 5 5 5 5 5 5 5 5 5 ]
public static int getSlotId(int)	= [-1 0 -1 -1 -1 -1 -1 -1 -1 -1 ]
public static [I getSubId(int)	= [| 0: 1 | 1: null | 2: null | 3: null | 4: null | 5: null | 6: null | 7: null | 8: null | 9: null ]

(*)
public String getNetworkCountryIso() = au
public String getNetworkCountryIsoForPhone(int) = au, au, au, au, au, au, au, au, au, au,
public String getNetworkCountryIsoForSubscription(int) = au, au, au, au, au, au, au, au, au, au,
public String getNetworkOperator() = 50502
public String getNetworkOperatorForPhone(int) = 50502, 50502, 50502, 50502, 50502, 50502, 50502, 50502, 50502, 50502,
public String getNetworkOperatorForSubscription(int) = 50502, 50502, 50502, 50502, 50502, 50502, 50502, 50502, 50502, 50502,
public String getNetworkOperatorName() = YES OPTUS
public String getNetworkOperatorName(int) = YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS,
public String getNetworkTypeName() = LTE
public static String getNetworkTypeName(int) = UNKNOWN, GPRS, EDGE, UMTS, CDMA, CDMA - EvDo rev. 0, CDMA - EvDo rev. A, CDMA - 1xRTT, HSDPA, HSUPA,
public String getSimCountryIso() = au
public String getSimCountryIso(int) = au, au, au, au, au, au, au, au, au, au,
public String getSimCountryIsoForPhone(int) = au, au, au, au, au, au, au, au, au, au,
public String getSimCountryIsoForSubscription(int) = au, au, au, au, au, au, au, au, au, au,
public String getSimOperator() = 50502
public String getSimOperator(int) = 		50502, 50502, 50502, 50502, 50502, 50502, 50502, 50502, 50502, 50502,
public String getSimOperatorName() = YES OPTUS
public String getSimOperatorNameForPhone(int) = YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS,
public String getSimOperatorNameForSubscription(int) = YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS, YES OPTUS,
public String getSimOperatorNumeric() = 50502
public String getSimOperatorNumericForPhone(int) = 50502, 50502, 50502, 50502, 50502, 50502, 50502, 50502, 50502, 50502,
public String getSimOperatorNumericForSubscription(int) = 50502, 50502, 50502, 50502, 50502, 50502, 50502, 50502, 50502, 50502,

(*)
public java.util.List getAllCellInfo()
public android.telephony.CellLocation getCellLocation()
public int getCurrentPhoneType()	= 1
public int getCurrentPhoneType(int)	= [1 1 1 1 1 1 1 1 1 1 ]
public int getDataActivity()	= 0
public boolean getDataEnabled()	= true
public boolean getDataEnabled(int)	= [true true true true true true true true true true ]
public int getDataNetworkType()	= 13
public int getDataNetworkType(int)		 = [13 13 13 13 13 13 13 13 13 13 ]
public int getDataState()	= 0
public static android.telephony.TelephonyManager getDefault()
public int getDefaultSim()	= 0
public int getLteOnCdmaMode()	= 0
public int getLteOnCdmaMode(int)		 = [0 0 0 0 0 0 0 0 0 0 ]
public static int getLteOnCdmaModeStatic()	= 0
public [LString; getMergedSubscriberIds()
public android.telephony.TelephonyManager$MultiSimVariants getMultiSimConfiguration()
public java.util.List getNeighboringCellInfo()
public static int getNetworkClass(int)	= [0 1 1 2 1 2 2 1 2 2 ]
public int getNetworkType()	= 13
public int getNetworkType(int)	= [13 13 13 13 13 13 13 13 13 13 ]
public [LString; getPcscfAddress(String)
public int getPhoneCount()	= 1
public int getPhoneType()	= 1
public static int getPhoneType(int) = [1 1 1 1 2 2 2 2 2 1 ]
public int getPreferredNetworkType()	= -1
public int getSimCount()	= 1
public int getSimState()	= 5
public int getSimState(int)	= [5 0 0 0 0 0 0 0 0 0 ]
public int getTetherApnRequired() = -1
public int getVoiceNetworkType() = 13
public int getVoiceNetworkType(int)	= [13 13 13 13 13 13 13 13 13 13 ]
public boolean isDataConnectivityPossible()	= true
public boolean isIdle()	= true
public boolean isImsRegistered()	= false
public boolean isMultiSimEnabled()	= false
public boolean isNetworkRoaming()	= false
public boolean isNetworkRoaming(int)	= [false false false false false false false false false false ]
public boolean isOffhook()	= false
public boolean isRadioOn()	= true
public boolean isVideoCallingEnabled()	= false
public boolean isVoiceCapable()	= true
public void listen(android.telephony.PhoneStateListener,int)

(*)
public String getCdmaEriText()
public String getCdmaEriText(int)
public String getCdmaMdn()
public String getCdmaMdn(int)
public String getCdmaMin()
public String getCdmaMin(int)
public String getDeviceId()
public String getDeviceId(int)
public String getDeviceSoftwareVersion()
public String getDeviceSoftwareVersion(int)
public String getGroupIdLevel1()
public String getGroupIdLevel1(int)
public String getIccSimChallengeResponse(int,int,String)
public String getIccSimChallengeResponse(int,String)
public String getImei()
public String getImei(int)
public String getLine1AlphaTag()
public String getLine1AlphaTagForSubscriber(int)
public String getLine1Number()
public String getLine1NumberForSubscriber(int)
public String getMsisdn()
public String getMsisdn(int)
public String getNai()
public String getNai(int)
public String getOtaSpNumberSchema(String)
public String getOtaSpNumberSchemaForPhone(int,String)
public String getSimSerialNumber()
public String getSimSerialNumber(int)
public String getSubscriberId()
public String getSubscriberId(int)
public static String getTelephonyProperty(int,String,String)

Sent from my HTC

**Comment by liclac** [comment]
@diego-plan9 Update: #195 is implemented, otto is no longer a dependency; package away!

**Comment by diego-plan9** [comment]
Thanks, @liclac! I noticed and did some preliminary packaging tests yesterday: it seems we might need to update a couple of dependencies that were already on Debian but not recent enough for our needs in the process, but other than that is looking good - I'll update this issue when I have a more solid picture!

**Comment by diego-plan9** [comment]
An status update: all the dependencies *introduced by k6* are finally sponsored and on the Debian repositories. There are still two dependencies that need to be updated (`color` and `isatty`), as they were already in Debian and updating them needed to be postponed until the freeze was over.

Which brings me to the second point: the new version of Debian will be released [2017-06-17](https://lists.debian.org/debian-devel-announce/2017/05/msg00002.html)! In practice, it means that after that date updating the two remaining dependencies should be a matter of days, and also means that we can move to using go 1.8 safely.

**Comment by robingustafsson** [comment]
@diego-plan9 Thanks for sharing, that's good news indeed! Then we should be able to move forward with https://github.com/loadimpact/k6/issues/188 soon.

**Comment by diego-plan9** [comment]
Another status update: at this moment,  the dependencies for `k6` version 0.17.1 are all in the Debian repositories ... except unfortunately for `babel-standalone`, which is the main blocker, and a pretty industrious one. 

The reason is that, according to Debian policies, the `babel-standalone` files included in the `k6` distribution are akin to binaries, and they need to be produced from the source (ie. regular `node-babel`), which in practice means a package that provides `babel-standalone` needs to be on the Debian repositories. The process for packaging it should be pretty similar to the work done for the rest of the dependencies, but due to me not being familiar with the node toolchain and intricacies, and due to the fact that there seems to be quite a number of nodejs dependencies (most of them would need to be produced by the recently packaged [`node-babel`](https://packages.debian.org/source/sid/node-babel), I'm unsure how long it will take to finally produce the `babel-standalone` package.

I do intend to get them packaged eventually, but as discussed on private, an alternative would be to provide non-Debian compliant `.deb` files in the meantime. The gist of the work is on the [alioth VCS](https://anonscm.debian.org/cgit/pkg-go/packages/k6.git)  and more details can be found on the private `k6-debian` repository (and I'd be happy to assist in any particulars!).
