### ISSUE TITLE
Setup function and test results

### ISSUE THREAD

**Issue by yiss** [loadimpact/k6#1508]
## Environment

- k6 version: v0.26.2 (2020-03-18T11:45:39+0000/v0.26.2-0-g459da79e, go1.13.8, windows/amd64)
- OS and version: Windows
- Docker version and image, if applicable:

## Expected Behavior

Before running my load tests I need some to create some records using a post method, so that the test data is dynamic. Normally I would expect that all the requests made in setup function to not be accounted for when displaying (metrics.http_req) since they're not part of the test (or the default function).

## Actual Behavior

The time to prepare data is accounted for in the results

is there anyway to not have this since it affects the benchmarks of our API, beside using statically generated data ? Thank you

**Comment by imiric** [comment]
Hi, thanks for reporting this. It's a known issue: see #891 and #1321, particularly the workaround with tags mentioned in #891.

So I'll close this as duplicate, but feel free to follow those issues for updates. Currently the team is focused on a big upcoming release, but this feature is one of the top priorities after that.

**Comment by yiss** [comment]
@imiric Thank you for your response :)
