### ISSUE TITLE
console.log not being .. compatible with browsers and nodejs

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#1510]
## Environment

- k6 version: v0.26.2

## Expected Behavior
```
console.log("something", "other", "and", "third");
```
will print
```
something other and third
```

## Actual Behavior
```
INFO[0000] something                                     0=other 1=and 2=third
```

## Steps to Reproduce the Problem

1. run `console.log("something", "other", "and", "third");`

This is not what either [browsers](https://developer.mozilla.org/en-US/docs/Web/API/Console/log
) or [nodejs]( https://nodejs.org/api/console.html#console_console_info_data_args) does, screenshot from firefox:
![image](https://user-images.githubusercontent.com/312246/85394022-9cc20f80-b556-11ea-9bd9-ec739d2d9a83.png)

I also don't see any useful reason to do it this way, so I propose it's changed to concat the strings and maybe we can add the formatting support at a later stage.

**Comment by na--** [comment]
I agree, though I think we should probably tackle https://github.com/loadimpact/k6/issues/1146 at the same time, given that we'll be mucking with type assertions in there
