### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by imiric** [loadimpact/k6#1537]
Sparked by [this forum question](https://community.k6.io/t/does-k6-support-ipv6/734), my tests in a VM lab show that k6 can't connect to an IPv6 address, even though this is natively supported in Go.

Also see related issue #1109.

## Environment
- k6 version: `k6 v0.26.2 (2020-03-18T11:45:39+0000/v0.26.2-0-g459da79e, go1.13.8, linux/amd64)`
- OS and version: Linux
- Docker version and image, if applicable: N/A

## Expected Behavior
k6 can connect to and test against an IPv6 address/host.

## Actual Behavior
Several errors are shown instead:
- `no such host` when trying an IPv6 address in bracket notation because of the port:
![2020-07-08-110340_801x81_scrot](https://user-images.githubusercontent.com/1009277/86903284-6ae0a980-c10f-11ea-97f3-7aab4a3f979f.png)
- `connect: invalid argument` when trying with a hostname that resolves to an IPv6 address:
![2020-07-08-110945_799x71_scrot](https://user-images.githubusercontent.com/1009277/86903165-3e2c9200-c10f-11ea-9b29-d563dd145cee.png)

Note that I can `nc`/`curl` the remote service OK, so it is accessible from the test VM:
![2020-07-08-114049_782x150_scrot](https://user-images.githubusercontent.com/1009277/86903873-36212200-c110-11ea-81ac-873b2d8862de.png)

## Steps to Reproduce the Problem

1. Setup 2 VMs connected on the same internal network and assign the NICs IPv6 addresses.
2. Run an HTTP service (e.g. `python -m http.server --bind ::`) on one VM and create a simple k6 script on the other:
```js
import http from 'k6/http';

export default function () {
  http.get('http://[fe80::6f02:cf05:1bc:8883]:8000');
}
```
3. Run `k6 run script.js`.

I also tried specifying the NIC as in the `nc`/`curl` example (`[fe80::6f02:cf05:1bc:8883%enp0s3]`), but that fails parsing the URL with `invalid URL escape "%!e(MISSING)n"`, with or without escaping `%`.

**Comment by SebastianStehle** [comment]
This is not exactly the same as my problem.

My case is the problem that when you have a hostname like "localhost" with two addresses (ipv4 and ipv6), k6 tries ipv6 and when it fails it gives up. The default implementation seems to be to try all addresses and to use the first working. Not 100% sure.

**Comment by na--** [comment]
hmm yeah, we should also support that, it's called `Happy Eyeballs` and can be configured via the [`Dialer.DualStack` option](https://golang.org/pkg/net/#Dialer).

**Comment by TobiasEngelbert** [comment]
Great, that this issue is placed in v0.27.1. Do you know when v0.27.1 is planned to be released?

**Comment by na--** [comment]
We plan to release v0.27.0 early next week. v0.27.1 means "soon after that", but I can't give you an exact time... I tagged it as v0.27.1 and not as v0.28.0 because we consider this a bug, and a high priority one at that, so we don't need to wait for a full new version to release it.

**Comment by imiric** [comment]
We decided to push this back to v0.28.0, as part of #1489. Since that PR also introduces a feature, it's not suitable for a patch release. We're planning more frequent releases now, so v0.28.0 will be a smaller release soon after v0.27.1.

If you want just this fix now, it can be compiled from the [fix/1537-ipv6 branch](https://github.com/loadimpact/k6/tree/fix/1537-ipv6).

**Comment by na--** [comment]
This was inadvertently resolved by https://github.com/loadimpact/k6/pull/1489
