### ISSUE TITLE
The Date().toUTCString() returns wrong result

### ISSUE THREAD

**Issue by georgekcchung** [loadimpact/k6#1540]
## Environment

- k6 version: v0.26.2
- OS and version: Ubuntu 20.04 LTS

Issue: The Date().toUTCString() returns wrong result.

let myDate = Date().toUTCString()
console.log(myDate);

## Expected Behavior

Wed, 08 Jul 2020 12:17:51 GMT

## Actual Behavior

Wed Jul 08 2020 12:17:51 GMT+0000 (UTC)

**Comment by MStoykov** [comment]
Hi @georgekcchung , this was an [upstream bug](https://github.com/dop251/goja/issues/119) that has been fixed and will be released in v0.27.0, soon :tm: . 

Thanks for reporting it :D

**Comment by na--** [comment]
You can use the k6 Docker `master` image until we release v0.27.0, which is expected to be next Monday.
