### ISSUE TITLE
Script filename in collector

### ISSUE THREAD

**Issue by martinfijal** [loadimpact/k6#155]
To properly be able to name tests in the cloud we need access to a name for the currently executing script/URL in the collector. @robingustafsson can you verify if we will need more than these cases from your notes about this?

1. Name of JS file if started with one
2. Name in the "loadimpact" part of the options object
3. URL for the simple URL tests

Do we support running a test in some way that doesn't produce a meaningful name (like sending in the script on stdin)?

**Comment by uppfinnarn** [comment]
I think the easiest way would be to simply provide the Options to the Collector, then you can pass a filename to the LoadImpact Collector's constructor specifically in `run.go`. The URL to the URL runner is actually a source file where both the filename and the file contents are a URL string, so you only need one code path for that.

(Note: the URL runner is likely going away to make way for #152, so don't worry too much about it.)

**Comment by martinfijal** [comment]
Sounds good to me :+1:

**Comment by liclac** [comment]
@martinfijal a SourceData struct is [now provided](https://github.com/loadimpact/k6/commit/4e825dfb897c4f585606e213807745c9cea531b3) to makeCollector(), and there's [a spot for external data](https://github.com/loadimpact/k6/commit/7a757c52a0b26521e342201405c42b9f06ece254) in the Options struct.

I suggest using [mapstructure](https://github.com/mitchellh/mapstructure) to decode the contents of Options.External["loadimpact"] into a more helpful struct of some kind.
