### ISSUE TITLE
Add option to csv output to gzip the file

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#1550]
Exactly the same as [json output](https://github.com/loadimpact/k6/pull/1114)

**Comment by thejasbabu** [comment]
I can take this up, should I also raise a PR in the k6s-doc repository? Seems like the documentation is also missing for csv output.

**Comment by na--** [comment]
@thejasbabu, go ahead! :+1:  And yes, we recently realized we're missing the CSV docs: https://github.com/loadimpact/k6-docs/issues/54 :sweat_smile:
