### ISSUE TITLE
URL pointing to test results when using cloud output plugin

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#156]
Would be good to have the URL of the test results printed to stdout when running k6 with `-o cloud=loadimpact`.

Maybe by adding something around the area of `output: Load Impact`?

The URL format is `https://$APP_HOSTNAME/k6/runs/$TEST_RUN_ID` where the current value of `$APP_HOSTNAME` is the app in our staging environment.

**Comment by uppfinnarn** [comment]
Collectors can actually modify what's put there; just make `String()` return something else. Or better yet: how about a hook to add another URL below "web ui"?

**Comment by robingustafsson** [comment]
@uppfinnarn Yeah, but it looks like the cloud output plugin doesn't know the test run ID until the collector's `Run()` is called, which happens after the banner+meta data output.

@martinfijal Could we perhaps move the `CreateTestRun()` call to `New()` so that we have the `referenceID` available from the start of the collector?

Alternatively introduce some kind of init/prepare interface for collectors that gets called after `New()` but before the k6 output starts.

**Comment by uppfinnarn** [comment]
I'd like to add an `Init()` hook or similar, yeah, that way we can print the banner and *then* wait for the collector - much better UX. (I'd also like to add a `Login()` hook for a hypothetical `k6 login [collector]` subcommand.)

**Comment by martinfijal** [comment]
Very much in favor of your `Init()` propsal @uppfinnarn.

**Comment by robingustafsson** [comment]
@uppfinnarn @martinfijal I've implemented the minimal changes needed for this now, how should I share it for your review? Fork, and create PR off of the `feature/cloud` branch (which would push down the current WIP commit on that branch)?

**Comment by uppfinnarn** [comment]
Just make a branch called `feature/collector-init` or something of the sort and PR that, may as well skip the fork. Make sure that's the only thing in it!

Or PR the whole cloud machinery, I suppose,

**Comment by robingustafsson** [comment]
Created [PR](https://github.com/loadimpact/k6/issues/157) for general changes now against `master`, will commit the cloud specific stuff on `feature/cloud` once the PR is merged to `master`.

**Comment by robingustafsson** [comment]
The URL has been added to the WIP commit on `feature/cloud`: https://github.com/loadimpact/k6/commit/5c624a24f9e3f7fc58b9d262dc33aceb95e2cb58

Closing this issue.
