### ISSUE TITLE
Export the status line text in HTTP response objects

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#1585]
## Feature Description

As noted in https://community.k6.io/t/need-to-get-http-response-status-line/839, there doesn't seem to be a way to get the HTTP status text from an HTTP response. There's no good reason for that, and it should be easy to add.

## Suggested Solution (optional)

Given that we currently transpose Go's [`http.Response.StatusCode`](https://github.com/golang/go/blob/5c7748dc9de9c9e0a6844bf72faaf5b484004ba9/src/net/http/response.go#L35-L37)

as the k6's [`Response.Status`](https://k6.io/docs/javascript-api/k6-http/response): https://github.com/loadimpact/k6/blob/0e94653c9954c17b2b1a480b456e23ec120feff2/lib/netext/httpext/request.go#L333

I guess we should add a new k6 field `Response.StatusText` or `Response.StatusLine` in which to save Go's `http.Response.Status`?

**Comment by lcd1232** [comment]
I'll do this
