### ISSUE TITLE
Update to Go 1.15

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#1589]
We should reenable `test-prev-golang` when we move to golang 1.15.x. This is being dropped as part of #1588 because goja requires go 1.14.x

**Comment by na--** [comment]
Edited the issue to track all Go 1.15 changes

As a part of our k6 v0.28.0 we should also mention some of the backwards compatibility breakages Go 1.15 introduces from https://golang.org/doc/go1.15, https://github.com/golang/go/issues/39568 specifically might affect some of our users.

**Comment by na--** [comment]
Moved this to v0.29.0, since it doesn't seem like the Go 1.15.2 bugfix release is going to be ready in time for us to build and test k6 v0.28.0 with it.
