### ISSUE TITLE
Display threshold specified statistic in metric stdout output

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#160]
When running a script with a threshold specifying a statistic other than the default ones we print in the stdout output we should show that statistic as well. Let me illustrate with an example:

```js
import http from "k6/http";

export let options = {
    thresholds: {
        http_req_duration: ["p(99)<100"]
    }
};

export default function() {
    http.get("http://test.loadimpact.com/");
}
```

The output printed for `http_req_duration` looks like:
`✗ http_req_duration.....: avg=231.33ms, max=231.33ms, med=231.33ms, min=231.33ms, p90=231.33ms, p95=231.33ms`

whereas I think it would make sense to add p99 here like:
`✗ http_req_duration.....: avg=231.33ms, max=231.33ms, med=231.33ms, min=231.33ms, p90=231.33ms, p95=231.33ms, p99=231.33ms`

**Comment by ppcano** [comment]
I don't know if this is an issue but it would be good if naming is consistent:

` http_req_duration: ["p(99)<100"]`  --> `http_req_duration: ["p99<100"]`

or use in the output `p(99)` instead of `p99`.

**Comment by uppfinnarn** [comment]
They're JS expressions, so `p(99)` is calling a function to get the 99th percentile, while `p99` would mean assigning 100 before every threshold run…

**Comment by robingustafsson** [comment]
Could we perhaps also highlight the statistic in someway in the output, color perhaps to show connection to cross or checkmark in the left gutter?

**Comment by ppcano** [comment]
@uppfinnarn 

This is not a big issue IMO but I want to clarify it.


My second idea was to modify the console output `p99` --> `p(99)`.

If we use the same syntax in both places (threshold API and output), it may be less error-prone and easier to understand.

Given the console output:

`http_req_duration.....: avg=231.33ms, max=231.33ms, med=231.33ms, min=231.33ms, p90=231.33ms, p95=231.33ms, p99=231.33ms`

`http_req_duration: ["avg<100"]`
`http_req_duration: ["max<100"]`
`http_req_duration: ["med<100"]`

But a threshold with percentiles follows a different convention (if seen from the output perspective).

`http_req_duration: ["p(90)<100"] `
`http_req_duration: ["p(99)<100"] `

**Comment by uppfinnarn** [comment]
Not a bad idea at all, I do like the copypaste'ability.

The thing about highlighting the dimensions used is that we don't actually know; `p(x)` we can catch because it's a function, but to catch *variable reads*, we'd have to dig into the AST when parsing the expressions - which would *also* let us make non-function `pX` work, but would be a lot of work for something relatively minor.

**Comment by ppcano** [comment]
@uppfinnarn I don't discuss the syntax `p99` vs `p(99)`, both option are fine to me. 

I would like both places (console output & code) to use the same syntax because:
- copypaste' ability
- less error prone
- easier to understand

Should I open an independent issue for this proposed change?

**Comment by liclac** [comment]
Doing some research, and we could actually invoke the [goja parser](https://godoc.org/github.com/dop251/goja/parser) manually, then scan through the results for [Identifier](https://godoc.org/github.com/dop251/goja/ast#Identifier) and [CallExpression](https://godoc.org/github.com/dop251/goja/ast#CallExpression) nodes. I do like the idea of highlighting the values the user is actually interested in.

**Comment by liclac** [comment]
Thoughts on the design?

![screenshot_20170612_162802](https://user-images.githubusercontent.com/428026/27041662-813e71be-4f8c-11e7-8602-f611b7583ae9.png)
![screenshot_20170612_162848](https://user-images.githubusercontent.com/428026/27041664-8145155a-4f8c-11e7-91e7-220c6c0cccd8.png)
![screenshot_20170612_162928](https://user-images.githubusercontent.com/428026/27041663-81407e78-4f8c-11e7-90a6-9a06e160097f.png)

**Comment by robingustafsson** [comment]
I vote for the middle one, having both key and value in bold.

**Comment by ppcano** [comment]
I talked with @majavojnoska about the command output when discussing #243. She proposed to show a title in the different sections.

**Checks**

**Metrics**

Yesterday at the @robingustafsson presentation, I found the threshold representation to be non-obvious.

A proposal could be to separate the thresholds from the metrics sections and show a title for each section.

**Thresholds**

**Checks**

**User metrics**

**System metrics**

@liclac, I can work on the output part when a decision is made.

**Comment by liclac** [comment]
@ppcano wrong issue! I think you meant to post that in #243

**Comment by ppcano** [comment]
@liclac No wrong issue. Likely bad/wrong explanation ;)

1) The proposal here is to have a list of thresholds independently of the metric list. 

2) Add a title for each section


```
Thresholds
     ✓ - http_req_duration: p(95)<800

Checks
    ✓ 100% - my first assertion
    ✗ 0% - my second assertion

User metrics

    myNewMetric.........: 78 kB (39 kB/s)

Default metrics

    checks................: 80.00%
    data_received.........: 78 kB (39 kB/s)
    data_sent.............: 505 B (252 B/s)
    http_req_blocked......: avg=146.13ms max=150.13ms med=150.05ms min=140.12ms p90=150.13ms p95=150.13ms
    http_req_connecting...: avg=144.79ms max=148.78ms med=148.73ms min=138.74ms p90=148.78ms p95=148.78ms
    http_req_duration.....: avg=2.47s max=2.65s med=2.47s min=2.27s p90=2.65s p95=2.65s
    http_req_receiving....: avg=60ms max=144.74ms med=60.06ms min=931.03µs p90=144.74ms p95=144.74ms
    http_req_sending......: avg=83.89µs max=127.41µs med=72.85µs min=40.46µs p90=127.41µs p95=127.41µs
    http_req_waiting......: avg=2.41s max=2.59s med=2.41s min=2.27s p90=2.59s p95=2.59s
    http_reqs.............: 5 (2.5/s)
    iterations............: 5 (2.5/s)
    vus...................: 5
    vus_max...............: 5

```

**Comment by liclac** [comment]
@ppcano Let's make it a different issue then, all I'm looking for here is how to highlight metrics that have a threshold on them.

**Comment by ppcano** [comment]
Created new issue #247
