### ISSUE TITLE
Default to application/x-www-form-urlencoded for auto-encoded bodies

### ISSUE THREAD

**Issue by liclac** [loadimpact/k6#161]
Passing an object as the body to an HTTP request encodes it as a form, but doesn't set the content type. It may as well be implicit.

**Comment by micsjo** [comment]
Possible to override? I.e. params passed (such as headers) will override automagic headers?

**Comment by uppfinnarn** [comment]
Yeah, of course, just a default for the `Content-Type` header

**Comment by micsjo** [comment]
Assume it applies to _all_ verbs, not just POST?

**Comment by uppfinnarn** [comment]
yeah

**Comment by robingustafsson** [comment]
@liclac This can be closed now, no?
