### ISSUE TITLE
Upgrade gjson library

### ISSUE THREAD

**Issue by sondnm** [loadimpact/k6#1624]
Current gjson version is 1.1.3 which is from late 2018 and lacks several features such as:
- Modifier `@flatten` to transform a json `[1, [2, 3]]` to `[1, 2, 3]` https://github.com/tidwall/gjson/blob/master/SYNTAX.md#modifiers
- Join multipaths https://github.com/tidwall/gjson/blob/master/SYNTAX.md#multipaths

**Comment by na--** [comment]
Hey, @sondnm, thanks for notifying us of the changes! Do you want to make a PR?

**Comment by sondnm** [comment]
@na-- Thanks for the quick response. I created a PR. Please help me review it 🙇
