### ISSUE TITLE
Intermittent error - ERRO[0000] The moduleSpecifier

### ISSUE THREAD

**Issue by andrewoh531** [loadimpact/k6#1635]
When running k6 via [docker-compose for InfluxDb/Grafana](https://k6.io/docs/results-visualization/influxdb-+-grafana)  I get the following error intermittently. If I wait a few minutes after the error then it will usually work again.

```
-> docker-compose run -v \
    $PWD/../tests/:/scripts \
    k6 run /scripts/public-api.js

          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |      |  /  ‾‾\
   /          \   |  |‾\  \ | (_) |
  / __________ \  |__|  \__\ \___/ .io

ERRO[0000] The moduleSpecifier "/scripts/public-api.js" couldn't be found on local disk. Make sure that you've specified the right path to the file. If you're running k6 using the Docker image make sure you have mounted the local directory (-v /local/path/:/inside/docker/path) containing your script and modules so that they're accessible by k6 from inside of the container, see https://k6.io/docs/using-k6/modules#using-local-modules-with-docker.
```

## Environment
- Docker version and image, if applicable: loadimpact/k6:0.27.1

## Expected Behavior
It should either consistently run successfully or consistently error out

## Actual Behavior
Sometimes the exact same command works, sometimes it fails.

**Comment by imiric** [comment]
Hi, thanks for reporting this.

You didn't provide the host OS and version you're using, which is relevant when discussing Docker issues.

I can't reproduce this on Linux, but if you're running Windows or macOS there might be some issues with the way they handle bind volume mounts.

You can workaround this by building your own k6 Docker image and bundling the scripts you need inside it, so you wouldn't have to use `-v`.

**Comment by andrewoh531** [comment]
I'm running this on macOS and the Docker version is `19.03.12, build 48a66213fe`.

Sure I'll work around this issue.

**Comment by anton-makarov-photobox** [comment]
Any updates?
