### ISSUE TITLE
NTLM username containing domain name raises exception

### ISSUE THREAD

**Issue by mostafa** [loadimpact/k6#1642]
According to [this forum post](https://community.k6.io/t/ntlm-authentication-not-working/940), I've tested the NTLM implementation and it doesn't process domain name correctly.

## Environment
- k6 version: k6 v0.28.0 (2020-09-21T12:06:29+0000/v0.28.0-0-gdee9c4ce, go1.14.9, windows/amd64)
- OS and version: Windows Server 2019

## Expected Behavior
I except to be able to authenticate with NTLM username/password and test an endpoint, in which the username part also includes the domain name.

## Actual Behavior
This error is returned
```bash
ERRO[0005] GoError: parse "http://localhost\\username:password@localhost/": net/url: invalid userinfo
        at github.com/loadimpact/k6/js/common.Bind.func1 (native)o
        at file:///C:/Users/Administrator/Desktop/test.js:9:81(23)  executor=per-vu-iterations scenario=default source=stacktrace
```

## Steps to Reproduce the Problem
Using the following script:
```js
import http from 'k6/http';

const domain = 'localhost';
const username = 'Administrator';
const password = 'password';

export default function () {
  const credentials = `${domain}\\${username}:${password}`;
  let res = http.get(`http://${credentials}@localhost/`, { auth: 'ntlm' });
  console.log(res.status);
}
```
and running it using
```bash
$ k6 run test.js
```

**Comment by MStoykov** [comment]
As I pointed in the community forum, the userInfo should be [percent encoded](https://en.wikipedia.org/wiki/Percent-encoding) and indeed if `/` is replaced with `%2F` it does work. 

I am not certain supporting having `/` will be easy ... or if even that is a good idea, but will leave this open for now

**Comment by na--** [comment]
As far as I can see, this is not a bug... I tried parsing the same by running this in a browser console and it produced a nonsensical result, so I'd be pretty comfortable saying it's an invalid URL that should be percent encoded...
```js
let u = new URL("http://domain\\username:password@example.com/")
console.log(u.href); // prints "http://domain/username:password@example.com/"
```

**Comment by michaellwest** [comment]
This worked for me:

```javascript
import http from 'k6/http'

const domain = 'domain'
const username = 'first.last'
const password = 'Abc123!'

export const options = {
    vus: 1,
    duration: '10s'
};

export default function() {
    const credentials = encodeURI(`${domain}\\${username}:${password}`)
    http.get(`https://${credentials}@api.company.com/api/location/123?includeLeadership=true`, { auth: 'ntlm'});
}
```
