### ISSUE TITLE
Bandwidth usage

### ISSUE THREAD

**Issue by caalle** [loadimpact/k6#166]
Could the http metrics contain how much data that was transmitted? We had a brief discussion about this yesterday but can't see anything in the JSON output.

(ping @robingustafsson )

**Comment by robingustafsson** [comment]
Yes, it would be great to have data on both `bytes_sent` and `bytes_received`.

**Comment by uppfinnarn** [comment]
Really easy to implement, I'll toss it in once the goja runner is merged.

**Comment by liclac** [comment]
Wheee https://github.com/loadimpact/k6/commit/2cf20479cf2d4e74880009219c4e573ae6787269
