### ISSUE TITLE
Thresholds console output format

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#1675]
k6 shows the threshold result as a success (✓) or failure (✗).

Given:

```js
  failed_requests: ["rate<0.1"],
  http_req_duration: ["p(95)<500", "p(90)<1500"]
```

The k6 output could be:

```shell
✓ failed_requests............: 0.00%  ✓ 0    ✗ 8970 
✓ http_req_duration..........: avg=131.22ms min=115.29ms med=124.77ms max=260.27ms p(90)=150.87ms p(95)=162.87ms
```

I suggest a change to the threshold output to show the existing threshold configuration.

Here a suggestion inline with the current format:

```shell
failed_requests............: 0.00%  ✓ 0    ✗ 8970
 └─ ✓ rate<0.1 
http_req_duration..........: avg=131.22ms min=115.29ms med=124.77ms max=260.27ms p(90)=150.87ms p(95)=162.87ms
 └─ ✓ p(90)<1500
 └─ ✓ p(95)<500
```

Showing this information is useful in case you didn't remember the threshold configuration or you changed it between test runs.

**Comment by na--** [comment]
it's probably a good idea, but we have to consider how this will mesh with sub-metrics and thresholds defined on them. This is also somewhat similar to https://github.com/loadimpact/k6/issues/1319, and is probably going to get resolved by the summary templates proposed in that issue as well.

**Comment by na--** [comment]
@ppcano, now that we have [`handleSummary()`](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.30.0.md#support-a-handlesummary-callback-at-the-end-of-the-test-1768) (https://github.com/loadimpact/k6/pull/1768) and [k6-summary in jslib](https://github.com/loadimpact/jslib.k6.io/tree/master/lib/k6-summary), I think I should close this.

In k6 v0.31.0, we want to replace the Go summary generation code with the one from jslib (https://github.com/loadimpact/k6/issues/1806), so if you think you have a workaround to the [issue I raised above](https://github.com/loadimpact/k6/issues/1675#issuecomment-712250715), please open a new issue in the jslib repo, or even a PR that adds the desired behavior as an option to `generateTextSummary()`.
