### ISSUE TITLE
Checks Arent reporting as failed when k6 test fails

### ISSUE THREAD

**Issue by mkkeffeler** [loadimpact/k6#1680]
We are running a K6 test in shell script, it's a functional test with 5 checks. 

We see certain errors when the responses that come back are invalid JSON, an issue recently introduced on the target system, that k6 completely fails with

```

time="2020-10-21T20:01:22Z" level=error msg="TypeError: Object has no member 'json'\n\tat file:///home/vcap/app/config/app1/tests/apptest1/definition.js:110:24(234)\n" executor=shared-iterations scenario=default source=stacktrace

```

When reviewing reports for this test, we see 1 check in the summary, and that check passed. There are 4 more checks, each of which would have failed in this case, but k6 doesn't report that, because it errors out at line 110, and the rest of the checks are below in the code.

What is the expected way to catch such an error? as far as it looks, the 1 check passed, but there are 4 that didn't execute.

## Environment
- k6 version: .28
- OS and version: RHEL 7
- Docker version and image, if applicable:

## Expected Behavior
See 5 checks, where 1 passed but the further 4 failed or didn't run for some reason.

## Actual Behavior
see 1 check passing, no indication that the other 4 didn't run or failed.

## Steps to Reproduce the Problem
1. get a k6 test where the first http check is did you get a 200
2. in that same test try to access a json attribute of the response, where the response is not valid JSON, then do a second check right below that piece of code for the JSON.
3. see that that second check is not reported.

**Comment by na--** [comment]
> it errors out at line 110, and the rest of the checks are below in the code.

Well, k6 doesn't (and in fact can't) know about all of your checks if it doesn't reach them when running your script. k6 [checks](https://k6.io/docs/javascript-api/k6/check-val-sets-tags) are normal JavaScript function calls, not part of the global exported `options` or something like that, so if your iteration is interrupted by an exception, they simply won't be executed and thus counted. Would you expect node.js or Java or C++ to know about code below an exception, if you don't catch it?

> What is the expected way to catch such an error? as far as it looks, the 1 check passed, but there are 4 that didn't execute.

You can catch exceptions like this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch

**Comment by mkkeffeler** [comment]
so is the recommendation to put the whole thing in a try catch? seems weird. Is there another pattern for this that we could follow to asert that each check we expect to have run shows as passing and wasn't missed?

**Comment by na--** [comment]
You are trying to parse as JSON something that is not JSON - why is it weird that it results in an exception? :confused: What precisely do you think k6 should do instead?

> Is there another pattern for this that we could follow to asert that each check we expect to have run shows as passing and wasn't missed?

Again - it's not that the `check()` call was "missed", it and all other code after the unhandled exception was never reached and executed at all. So, you can either `catch` and handle that exception, or make sure to never cause it in the first place. For example, check if the `response.status` of the request is `200` before you try to parse it as JSON, or something like that.

**Comment by mkkeffeler** [comment]
We are using K6 to do functional testing. so one of the things we expect, but don't always get, is a json response. Sometimes we find errors that cause the service we are testing to not return json at all. 

And yes, I agree that it wasn't "missed", even still your logic of "never cause that in the first place", is what I would like to do, but can't due to what I said above. 

I think what I am trying to get at, is this is a great framework but the examples of using checks in tests should probably be enhanced so that errors like this can get caught and reported up for those who are using checks. Either that, or have k6 export the number of checks that are in the code, alongside the status of those checks, and let users manually compare and say " oh look, not all the checks ran, let me look into that"

**Comment by mkkeffeler** [comment]
Again, great framework and loving it, but need all my checks to run all the time, or have a way to know (without looking at the code of the test) the number of checks I should expect to have run.

**Comment by sniku** [comment]
Hey @mkkeffeler 

We are currently working on documenting how to properly use k6 for functional/integration testing. While this documentation is not yet released, I can give you a sample script that illustrates how to achieve your goal. 

```js
import { Counter } from 'k6/metrics';
import { test } from 'https://jslib.k6.io/functional/0.0.1/index.js';
import { Httpx, Request, Get, Post } from 'https://jslib.k6.io/httpx/0.0.1/index.js';

import { randomIntBetween, randomItem } from "https://jslib.k6.io/k6-utils/1.0.0/index.js";
import { crocodileAPIcontract, crocodileListAPIcontract } from './contracts/my_contracts/contracts.js'

export let options = {
  thresholds: {
    checks: [{threshold: 'rate == 1.00', abortOnFail: true}],
  }
};

const USERNAME = `user${randomIntBetween(1, 100000)}@example.com`;  // Set your own email;
const PASSWORD = 'superCroc2019';

let session = new Httpx();
session.setBaseUrl('https://test-api.k6.io');
// session.addErrorMetric(new Counter('http_req_errors'), (r) => r.status >= 200 && r.status <=399);

export default function testSuite() {

  test('01. Fetch public crocs', (t) => {
    let responses = session.batch([
      new Get('/public/crocodiles/1/'),
      new Get('/public/crocodiles/2/'),
      new Get('/public/crocodiles/3/'),
      new Get('/public/crocodiles/4/'),
    ], {
      tags: {name: 'PublicCrocs'},
    });

    responses.forEach(response => {
      t.expect(response.status).as("response status").toEqual(200)
        .and(response).toHaveValidJson()
        .and(response.json()).as("Croc API schema").toMatchAPISchema(crocodileAPIcontract)
        .and(response.json('age')).as('croc age').toBeGreaterThan(7);
    });
  })


  test(`02. Create a test user ${USERNAME}`, (t) => {

    let resp = session.post(`/user/register/`, {
      first_name: 'Crocodile',
      last_name: 'Owner',
      username: USERNAME,
      password: PASSWORD,
    });

    t.expect(resp.status).as("status").toEqual(201)
      .and(resp).toHaveValidJson();
  })

  
  test(`03. Authenticate the new user ${USERNAME}`, (t) => {

    let resp = session.post(`/auth/token/login/`, {
      username: USERNAME,
      password: PASSWORD
    });

    t.expect(resp.status).as("Auth status").toBeBetween(200, 204)
      .and(resp).toHaveValidJson()
      .and(resp.json('access')).as("auth token").toBeTruthy();

    let authToken = resp.json('access');
    // set the authorization header on the session for the subsequent requests.
    session.addHeader('Authorization', `Bearer ${authToken}`);

  })


  test('04. Create a new crocodile', (t) => {
    let payload = {
      name: `Croc Name`,
      sex: randomItem(["M", "F"]),
      date_of_birth: '2019-01-01',
    };

    let resp = session.post(`/my/crocodiles/`, payload);

    t.expect(resp.status).as("Croc creation status").toEqual(201)
      .and(resp).toHaveValidJson();

    session.newCrocId=resp.json('id');
  })


  test('05. Fetch private crocs', (t) => {

    let response = session.get('/my/crocodiles/');

    t.expect(response.status).as("response status").toEqual(200)
      .and(response).toHaveValidJson()
      .and(response.json().length).as("number of crocs").toEqual(1)
      .and(response.json()).toMatchAPISchema(crocodileListAPIcontract);
  })


  test('06. Update the croc', (t) => {
    let payload = {
      name: `New name`,
    };

    let resp = session.patch(`/my/crocodiles/${session.newCrocId}/`, payload);

    t.expect(resp.status).as("Croc patch status").toEqual(200)
      .and(resp).toHaveValidJson()
      .and(resp.json('name')).as('name').toEqual('New name');

    let resp1 = session.get(`/my/crocodiles/${session.newCrocId}/`);

  })


  test('07. Delete the croc', (t) => {

    let resp = session.delete(`/my/crocodiles/${session.newCrocId}/`);

    t.expect(resp.status).as("Croc delete status").toEqual(204);
  });

}
```

Note the `t.expect(...).and(...).and(...)` chains. The chain executes until one of the chain links returns false. In your use case, one of the responses doesn't have valid JSON, so this cha

**Comment by mkkeffeler** [comment]
this does look like what I am discussing :) any docs on that functional jslib and how that is working? or should I await release?

**Comment by sniku** [comment]
Both the `functional` and `httpx` libs are in the alpha version and evolve as I'm documenting them. I hope to release the docs in the next ~4 weeks. The code should be stable enough to use, so feel free to try it. 
The source code for the libraries (https://jslib.k6.io/) is fairly small and easy to read so you may want to just look at that until the docs are released.

**Comment by mkkeffeler** [comment]
thanks for sharing, i think id rather wait until we know these libs you are using are stable. then start to refactor, thanks a ton for the info, this looks like a big improvement
