### ISSUE TITLE
gRPC protobuf definitions aren't included in archive bundles

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#1696]
If I download [`addsvc.proto`](https://github.com/moul/pb/blob/master/addsvc/addsvc.proto) from https://grpcb.in/, the following code will work with `k6 run` but won't work with `k6 cloud`:
```js
import grpc from 'k6/protocols/grpc';
import { check } from 'k6';

let client = grpc.newClient();
client.load([], 'addsvc.proto')

export default () => {
  console.log('Connecting to grpcb.in...');
  client.connect('grpcb.in:9001', {})

  console.log('Done, invoking RPC...');

  const response = client.invoke('addsvc.Add/Sum', {
    a: 1,
    b: 1
  })

  check(response, { 'status is OK': (r) => r && r.status === grpc.StatusOK });
  console.log(JSON.stringify(response.message))

  client.close()
}
```

The reason for this is that `client.load()` doesn't include the .proto files in the [archive bundle](https://k6.io/docs/misc/archive-command) k6 generates. Connected to that, when we're executing a k6 archive bundle (`k6 run archive.tar`), k6 should not do any file lookups on the real filesystem and instead should be restricted to the files in the archive. 

I think this can be solved by implementing [`protoparse.FileAccessor`](https://godoc.org/github.com/jhump/protoreflect/desc/protoparse#FileAccessor) and hooking it into the [`protoparse.Parser`](https://godoc.org/github.com/jhump/protoreflect/desc/protoparse#Parser), though messing with `LookupImport` may also be necessary? 

@rogchap, I'll try to fix this, since it involves somewhat gnarly k6 internals, but I'd appreciate a PR review when I post it :sweat_smile:

**Comment by rogchap** [comment]
I'm not familiar with the archiving process, but I could imagine this could get difficult with multiply import paths and large number of nested proto files.

My initial thought was to see if we could "load" the protos (as is) and then convert all the File Descriptors to a protoset file (a binary file for protos) and add that to the archive; but it seems this format can only be generated by protoc (C++) 😞

My next thought was to use the `protoprint` which takes the File Descriptors and converts them back into the proto source files, which we can add to the archive. The reason for doing this would be to avoid any unusual file structures and import roots that may be present.

But now I'm thinking that that may cause issues with the script load, unless there was a way to load differently if from an archive?

Sorry for the brain dump; just getting my head around the archive process.

**Comment by na--** [comment]
I think I managed to avoid any of the complicated suggestions you proposed above, but I am not sure if I haven't broken anything important in the process... :sweat_smile: 

The archive bundling in k6 happens by using a virtual filesystem that cached files when they are read initially, and then we save the whole cached filesystem in the `.tar` archive bundle. Then, when running the `.tar` archive bundle, we create a virtual file system out of its contents and essentially present that to the k6 modules, so they shouldn't read the actual OS file system at all. 

Please take a look at https://github.com/loadimpact/k6/pull/1706 and tell me if I've broken something important with the import resolution changes I had to do. Please test your use case with both `k6 run script.js` and `k6 archive script.js -O test.tar && k6 run test.tar`, if both should work exactly the same.
