### ISSUE TITLE
Design logotype + styleguide/typography

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#17]
*Imported from https://trello.com/c/8hcUWLnx/94-design-logotype-styleguide-typography*

**Comment by uppfinnarn** [comment]
We seem to have a logo, do we have a style guide to go with it?

**Comment by adr0sen** [comment]
Logo will likely be updated to better match our styleguide. /cc @majavojnoska @jeffhadfield - we will clarify this ASAP
