### ISSUE TITLE
taint() is gone?

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#170]
$ echo 'import { taint } from "k6"; export default function() { taint(); }' |./k6 run -

          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /   
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/  Welcome to k6 v0.12.1!

  execution: local
     output: -
     script: - (js)

   duration: 0s, iterations: 1
        vus: 1, max: 1

    web ui: http://127.0.0.1:6565/

ERRO[0002] TypeError: 'Taint' is not a function======================] -- / --
    at taint (k6.js:71:448)

**Comment by technololigy** [comment]
Ah, yes, this is from [this commit](https://github.com/loadimpact/k6/commit/49be09a783eb65530ce1503b27e2f95c12d497ab) (issue #100); `--acceptance` was redundant with (and more blunt than) setting a threshold on the `checks` metric and `errors` metrics respectively, and `taint()` and `check()`'s tainting side effect was a relic from the pre-Threshold days.

**Comment by ragnarlonn** [comment]
Ah, sorry, I knew checks didn't cause tainting anymore but I thought we could still do it from a script. Poor, old taint().

**Comment by technololigy** [comment]
:(

The way to taint a script right now is to throw an error or use `fail("message")` (…which throws an error…), unless there's a use case for silently tainting an iteration without an error?

**Comment by ragnarlonn** [comment]
My gut says there might be such a use case, but nothing obvious comes to mind so I'd suggest we keep things the way they are (i.e. no taint()) until someone complains. I just liked that function :)
