### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [loadimpact/k6#1701]
The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: https://k6.io/docs/using-k6/archives-for-bundling-sharing-a-test

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by tinfoil-knight** [comment]
Clicking on the link now redirects to https://k6.io/docs/misc/archive-command

**Comment by na--** [comment]
Ah, thanks! Apparently we forgot to close this issue when fixing this with https://github.com/loadimpact/k6-docs/commit/76f93d51dc0712cffa38e6526a17c3e990bbd4c4
