### ISSUE TITLE
There is no new line after `password` prompt for login command

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#1703]
The screenshot shows it very clearly :). 
![image](https://user-images.githubusercontent.com/312246/97853294-96138800-1d00-11eb-9189-3ada13a42e69.png)

I expect that the reading of the password just swallows the newline as well so it doesn't get printed ?

**Comment by paroar** [comment]
I'd like to work on this one :hand:

**Comment by na--** [comment]
Sure, @paroar, thanks!
