### ISSUE TITLE
Make http.request() accept an object as parameter, like http.batch() ?

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#172]
http.batch() is quite flexible in what kind of input it allows. You can send in:

- an array, where elements can be either URL strings or request objects
- a dictionary-object, with named request objects or named URL strings

Request objects look like this:

{ method: a, url: b, body: c, params: d }

To be consistent, shouldn't we make http.request() also accept a request object as a single parameter?  Perhaps also a single string URL (making http.request() default to the GET method).

**Comment by liclac** [comment]
I'm skeptical to this, it'd introduce overhead and more complexity in http.request(), because we'd have to make it varadic and then make checks on the number and types of the arguments.
