### ISSUE TITLE
blockHostnames- Can't block hostname with and without subdomain at the same time

### ISSUE THREAD

**Issue by curvedriver** [loadimpact/k6#1721]
I try to block a domain which will be called with and without a subdomain.

I tried the following combinations:
```javascript 
blockHostnames: ['*.httpbin.org', 'httpbin.org']

blockHostnames: ['httpbin.org']

blockHostnames: ['*httpbin.org']

blockHostnames: ['*.shttpbin.org']
```

Sorry I tried to write a test with different scenarios but I was not able to set the `K6_BLOCK_HOSTNAMES` via the `env` property.

## Environment

- k6 version: 0.29.0
- OS and version: windows 10

## Expected Behavior
block should be possible for domains with and without subdomains at the same time

## Actual Behavior
Can't block domain with and without subdomain at the same time

## Steps to Reproduce the Problem

```javascript
import http from 'k6/http';
import { check, group } from "k6";

export const options = {
    blockHostnames: ['*.httpbin.org', 'httpbin.org']
}

export default function getFromBlockedHostname() {
    [
        'https://httpbin.org/get?my_param=my_value',
        'https://www.httpbin.org/get?my_param=my_value',
        'https://eu.httpbin.org/get?my_param=my_value'
    ].forEach(url =>
        group(url, () => {
            check(http.get(url, { redirects: 0 }), {
                "status is 0": (r) => r.status === 0
            });
        }));
}
```

**Comment by na--** [comment]
Thanks for posting this, just tried to reproduce it and it's definitely a bug... :disappointed: Your example should have worked, and `'*httpbin.org'` should have also blocked all three URLs in your example, since the wildcard should also allow for zero-length matches.
