### ISSUE TITLE
Share variable across multiple VUs

### ISSUE THREAD

**Issue by hrai** [loadimpact/k6#1726]
I am using multiple VUs to make an auth call. For each VU, the auth call was being made which was not efficient. So I wanted to use a global variable to hold the token value. It seems like the global variable is global only for the VU.

I resolved this issue by using setup and teardown functions as mentioned [here](https://staging.k6.io/docs/using-k6/test-life-cycle#setup-and-teardown-stages).

Example code below:

```
export function setup() {
  let token = token == null ? getAuthToken() : token;
  return token;
}

export default function (token) {
  let requests = getRequests(token);
  .....
```

This should be documented so it's easier to find. I spent days trying to find a solution and [this pointed me in the right direction](https://community.k6.io/t/using-auth0-authentication/854/2)

**Comment by MStoykov** [comment]
Hi @hrai, I have already opened https://github.com/loadimpact/k6-docs/issues/148 . I hope this is enough and ... that one day we actually sit down and write that documentation :)
