### ISSUE TITLE
Automatically stop when threshold is not met

### ISSUE THREAD

**Issue by L-sing** [loadimpact/k6#1737]
Automatically stop when threshold is not met Over a period of time
## Feature Description

If the threshold is not met, subsequent testing is meaningless. So I think the test should stop automatically when the threshold is not met for a certain period of time. For example, RT p95 is greater than 500 ms for 10 seconds.

**Comment by na--** [comment]
Please take a look at https://k6.io/docs/using-k6/thresholds#aborting-a-test-when-a-threshold-is-crossed

Are the current `abortOnFail` and `delayAbortEval` threshold options the feature you want, or do require more functionality? If so, can you share your specific use case in more details, describing exactly what you want to happen? We have some ideas for future threshold improvements described in https://github.com/loadimpact/k6/issues/1136 and other issues, so I'd like to know if the current k6 capabilities are insufficient for your use case, whether the things we have already considered as future improvements will cover it.

**Comment by L-sing** [comment]
wow,I didn't find this feature when I read the document. I was too careless.Thank you very much.

**Comment by AmanuenRaphim** [comment]
#- - - {@[``]()
