### ISSUE TITLE
process/hrtime cannot be accessed

### ISSUE THREAD

**Issue by RichardWright** [loadimpact/k6#1759]
Hi

## Environment

- k6 version: latest (of docker image)
- OS and version: macos catalina
- Docker version and image, if applicable: latest

## Expected Behavior

process.hrtime should return nanosecond time.

## Actual Behavior

`ReferenceError:` process is not defined\n\tat file:///tmp/socket-test.js:63:19(93)\n\tat github.com/loadimpact/k6/js/common.Bind.func1 (native)\n\tat _default (file:///tmp/socket-test.js:42:33(50))\n" executor=ramping-vus scenario=default `source=stacktrace`

## Steps to Reproduce the Problem

1. inside a javascript load test, run the followingcode 
`const` now = `process.hrtime.bigint();`

**Comment by imiric** [comment]
Hi, as [explained in the forum post](https://community.k6.io/t/process-hrtime-cannot-be-access-inside-js-file/1160/2), this is not a bug but a limitation of the built-in JS support. I doubt we'll add a built-in nanosecond precision API, and in the meantime you can use the xk6 workaround.

Also, there's no need to create both a GitHub issue and a forum post. :) Unless you're certain it's a bug and no such issue exists before, it's better to use the forum for these types of questions.
