### ISSUE TITLE
Post call is falling

### ISSUE THREAD

**Issue by waytoharish** [loadimpact/k6#1762]
Hi Team, 
I am trying to call a rest service which is working fine with curl and postman but falling with K6.
Error i am getting -

INFO[0000] >>>>>>>>>>["Harish"]                          source=console
ERRO[0001] SyntaxError: EOF
running at parse (native)
default at file:///Users/hshar119/script.js:20:28(21)
	at github.com/loadimpact/k6/js/common.Bind.func1 (native)
	at file:///Users/hshar119/script.js:18:19(40)  executor=per-vu-iterations scenario=default source=stacktrace

Code

import http from "k6/http";
import { check, group } from "k6";
import { sleep } from 'k6';

/*export let options = {
    rps: 20,
    vus: 20,
    duration: '10s'
  };*/

export default function() {
  const url = 'https://RestEndpoint.com/ReadHelloWorld.v1';
  let headers = { 'Content-Type': 'application/json' };
  let data = ['Harish'];
  console.log(">>>>>>>>>>"+JSON.stringify(data))
  const before = new Date().getTime();
   
  group("POST", function() {
    let res = http.post(url, JSON.stringify(data), { verb: "post" });
    let j = JSON.parse(res.body);
    console.log(">>>>>>>>>>"+res.body)
    check(res, {
        "status is 200": (r) => r.status === 200
    });
});

};

**Comment by na--** [comment]
You are getting an exception when parsing the `res.body` as JSON, so it's probably an invalid JSON... Try logging it and `res.status` _before_ `JSON.parse()`, to see exactly what you are getting from the server. Also, this is not a bug report or a feature request, so please ask similar questions in the community forum: https://community.k6.io/
