### ISSUE TITLE
Create JMeter -> k6 script converter

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#177]
We want a piece of code that will take a Jmeter test plan and convert it into a k6 JS script that does the same thing as the Jmeter plan (preferably also producing readable JS code).

Language should probably not be Go for this. Python may be a good choice. We want a language that is ubiquitous, so that people can run it locally without installing dependencies, and we want code that can easily be turned into a hosted web service (i.e. a language well suited for writing web services).

**Comment by aidylewis** [comment]
Is this more hassle than it is worth? Let users keep their legacy JMeter scripts and write new ones in k6.

**Comment by micsjo** [comment]
Run the jmeter script through Fiddler as a proxy and then export as k6 (or for that matter lua) script using our exporter.

**Comment by ragnarlonn** [comment]
There is a big legacy Jmeter community out there, where many users are not expert programmers and would likely benefit from some automated conversion tool that is simpler to use than running it through Fiddler (if we have the tool, we can easily host it somewhere, allowing people to just copy-paste their Jmeter test plan in their browser, and get a converted k6 script back).

**Comment by liclac** [comment]
Thought: a web service that does this, split panels-style, no installation needed.

**Comment by micsjo** [comment]
You almost never treat jMeter scripts in plain. It's a big blob of XML. So copy/paste is a bad idea but the principle of UL/DL should be fine. 

But this I would consider completely wrong: " _jMeter community out there, where many users are not expert programmers and would likely benefit from some automated conversion tool that is simpler to use than running it through Fiddler_ "

Running a jMeter script through a proxy is as simple as

```jmeter -H my.proxy.server -P 8000 -u username -a password -N localhost```

jMeter recordings are done with jMeter acting as a proxy so the concept of how to do it is a prerequisite for using jMeter at all.

If a user is capable of using the _highly complex_ jMeter setup for just about anything, they are very much so capable of running it through a proxy setup. 

There can very well be many other highly valid reasons for implementing it but assuming jMeter users are not capable of executing a jMeter test once through a proxy is _not_ one of them.

There's also a caveat here: jMeter plugins can and will do all sorts of things. Even core functionality in jMeter are plugins. W/o plugins jMeter isn't of much use to anyone really so I would recommend figuring out from the start which to support in a converter.

**Comment by liclac** [comment]
The big problem with using a recording proxy is that it will catch *one* possible execution scenario. No variables, no random influences(?), etc. They're useful, but it's a very different thing from a straight-up script converter.

We'd have to pick a bunch of JMeter plugins to support, but we'd have to do that either way, and we can always add more if requested.

**Comment by micsjo** [comment]
Yes, but auto-converting the entire setup for data driven tests, different types of randomization and data generators and if not including but at least referencing data sources is slightly more advanced than just a "converter".

If that's the goal I personally would like an open ended design - one reader part that can be extended with other sources than jMeter and one writer part for k6.

If it is to be a full blown tool I'm with @aidylewis , it's more work than gain.

If it's to be a "quick fix" to attract jMeter users - it should not be this full blown and thus we're back to comparing with proxy based recording of usage. Not my choice of course.

**Comment by liclac** [comment]
Honestly, my dream setup would be something like Babel's or LLVM's architecture: one part that converts scripts in arbitrary formats (JMeter, Postman, etc) into an AST of sorts of actions to take, then you feed that through a funnel of stuff that applies transformations (not generating single-request batches, avoiding a temporary variable for requests that are only used in a single check and never again, etc), then you have a third stage that just spits out JS.

**Comment by ragnarlonn** [comment]
I see it as a fairly simple solution to attract JMeter users. It would not handle the most complex configurations. The big advantage over a proxy-based solution is in the onboarding. @micsjo may be right that many JMeter users are familiar with proxy-based recording, but let's consider the onboarding flow here: if a JMeter user has a need to do some load testing, and wants to reuse some old JMeter test plans but is interested in using a new tool (k6), the Fiddler-based solution assumes that:

- The Jmeter environment is up and running, fully functional
- The test/sink environment is up and running, will accept traffic and that we're allowed to test it *right now*
- The user has a Windows machine up and running
- The user has Fiddler installed
- The user has Fiddler2k6 installed

On comparison, a Jmeter2k6 converter hosted online assumes *zero* of these things. The user just has to have a web browser. This fact is going to dramatically increase the funnel for the hosted-converter-tool solution, and make it a lot more efficient as a way to increase k6 adoption.

**Comment by micsjo** [comment]
Consider this: to my knowledge there is _no_ converter at all available to convert from jMeter JMX to anything whatsoever.

**Comment by aidylewis** [comment]
@micsjo SOASTA CloudTest has a JMeter converter.

**Comment by micsjo** [comment]
AFAIK SOASTA CloudTest does not convert jMeter tests. They _run_ jMeter as part of their cloud offering. At least according to what they have published on it.

They have provided a somewhat "kludgy" UI to manage jMeter aspects of test configurations but I don't think that qualifies as converting.

[SOASTA + jMeter blog](https://www.soasta.com/blog/cloudtest-jmeter-load-testing/)
[SOASTA + jMeter page](https://www.soasta.com/solutions/jmeter/)

**Comment by liclac** [comment]
@micsjo You sound as if offering something nobody else has is a bad thing!

**Comment by micsjo** [comment]
Ahhh, not at all. It can make quite a splash.

But it hints at the complexity of doing it and the possible business value _other_ organisations have assessed (or rather not) from doing it.

**Comment by aidylewis** [comment]
@micsjo You're right.

**Comment by aidylewis** [comment]
And I think yes if the complexity is too high than business value can be spent elsewhere.  Most (load)testers will know some JavaScript and I feel ES6 is much less horrible than ES5.

**Comment by MStoykov** [comment]
There is now a separate project [jmeter-to-k6](https://github.com/loadimpact/jmeter-to-k6) that does this :)
