### ISSUE TITLE
Updated 'Environment variable' in 'Request.Pre' was not updated in the request body.

### ISSUE THREAD

**Issue by Auttasak-L** [loadimpact/k6#1774]
I found that the updated value of variable 'counter'
in 'pm.environment' was not be replaced correctly
 in the 'request body'.

## Environment
- k6 version: k6 v0.29.0 (2020-11-11T13:27:03+0000/d9bced3, go1.15.4, linux/amd64)
- OS and version: WSL2 Ubuntu-20.04

## Expected Behavior
Value of 'counter' that was set in
the 'pm.environment' variable
should be replaced correctly in
the sent request data.

## Actual Behavior
The 'counter' value of first '/echo/'
request is 'undefined'.

## Steps to Reproduce the Problem
1. k6 run test.js

## To fix this
1. I found that the problem is in below function
    at the commented line (line contains pm[Var])
    which can be fixed by replace it with
     'pm.environment.get'.

   function evaluate(string) {
      // return string.replace(expression.variables, (match, name) => pm\[Var\](name));
      return string.replace(expression.variables, (match, name) => pm.environment.get(name));
   }
   

   
[test.js.txt](https://github.com/loadimpact/k6/files/5708745/test.js.txt)

**Comment by imiric** [comment]
Hi, thanks for reporting this.

This seems like an issue with the generated code from the postman-to-k6 tool. Would you mind creating an issue [there](https://github.com/loadimpact/postman-to-k6/issues)?

Before you do that, make sure you're using the latest version to convert the Postman collection.
