### ISSUE TITLE
High memory usage with large responses

### ISSUE THREAD

**Issue by staticfloat** [loadimpact/k6#1777]
## Environment
- k6 version: `loadimpact/k6:latest`
- OS and version: Ubuntu 20.04, kernel 5.4.0
- Docker version and image, if applicable:

## Expected Behavior
Running tests should take <10GB of memory

## Actual Behavior
With 1000 VUs, `k6` hits 18.2 GB of RSS.

## Steps to Reproduce the Problem
I am load testing the [Julia Language](https://julialang.org/) package servers, which serve large gzipped tarballs, which can be anywhere from 100k-500MB, although in my experiments, the largest tarball is ~2MB.  I am not processing the response bodies at all, but assuming that `k6` is buffering the body response in memory and that all 1000 VUs end up downloading the 2MB tarball at the same time, this would account for 2GB of memory.  With additional runtime overhead, it seems reasonable to expect there to be ~5GB of memory usage, but there's clearly more occurring somewhere.

Removing the 2MB tarball from the test flow reduces maximum RSS to 4.8 GB, which I believe shows that 1000 VUs * 2MB payload -> ~13.6 GB of RSS.

The test I'm using is:
```
import http from 'k6/http';
import { sleep, check, group } from 'k6';
import { Trend, Rate } from 'k6/metrics';

export let options = {
    stages : [
        // Over 10s, ramp up from 0 users to 10
        { duration: '10s', target: 10},
        // Hold steady at 10 users for another 20s (enough time for us to get through initial compilation)
        { duration: '20s', target: 10},

        // Zoom up to 1000 users
        { duration: '30s', target: 1000},
        { duration: '60s', target: 1000},
    ],
};

let trend_reg = Trend('timing_registry');
let trend_pkg = Trend('timing_package');
let trend_art = Trend('timing_artifact');
let trend_404 = Trend('timing_404');

let trend_tasks = Trend('live_tasks');
let rate_errors = Rate('errors');

export default function () {
    let base = 'http://localhost:8000';

    let check_200 = {'200 OK': (r) => r.status === 200};
    let check_404 = {'404': (r) => r.status === 404}
    
    // Get ourselves a registry, a package and an artifact
    let resources = [
        // Un-comment this to get a 2MB tarball
        //["/registry/23338594-aafe-5451-b93e-139f81909106/05a3c5553c916ff9585b6393860e91f51d931448", trend_reg, check_200],
        ["/package/009559a3-9522-5dbb-924b-0b6ed2b22bb9/8a692f817f1a6c15ef4913a0ffefa6163117f43d", trend_pkg, check_200],
        ["/artifact/004eafdccbb9f9bd68b9c3a01a25312d2126fc8f", trend_art, check_200],
        ["/foofoo/roflmao", trend_404, check_404],
    ];
    for (let idx in resources) {
        let [resource, trend, check_functor] = resources[idx];
        let res = http.get(base + resource);
        rate_errors.add(!check(res, check_functor));
        trend.add(res.timings.duration);

        // Sleep a bit so that our rps go up with our VUs
        sleep(0.01);
    }

    // Hit /meta and ask how many tasks are currently running, if the server supports that
    {
        let res = http.get(base + "/meta");
        rate_errors.add(!check(res, check_200));
        let num_live_tasks = res.json("live_tasks")
        if (num_live_tasks != undefined) {
            trend_tasks.add(num_live_tasks);
        }
        sleep(0.01);
    }
}
```

It's being run by:

```
docker run --rm -v /home/sabae/src/PkgServer.jl/test/perf:/config:ro -v /home/sabae/src/PkgServer.jl/test/perf/results:/results --net=host -ti loadimpact/k6 run --out csv=/results/hot_cache.csv --out influxdb=http://localhost:8086/k6 /config/hot_cache.js
```

Please let me know if there's anything I'm doing that is obviously wrong.

**Comment by MStoykov** [comment]
Hi @staticfloat ,

 given your comment about large responses and your code - yes the problem is that k6 downloads and needs to keep the responses for some time before they get GCed. 


If you don't need the responses you can set [discard response bodies](https://k6.io/docs/using-k6/options#discard-response-bodies).

Hope this helps and happy holidays!

**Comment by staticfloat** [comment]
Thanks, that is super helpful!
