### ISSUE TITLE
Custom exit code setting for threshold

### ISSUE THREAD

**Issue by lemon-li** [loadimpact/k6#1778]
## Feature Description

When I run K6 in the docker, if threshold fails, it will cause exit code `99` (#870).

I expect that it should be possible to customize the configuration, because my monitoring system will catch the exit, thinking this is an unexpected exit.

**Comment by na--** [comment]
@lemon-li, can you share some more details about your use case? And can you look through https://github.com/loadimpact/k6/issues/680 and https://github.com/loadimpact/k6/issues/870 and explain how the feature you want differs from them?

**Comment by lemon-li** [comment]
> @lemon-li, can you share some more details about your use case? And can you look through #680 and #870 and explain how the feature you want differs from them?

thank you for your reply，I think that same feature.  
when the threshold fails, I can change the exit code from 99 to 0.

**Comment by na--** [comment]
I still don't understand precisely why you want to do that, sorry. After all, the main purpose of the k6 thresholds is to act as a pass/fail criteria for the load test, so k6 returning with non-zero exit code is precisely meant to signal the CI system to treat the test run as a failure... In any case, wouldn't suppressing the exit code this way also work:
```bash
k6 run whatever.js || true
```
This way, even if k6 exits with a non-zero code, the script/CI job will not abort.

**Comment by na--** [comment]
Closing this issue due to lack of response. I though about it some more and there's a valid use case for wanting a `0` exit code for some thresholds, but that is tracked in https://github.com/loadimpact/k6/issues/680#issuecomment-767426473
