### ISSUE TITLE
--summary-trend-stats  not being used in the JSON final summary report; --summary-export

### ISSUE THREAD

**Issue by nsshunt** [loadimpact/k6#1779]
## Environment

- k6 version:
k6 v0.29.0 (2020-11-11T13:27:19+0000/d9bced3, go1.15.3, linux/amd64)
OS and version: ubuntu 20.04 LTS

## Expected Behavior

when using this;
export let options = {
    summaryTrendStats: ['avg', 'p(95)'],
  };

stdout gets the correct output;

running (02.0s), 0/8 VUs, 3699 complete and 0 interrupted iterations
default ✓ [ 100% ] 8 VUs  2s

    data_received..............: 2.0 MB 984 kB/s
    data_sent..................: 980 kB 483 kB/s
    http_req_blocked...........: avg=2.1µs   p(95)=2.09µs 
    http_req_connecting........: avg=338ns   p(95)=0s     
    http_req_duration..........: avg=4.21ms  p(95)=6.33ms 
    http_req_receiving.........: avg=27.41µs p(95)=60.57µs
    http_req_sending...........: avg=11.3µs  p(95)=27.41µs
    http_req_tls_handshaking...: avg=0s      p(95)=0s     
    http_req_waiting...........: avg=4.17ms  p(95)=6.26ms 
    http_reqs..................: 3699   1822.81022/s
    iteration_duration.........: avg=4.32ms  p(95)=6.43ms 
    iterations.................: 3699   1822.81022/s
    vus........................: 8      min=8 max=8
    vus_max....................: 8      min=8 max=8

The JSON summary does not;
{
  metrics: {
    data_received: { count: 1997460, rate: 984317.5185556513 },
    data_sent: { count: 980235, rate: 483044.70818008814 },
    http_req_blocked: {
      avg: 0.002107231143552311,
      max: 0.411598,
      med: 0.001279,
      min: 0.000731,
      'p(90)': 0.0017084000000000005,
      'p(95)': 0.0020934999999999994
    },
    http_req_connecting: {
      avg: 0.0003387472289808056,
      max: 0.271552,
      med: 0,
      min: 0,
      'p(90)': 0,
      'p(95)': 0
    },
## Actual Behavior

See above.

## Steps to Reproduce the Problem

1. Specify metric outputs using --summary-trend-stats "min,avg,med,max,p(10),p(90),p(95),p(99),p(99.99)"
2. Specify summary export report using --summary-export output.json

**Comment by na--** [comment]
Thanks for reporting this, however it was previously reported in https://github.com/loadimpact/k6/issues/1611 and https://github.com/loadimpact/k6/issues/1433, so I'll close this issue. The good news is that the bug is already fixed in a WIP PR (https://github.com/loadimpact/k6/pull/1768), which will hopefully be released in k6 v0.30.0.
