### ISSUE TITLE
Export grpc request count metric

### ISSUE THREAD

**Issue by shouichi** [loadimpact/k6#1781]
## Feature Description

The `http_reqs` metric is available for HTTP, we need a similar metric for gRPC.

## Suggested Solution (optional)

Simply count grpc unary requests and export the count (I'm not sure k6 supports grpc stream).

**Comment by na--** [comment]
k6 doesn't support gRPC streaming yet. As to the count, there's a reason we don't have `grpc_req_count` - you can get the count from the `grpc_req_duration` metric by specifying `count` as a part of the [`summaryTrendStats` option](https://k6.io/docs/using-k6/options#summary-trend-stats). For example:
```bash
k6 run --summary-trend-stats="avg,min,med,max,p(90),p(95),p(99.9),count" grpc-script.js
```

I see that's not documented very well, so I added a new issue (https://github.com/loadimpact/k6-docs/issues/184) to correct that... And the reason that `http_reqs` exists is that it precedes the `http_req_duration.count` significantly, the `count` for `Trend` metrics was only [introduced in k6 v0.26.0](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.26.0.md#new-optional-count-column-in-the-end-of-test-summary-1143).

**Comment by shouichi** [comment]
Thanks for the explanation! Confirmed that the option you gave worked, feel free to close this.
