### ISSUE TITLE
Cannot download k6 for Ubuntu using Dockerfile

### ISSUE THREAD

**Issue by AnatoliiHanziuk** [loadimpact/k6#1807]
I'm trying to execute steps to install k6 on Ubuntu but the repository where k6 lives is marked as non-trusted.

## Environment

- k6 version: latest
- OS and version: Ubuntu 18.04, Ubuntu 20.10
- Docker version and image, if applicable:  20.10.2

## Expected Behavior
I need to be able to download k6.

## Actual Behavior
Error message `The repository 'https://dl.bintray.com/loadimpact/deb stable Release' does not have a Release file.` is thrown.
Before that error `Err:5 https://dl.bintray.com/loadimpact/deb stable Release
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. ` could be found.

## Steps to Reproduce the Problem

1. Create a Dockerfile
```
FROM ubuntu:18.04
RUN apt-get update && apt-get install -y gnupg2 && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61 && \
    echo "deb https://dl.bintray.com/loadimpact/deb stable main" | tee -a /etc/apt/sources.list && \
    apt-get update && apt-get install -y k6
```
2. Build Dockerfile as `docker build .`
3. Check for error messages during the build.

**Comment by na--** [comment]
The full error that I got when trying to repeat your steps was
```
Reading package lists... Done                         
W: https://dl.bintray.com/loadimpact/deb/dists/stable/InRelease: No system certificates available. Try installing ca-certificates.
W: https://dl.bintray.com/loadimpact/deb/dists/stable/Release: No system certificates available. Try installing ca-certificates.
E: The repository 'https://dl.bintray.com/loadimpact/deb stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

So... that's what I did, I installed `ca-certificates` with `apt-get install -y ca-certificates` and everything worked after that. It is going to be needed not only for `apt` to connect to https://dl.bintray.com, but also for k6 itself to verify https connections, we include the same package in our Alpine-based docker images: https://github.com/loadimpact/k6/blob/45fff81b0b3af8d174c960450d16f5c4431ef9a4/Dockerfile#L8

**Comment by AnatoliiHanziuk** [comment]
You did correct steps. But I'm saying that installation of any additional dependencies is missing in the [installation guide](https://k6.io/docs/getting-started/installation).

**Comment by na--** [comment]
I am pretty sure that a normal Ubuntu or Debian installation comes with `ca-certificates` preinstalled. You literally won't be able to connect to most of the web without it. I guess they left it out of the Docker image to make it smaller... :man_shrugging: 

That said, the way to fix this shouldn't be updating the docs, instead we should specify in our .deb package that we depend on `ca-certificates`. Then the package will be automatically installed if it's not already present. Sorry for prematurely closing this and thanks for sticking with it, I didn't give it enough consideration initially... :disappointed:
