### ISSUE TITLE
Omitting "method" field in http.batch() call fails

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#181]
It seems that when calling http.batch() and supplying an object with info about an HTTP request I want to make, I have to include the "method" field or I will get a weird error saying "Malformed HTTP response"

![screen shot 2017-04-18 at 14 38 58](https://cloud.githubusercontent.com/assets/6524809/25131251/4db3fd04-2445-11e7-8a1e-f97c40e746f1.png)

Including the "method" field generates no error:

![screen shot 2017-04-18 at 14 39 38](https://cloud.githubusercontent.com/assets/6524809/25131277/6b151e32-2445-11e7-98d1-85e4917fc0c1.png)

**Comment by liclac** [comment]
No longer applicable in js2; the object syntax is gone, and faulty requests will generate proper errors.
