### ISSUE TITLE
SharedArray doesn't work with forEach

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#1820]
The following code:
```
import { SharedArray } from 'k6/data'
var csvData = new SharedArray("another data name", function() {
    return ["one", "two"];
});
export default function() {
    csvData.forEach((item) => console.log(item));
}
```

Gets 
```
 TypeError: Value is not an object: undefined
```
which needs to be investigated

**Comment by na--** [comment]
Maybe the recently added [`goja.DynamicArray`](https://godoc.org/github.com/dop251/goja#DynamicArray) could help?

**Comment by MStoykov** [comment]
I need to check if it doesn't allow changing the values as that was part of the idea of the SharedArray. 

I am mostly nothing this as forEach was used in the example in the cloud that I edited in https://github.com/loadimpact/k6-docs/pull/196/commits/cc8c184bd2e14faef655bf1fc1aefdc834578f46 so I don't forget to test it later ;)
