### ISSUE TITLE
Large JSON string to console causes k6 to hang

### ISSUE THREAD

**Issue by atombender** [loadimpact/k6#1823]
As part of a test, I read a result into memory. [Here](https://gist.github.com/atombender/397d78ae73566acedcb00455980a9229) is such a file. It's about 500KB. I then do a deep equals comparison and emit an error using `console` if there's a failure, just so it's possible to get at the expected and actual result afterwards. However, when I do so, k6 simply hangs indefinitely, and I've narrowed it down to the fact that any `console.log(veryBigString)` will cause k6 to hang.

**Comment by MStoykov** [comment]
Works fine for me @atombender :
```javascript
var s = open("./result.json").repeat(5);
export default function() {
    console.log(s);
}
```
running with `/usr/bin/time -v k6.v0.30.0 run  -u 5 -d 10s issue-1823.js` manages to do a "grand" total of 17 iterations and using up 326 MB, but still does it.

I would guess it might be your terminal that can't keep up. Can you provide more information including OS, terminal, version of k6, and if it's reproducible with another terminal

**Comment by atombender** [comment]
I'm not outputting to a terminal; I'm piping to a file. But I see what's going on. I'm invoking k6 via Go and consuming its output, using `bufio.NewScanner(r)`, which of course blows up on long lines, thus causing the stream to no longer be consumed. In other words, k6 is getting stuck because stdout isn't being consumed. That's an easy fix. Thanks for pointing me to the cause.

**Comment by MStoykov** [comment]
Glad I could help.

 I (as well as the whole k6 team) will be interested in what you are building and your experience using k6. If you are willing to share of course :). 

You can probably make a post in the [community forum](https://community.k6.io/) as the issues are probably not the best place l)
