### ISSUE TITLE
Having Invalid Regular Expression when using url lib

### ISSUE THREAD

**Issue by wsee911** [loadimpact/k6#1834]
I am getting an `Invalid regular expression (re2)` when using `import "url"`. I have gone through and isolated that this lib when imported is giving issues.

## Environment
- k6 version: 0.29
- OS and version: MacOS 10.15.7
- NodeJS: 12.16.3

## Expected Behavior
The test should build normally with using the url lib 

## Actual Behavior
It is throwing invalid regular expression when k6 is building.
![image](https://user-images.githubusercontent.com/29671625/106549147-5486b900-654b-11eb-80c1-c9199149b692.png)
Screenshot above on the error.

## Steps to Reproduce the Problem
May try using the below code to run the load test.
```
import * as k6Options from "k6/options";
import "url";

export const options: Partial<k6Options.Options> = {
	scenarios: {
		createEventLoadTest: {
			executor: 'per-vu-iterations',
			vus: 2,
			iterations: 10,
			exec: "loadTest",
		},
	},
};

let count = 0;

export function setup() {
}

export function loadTest() {
	console.log("running");
}

export function teardown() {
}
```

**Comment by na--** [comment]
How exactly have you bundled your script before you ran it with k6? browserify, webpack? please give us the **complete** steps we can use to reproduce this behavior...

Also, you might try to upgrade to k6 v0.30.0, it has some changes in the JS runtime we use that are related to regular expressions, so it might fix your problem.

**Comment by imiric** [comment]
Isn't the "invalid repeat count" error a limitation of Go's `regexp` package? https://github.com/golang/go/issues/7252

There's not much we can do in that case.

**Comment by na--** [comment]
Yeah, seems so, and yes, it's not something we can change in k6 or even goja... :disappointed:  Sorry, @wsee911, I'm not sure where `{1,8856}` comes from, probably something auto-generated from babel/browserify/webpack/etc., since I doubt such a group count would make sense in a normal program...

**Comment by wsee911** [comment]
I see, but to reply to @na-- question, I am using webpack and ts-loader to bundle the script.

**Comment by na--** [comment]
@wsee911, can you post a _complete_ example reproduces this issue in a github gist that? Both a simple k6 TS script and a webpack config that result in a faulty script? I tried using the snippet you provided with https://github.com/k6io/template-typescript and that didn't result in the error.

I'm asking, since it might be worth tracking down which JS library is responsible for the unusual regex and submitting a small PR to fix it, if it's simple.

**Comment by wsee911** [comment]
Hi so been searching around and realise this was the issue that has been plaguing me this few days. As webpack was having trouble bundling it. Gonna close this bug as its not a k6 issue. 
https://github.com/defunctzombie/node-url/issues/37
