### ISSUE TITLE
Test duration in collector plugins

### ISSUE THREAD

**Issue by martinfijal** [loadimpact/k6#184]
I want to have access to the "final" test duration in collector plugins (for tests that actually specify a duration). So far I know of, in order of priority from a quick test:

* `options.stages`
* `-d 10s` -- not accessible in collector
* `options.duration`

To avoid duplicating the logic for figuring out the actual duration, the final value should be made available to the collector plugin.

**Comment by liclac** [comment]
Couldn't you just look at when the context is terminated, or the timestamp of the last emitted sample?

**Comment by caalle** [comment]
I don't have full insight in how the collectors work so I'll leave "look at when the context is terminated" for @martinfijal to answer.

But just to give context to the request:

In many cases the test will have a duration or stages that will remain the same during the entire test run. This duration can then be used to determine and visualize the progress of the test run.

By using `the timestamp of the last emitted sample` I guess you'll get the duration of the test so far, and not the actual expected duration.

**Comment by martinfijal** [comment]
What we are after is an indicator of how long the test will be to visualize that in the UI. That's why we'd like access to configured information so we can sent it to the cloud in when init-ing the collector.

**Comment by liclac** [comment]
You can get that out if the options struct, which is passed to makeCollector, but you have to pass it to your runner yourself. But what are you going to do if the user changes the plan mid-test, or it's iteration based?

For changes, we can add a hook to notify collectors of the test plan on startup and every time it chanhes, but iterations would need some sort of averaging of the iteration duration...

**Comment by martinfijal** [comment]
But does the options struct take `-d` parameter into consideration? And yes, I know this will not be fool proof but I suspect many test runs will not change duration or use iteration based duration. Not covering everything is OK for now so hanges with hooks we can leave for another day.

**Comment by liclac** [comment]
Yup, Options takes into account defaults, script exports and CLI options.
