### ISSUE TITLE
ERRO[0000] GoError: unknown module: k6/data at reflect.methodValueCall (native)

### ISSUE THREAD

**Issue by Binternet** [loadimpact/k6#1840]
k6/data module is missing

## Environment

- k6 version: k6 v0.29.0 ((devel), go1.15.5, darwin/amd64)
- OS and version: macOS Big Sur
- Docker version and image, if applicable:

## Expected Behavior
trying to import SharedArray using
`import { SharedArray } from 'k6/data';`
and getting an error

## Actual Behavior
Getting this error:
`ERRO[0000] GoError: unknown module: k6/data at reflect.methodValueCall (native)`

## Steps to Reproduce the Problem
Run a script with `import { SharedArray } from 'k6/data';` in it

**Comment by na--** [comment]
Please update your k6 version, `SharedArray` is part of k6 v0.30.0: https://github.com/loadimpact/k6/releases/tag/v0.30.0
