### ISSUE TITLE
Load test fail with multi vm

### ISSUE THREAD

**Issue by JennyMet** [loadimpact/k6#1844]
HI, 

Im running the following simple config which runs ok 

```
export let options = {
	stages: [
		{ duration: "30s", target: 100 },
		{ duration: "30s", target: 2200 },
		{ duration: "30s", target: 0 },
	],
	thresholds: {
		'http_req_duration': ['p(99)<1500'], // 99% of requests must complete below 1.5s
	},
	insecureSkipTLSVerify: true
};
```

when I increase the num on VU  to `> 2369` for the second stage I got error and the test stopped without any
helpful message , is there any limitation (beside my machine)  ? if not, what could be the reason and how to overcome this ? 

This is the error
```
make[2]: *** [exec] Error 137
make[1]: *** [test-endpoints] Error 2------------] 2369/5000 VUs initialized
make: *** [run] Error 2--------------------------]
```

- k6 version: 0.30
- OS and version: docker image 
- Docker version and image, if applicable: 
- https://github.com/loadimpact/k6/blob/master/docker-compose.yml
os mac big sur with 32gb mem which doesnt have any issue with this load

Thanks

**Comment by na--** [comment]
>  os mac big sur with 32gb mem which doesnt have any issue with this load

Well, how much memory does the machine that is having issues with this k6 script have? It looks like your machine is running out of memory and k6 gets killed, the exit code 137 for the docker container also suggests it: https://stackoverflow.com/questions/47487650/alpine-3-6-docker-container-error-on-stop-exit-code-137

To run more VUs on the same amount of RAM, I'd suggest following the steps in this article, https://k6.io/docs/testing-guides/running-large-tests, specifically the `--compatibility-mode=base` advice (explained more in depth here as well: https://k6.io/docs/using-k6/javascript-compatibility-mode). If you have large data files, this might also be useful: https://k6.io/docs/javascript-api/k6-data/sharedarray

**Comment by JennyMet** [comment]
HI,

@na-- Thanks will check it, one question , assume that I have test which run about an hour, is it possible to inject dynamic endpoints to the tests ? e.g. the test start with 100 endpoints and during the test I will add additional endpoints and the test will end with 200 endpoints. 

Thanks

**Comment by na--** [comment]
Sure. This might be easier when we implement https://github.com/loadimpact/k6/issues/1320, but even now you could just have a variable `let startTime = new Date()` in the [init context](https://k6.io/docs/using-k6/test-life-cycle). Then, every iteration, you can check how much time has elapsed since then and add more URLs to your list.
