### ISSUE TITLE
Overwrite request header "application/x-www-form-urlencoded", when none is specified

### ISSUE THREAD

**Issue by thim81** [loadimpact/k6#1865]
The K6 requests always seems to fallback to the request header "application/x-www-form-urlencoded", when none is specified. This is the default behavior of k6, as described in https://k6.io/docs/javascript-api/k6-http/post-url-body-params.

This is not ideal, when your API requests a specific content-type, which would mean that the content-type has to be set on all http.res functions. This is not ideal when having large K6 test sets.

## Feature Description
A Provide the option to define/overwrite the request header with another another default, for when none is specified.

## Suggested Solution (optional)

Allow the definition of default request headers in the "option".

Example

```
export let options = {
    vus: 5,
    stages: [
        { duration: "3m", target: 10 },
        { duration: "5m", target: 10 },
        { duration: "10m", target: 35 },
        { duration: "1m30s", target: 0 },
    ],
request-headers: [
"Content-Type": "application/json"
]
};
```

```
export default function () {
  // our HTTP request, note that we are saving the response to res, which can be accessed later
  const res = http.get('http://test.k6.io');
  sleep(1);
  const checkRes = check(res, {
    'status is 200': (r) => r.status === 200,
    'response body': (r) => r.body.indexOf('Feel free to browse') !== -1,
  });
}

```

**Comment by na--** [comment]
Thanks for making this issue! I think it can be classified as a sub-set of https://github.com/loadimpact/k6/issues/761, so I'll close this one in favor of it.

Take a look at the comment I left there today (https://github.com/loadimpact/k6/issues/761#issuecomment-782031960) with some workarounds for the issue you're having, until we get around to fixing it properly.
