### ISSUE TITLE
How to exit the K6 script loop anywhere I want?

### ISSUE THREAD

**Issue by wmsken** [loadimpact/k6#1871]
Hi, as we know, the k6 script will loop until the running time is expired, but if I want to exit the script when the exit condition is triggered, then how to exit the script before running time is expired?

**Comment by na--** [comment]
There isn't a straightforward way to exit the script from inside of it yet, but you can set a [threshold with `abortOnFail: true` ](https://k6.io/docs/using-k6/thresholds#aborting-a-test-when-a-threshold-is-crossed) and do it that way:
```js
import { sleep } from 'k6';
import http from 'k6/http';
import { Counter } from 'k6/metrics';

export let options = {
    // ...
    thresholds: {
        'fatal_errors': [{threshold: 'count<1', abortOnFail: true}]
    }
};

const abortMetric = new Counter('fatal_errors');

export default function() {
    // ... test code ...
    if ( /* some fatal condition check */ ) { 
        abortMetric.add(1);
        sleep(5); // aborting from the threshold doesn't happen immediately, it may take a few seconds
    }
    // ... test code ...
};
```

We plan to add a straightforward "abort test run" JS API eventually as well. That effort is already tracked in https://github.com/loadimpact/k6/issues/1001, so I'll close this issue, please follow the other one for updates.

**Comment by wmsken** [comment]
> There isn't a straightforward way to exit the script from inside of it yet, but you can set a [threshold with `abortOnFail: true` ](https://k6.io/docs/using-k6/thresholds#aborting-a-test-when-a-threshold-is-crossed) and do it that way:
> 
> ```js
> import { sleep } from 'k6';
> import http from 'k6/http';
> import { Counter } from 'k6/metrics';
> 
> export let options = {
>     // ...
>     thresholds: {
>         'fatal_errors': [{threshold: 'count<1', abortOnFail: true}]
>     }
> };
> 
> const abortMetric = new Counter('fatal_errors');
> 
> export default function() {
>     // ... test code ...
>     if ( /* some fatal condition check */ ) { 
>         abortMetric.add(1);
>         sleep(5); // aborting from the threshold doesn't happen immediately, it may take a few seconds
>     }
>     // ... test code ...
> };
> ```
> 
> We plan to add a straightforward "abort test run" JS API eventually as well. That effort is already tracked in #1001, so I'll close this issue, please follow the other one for updates.

Thank you very much.
