### ISSUE TITLE
Form-data doesn't support normal string fields .

### ISSUE THREAD

**Issue by wadhwanidivya** [loadimpact/k6#1878]
## Environment
- k6 version: k6 v0.30.0 (2021-01-20T13:14:50+0000/2193de0, go1.15.6, windows/amd64)

## Expected Behavior : 
File should be uploaded.

## Actual Behavior : Getting the below error :
unable to upload a file in s3 : Getting the following error , 

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>User key must have a length greater than 0.</Message><ArgumentName>key</ArgumentName><ArgumentValue></ArgumentValue><RequestId>9H0TFHCK8HCH0J6T</RequestId><HostId>ykElo8dDuZc3dta37lEYGkM7mUtoEcjpXV2shNVqA6VEN/+orzlhRKGaQPFRH4EMZDTCErPaFSQ=</HostId></Error>

## Steps to Reproduce the Problem

import http from 'k6/http';
import { FormData } from 'https://jslib.k6.io/formdata/0.0.1/index.js';

  let obj = JSON.parse(response);
  let postResponse, checkPostResponse;
  var key = obj.formdata['key']
  const fd = new FormData();
  fd.append('bucket', obj.formdata['bucket']);
  fd.append('key', obj.formdata['key']);
  fd.append('policy', obj.formdata['policy']);
  fd.append('x-amz-algorithm', 'obj.formdata['algorithm'])');
  fd.append('x-amz-credential', obj.formdata['x-amz-credential']);
  fd.append('x-amz-date', obj.formdata['x-amz-date']);
  fd.append('x-amz-security-token', obj.formdata['x-amz-security-token']);
  fd.append('x-amz-signature', obj.formdata['x-amz-signature']);
  fd.append('file', http.file(text, 'test.txt', 'text/plain' ));

	const params = {
		headers: {'Content-Type': `multipart/form-data; boundary=${fd.boundary}`},
	};
  postResponse = http.post(`${route_fileUploadToApplication(obj)}`, fd.body(),
  { headers: { 'Content-Type': 'multipart/form-data; boundary=' + fd.boundary }});

  fileUploadToApplication_trend.add(postResponse.timings.duration);
  checkPostResponse = check(postResponse, {
    'CREATE file Upload To Application': r => r.status === 204
  });
  checkFailureRate.add(!checkPostResponse);
  const postResponseBody = JSON.parse(postResponse.body);
  return postResponseBody;

**Comment by imiric** [comment]
Hi,

string fields are actually supported by the `FormData` polyfill, see [this comment](https://github.com/loadimpact/k6/issues/1382#issuecomment-781903160). It's just that the current documentation doesn't mention this use case, and that the API could be more user-friendly to support it.

We have issues for both of these, see https://github.com/k6io/jslib.k6.io/issues/23 and https://github.com/k6io/docs/issues/225 , which should be fixed soon. So I'll close this as it's not a k6 issue and there's a workaround for it.
