### ISSUE TITLE
TCP and TLS handshake timings. 

### ISSUE THREAD

**Issue by aidylewis** [loadimpact/k6#188]
Can we add TLS handshake timings?

**Comment by liclac** [comment]
Wouldn't the TCP handshake timing be the same as `http_req_connecting`?

**Comment by aidylewis** [comment]
Wasn't sure, but sounds right.

**Comment by liclac** [comment]
Ah, I was wondering why we didn't have TLS handshake timings yet, it was [added in Go 1.8](https://golang.org/doc/go1.8#net_http_httptrace).

Just to be 100% sure, depending on 1.8 shouldn't cause any problems for Debian packaging, right? @diego-plan9

**Comment by diego-plan9** [comment]
I completely missed the mention - sorry for the delay in updating the issue!

As of this moment, Debian has:
* Go 1.7 in [testing and unstable](https://packages.debian.org/stretch/golang)
* Go 1.8 in [experimental](https://tracker.debian.org/pkg/golang-defaults)

And Debian is ongoing a [freeze](https://www.debian.org/doc/manuals/debian-faq/ch-ftparchives#s-frozen) - in practice means that 1.8 will not be included on testing/unstable until the freeze is over and a new Debian version is released. Unfortunately there is not specific date for the new release, as the policy is release it "as soon as it is ready" - the [latest update](https://lists.debian.org/debian-devel-announce/2017/04/msg00008.html)  is from April 15th; but it should be a matter of weeks.

Going back to the original question: introducing a dependency on 1.8 would prevent packaging k6 for *unstable* until the next Debian release, ie. we would have to aim for *experimental*. I'm wondering if it would be possible to wait a bit before implementing this feature?

**Comment by aidylewis** [comment]
@diego-plan9 Couldn't Debian/Ubuntu users compile Go from source without waiting for an upstream package?

**Comment by diego-plan9** [comment]
@aidylewis Yes, if the user is inclined to do so there are ways to compile Go from the latest sources (using experimental packages on Debian, [golang-1.8](http://packages.ubuntu.com/zesty/golang-1.8) in ubuntu zesty, tarball from golang.org, etc).

The main issue is that at the moment those methods deviate from the ideal, hassle-free goal of  having `k6` on the official distribution and being able to install it via simply:
```
$ apt-get install k6
```

**Comment by liclac** [comment]
Hmm, I think we may wanna hold off on this for now then. I could use build tags to enable it only on 1.8, but that's a lot of hassle for little gain if it's only a matter of weeks.

I'd accept a PR that adds this with build tags though, until we can officially drop 1.7 support.

**Comment by diego-plan9** [comment]
An update to confirm that [Go 1.8 is now on Debian testing](https://packages.debian.org/buster/golang-go) since a few days ago, which means that at least from the packaging side it should be safe to go ahead and implement any 1.8-specific functionality! :+1:
