### ISSUE TITLE
Fix xk6 CI check so it works with forks

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#1891]
As https://github.com/loadimpact/k6/pull/1886#issuecomment-792997189 explains, the CI check I added last Friday fails with PRs from forks. Specifically this part seems to be the problem: https://github.com/loadimpact/k6/blob/2036baeaa83d76ce17aae95fef7e78e3ef24c735/.github/workflows/xk6.yml#L38-L41

Maybe we could do something like `--with github.com/loadimpact/k6="$(pwd)/../../"`? cc @imiric would something like that work, or would xk6 changes be required?

**Comment by imiric** [comment]
No, that doesn't look like it would work, since xk6 does a `go get` to a static "github.com/loadimpact/k6" and replacements are not applied at that point. I'll take a look at what can be done today.
