### ISSUE TITLE
k6 cloud - Add Error count / Error rate to Performance overview header

### ISSUE THREAD

**Issue by leathej1** [loadimpact/k6#1896]
## Feature Description
As I am running a performance test in the cloud, I need to see new errors at a glance at the top of the test results page.

![2021-03-10 11_02_49-Window](https://user-images.githubusercontent.com/24658347/110675596-4ce0b280-8190-11eb-8485-c26123fb72e7.jpg)

**Comment by na--** [comment]
Wrong repo :smile: Can you please open an issue in https://github.com/k6io/cloud-feature-requests/issues ? I can't move it, since we haven't moved the k6 repo to the new https://github.com/k6io/ organization yet...
