### ISSUE TITLE
Module: crypto

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#19]
- [ ] md5()
- [ ] sha1()
- [ ] sha256()
- [ ] sha512()
- [ ] rand()

*Imported from https://trello.com/c/82UnP6nB/96-module-crypto*

**Comment by robingustafsson** [comment]
@technololigy I'm working on this in https://github.com/loadimpact/k6/tree/feature%2Fcrypto. Need it for some examples. Aiming for simple API first. Will then look at maybe mimicking parts of the more flexible nodejs Crypto API: https://nodejs.org/api/crypto.html.

**Comment by technololigy** [comment]
What if you tried implementing it against `feature/js2` instead? Some stuff (metrics emission) is still missing, but something like this would work no problem.

**Comment by robingustafsson** [comment]
@technololigy Great, I'll have a look at the `feature/js2` branch. Part of the reason for doing this work is because I want to get an oauth1 example created so I want to be able to run tests.

**Comment by robingustafsson** [comment]
We want to initially support the following crypto algorithms (the ones supported out-of-the-box by Go: https://golang.org/pkg/crypto/):

- MD4, MD5
- SHA1, SHA224, SHA256, SHA384, SHA512, SHA512_224, SHA512_256
- RIPEMD160


General outline proposal for Crypto API

1. Provide flexible API for each crypto algorithm as follows:

```js
import { crypto } from 'k6/crypto';

export default function() {
    let hasher = crypto.createHash("sha1");
    hasher.update("some data");
    let hash = hasher.digest("hex");
    console.log(hash);
}
```

2. Provide simple wrapper functions for common use:

```js
import { crypto } from 'k6/crypto';

export default function() {
    let hash = crypto.sha1("some text", "hex");
    console.log(hash);
}
```

**Comment by ragnarlonn** [comment]
Note to all: @robingustafsson has said it is fine to make a bounty out of this issue, so I'm putting one up. If someone starts working on it, they can look at Robin's feature branch (mentioned above) for inspiration, but he started writing this for the old js runner and we want it implemented for the js2 runner. This runner is included in the master branch, but disabled by default (you have to supply a --type js2 switch when running k6 to make it use the js2 runner).

**Comment by liclac** [comment]
Update: the old JS runner is gone, JS2 is all that remains. The code in the feature branch won't work anymore though.

**Comment by ppcano** [comment]
As a workaround, importing a JS library could make the job.

**Comment by gbts** [comment]
Just submitted PR #208 for this. It's a fairly basic wrapper that follows the proposed API.
