### ISSUE TITLE
Record: TTFB and TTLB

### ISSUE THREAD

**Issue by aidylewis** [loadimpact/k6#190]
Would it be possible to return timings for both Time To First Byte and Time To Last Byte? 

The point of TTLB is to exclude HTML parse time.

**Comment by liclac** [comment]
HTML is only parsed if you explicitly call `res.html()`, and is not included in any metrics.

**Comment by aidylewis** [comment]
Thanks for the clarification. How would I access the timings for the FirstResponseByte?

**Comment by liclac** [comment]
…I coulda sworn there was a `http_req_ttfb` metric here not long ago, I'll readd it in a moment.

**Comment by aidylewis** [comment]
It look like http_req_waiting is TTFB ("the moment the request has been fully sent (http_req_sending) until the first response byte has been received").

**Comment by aidylewis** [comment]
In fact, *http_req_duration* includes time spent reading the response body which includes additional timings to TTLB.

**Comment by liclac** [comment]
Reading from `res.Body` is actually what reads from the socket, so there shouldn't actually be a distinction between the two
