### ISSUE TITLE
Can I run two scripts at the same time by a command?

### ISSUE THREAD

**Issue by wmsken** [loadimpact/k6#1918]
Hi, I need to run script1.js and script2.js in parallel on windows, and I found the following command is failed, it just run the first script and then prompt syntax error for the second script:
k6 run script1.js --vus 1 --duration 10s & script2.js --vus 1 --duration 20s

How can I do this please?
Thank you!

**Comment by na--** [comment]
If you want to run multiple scripts simultaneously, you might be better off using the built-in k6 `scenarios` instead of separate scripts: https://k6.io/docs/using-k6/scenarios

Regarding running CLI apps in the background in Windows, this might be helpful: https://superuser.com/questions/198525/how-can-i-execute-a-windows-command-line-in-background

Here's also a k6 issue where we explore how we might support running multiple scripts from the k6 command line: https://github.com/loadimpact/k6/issues/1342

Finally, these types of questions are better suited to the community forum, so please use that in the future: https://community.k6.io/

**Comment by wmsken** [comment]
Thank you na for your reply, but i am confusing now about how to write my script with scenarios.
Supposed that i have two separate scripts named script1.js and script2.js, and the default function is script1() and script2(), now i need to run these two scripts in parallel, do i need to write a new script named script3.js like this as below?

export let options = {
  "scenarios": {
    "script1": {
      "executor": "constant-vus".
      "vus": 2,
      "duration": 1m,
      "startTime": 0s,
      "exec": "script1"
    },
    "script2": {
      "executor": "constant-vus".
      "vus": 1,
      "duration": 1m,
      "startTime": 0s,
      "exec": "script2"
    }
  }
}

export default function() {
    script1();
    script2();
  }
}

**Comment by na--** [comment]
You can do it like this:

```js
export { default as func01 } from './test1.js';
export { default as func02 } from './test2.js';

export let options = {
  scenarios: {
    'first_scenario': {
      executor: 'constant-vus',
      vus: 2,
      duration: '10s',
      exec: 'func01',
    },
    'second_scenario': {
      executor: 'constant-vus',
      vus: 3,
      duration: '15s',
      exec: 'func01',
    },
  }
}
```

**Comment by wmsken** [comment]
Thank you na, this really helps! i can do my test normally now.
Thanks again.

**Comment by emil45** [comment]
Hey @na--, if I'm using `setup/teardown/handleSummary` - where it goes in your example?
Thank you very much for your help.

**Comment by na--** [comment]
You can put `setup`, `teardown` and `handleSummary` in their own file, like this:
```js
import { textSummary } from 'https://jslib.k6.io/k6-summary/0.0.1/index.js';

export function setup() {
    console.log('helpers.js setup()');
    return { foo: 'bar' };
}

export function teardown(data) {
    console.log(`helpers.js teardown(${JSON.stringify(data)})`);
}

export function handleSummary(data) {
    console.log('helpers.js handleSummary()');

    return {
        'stdout': textSummary(data, { indent: ' ', enableColors: true, }),
        'raw-summary-data.json': JSON.stringify(data, null, 4),
    };
}
```

And then you can just re-export them in every other file - `script1.js`, `script2.js`, `main.js` like this:
```js
export { setup, teardown, handleSummary } from './helpers.js';
```

Also, please don't ask questions in _closed_ GitHub issues... The place for such things is the k6 community forum: [community.k6.io](https://community.k6.io/)

**Comment by na--** [comment]
I saved the complete example as a GitHub gist: https://gist.github.com/na--/7105cd97ce76edd4d99c33a8ad38c889
