### ISSUE TITLE
Can I use selenium on my scenario script.js?

### ISSUE THREAD

**Issue by livyson** [loadimpact/k6#193]
Guys,

I am trying to run selenium on my K6 script.js, but when I run the script the following error is displayed:
`ERRO[0002] Couldn't create a runner                      error="Error: open usr/local/bin/chrome.js: file does not exist"
Error: open usr/local/bin/chrome.js: file does not exist`

Could you help with this problem?

Follow attached my script. 
[script.js.zip](https://github.com/loadimpact/k6/files/970241/script.js.zip)

Thanks

**Comment by liclac** [comment]
I think the fundamental problem here is that k6 does not run node.js, so importing native node modules isn't possible.

You could theoretically add support for Selenium to k6, as I believe it communicates over a socket? It's been a while, but the bigger problem is that invoking a full browser to do something is *really slow*, which diminishes the gains of doing so in a load test, where your entire objective is to go fast.

That said, it looks like what you're looking to do here is to extract contents from an HTML page, in which case you should have a look at the [k6/html](https://docs.k6.io/docs/k6html) module, which implements a subset of the jQuery API (soon to be greatly expanded by #21).

Example use case:

```js
import http from "k6/http";
import { check } from "k6";

export default function() {
  let res = http.get("http://example.com/")
  check(res, {
    "status is 200": (r) => r.status == 200,
    "header is correct": (r) => r.html("h1").text() == "Example Domain",
  })
}
```

(Using `res.html("sel")` is a shorthand for `html.parseHTML(res.body).find(sel)`, which also caches the call to `parseHTML()` for the lifetime of the response object.)
