### ISSUE TITLE
statsd collector

### ISSUE THREAD

**Issue by geekdave** [loadimpact/k6#196]
geekdave [8:35 AM] 
@emily Tangent to that thought - Could this be a good time to output to a more general timeseries protocol like `statsd` rather than speaking InfluxDB's protocol directly?

I'm a big fan of InfluxDB myself - but am considering going "back to Graphite" for my load testing dashboards for one main reason: InfluxDB does not support _math across measurements_ (https://github.com/influxdata/influxdb/issues/3552).  

Why does this matter?  Because ideally I want to create some Grafana dashboards that distill down a bunch of results into some easy-to-reason stats like "this endpoint is 30% faster than it was last month".  With InfluxDB-backed dashboards, I can plot two lines and let the viewer make their own visual determination, but with Graphite, I could do the math for them.

If k6 outputted to statsd, then statsd could feed into InfluxDB, Graphite, DataDog, whatever... (edited)

emily [8:40 AM] 
We could totally add statsd support, Collectors live rather independent of the rest of the application and adding one would be really easy, but I don't think it should be the only option; `-o influxdb=http://localhost:8086/k6` makes for much nicer onboarding than having to spin up a statsd proxy in front of InfluxDB to get your metrics in there

**Comment by geekdave** [comment]
Gonna take a crack at PR'ing this myself!

**Comment by ppcano** [comment]
Related issue #343 (Add additional stats provider)

**Comment by ppcano** [comment]
For reference, the [instructions of the k6/StatsD collector](https://docs.k6.io/docs/results-output#section-statsd-output)
