### ISSUE TITLE
Error running Docker image

### ISSUE THREAD

**Issue by michaelmior** [loadimpact/k6#199]
When trying to run an example from [the documentation](https://k6.readme.io/docs/running-k6) I get the error message below. (Docker image ID is 3d1ca569238d)
```
$ docker run loadimpact/k6 run http://test.loadimpact.com
time="2017-05-06T20:01:26Z" level=error msg="Failed to parse input data" error="imports should not contain a protocol"
imports should not contain a protocol
github.com/loadimpact/k6/loader.Load
        /go/src/github.com/loadimpact/k6/loader/loader.go:69
main.getSrcData
        /go/src/github.com/loadimpact/k6/run.go:193
main.actionRun
        /go/src/github.com/loadimpact/k6/run.go:278
gopkg.in/urfave/cli%2ev1.HandleAction
        /go/src/gopkg.in/urfave/cli.v1/app.go:485
gopkg.in/urfave/cli%2ev1.Command.Run
        /go/src/gopkg.in/urfave/cli.v1/command.go:193
gopkg.in/urfave/cli%2ev1.(*App).Run
        /go/src/gopkg.in/urfave/cli.v1/app.go:250
main.main
        /go/src/github.com/loadimpact/k6/main.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:183
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2086
```

**Comment by liclac** [comment]
Ouch, looks like that detection isn't working properly…

As a workaround, explicitly pass `-t simple` for now, or give it a script.

**Comment by michaelmior** [comment]
I get the same error with `-t simple`

**Comment by liclac** [comment]
Sorry, `-t url`; this is what I get for replying from my phone ^^;;

**Comment by michaelmior** [comment]
```
$ docker run loadimpact/k6 run -t http://test.loadimpact.com
Wrong number of arguments!
```

**Comment by michaelmior** [comment]
I still get the same error with `-t url` unfortunately.

**Comment by liclac** [comment]
Argh…

The `main` package is unfortunately a bit of a mess and needs a major facelift (and some unit tests…), please use scripts for now.

**Comment by michaelmior** [comment]
I'm just following the getting started documentation, so I have no idea how k6 works at this point. I guess I'll keep reading :)

**Comment by c-Brooks** [comment]
Just confirming this bug, I get the same error when running `docker run loadimpact/k6 run http://test.loadimpact.com`.  Passing in a script works fine for me though.

**Comment by ragnarlonn** [comment]
@c-Brooks @michaelmior Very sorry about that. Things are moving fast here and especially the docs aren't always keeping up - we recently decided to prioritize JS script execution before being able to hit a single URL, and @liclac designed something that works similar to how `go get` operates, where you can supply a string like "github.com/myrepo/myfile" (e.g. `k6 run github.com/loadimpact/k6/samples/es6sample.js`). This feature made it necessary to disable the hit-a-single-URL option by default, but the docs had not been updated. I just changed them so they don't mention the `k6 run [TARGET-URL]` mode, but will shortly put up a simple .js script that hits a single URL and then let the "Getting started" section use that instead.

**Comment by ragnarlonn** [comment]
Ok, now I have pushed the simplest possible sample file (called "http_get.js") to our /samples directory here on Github, and changed the docs so the "Getting started" section tells people to do `k6 run github.com/loadimpact/k6/samples/http_get.js` instead, as their very first k6 command.

**Comment by michaelmior** [comment]
@ragnarlonn Thanks! That does indeed work.
