### ISSUE TITLE
JS: http: Local HTTP clients, with their own TLS state, etc.

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#20]
*Imported from https://trello.com/c/8IcCqfjD/97-js-http-local-http-clients-with-their-own-tls-state-etc*

**Comment by uppfinnarn** [comment]
Infeasible architecturally, but partially solved by non-reused clients/reused transports. TLS client certs are doable globally though.

**Comment by liclac** [comment]
The js2 runner has this.
