### ISSUE TITLE
Simpler URL for code samples

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#201]
@robingustafsson Could we set up a URL rewrite rule, or something, for samples.k6.io/[path] => https://raw.githubusercontent.com/loadimpact/k6/master/samples/[path] ?

So that people could do `k6 run samples.k6.io/http_get.js` instead of `k6 run github.com/loadimpact/k6/samples/http_get.js`

**Comment by liclac** [comment]
Hm, can you set up redirects on that server?

If not, I can do something similar to what `go get` does where it parses <meta> tags, but I'd like to avoid having to figure out if a response is HTML or JS if possible…
