### ISSUE TITLE
API control example

### ISSUE THREAD

**Issue by neilstuartcraig** [loadimpact/k6#202]
Hi 

I've just started experimenting with K6 and wondered if anyone can point me to an example of how to run a fleet of load generators which are controlled by a central API server? (I am assuming this is or will be possible, based on the CLI `--address` arg - please correct me if i'm wrong).

Cheers

**Comment by liclac** [comment]
This currently needs some manual work, eg. copying your scripts to each machine and pointing them all to the same output database - #140 is my proposal to implement clustering, and I would love some feedback on it.

**Comment by neilstuartcraig** [comment]
Thanks for the info @liclac - I'm still not quite sure how i'd achieve this though. Any chance you could note down some bullet points to illustrate the steps please? I'm assuming i'd be using the `--address` arg somewhere but i can't quite tell where. Sorry if i am being a bit thick.

I'll add a note/observation to #140 which occurred to me when reading through. I also have a couple of other questions/issues which i'll create separate issues for.

Cheers

**Comment by liclac** [comment]
Basically... exactly what you describe can't be done just yet, but that issue is for adding it, almost exactly as you describe.

Today, your best bet would be to use an orchestration mechanism of your choice to run `k6 run ...` across multiple hosts; I believe @aidylewis has some kind of working setup for this?

**Comment by carlwright4** [comment]
Re:  [load impact/k6] APl control

**Comment by aidylewis** [comment]
I'd just just pdsh and Influx.

**Comment by neilstuartcraig** [comment]
@aidylewis - Yeah, sorry, it's me - the one you know :-)

Thanks @liclac - i'm going to try out @aidylewis suggestion.

**Comment by aidylewis** [comment]
We discussed on Slack that InfluxDB may average percentiles and a careless Grafana setup could have us average maximums. My opinion would by to try k6 insights.
