### ISSUE TITLE
"too many colons in address" when dialing IPv6 addresses

### ISSUE THREAD

**Issue by liclac** [loadimpact/k6#203]
```
dial tcp: address ::1:8080: too many colons in address
```

Something about our DNS caching broke it.

**Comment by nathanborror** [comment]
Still getting this error when using: http://localhost:8080/

**Comment by liclac** [comment]
Hm, are you fully up to date? Running samples/localhost.js, replacing "localhost" with "ip6-localhost" to force IPv6, seems to work on my machine.
