### ISSUE TITLE
Configurable TLS ciphersuite and version

### ISSUE THREAD

**Issue by neilstuartcraig** [loadimpact/k6#205]
Hi again

Just noting that i'd really like to be able to run a test and specify (either on CLI or in the JS test config) which TLS ciphersuite and/or protocol version are used in the connections. This is something we do quite often and is supported in several current test apps we use so it'd be great if it is/could be possible in K6.

Cheers

**Comment by robingustafsson** [comment]
JS API proposal:

```js
export let options = {
    tlsCipherSuites: [
        "TLS_RSA_WITH_RC4_128_SHA",
        "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
        ...
    ],
    tlsVersion: {
        min: "ssl3.0",
        max: "tls1.2"
    }
};
```

Where both `tlsVersion.min` and `tlsVersion.max` are optional and default to SSLv3.0 and TLSv1.2 respectively.

Go TLS config (https://golang.org/pkg/crypto/tls/#Config & https://golang.org/pkg/crypto/tls/#pkg-constants):

```go
tlsConfig := &tls.Config {
    CipherSuites: []uint16 {
        tls.TLS_RSA_WITH_RC4_128_SHA,
        tls.TLS_RSA_WITH_3DES_EDE_CBC_SHA,
        ...
    },
    MinVersion: tls.VersionSSL30,
    MaxVersion: tls.VersionTLS12
}
transport := &http.Transport{
    TLSClientConfig: tlsConfig, // https://github.com/loadimpact/k6/blob/master/js/runner.go#L106
}
```

@neilstuartcraig @liclac Thoughts?

**Comment by neilstuartcraig** [comment]
Looks good @robingustafsson - that'd certainly work for my use cases.
If it makes things simpler, i'd usually only really need to specify one of each of ciphersuite and TLS protocol version since i'm load testing, not functional testing but if allowing >1 is simpler and/or desirable then that's totally good from my side.

If you have to use Go TLS ciphersuite naming (a la OpenSSL) then it'd be handy for the docs to point to the OpenSSL page which shows the conversion to their TLS spec equivalents:
https://www.openssl.org/docs/man1.0.2/apps/ciphers.html
https://www.openssl.org/docs/man1.1.0/apps/ciphers.html
etc.

Cheers

**Comment by robingustafsson** [comment]
Thanks, good points @neilstuartcraig .

- We should make the `tlsVersion` option accept a string only as well which would set both `MinVersion` and `MaxVersion` to that version:

```js
export let options = {
    tlsVersion: "ssl3.0"
};
```

- Yes, we should definitely mention in the docs that the cipher suites uses the RFC naming and not the OpenSSL naming.

**Comment by robingustafsson** [comment]
I just posted a bounty for this issue: https://www.bountysource.com/issues/44973136-configurable-tls-ciphersuite-and-version

**Comment by gbts** [comment]
Just submitted PR #235 that implements the above API.

**Comment by gbts** [comment]
With the final merge of #265 I think this issue can be closed now.
