### ISSUE TITLE
Implement more of the jQuery API

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#21]
**Manipulation API**
- [ ] attr() [readonly]
- [ ] html() [readonly]
- [ ] prop() [readonly]
- [x] text() [readonly]
- [ ] val() [readonly]

**Traversal API**
- [x] add()
- [ ] children()
- [ ] closest()
- [ ] contents()
- [ ] each()
- [ ] end()
- [ ] eq()
- [ ] filter()
- [x] find()
- [ ] first()
- [ ] has()
- [ ] is()
- [ ] last()
- [ ] map()
- [ ] next()
- [ ] nextAll()
- [ ] nextUntil()
- [ ] not()
- [ ] parent()
- [ ] parents()
- [ ] parentsUntil()
- [ ] prev()
- [ ] prevAll()
- [ ] prevUntil()
- [ ] siblings()
- [ ] slice()

**Misc API**
- [ ] get()
- [ ] toArray()
- [ ] index()
- [ ] data() [readonly]

*Imported from https://trello.com/c/1XvRjs9A/89-implement-more-of-the-jquery-api*

**Comment by ppcano** [comment]
@uppfinnarn `Help wanted` label?

**Comment by uppfinnarn** [comment]
@ppcano Yes, please. Though it'll have to wait until the new JS runner is merged, which will make this all even easier to do.

**Comment by micsjo** [comment]
val() is not implemented in goquery. attr() is as well as attrOr(). I suggest implementing at least attr().

**Comment by denim2x** [comment]
@ragnarlonn I'd like to finish this task; is the bounty still available ?

**Comment by robingustafsson** [comment]
@denim2x Yes, the bounty is still available. No one else has started working on this issue afaik, so go for it!

**Comment by robingustafsson** [comment]
@denim2x To clarify, this issue should be implemented in terms of the js2 runner (https://github.com/loadimpact/k6/tree/master/js2). So extending what's in https://github.com/loadimpact/k6/blob/master/js2/modules/k6/html/html.go more or less.

**Comment by denim2x** [comment]
@robingustafsson Thanks

**Comment by denim2x** [comment]
@robingustafsson question: What is the expected behavior of `prop()`:
 - hash map storage
 - empty string
 - nil
 - other?

**Comment by liclac** [comment]
Could you elaborate?

**Comment by denim2x** [comment]
`prop(name)` is supposed to return the *property* `name` and there's no implementation in `goquery` for this - so how should it behave?

**Comment by liclac** [comment]
Ah, I see. Just leave it out then - I believe the `attr()`/`prop()` split was in a more recent jQuery version.

**Comment by denim2x** [comment]
- do methods like `children` have to support filtering?
- if so - are `Matcher`s also required?

**Comment by liclac** [comment]
I'd say yes, we want to get as close to the original jQuery API as possible; `goja.AssertFunction` is your friend, that gives you a function you can call as `fn(this goja.Value, args ...goja.Value) goja.Value`.

**Comment by ragnarlonn** [comment]
@denim2x Hi Cristian, are you making any progress?  Is anything still unclear?

**Comment by mitnuh** [comment]
Hello. On bountysource they changed status to stopped working on it so it seemed like it'd be ok for me to step in... 

I've made a fork and a start in feature/jquery branch. Have only added Html() and a basic implementation of Val() so far.

Would you like a PR with what I've got now?

**Comment by ragnarlonn** [comment]
@mitnuh Yeah, I think a PR is probably good. If @liclac can take a look at it now and give feedback it might save you some time spent changing things later.

**Comment by mitnuh** [comment]
Hi. Sorry to bother you but is it ok to close this issue? The PR has been merged but the bounty can't be claimed until the related issue is closed. Thank you.

**Comment by robingustafsson** [comment]
@mitnuh Yes, I'll close the issue. Thank you for your hard work!

**Comment by mitnuh** [comment]
Thank you!
