### ISSUE TITLE
ReferenceError does not stop the test execution

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#213]
Giving the following test (where `check` import is missing):

```
import http from "k6/http";

export default function() {

  let res = http.get("http://google.com/");
  check(res, {
    "status was 200": (r) => r.status == 200
  });

}
```
The load test is executed and reports:

```
ERRO[0002] ReferenceError: check is not defined=======================]       1.1s / 0s
	at /Users/ppcano/dev/li/k6-tests/th1.js:13:8(15)
 
      done [==========================================================]       1.1s / 1.1s

    data_received.........: 15 kB (15 kB/s)
    ....
```

Is this intentional? I was expecting the test run wasn't started.

**Comment by liclac** [comment]
It's intentional, we only run the code outside of `default()` on load.

**Comment by ppcano** [comment]
@liclac Any workaround/solution to identify the `VARIABLE_NAME is not defined` error in the test load? If not, we could mention this case in a "common issue doc article" and recommend to validate the load tests (1 VU running) when scripting the load test.

**Comment by liclac** [comment]
It defaults to running one iteration of one VU. If you have an error in your script, you will get errors when you run it. That seems a little obvious for an FAQ.
