### ISSUE TITLE
Aborting k6 with Ctrl-C/Cmd-C when streaming to Load Impact Insights

### ISSUE THREAD

**Issue by tylenh** [loadimpact/k6#217]
When running k6 in a local Docker container and pressing Ctrl-C/Cmd-C, there's currently no abort command sent from k6 to Load Impact Smart Analysis Service, Insights (https://loadimpact.com/Insights).

Result is that Insights continues to wait for streamed results from the initiated session until the defined session time ends. If a second session is started with k6, Insights is not fetching the the new stream at all, neither as a new test run.

**Comment by robingustafsson** [comment]
solved by #281
