### ISSUE TITLE
Use with phantomjs, nightwatch, or what? 

### ISSUE THREAD

**Issue by nadeemja** [loadimpact/k6#219]
Hello,

It was quick and easy to get started, but not sure where to go from here.

What libraries are people using to simulate clicks and inputs? 

Any examples?

**Comment by liclac** [comment]
I feel like there's some confusion here about what k6 is and what it does. We're not a Selenium equivalent, we don't test frontend performance, but the backend and the network layer.

If what you want is to lift data off a page to use in form submissions (eg. CSRF tokens), you can use a subset of jQuery to do that (see [my answer here](https://github.com/loadimpact/k6/issues/193#issuecomment-298628343), also follow #21 and #197).
