### ISSUE TITLE
Spec API for cloud integration

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#22]
The WIP document specifying the protocol/API:
https://loadimpact.quip.com/08WVAPpFVbfG

Tasks
- [ ] Specify how we intend to use JWTs
- [ ] Specify API endpoints in terms of JSONAPI
- [x] Create state diagram for test statuses
- [ ] Specify metrics format for streaming/upload and download

*Imported from https://trello.com/c/QbNxMPku/98-spec-api-for-cloud-integration*

**Comment by liclac** [comment]
Is this still relevant?

**Comment by robingustafsson** [comment]
@liclac No, let's close this for now.
