### ISSUE TITLE
How to generate graph of generated reports

### ISSUE THREAD

**Issue by akashshinde** [loadimpact/k6#224]
Do we get proper report once execution gets done and is there way to get graphical result of request response time over no of users, something like that ?

**Comment by liclac** [comment]
@ragnarlonn

**Comment by robingustafsson** [comment]
@akashshinde Have you had a look at https://docs.k6.io/docs/influxdb-grafana? Seems to be what you're looking for.

Alternatively, if you don't won't to set up InfluxDB and Grafana you can also output results to our (LoadImpact's) Insights product: https://docs.k6.io/docs/results-output#section-load-impact-insights-output (see also https://loadimpact.com/insights for how to get started).

Disclaimer: I work for LoadImpact
