### ISSUE TITLE
Modifying http inputs for each VU iteration

### ISSUE THREAD

**Issue by Stumblor** [loadimpact/k6#226]
Hey!

I'm testing a user creation endpoint (put) that has data validation checks to ensure no two users are being created with the same username/email. Any suggestions for being able to modify the http data inputs during each iteration?

Ideally 'body' could also accept as input a function, that is called each time.

Many thanks

**Comment by liclac** [comment]
`default()` is called once for every iteration, so you can simply make the request with different arguments every time. You'll probably want to use the `__VU` and `__ITER` variables, both are numeric counters.

If you want to keep more state, you can do so by simply keeping it outside of `default()`, but be aware that VU instances are recycled when a test is scaled; scaling a test down doesn't destroy VU instances, they're simply suspended for an arbitrary amount of time, while scaling a test up reassigns it a new ID (they're guaranteed not to be reused within the same test run).

**Comment by Stumblor** [comment]
Brilliant, thanks @liclac exactly what I was looking for.
