### ISSUE TITLE
Broken link on documentation

### ISSUE THREAD

**Issue by JoaoGFarias** [loadimpact/k6#229]
The link for the [Selection class](https://docs.k6.io/docs/selection-k6html) on the [parserHTML](https://docs.k6.io/docs/parsehtml-src) is broken, returning a 404 error.

Selection Class page:

![screen shot 2017-05-22 at 15 57 34](https://cloud.githubusercontent.com/assets/1585655/26324342/d447eeb0-3f08-11e7-9bd7-e12b5b6bcf76.png)

--------------------------

ParserHTML page:
![screen shot 2017-05-22 at 15 58 15](https://cloud.githubusercontent.com/assets/1585655/26324350/d6c606f4-3f08-11e7-9b33-6b25fe6167bd.png)

--------------------------

404 Error:

![screen shot 2017-05-22 at 16 05 08](https://cloud.githubusercontent.com/assets/1585655/26324355/d9959eb2-3f08-11e7-82a8-8167e2502760.png)

**Comment by ragnarlonn** [comment]
@JoaoGFarias Thanks, fixed now!
