### ISSUE TITLE
Add option to disable automatic redirects

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#232]
When redirects happen, information about intermediate requests gets lost. This could perhaps be solved by making the http.Response object more similar to how the Python Requests response object works, but it can also be useful to be able to control redirect behaviour - e.g. for server debugging purposes. 

A feature that allows the user to turn off automatic redirects would enable a user to both control redirect behaviour and also allow them to gather information about intermediate requests. 

@liclac thinks the best solution is to add a per-request flag that turns off automatic redirects for that particular request, so that is the suggestion:

```
// This check() should pass
check(http.get("http://loadimpact.com", { autoRedirect: false }),
    { "Got redirect": (r) => r.status == 301 }
);
```

**Comment by lambertjosh** [comment]
This would help me greatly, for two reasons:
1. I am trying to work with a site that rotates a session key with each request, and from what I can tell cookies seem to be a manual effort right now. This means if there is a redirect the old cookie is still used.
1. Headers seem to be blindly passed when a POST request gets a redirect response. For example, POST your sign in credentials, server responds with a redirect... and "Content-Type" is still sent in the GET request when auto-following the redirect.

**Comment by liclac** [comment]
Ah, this is implemented, so I'm closing it:

```js
http.get("...", { follow: false});
```

**Comment by romanlv** [comment]
looks like latest version uses `redirects: number` 

`http.get("...", { redirects: 0});`
