### ISSUE TITLE
Clean up old stuff from repo

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#233]
Shouldn't we remove these:

- /tutorials   (old, obsolete stuff, most of it)
- /samples/pantheontest.js
- ...any other obsolete samples?

- Are there any groups of files in the root that we could move to subdirectories, to make the root less cluttered?

**Comment by MStoykov** [comment]
Also:
- jsdoc.json
- k6.sublime-project
- .gitmodules (to check if it won't create big problems when you checkout very old versions of k6, if not for something else at least to know it :))
- Vagrantfile
- Caddyfile
- API.md - it's old ...

Also we should probably clean .dockerignore and .gitignore

**Comment by MStoykov** [comment]
Probably move the logo.png and demo.svg to a separate folder as well

**Comment by MStoykov** [comment]
./external also looks suspect for being completely outdated

**Comment by imiric** [comment]
While we're on the topic of demo.svg, could we consider replacing it with something less CPU taxing? My laptop fans go into overdrive whenever I browse the repo root on GitHub. :-/

On some browsers more than others, but the performance impact is noticeable on all. And I'm on a fairly decent i7 laptop, so the experience must be worse on less powerful machines.

SVG animations don't seem like an efficient solution for this type of demo. How about switching to https://asciinema.org/ or something similar? I'm not sure if their animation can be embedded in GH's README, but I wouldn't mind this opening in a new window as asciinema's UX is decent, and it's popular among open source projects.
