### ISSUE TITLE
k6 run with --insecure-skip-tls-verify drops: "x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by Trudels** [loadimpact/k6#234]
Hi There,

I'd like to run a simple test looking like this:
**Content of test.js**
`import http from 'k6/http';`
`export default function() {`
          `const response = http.get("https://somedomainname/");`
`};`
**By calling k6 like this:**
`docker run --add-host mysecrethost:mysecretip -i loadimpact/k6 run -u 1 -d 10s --insecure-skip-tls-verify - < test.js`

**But i keep getting the error:** 
`x509: certificate signed by unknown authority`

The certificate of the webserver is signed by our internal CA which is also embedded on our docker host.

Is there a way to let k6 know that this ca is secure by adding our CA to a specific pool or something? If thats not possible, why is my --insecure-skip-tls-verify parameter not working?

Thanks for your help
Trudels

**Comment by liclac** [comment]
Which version of k6 are you using? See if this still happens after a `docker pull loadimpact/k6`.

**Comment by Trudels** [comment]
The --insecure-skip-tls-verify argument is working now. But is it possible to add our internal CA Certificate to the trust chain somehow?

**Comment by liclac** [comment]
The recommended way is to add it to the system's trust pool, see: #218 

That said, I would accept a PR that adds a --trust-ca flag.
