### ISSUE TITLE
quiet ignored in windows build

### ISSUE THREAD

**Issue by micsjo** [loadimpact/k6#237]
For some reason the -q and the --quiet flags are ignored in the windows version. Haven't tried any *nix release yet.

It's supposed to be the 0.15.0 version, at least what it says when run with --version

Downloaded from the release page, not built myself.

**Comment by liclac** [comment]
`--quiet` has a slightly misleading name, because all it does is hide the progress bar; it should probably be called `--no-progress` or something of the sort with `--quiet` actually, you know, silencing all output.
