### ISSUE TITLE
Console output suggestion

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#243]
@liclac 

I suggest `k6` to print in red the `% of errors` instead `% of passes`. Because it looks more obvious, we have modified it into [Load Impact K6 Insights](http://support.loadimpact.com/knowledgebase/articles/1172458-insights-overview) 

__Current behaviour__

![screen shot 2017-06-12 at 10 55 25](https://user-images.githubusercontent.com/825430/27026312-9b6ff38e-4f5d-11e7-8193-d9aa7fd598f4.png)

__Suggestion 1__

![screen shot 2017-06-12 at 10 53 00](https://user-images.githubusercontent.com/825430/27026242-615a07ca-4f5d-11e7-961d-9cee363b34ab.png)

__Suggestion 2__

![screen shot 2017-06-12 at 10 52 30](https://user-images.githubusercontent.com/825430/27026241-5feebc28-4f5d-11e7-9560-76c0a88ecb47.png)

If there is an agreement on one of the proposals or a new one, I can write the PR.

**Comment by liclac** [comment]
I like #2, actually, but let's get some more opinions on it.

**Comment by robingustafsson** [comment]
I vote for #2 as well.

**Comment by neilstuartcraig** [comment]
FWIW, i personally prefer the current/original - it's completely unambiguous IMO. Sorry :-)

**Comment by ppcano** [comment]
@neilstuartcraig Feedback is appreciated

![screen shot 2017-06-13 at 09 01 55](https://user-images.githubusercontent.com/825430/27069865-edf29d6e-5016-11e7-88bf-b7c00086efd6.png)

IMO, the example above (with one or multiple failing checks) does not look obvious. 

This means that 60% of the load has succeeded and 40% has failed, but users may interpret the text in red color as 60% of errors.

**Comment by liclac** [comment]
Wild idea: something along the lines of...

```
    ✓ a check that passes
    ✓ another check that passes
    ✗ check that doesn't pass
            ✓ 150 (75%)    ✗ 50 (15%)
    ✓ a third check that passes
```

**Comment by neilstuartcraig** [comment]
I like that @liclac  - it's unambiguous and complete

**Comment by ragnarlonn** [comment]
I also vote for that latest suggestion by @liclac
