### ISSUE TITLE
Console report: show section title

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#247]
We discussed adding a title to the console report to make it clearer the different sections:

```
Thresholds
     ✓ - http_req_duration: p(95)<800

Checks
    ✓ 100% - my first assertion
    ✗ 0% - my second assertion

User metrics

    myNewMetric.........: 78 kB (39 kB/s)

Default metrics

    data_received.........: 78 kB (39 kB/s)
    data_sent.............: 505 B (252 B/s)
    http_req_blocked......: avg=146.13ms max=150.13ms med=150.05ms min=140.12ms p90=150.13ms p95=150.13ms
    ...
    vus_max...............: 5

```

In case the proposal would be accepted:

- Should the report separate User metrics vs Default/System metrics?

- When `Checks`, `Thresholds` or `User metrics` are empty, should the report show an empty message?

**Comment by liclac** [comment]
I honestly don't like this. It's just taking up more space to present the exact same information as the current UI.

**Comment by ppcano** [comment]
Closing, we can re-open later if anyone is interested.
