### ISSUE TITLE
HAR converter

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#248]
When testing web pages, it's common to use some `recorders` to help auto-generating load scripts.

This is a useful feature for web pages testing because, amongst other things, page assets change often its filename on each deployment (when adding fingerprint checksums to the filename before uploading to the CDN). 

Deployment 1: https://subdomain.cloudfront.net/images/foo-342b0f87ea609e6d349c7925d86bd597.png

Deployment 2: https://subdomain.cloudfront.net/images/foo-735d6c098496507e26bb40ecc8c1394d.png

A recorder can help to:

- create your first version of your load tests
- identify some of your web page assets

Other load testing tools offer similar utils either as command option as ["gatling"](https://github.com/gatling/gatling/tree/master/gatling-recorder/src/test/resources/har) or making use of external libraries as ["jmeter"](https://github.com/Seitenbau/har2JMeter). 

In case the converter made sense, I see two possibilities:

1) Add the conversion option to `k6`

```
k6 convert  my-session.har -o script.js
```
2) Create an external tool for example as global npm package
 
```
npm install -g hartok6
hartok6 convert  my-session.har -o script.js

```

I have the doubts with the first option because I am not a fan to expand the scope of libraries and tools, but if the `HAR` approach proves to be a robust solution to the problem, I find better the `k6 convert` option because of developer convenience.

**Comment by liclac** [comment]
I would love to write a `k6conv` tool (or whatever we wanna call it), see also: my comments in #177 on how I'd love to make it a proper compiler.

**Comment by ppcano** [comment]
@micsjo 

1) I find the problem with the Fiddler converter to be the `Fiddler` support for [Mac](http://www.telerik.com/blogs/introducing-fiddler-for-os-x-beta-1) and [Linux](http://www.telerik.com/blogs/fiddler-for-linux-beta-is-here).

2) Do you know if a HAR recorder has any limitations in comparison with a Web Proxy recorder?

**Comment by micsjo** [comment]
True - it's a single platform tool at the moment. The *nix beta is really very Beta.

Regarding a proxy recorder vs HAR recorder I think the HAR is often better. Less hassle with certificates and stuff for SSL. However all the major (IE, Edge, FF, Chrome) HAR file recorders are broken in one way or another. They are not all equal and leave out different details. Mostly enough data there but problems in recreating POSTS from the info available sometimes.

The proxy recorder has the advantage of capturing the exact requests made but can then have timing issues and context issues (such as authorization being out of sequence in the resulting recording) depending on how the proxy actually does the job. And especially handling certificates is a pain. You have to accept your injected recording certificate as valid for all integrated services for the website your recording or else you'll miss out on all the integrated stuff, even simple things as jQuery. You can probably live w/o that but if you use any SSO solution that needs to be included. Can be a pain, especially on ios devices.

**Comment by micsjo** [comment]
A straight forward HAR converter should be easy enough. Very little code needed for that. If you want context in the conversion however it can be a little bit more tricky (such as grouping requests or similar). Same problems as for the chrome recorder plugin for Classic Load Impact Lua script. But less information to use from the HAR file to solve the problem with.

**Comment by robingustafsson** [comment]
To prepare this for becoming a bounty, I want to set the requirements:

- The converter is a builtin k6 command; `k6 convert` or similarly named command.
- The command takes an input file `<input>` and outputs a k6 JS file with the same name as input file, unless overridden with `-o <output>`; the whole command being `k6 convert <input> -o <output>`.
- `version`, `creator` and `browser` objects, as well as the `comment` string if present, should be converted to a header comment in the JS file.
- If `pages` are present and request entries contain `pageref`s then each page's requests should be put into a [group](https://docs.k6.io/docs/tags-and-groups#section-groups).
- For each request `entry`, the `request` object should be converted in full to a k6 HTTP request, including cookies, headers, query string and body data. Any `comment` should be added as a comment above the request line in the JS file.
- Cookies added as headers (until https://github.com/loadimpact/k6/issues/68 is implemented).
- Each request should have a matching [check](https://docs.k6.io/docs/checks) with the status code from the `response.status` field (could perhaps be a configurable parameter `--disable-status-code-checks`).
- Use the request entry `startedDateTime` field to create [request batches](https://docs.k6.io/docs/batch-requests) if start time is close in proximity according to some acceptance value (could be a configurable parameter `--batch-inclusion-threshold` or similar).

HAR references:
- Spec: https://w3c.github.io/web-performance/specs/HAR/Overview.html
- Go code: https://github.com/google/martian/tree/master/har

Thoughts?

**Comment by liclac** [comment]
:+1:

**Comment by robingustafsson** [comment]
Now up as a bounty: https://www.bountysource.com/issues/46204855-har-converter

**Comment by ppcano** [comment]
I think it may be useful to provide the option to `skip` certain domains or URLs. 

```
--skip '*.facebook.com,*.googleanalytics.com'
```

As well, we could provide the option to record only the resources from some specific domains.

```
--only  'myapp.com, mydomain.cdn.com, myapidomain.com'
```

We should think more about all the possible cases and how the API could cover them. 

Thoughts?

**Comment by borjacampina** [comment]
Good idea. I think filtering requests URL domains should be a must since record tools like web browsers/inspectors can export too many resources from CDNs/third party libs, external tracking services.. which (mostly) will not be subject of the tests.

**Comment by micsjo** [comment]
Filtering is needed, not only cmd-line but also as options Id' say.

**Comment by ppcano** [comment]
I think the output should not add status checks by default; the `har` could have saved unexpected response status whose `checks` would be wrong.

I am not convinced at all about this feature but initially, I would make this optional like, for example:
`--enable-status-code-checks`

**Comment by micsjo** [comment]
Why is it a builtin k6 command? There has to be some design rationale for that?

**Comment by ppcano** [comment]
@micsjo I would say "Easy of use"; avoiding to install an additional tool.
