### ISSUE TITLE
Missing setTimeout

### ISSUE THREAD

**Issue by larsla** [loadimpact/k6#251]
I'm trying to use a node library that I need in order to generate keys for use in later load tests.
Since K6 doesn't support node imports I am running the library through webpack/babel to make a bundle.
When trying to use the resulting bundle K6 first takes a very long time to load and then fails with an error:
```
$ k6 -v run -i 1 main.js
DEBU[0000] Babel: Transformed                            t=113.907446ms
DEBU[0000] Loading...                                    name="./bundle.js" pwd="/home/lars/Projects/k6"
DEBU[0000] Resolved...                                   name="/home/lars/Projects/k6/bundle.js"
DEBU[0119] Babel: Transformed                            t=1m58.451998601s
ERRO[0119] ReferenceError: setTimeout is not defined
        at useSetTimeout (/home/lars/Projects/k6/bundle.js:22018:32(2))
        at attemptVertx (/home/lars/Projects/k6/bundle.js:22046:31(30))
        at attemptVertx (/home/lars/Projects/k6/bundle.js:22044:31(28))
        at /home/lars/Projects/k6/bundle.js:22059:37(324)
        at /home/lars/Projects/k6/bundle.js:21912:120(21)
        at /home/lars/Projects/k6/bundle.js:21917:7(30)
        at /home/lars/Projects/k6/bundle.js:23063:92(15)
        at __webpack_require__ (/home/lars/Projects/k6/bundle.js:20:76(32))
        at /home/lars/Projects/k6/bundle.js:35959:24(9)
        at __webpack_require__ (/home/lars/Projects/k6/bundle.js:20:76(32))
        at /home/lars/Projects/k6/bundle.js:35982:33(26)
        at __webpack_require__ (/home/lars/Projects/k6/bundle.js:20:76(32))
        at /home/lars/Projects/k6/bundle.js:66:37(43)
        at /home/lars/Projects/k6/bundle.js:67:13(174)
        at native
        at /home/lars/Projects/k6/main.js:18:122(55)

ReferenceError: setTimeout is not defined at useSetTimeout (/home/lars/Projects/k6/bundle.js:22018:32(2))
```

main.js:
```
import { generateKey } from './bundle.js';

export default function() {
    generateKey()
}
```

crypto.js:
```
var jose = require('node-jose');

export function generateKey() {
    let keystore = jose.JWK.createKeyStore();
    return keystore.generate('EC', 'P-256')
}
```

webpack.config.js:
```
module.exports = {
  entry: './crypto.js',
  output: {
    filename: 'bundle.js'
  },
  module: {
    rules: [
        {
            test: /\.js$/,
            loader: 'babel-loader',
            query: {
                presets: ['es2015']
            }
        }
    ]
  }
}
```

package.json:
```
{
  "name": "test",
  "version": "0.0.1",
  "dependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^7.0.0",
    "babel-preset-es2015": "^6.24.1",
    "node-jose": "^0.9.4",
    "webpack": "^2.6.1"
  }
}
```

Steps to replicate:
* npm install
* export PATH=$PATH:node_modules/.bin
* webpack
* k6 -v run -i 1 main.js

It seems like setTimeout is missing. Is there any way to register the global function myself?
Using the sleep function from k6 it would be possible to do something like:
```
global.setTimeout = function(callback, ms) {
    sleep(ms/1000);
    callback();
}
```

Is there any way to do this?

Thanks

**Comment by ppcano** [comment]
1) @liclac  could it be related to #250?

2) @larsla, I have imported the library with these steps (it may help, looks easier at first glance):

- cloning the project
- npm install
- gulp bundle
- copy the build library into the project
- importing it into the load test

```
import jose from "./vendor/node-jose.js";
export default function() {
  keystore = jose.JWK.createKeyStore();
  keystore.generate("oct", 256).then(function(result) {
    key = result;
    console.log(result);
  });
  http.get("http://test.loadimpact.com/");
}
```

**Comment by liclac** [comment]
You can't use `setTimeout()` because VUs don't run event loops, only sequential calls. It seems odd that a crypto library would need `setTimeout()` though? Is it possible that you're pulling in some browser-specific code that you shouldn't be?

Also:
1. Slow imports of large files is a known issue, and is related to how slow it is to run Babel on our integrated JS engine... we really need to figure out a workaround of some kind :/ #212 
1. I'd love to add a native JOSE module, and I'd highly appreciate contributions! Crypto is something that can be done a lot faster on the Go side than on the JS side.

**Comment by larsla** [comment]
I also came to the conclusion that a native module would be better. I have started coding on it.
I have a question: What is the best way to access the string/[]byte representation of an JS object passed as a goja.Value?
If i use .ToObject(rt).Export() I can get a map[string]interface{}, but most of the time i need to pass the JSON structure to a json.Unmarshal function to get the Go object.
.String() only gives me [object Object] which isn't very helpful.

**Comment by liclac** [comment]
Hm, what are you trying to do, exactly? If you wanna process an object, you can use `v.ToObject(rt)` to convert it into a `goja.Object` you can further inspect.

Also: Could you please post another issue for a JOSE module with an API suggestion, just so we can quickly agree on that before you go implementing it?
