### ISSUE TITLE
emit for WebSockets

### ISSUE THREAD

**Issue by caalle** [loadimpact/k6#254]
Does the WebSocket module support using [emit](https://socket.io/docs/client-api/#socket-emit-eventname-args-ack)? I can only make `send` work.

We're using custom message types to do things like authentication, something like:

```javascript
      const socket =io.connect(host);
      socket.on('connect', function() {
          socket.emit('authenticate', {token}, () => {
              // Ack. callback
          });
      });

      socket.on('my-custom-message-type', onCustomMessage);
    }
```

(ping @gbts )

**Comment by gbts** [comment]
Hi @caalle , the websocket module supports the vanilla websocket protocol. So our version of `socket.send` is similar to node.js's `ws` send, i.e. it sends raw data frames to the server. Socket.io  is an additional abstraction over that protocol and one of the things it does is to add an event type to each message.

Looking up their client's source code, what socket.io's `emit` seems to do is to pack the message event type & data in a JSON array and then send it, which I assume you could emulate with something like this:

    socket.send(JSON.stringify(['authenticate', {token}])

and conversely, to receive custom messages you could parse the array and check the event type:

    socket.on('message', function(data) {
        var args = JSON.parse(data);
        if (args[0] == 'my-custom-event-type') {
            var data = args[1];
            ...
        }
    });

Now the reason that our `send` worked for you without encoding the data is that socket.io probably defaults to the 'message' event when it receives unpacked data. Take the code above with a grain of salt as I'm not very familiar with socket.io, so maybe I'm missing some additional step here.

**Comment by ppcano** [comment]
The `ws` docs has been recently updated [here](https://docs.k6.io/docs/k6-websocket-api)

Closing this issue.
