### ISSUE TITLE
Feedback on docker-compose example at /docs/Grafana+Influx

### ISSUE THREAD

**Issue by MWeesenaar** [loadimpact/k6#258]
I was trying to get the docker-compose example up and running and found a couple of thingies:
- Before I started, I had docker-compose v1.11.2, which was not capable of using volume mounts. I then upgraded to the latest, greatest: v1.14.0 which solved the problem. Changelog shows that this is introduced as of v1.12.0. It might be noteworthy to include that somewhere.
- It's better to do `docker-compose up -d influxdb && docker-compose -d grafana`, and then start k6. Otherwise Influx and Kibana will start in the foreground, whereas you would preferably have these running in the background.
- Include the credentials for Grafana (I guessed admin/admin, but who knows...)

Also, as of [77c90b8](https://github.com/loadimpact/k6/commit/77c90b8d8da0702f001f329dd50b5b19411d646f), there seems to be something broken in a rather bad way :-)

I'd love to hear from you, via Slack or PM, because I might be able to help here!

**Comment by liclac** [comment]
Broken...? But yes, please poke me on Slack.

@ragnarlonn You can configure Grafana for anonymous access and disable the login UI altogether: http://docs.grafana.org/installation/configuration/#auth-anonymous

**Comment by ragnarlonn** [comment]
@liclac anonymous access sounds nice. If @MWeesenaar wants to help with the docker-compose config maybe he could set that up also?

**Comment by MWeesenaar** [comment]
I'll have a look, right away!

**Comment by MWeesenaar** [comment]
Added anonymous access via [PR260](https://github.com/loadimpact/k6/pull/260) and added suggestions to change on the [docs](https://docs.k6.io/docs/influxdb-grafana). 

So it wasn't really broken, it just missed a vital step :) 
Therefore this issue can be closed, in my opinion.
