### ISSUE TITLE
http/2 connections not made by default

### ISSUE THREAD

**Issue by neilstuartcraig** [loadimpact/k6#268]
Hi

I notice that k6 isn't making h2 connections by default to my h2-enabled endpoint. Do i need to pass a flag or add some config?

I've double-checked (via `nghttp2/h2load` that h2 is definitely working on the endpoint.

My `k6` config is very simple:

```
// Main K6 HTTP lib
import http from "k6/http";

// K6 assertions lib
import { check } from "k6";

// K6 test runner options
export let options = 
{
    insecureSkipTLSVerify: true, // GTM currently has an untrusted, self-signed cert
	stages:
	[
        // Ramp up
		{
			duration: "120s",
			target: 100
		},
        // Steady state
		{
			duration: "120s",
			target: 100,
		},
        // Ramp down
		{
            duration: "120s",
            target: 0,
        }
	]

};

// This function is what's executed for each request made by a virtual user (vu)
export default function()
{
    let baseURL = "https://<endpoint address>"

    let res = http.get(baseURL + "/news");

    // Output assertions
    check(res, 
    {
        "status is 200": (res) => res.status === 200
    });
}
```

And i am testing via the latest docker image for `loadimpact/k6` via:
```
docker run -i loadimpact/k6 run - < basic-test.js
```

k6 version info:
```
          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |      |  /  ‾‾\
   /          \   |  |‾\  \ | (_) |
  / __________ \  |__|  \__\ \___/  Welcome to k6 v0.16.0!
```

Any suggestions gratefully received.

Cheers

**Comment by liclac** [comment]
Sorry, finally had a chance to take a look at this, and I can't seem to reproduce it. I added a 'proto' tag to samples and a `res.proto` field for easier debugging though.

(ping @martinfijal for tag change; also @geekdave in case you wanna do something with this in the UI.)

**Comment by markingman** [comment]
Hi, I get the same issue.

Website tests as HTTP2 correctly, a web browser like Chrome uses HTTP2 but the k6 request reports in the logs as "HTTP/1.1".

Might this be something to do with ALPN interaction?

My simple test is below...

cheers,
Mark

`import http from "k6/http";

export default function() {
  http.get("https://test.valhalla.software/index.html");
};`

**Comment by liclac** [comment]
There we go, there were tests for HTTP/2 support, but they were run on a module level and broke specifically within a VU context ever since #205.

**Comment by markingman** [comment]
Great, thanks! :)
