### ISSUE TITLE
Make open() handle binary files

### ISSUE THREAD

**Issue by liclac** [loadimpact/k6#269]
I'm thinking `open(filename, "b")`. Should return a wrapper type with a `.length` and `.hex()` at the very least, and functions in `k6/crypto`, etc. should be amended to handle these values.

**Comment by calvernaz** [comment]
Does it mean the `open(filename)` without the mode would still return a string or should return the wrapper consistently? If returns the wrapper how this case can be handled (I assume operator overloading can't be done) 

```
/path/to/file.txt ->  hi
/path/to/exclaim.js -> export default function(s) { return s + "!" };

import exclaim from "./exclaim.js";
export let file = open("./file.txt");
export default function() { return exclaim(file); };
```

Since the `value.Export()` of `open` is not a string anymore.

**Comment by liclac** [comment]
I don't think there's much value in wrapping strings, since I'm imagining their main use will be in things like configuration files (`let conf = JSON.parse(open("./config.json"))`), and it'd be a breaking change for (in my eyes) very little gain... plus, relevant functions would have to handle both anyhow, or passing plain ol' strings would error.

**Comment by micsjo** [comment]
Major usage for non-binary files when making tests datadriven as well. And for binary as well...

**Comment by calvernaz** [comment]
I agree that would serve other use cases (definitely the one I was trying anyway). I tried to implement the open for binary files but it would break some current assumptions.

In resume, I think it adds great value but it as it stands it would break some things

**Comment by liclac** [comment]
Yeah, but I don't think wrapping text files would really add anything - but that's just me.

**Comment by lambertjosh** [comment]
Would this also include multipart form support, or is that a separate issue?

**Comment by micsjo** [comment]
Bump? Any progress/plans for this?

**Comment by robingustafsson** [comment]
@micsjo Nothing has been implemented yet, but it's high in our backlog, in the top 5 currently. We're discussing ways to communicate our planning better through the use of Github issue milestones.

**Comment by robingustafsson** [comment]
@ragnarlonn Had you started working on this? If so, please assign it to yourself.

**Comment by dstpierre** [comment]
I'm taking look into this to support opening binary files and also handling multipart requests

**Comment by ragnarlonn** [comment]
I submitted a PR for this - https://github.com/loadimpact/k6/pull/370 - waiting for comments from @liclac but if you want to do something in the http module you may want to start with that PR, or at least check it out.

**Comment by dstpierre** [comment]
@ragnarlonn yes sure that's what I did. I started a new branch and added your changes.

One thing I was not clear was why the `crypto` package and `encoding` would need any changes?

Are files are often passed to those packages functions?

**Comment by ragnarlonn** [comment]
@dstpierre The crypto and encoding functions should be able to handle binary data. You may want to hash a file that is in binary format (maybe compute a checksum for an image) for instance. I changed the functions so they accept goja.Value parameters instead of strings, and check if the parameter they get is a string or a Javascript object, in which case it is assumed it is the TextOrBinaryData object (which can store binary data). I am not sure if this approach is the best one though, I am kind of new to dealing with goja and exchanging data between Go and Javascript.

**Comment by liclac** [comment]
Data exchange is hairy and there's basically no one right way to do it… ^^;;

**Comment by robingustafsson** [comment]
This is now in `master`, closed by https://github.com/loadimpact/k6/pull/524. Will be included in next release.
