### ISSUE TITLE
Aggregated metrics as JSON

### ISSUE THREAD

**Issue by jkpl** [loadimpact/k6#271]
Feature request: Option for writing the aggregated metrics to a JSON file similar to the metrics output.

**Comment by liclac** [comment]
Not a bad idea, I would like to see something like a `--report` flag that writes all that info to a JSON file. Think you could send a PR?

You definitely want to change the post-test summary to be backed by a model of some kind, that you then dump straight to JSON at the end.

**Comment by jkpl** [comment]
I'll see if I can work something out. :)
