### ISSUE TITLE
Incorrectly reported checks

### ISSUE THREAD

**Issue by jkpl** [loadimpact/k6#273]
This script should fail checks on all requests.

```javascript
import { check } from "k6";
import http from "k6/http";

export let options = {
  vus: 5,
  duration: "10s",
  iterations: 100
};

function run_test() {
  let res = http.get("http://localhost:8080");

  check(res, {
    "true": (r) => false
  });
}

export default run_test;
```

But the result says all the requests succeed:

```
   duration: 10s, iterations: 100
        vus: 5, max: 5

    web ui: http://127.0.0.1:6565/

      done [==========================================================]        10s / 10s

    ✓ true

    data_received.........: 0 B (0 B/s)
    data_sent.............: 475 B (47 B/s)
    http_req_blocked......: avg=153.35µs max=379.67µs med=0s min=0s p(90)=379.63µs p(95)=379.67µs
    http_req_connecting...: avg=116µs max=282.04µs med=0s min=0s p(90)=281.96µs p(95)=282.04µs
    http_req_duration.....: avg=47.46µs max=135.6µs med=0s min=0s p(90)=110.32µs p(95)=135.6µs
    http_req_receiving....: avg=0s max=0s med=0s min=0s p(90)=0s p(95)=0s
    http_req_sending......: avg=47.46µs max=135.6µs med=0s min=0s p(90)=110.32µs p(95)=135.6µs
    http_req_waiting......: avg=0s max=0s med=0s min=0s p(90)=0s p(95)=0s
    http_reqs.............: 12 (1.2/s)
    vus...................: 0
    vus_max...............: 5
```

On repeated runs, the check occasionally reports the opposite. Maybe a race condition somewhere?

It's also strange how the HTTP requests in the summary are so low.

On `v0.16.0`, the check seems to be always reported correctly.

**Comment by jkpl** [comment]
Git bisect suggests that the issue could be found from one of these commits:

* 7bcf8dad19c7ee1bd4f814d4d64dbd8eab37a2ef
* a9c7549df987cad8ea045502b0e01a8ec3f3ed10
* 371b4af8d443dd1eb9717c35d9cdd19d633af40a
* 41c29dd4e1c06b200b58e4d01028507d66f2437f
* 6447343e10c569767b9ac575d64ce02589c280e5

**Comment by liclac** [comment]
Urgh, looking for this made me notice how something is just majorly broken in the split engine's VU orchestration... this may take a bit >_>
