### ISSUE TITLE
Aggregation metrics are incorrect

### ISSUE THREAD

**Issue by artych** [loadimpact/k6#275]
k6 cli reports 79 reqs, avg duration time = 180.92 (screenshot below).
it means total duration time = 79 x 180.92 =  14 292 

![screen shot 2017-07-04 at 17 42 01](https://user-images.githubusercontent.com/1912947/27835692-ba49508c-60e4-11e7-8a8e-c7b2a9c5a6d1.png)

Insights dashboard reports:
64 reqs (status=200) + 5 reqs (status=0) = 69 reqs (less then cli reported) with avg duration = 207.14, 
it means total duration time = 69 x 207.14 = 14 292 (the same as cli reported)

Hence 
1) Some number of reqs (10 reqs in the example above) have zero impact on duration time and are not included in the insights payload. That could be reqs from the end of the test that reqs that hadn't been responsed before test run time finished (my guess, but I'm not sure). That reqs must not be included in the aggregation.

2) There are reqs with `status=0` (5 reqs from above), it means reqs with network error. They are reported with `http_duration_time=0ms` and they also must not be included in the aggregation. So in fact now both k6 cli and insights are incorrect.

**Comment by liclac** [comment]
I can make it so that only `http_reqs` is emitted for failed requests, if we can be sure that nothing relies on the old behaviour. Ping @martinfijal for Insights, @geekdave for Grafana.

**Comment by luizbafilho** [comment]
Hi @artych, it's a while since this issue was opened, but, could you confirm if this is still happening? I tried here, and all requests are being correctly reported on insights.

**Comment by artych** [comment]
@luizbafilho 
Hey, I've run several tests and the issue looks outdated. Closing it.
