### ISSUE TITLE
Returned status code 500 after several redirects

### ISSUE THREAD

**Issue by lichenglu** [loadimpact/k6#286]
## What is the issue?

My test keeps receiving 500 error code for a GET request.

## What did I do
```
export let options = {
    maxRedirects: 10,
};

export default function() {
    group('Login', () => {
            let res = http.get('https://dashboard.stage.texasoncourse.org');
            // Status is 500, with "internal server error" body
            console.log(JSON.stringify(res)); 
    }
}
```
## More description

So when visiting `https://dashboard.stage.texasoncourse.org`, users will eventually be redirected to another subdomain `https://account.stage.texasoncourse.org/interaction/:sessionId` for login. I am quite sure the `internal server error` has something to do with the sessionId. If the cookie which records the sessionId is gone, then an internal server error will be thrown. But I thought k6 keeps the cookie for an individual VU?

Any thoughts on what might cause the issue? Thank you!

**Comment by liclac** [comment]
Hm, it *should* persist the cookies, as you say... it is set for the correct domain, right?
