### ISSUE TITLE
Provide a native get() method

### ISSUE THREAD

**Issue by NuSkooler** [loadimpact/k6#290]
A native `get()` (note: I'd personally go for a more explicit `getJSON()` or similar) method that would allow checking response results from JSON:

```
(r) => getJSON(r, 'path.to.nested.json') === 'foo'
```

Should return `undefined` if response is not in fact JSON.

See #287

**Comment by liclac** [comment]
I'd implement this as: `res.json('path.to.nested.json')`, PRs extremely welcome - I won't have time to get to it in a while.
