### ISSUE TITLE
More built-in metrics

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#30]
Metrics
- [ ] VU: runtime
- [ ] VU: sleep time
- [ ] group: runtime
- [ ] request: total size
- [ ] request: header size
- [ ] request: body size

Tags
- [ ] ...

*Imported from https://trello.com/c/x0XHOp8D/106-more-built-in-metrics*

**Comment by ppcano** [comment]
A few of these metrics have already added. 

Closing, open a new issue for any metric request.
