### ISSUE TITLE
Deprecate and remove the current Web UI

### ISSUE THREAD

**Issue by liclac** [loadimpact/k6#300]
To be perfectly honest, nobody uses it, it kinda sucks, and it adds *a lot* of build time. I'd like to replace it with something lighter weight down the line (#111), but in the shorter term, I'd like to remove it from the default build.

(It's already unavailable in Homebrew builds, because the build straight up broke there, and so far nobody has commented on it.)

**Comment by aidylewis** [comment]
Don't forget to remove the reference in stdout (if this is to be removed however) @robin

**Comment by olka** [comment]
Used Homebrew build and was confused by this reference to empty web page on localhost )

**Comment by StephenRadachy** [comment]
Same. This explains a lot haha.

**Comment by StephenRadachy** [comment]
Once https://github.com/loadimpact/k6/pull/337 is merged in, the last thing to do, will be to remove any looming references in the docs

**Comment by liclac** [comment]
Closed by #337
