### ISSUE TITLE
[Request] Add-on on-top protocols

### ISSUE THREAD

**Issue by micsjo** [loadimpact/k6#302]
Pluggable architecture for add-on protocols:

There are a number of add-on protocols built on top of http(s) such as streaming protocols, authentication and authorization protocols, IoT protocols and so on.

Would it be possible to implement some type of on-top protocol implementation stack/hierarchy? 

I am fully aware that most of these on-top protocols have implementations in javascript but rather than refactoring for k6 use as modules it would be nice to have a native architecture that is simple to build add-on protocols for. Also, most javascript implementations are dependent on the browser context or nodejs context. We want it in a k6 context.

Optionally a "k6 javascript verified modules" listing/library?

**Comment by liclac** [comment]
The latter I'm definitely for.

**Comment by liclac** [comment]
I'm going to close this in favour of PRing implementations to k6 itself.
