### ISSUE TITLE
Something is missing in Linux 64-bit 17.2 release !

### ISSUE THREAD

**Issue by mmoharam** [loadimpact/k6#304]
Hi,

I'm trying to install k6 linux 64 binaries on ubuntu 16.04 but I keep getting the following error:

panic: could not locate box "core-js"

goroutine 1 [running]:
github.com/GeertJohan/go%2erice.MustFindBox(0xb3bf5a, 0x7, 0xb5cabe)
        /Users/ragnarlonn/src/go/src/github.com/GeertJohan/go.rice/box.go:110 +0x94
github.com/loadimpact/k6/js/lib.init()
        /Users/ragnarlonn/src/go/src/github.com/loadimpact/k6/js/lib/lib.go:10 +0x69
github.com/loadimpact/k6/js.init()
        /Users/ragnarlonn/src/go/src/github.com/loadimpact/k6/js/runner.go:234 +0x6b
main.init()
        /Users/ragnarlonn/src/go/src/github.com/loadimpact/k6/util.go:89 +0xfd

I tried installing the previous version 17.1 and it worked fine.

**Comment by liclac** [comment]
We seem to have pushed broken binaries for v0.17.2, whoops.

Fixed now, please redownload!
