### ISSUE TITLE
[Docs] http_req_duration definition

### ISSUE THREAD

**Issue by artych** [loadimpact/k6#305]
From https://docs.k6.io/docs/result-metrics#section-http-specific-built-in-metrics
> `http_req_duration` - Trend - Total time (ms) for request, excluding time spent blocked (`http_req_blocked`), DNS lookup (`http_req_looking_up`) and TCP connect (`http_req_connecting`) time. 

From https://docs.k6.io/docs/results-output
> `http_req_duration` Total request duration, excluding TCP connect time and DNS lookup time (but including `http_req_blocked time`).

**Comment by liclac** [comment]
The former is correct.

```go
trail.Duration = trail.Sending + trail.Waiting + trail.Receiving
```

**Comment by artych** [comment]
I've fixed https://docs.k6.io/docs/results-output. Closing this.
