### ISSUE TITLE
[Docs] Add new options page to --help or man page

### ISSUE THREAD

**Issue by aidylewis** [loadimpact/k6#309]

**Comment by liclac** [comment]
...please elaborate?

**Comment by aidylewis** [comment]
```$ man k6```

**Comment by liclac** [comment]
Is there anything in particular that you feel is missing from that list...?

**Comment by aidylewis** [comment]
Just been through it on #documentation with Robin.

**Comment by liclac** [comment]
Please write Github issues that make sense without context from elsewhere.
