### ISSUE TITLE
k6 specific default user agent

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#310]
I think we by default should send a k6 specific user agent. Currently we're sending whatever Go is setting by default, something like "Go-http-client/2.0". Maybe something as simple as "k6/0.17.1 (https://k6.io);" would be enough?

**Comment by liclac** [comment]
I like that; it'd be a really quick fix if someone wants to PR it, just add a default for that flag.

**Comment by robingustafsson** [comment]
Closed by https://github.com/loadimpact/k6/pull/466
