### ISSUE TITLE
Wrong version in Windows binaries for 0.17.2

### ISSUE THREAD

**Issue by alfeg** [loadimpact/k6#312]
Both x86 and x64 windows version of `K6.exe` shows that they are of `0.17.1` version

```
NAME:
   k6 - a next generation load generator

USAGE:
   k6.exe [global options] command [command options] [arguments...]

VERSION:
   0.17.1
```

SHA1 hashes
```
x86 - d0e075b7d76998f22a00248427cb6dd727bad9b7 *k6.exe
x64 - e5158564cb8d99d9a4a1c84d1306d42eff7b1324 *k6.exe
```

**Comment by liclac** [comment]
Whoops, looks like @ragnarlonn forgot to update that message for 0.17.1. Rest assured that the release is correct though.

**Comment by liclac** [comment]
I'll keep this issue open for posterity until the next release.

**Comment by ppcano** [comment]
A few releases have been created since this issue was reported. I am closing this issue.
