### ISSUE TITLE
Script debug mode

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#331]
wallrus suggested on Slack that k6 should have a verbose debug mode where it dumped as much detail as possible to stdout about any HTTP transactions made. Seems to me a pretty useful thing to have.

**Comment by liclac** [comment]
Good idea. Could you open a PR that adds this under an option and a CLI flag, named something like Debug? It should probably log to Info, or you'll need `-v`/`--verbose` to see the output.

**Comment by StephenRadachy** [comment]
@liclac on slack
> Yeah, just add an HTTPDebug option to Options, add a `--http-debug` flag and put a bunch of log statements in http.request()

**Comment by marklagendijk** [comment]
Go has methods for this:
- [DumpRequestOut](https://golang.org/pkg/net/http/httputil/#DumpRequestOut)
- [DumpResponse](https://golang.org/pkg/net/http/httputil/#DumpResponse)

I would propose the following approach:

1. Add `HTTPDebug` option to Options and add a `--http-debug` flag as proposed above.
2. Add `if debug { DumpRequestOut(request, true) }` just before the request is sent.
3. Add `if debug { DumpResponse(response, true) }` just after the response is received.

@liclac, @robingustafsson do you agree with this approach?

**Comment by robingustafsson** [comment]
@marklagendijk Sounds good to me.

**Comment by na--** [comment]
This was closed by https://github.com/loadimpact/k6/pull/483
