### ISSUE TITLE
Timers API: `setTimeout, setInterval, clearTimeout, clearInterval`

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#332]
[Browsers](https://developer.mozilla.org/es/docs/Web/API/WindowTimers) and [NodeJS](https://nodejs.org/docs/v0.6.1/api/timers.html#setTimeout) provide a Timers API. `k6` could also provide a `k6/timers` API.

- setTimeout
- setInterval
- clearTimeout
- clearInterval

The WebSocket API provides the [Socket.setTimeout](https://docs.k6.io/docs/socketsettimeout) and [Socket.setInterval](https://docs.k6.io/docs/socketsetinterval) methods to delay a function call while the WebSocket connection is open. 

May users want to use the `k6/timers` API for non-WebSocket tests as well?

If yes, the `k6/timers` API in conjunction with an API for the WebSocket connection status would deprecate the [Socket.setTimeout](https://docs.k6.io/docs/socketsettimeout) and [Socket.setInterval](https://docs.k6.io/docs/socketsetinterval).

**Comment by liclac** [comment]
To be perfectly blunt, no. Node uses an event loop, k6 uses VU iterations. An API like this would make no sense for us, like I keep saying every time someone asks for this.

The websocket API is different because it starts its own event loop inside of a VU iteration.
