### ISSUE TITLE
When `k6` interrupts the execution, `WSSessions/WSConnecting/WSSessionDuration`are not reported

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#333]
The last `ws_sessions, ws_connecting, ws_session_duration` metric points are not reported when `k6` interrupts the execution.

The metrics are included in samples [here](https://github.com/loadimpact/k6/blob/master/js/modules/k6/ws/ws.go#L251), but their `Sample.Time` value will be later than the end of the test and the metrics are not reported.

Running the following [test](https://gist.github.com/ppcano/c20cf4b4b6daa2230af74237944ebeae) replicates the issue. The console output or selected output won't show the metrics.

I was not able to fix it on the [engine](https://github.com/loadimpact/k6/blob/master/core/engine.go#L179). @liclac I can try it again if you tell me how it can be done.

**Comment by liclac** [comment]
Hm. I feel like we need a better solution for filtering out context-cancelled requests than this, because this is a straight up design flaw. I didn't want to do context selects in `http.Request`, but it may be the only way to ensure final metrics like this are emitted properly.
