### ISSUE TITLE
[QUESTION]  - How make break Jenkins build when loadimpact/k6 check failure? 

### ISSUE THREAD

**Issue by rgarbin** [loadimpact/k6#335]
Jenkins stage: 

docker run -i loadimpact/k6 run  -< script.js

I used the simple sample like doc and my check failure as expected but my Jenkins build should failure the build. 

```js
export default function() {
    let res = http.post(BASE_URL + "/service", JSON.stringify(payload), { headers: headers });
    check(res, {
        "is status 200": (r) => r.status === 200,
        "transaction time OK(All under 1s)": (r) => r.timings.duration < 1000
    });
};
```
The stage output on Jenkins build is all right, but build didn't failure.

```bash
    ✓ is status 200
    ✗ transaction time OK(All under 1s)
          0.20% (10/4906) 
```

I take a look in last exit code after runnner stage with docker and for me always return 0(SUCCESS). 

```bash
➜  zenvia-api git:(loadimpact) ✗ echo $?                                                               
0
```

**Comment by robingustafsson** [comment]
Hi @rgarbin, have a look at https://docs.k6.io/docs/checks#section-using-checks-in-a-ci-setting.

Check failures won't affect the exit status of k6 (as a [threshold](https://docs.k6.io/docs/thresholds) would), so to make k6 exit with a non-zero exit code, and signal to Jenkins that the build step failed, you have to setup thresholds on your checks via a custom metric.

Modified example from doc above:
```js
import http from "k6/http";
import { check } from "k6";
import { Rate } from "k6/metrics";

export let errorRate = new Rate("errors");

export let options = {
  thresholds: {
    "errors": ["rate<0.1"], // <10% errors
  }
};

export default function() {
    let res = http.post(BASE_URL + "/service", JSON.stringify(payload), { headers: headers });
    let passed = check(res, {
        "is status 200": (r) => r.status === 200,
        "transaction time OK(All under 1s)": (r) => r.timings.duration < 1000
    });
    if (!passed) {
        errorRate.add(1);
    }
};
```

**Comment by rgarbin** [comment]
thks a lot @robingustafsson.

**Comment by ragnarlonn** [comment]
although that code contains a logical error: the threshold as it is set up will always fail.

**Comment by robingustafsson** [comment]
@ragnarlonn Ah yes, my bad, thanks for the correction!

**Comment by xavierlefevre** [comment]
Hello @robingustafsson , jumping in the conversation.

I'm starting with K6, and I like it. We need to control our APIs performance for our current project and it seems to fit our need.

I also want to have my CI fail on conditions, but so far from my understanding a threshold applies to all tests. However if I run the test for all my API routes, I wanted to be able to have a unique threshold check per route.

**Example:**
- Context: I have an Authentication API with 2 Routes
- Tests: Make sure that for each route, the performance test has 70% success
- Result: If one route requests tests has 60% success and the other one has 80% success, the threshold will be green
- Problem: I wanted it red to tell me that one route test threshold was below 70%

Is it possible to do so ?

Thanks for your work !! And your help on this question :)

**Comment by robingustafsson** [comment]
Hi @xavierlefevre, great to hear you like k6!

A threshold can be applied to all or a subset of data points for a metric. In the example from my comment above the threshold is applied to all data points of the custom metric `errors` which has data added from all requests in the test, but you can instead set it up to have thresholds per API endpoint by using tags.

You'd do something like this:
```js
import http from "k6/http";
import { Rate } from "k6/metrics";
import { check, sleep } from "k6";

let errorRate = new Rate("errors");

export let options = {
    thresholds: {
      "errors{endpoint:root}": ["rate<0.1"], // <10% errors
      "errors{endpoint:get}": ["rate<0.3"], // <30% errors
    }
};

export default function() {
    // Call endpoint 1
    let res = http.get("http://httpbin.org/");
    let passed = check(res, {
        "status is 200": (r) => r.status === 200
    });

    // Add custom metric data point with tag to specify which API endpoint it concerns
    errorRate.add(!passed, { endpoint: "root" });

    // Call endpoint 2
    res = http.get("http://httpbin.org/get");
    passed = check(res, {
        "status is 200": (r) => r.status === 200
    });

    // Add custom metric data point with tag to specify which API endpoint it concerns
    errorRate.add(!passed, { endpoint: "get" });

    sleep(1);
}
``` 
but you can also set up a custom metric per endpoint of course. Tagging is a rather powerful thing though and can be used to set threshold on response times for specific URLs etc as well. See the tags docs for more examples: https://docs.k6.io/docs/tags-and-groups#section-user-defined-tags

I hope that helps!

**Comment by xavierlefevre** [comment]
@robingustafsson super clear, thanks for your answer!

I had another question, if I may in this thread : Can I modify the terminal output to show less data? All the agglomerated data for duration etc. is not useful when needing to analyse on a per root basis.

I know I can grep and re-output something of my likings, but it will be tedious and breakable if you change your output.
