### ISSUE TITLE
k6 needs more informative connection error messages

### ISSUE THREAD

**Issue by Griatch** [loadimpact/k6#336]
When running `k6` in testing, for example against online cloud services, the error reporting is very primitive. For example when testing against a k6-cloud server whose SSL certificate had expired, this was the result: 

```
          /\      |‾‾|  /‾‾/  /‾/   
     /\  /  \     |  |_/  /  / /   
    /  \/    \    |      |  /  ‾‾\  
   /          \   |  |‾\  \ | (_) | 
  / __________ \  |__|  \__\ \___/  Welcome to k6 v0.17.1!
ERRO[0002] Cloud collector failed to init                error="An error occurred talking to Load Impact cloud"
...
```

Not only is this a less-than-pretty error display, it's also not very informative. It would be reasonable for k6 to report the expired SSL certificate here (compare e.g. to how `curl` does it) or any other reason it can deduce for the network problem, like timeouts etc.

**Comment by liclac** [comment]
Forgot to close it, but this was fixed a while ago.

*glares at the person who decided to obscure the actual error like that*
