### ISSUE TITLE
setup code coverage with coveralls

### ISSUE THREAD

**Issue by StephenRadachy** [loadimpact/k6#345]
see: https://coveralls.io/

**Comment by liclac** [comment]
I would love a PR for this! I'd do it, but there are some more pressing issues I need to get done first.

**Comment by StephenRadachy** [comment]
should wait until https://github.com/loadimpact/k6/pull/337 is merged - circleci config is changing

**Comment by robingustafsson** [comment]
Closing this as we have codecov implemented and it feels like it's working nicely for us.
