### ISSUE TITLE
When using `stages`, the duration and progressbar on console output is wrong

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#347]
![screen shot 2017-10-20 at 10 56 53](https://user-images.githubusercontent.com/825430/31813162-b32b1696-b585-11e7-9d34-27551f4f399c.png)

@liclac I could try a PR but perhaps better to wait for the CLI refactor.

**Comment by liclac** [comment]
Yeah, this is causing confusion. You could PR against the `cobra` branch if you like.
