### ISSUE TITLE
Not allowed to upload result to Load Impact cloud 

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#349]
```
k6 run -o cloud my-script.js
```

Uploading results to Load Impact fail after the CLI refactor.

**Comment by liclac** [comment]
Right, you need to do `k6 login cloud` or rename your environment variable to `K6_CLOUD_TOKEN`; all configuration options are now configurable this way.

**Comment by ppcano** [comment]
@liclac 

Would it be possible to find out a workaround to avoid this breaking change? There are a few Insights documentation articles referring to `K6CLOUD_TOKEN`.

We could clean the patch later after upgrading the documentation and some period.

I can try a patch at [k6/config.go](https://github.com/loadimpact/k6/blob/aa66f0ed9532aabb9ba64514ed5fc216e5cc21ac/stats/cloud/config.go#L37)

**Comment by liclac** [comment]
Keeping this open until #352 is merged.
