### ISSUE TITLE
T̶a̶g̶ ̶n̶e̶w̶ ̶r̶e̶l̶e̶a̶s̶e̶ Add more frequent rc pre-releases

### ISSUE THREAD

**Issue by StephenRadachy** [loadimpact/k6#354]
The only way to use the latest alpine build is to run off of latest - I'd like to be able to pin a stable release :)

**Comment by liclac** [comment]
I agree, the reason it hasn't been done yet is because #110 was just merged and the sheer amount of code it changed warrants some caution… ^^;;

(797bc4152f9d1690cd1d3ec9f2affe1bd45e0825, #349 and #355 are directly because of it, we don't want stuff like that slipping into a tagged release…)

**Comment by StephenRadachy** [comment]
👍  100% on board. What if in addition to releases, we had more frequent pre-releases which would be postfixed with '-rc-0,1,2,etc'. This way, those of us who like to live dangerously can without the uncertainty of a new docker pull breaking something without our knowledge.

**Comment by ragnarlonn** [comment]
I think time-based releases are better than feature-based. It feels like the modern way to do things, and a) motivates the developers to keep things release-ready at all times and b) ensures regular releases to the public. Maybe using "rc" releases whenever something feels not quite stable or tested enough is a good compromise that both gets these benefits while also making it easy for less adventurous people to identify the stable releases.

**Comment by robingustafsson** [comment]
On a related note, I think we should stop pushing master as the `latest` tag for Docker image builds. We promote `docker pull loadimpact/k6` as one of the recommended ways to install k6, but on several occasions now the code on master has not been ready for prime time. How about we instead reserve the `latest` tag to be the equivalent of the latest stable/tagged version and then build a `master` or `unstable` branch for master builds?

**Comment by liclac** [comment]
Sure, makes sense. Could someone PR an amendment to the CircleCI script to make that happen?

**Comment by liclac** [comment]
I'm personally not a fan of time-based releases because it adds more work for the maintainers (eg. me)

**Comment by na--** [comment]
Closing this, because:
- we've switched to time-based releases, we release a new k6 version roughly every 8 weeks
- the official docker `latest` tag tracks the latest stable (or hotfix) k6 release, while the Docker `master` image is built from every k6 git commit in the `master` branch
- while we don't have _public_ RC versions, we try to keep `master` quite stable and bug-free
