### ISSUE TITLE
JSON -report does not work. 

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#355]
I didn't know about the feature "Aggregated metrics in JSON format" - #274.

Does `k6` support the option `k6 run -r`? I think this may be a bug introduced during the CLI refactor.

Relates to #351

**Comment by liclac** [comment]
This vanished in the CLI rewrite as the way reports are generated changed majorly.

**Comment by jakobnielsen** [comment]
Has this functionality been included again?
It doesn't seem version 0.21 supports the --report /-r flag.

If not, do you have an idea of when it might be included again?

**Comment by na--** [comment]
@jakobnielsen: no, unfortunately we still don't have this, mostly due to the complexities involved with clustered/cloud orchestration and `teardown()`. Follow this issue (and the related ones), we'll update them when there's progress on this.

**Comment by jakobnielsen** [comment]
Thank you for the reply, I'm following this issue and hoping for it to to be included again.

**Comment by chipironcin** [comment]
Amazing! Thanks for adding this!

**Comment by jcabmora** [comment]
Thank you so much, this is great!
