### ISSUE TITLE
Public roadmap / kanban board

### ISSUE THREAD

**Issue by StephenRadachy** [loadimpact/k6#356]
I would LOVE to see a public roadmap and a Github Project (or some sort of kanban board) for k6. 

It's beneficial for you all, so others can get pumped and maybe even help towards achieving your goals. Also, this will help decrease time spent repetitively answering the same questions. 

For everyone else, it's very much appreciated project visibility :D.

**Comment by robingustafsson** [comment]
Fully agree, we're working on it :)

I'll assign myself to this issue.

**Comment by robingustafsson** [comment]
Have now created a first version of a roadmap: https://github.com/loadimpact/k6/projects/2. We'll keep expanding it. For now we'll not communicate any dates, only how we (Load Impact) prioritize things. We'll discuss how to communicate dates and releases as part of https://github.com/loadimpact/k6/issues/354.

**Comment by robingustafsson** [comment]
We have now published the roadmap for 2018: https://github.com/loadimpact/k6/wiki/Roadmap

We've also started using milestones to communicate what we intend to include in each release.

Closing this issue.
