### ISSUE TITLE
Node packages should not be fetched

### ISSUE THREAD

**Issue by arichiardi** [loadimpact/k6#360]
Hello all!

I am trying the following in my script:

```javascript
import * as fs from "fs"
...

```

but I receive:

```
ERRO[0000] GoError: Get https://fs?_k6=1: dial tcp: lookup fs on 127.0.0.11:53: no such host
```

It seems to me that the feature (I was reading issue https://github.com/loadimpact/k6/issues/167) that fetches dependencies should skip fetching node built-in modules, but I might be doing something wrong instead.

Thanks for this, it looks very nice!

**Comment by arichiardi** [comment]
I have also some debug logs, and it seems my theory is not that far from reality:

```
DEBU[0000] Loading...                                    name=/scripts/k6sendEvent.js pwd=/go/src/github.com/loadimpact/k6
DEBU[0000] Resolved...                                   name=/scripts/k6sendEvent.js
DEBU[0000] Babel: Transformed                            t=128.073014ms
DEBU[0000] Loading...                                    name=fs pwd=/scripts
DEBU[0000] Resolved...                                   name=fs
DEBU[0000] Fetching source...                            url="https://fs?_k6=1"
DEBU[0000] Fetching source...                            url="https://fs"
ERRO[0000] GoError: Get https://fs?_k6=1: dial tcp: lookup fs on 127.0.0.11:53: no such host
```

**Comment by arichiardi** [comment]
There is a [node package](https://github.com/sindresorhus/builtin-modules) package that seems to have a list of built-in modules.

**Comment by ppcano** [comment]
`k6` cannot load NodeJS API, because it does not run in NodeJS. `k6` is written in `go` and use a JS interpreter to execute JS code.

Although you cannot import NodeJS API, you may use npm modules as described in the [k6 Modules documentation](https://docs.k6.io/docs/modules#section-npm-modules).

If you want to open a file, you can use the `open` method, which given a file or a URL will return its contents. You have to call `open` outside the default function to avoid opening the file for each VU iteration.

```
import http from "k6/http";

const data = JSON.parse(open("./data.json"));

export default function() {
  let formData = ...;
  let res = http.post("https://httpbin.org/post", formData);
}
```

**Comment by arichiardi** [comment]
Oh wow got it! 

Where is `open` coming from? What if a dependency uses `node` calls?

May I ask you the why of mixing the two worlds? In terms of usability it does seem a bit confusing I have to say. Or maybe I did not read the docs properly and this was written all along. In any case thanks a lot for the prompt response!

**Comment by ppcano** [comment]
> Where is open coming from?

Sorry for that, there is a documentation article pending of being published.

> What if a dependency uses node calls?

The [Modules documentation](https://k6.readme.io/docs/modules) describes that you have to [browserify](http://browserify.org/) the npm module. [Browserify](http://browserify.org/) will take care of the `node calls`.

> May I ask you the why of mixing the two worlds?

JS as the scripting language for user adoption and `go` to achieve a decent performance. 
You could read about `k6` performance in this [Performance comparison of Load testing tools](http://blog.loadimpact.com/open-source-load-testing-tool-benchmarks-v2)

> In terms of usability it does seem a bit confusing 

I think we have to improve our documentation/communication in this aspect. 

Thanks for the feedback. 

I am closing the issue, let us know if you have any other question here or in stackoverflow using `k6` tag

**Comment by arichiardi** [comment]
@ppcano I tried `open` but still does not find the file, is it a wrapper or straight `go`?
