### ISSUE TITLE
Create CHANGELOG

### ISSUE THREAD

**Issue by artych** [loadimpact/k6#361]
> A changelog is a log or record of all notable changes made to a project.

**Comment by ragnarlonn** [comment]
My first reaction was "of course we should have a CHANGELOG", but more or less the same information is available here: https://github.com/loadimpact/k6/releases

However, it is slightly cluttered with releases information and links etc. so perhaps there is a case for keeping changelog entries in a standalone file also?  It's easy enough to create, but would people use it?

**Comment by liclac** [comment]
The release page is basically a changelog.
