### ISSUE TITLE
Open does not work on files?

### ISSUE THREAD

**Issue by arichiardi** [loadimpact/k6#362]
Hello again!

I thought of opening a new issue for a problem encountered while trying a solution to my problem described in #360 .
Maybe I am doing something wrong, but it seems the following does not work currently:

```
const data = JSON.parse(open("./events.json"));
```

```
time="2017-11-14T20:33:13Z" level=error msg="GoError: Get htt: lookup events.json on *my-ip-address:port:* no such host"
```

I have also tried the `file://` variant to no avail.

Another question I had is whether it works in the docker container (provided the folder is mapped with `-v`.

**Comment by ppcano** [comment]
@arichiardi 


When running the k6 binary, I can use `open` outside the default function, but I haven't tried `open` with docker.

https://docs.k6.io/v1.0/docs/open-filepath

[The Modules article](https://docs.k6.io/docs/modules#section-using-local-modules-with-docker) has a section describing how to mount folders with docker to access the filesystem correctly.

Perhaps, there is a bug using `open` from the docker container; @ragnarlonn Would you mind to try it?

**Comment by liclac** [comment]
If you're running k6 as `docker run loadimpact/k6 run - < script.js`, then the docker container will have no access to your filesystem.

**Comment by arichiardi** [comment]
Ok thanks folks, I will try again today, I think I have `-v`. Will report back.

**Comment by arichiardi** [comment]
I have re-tried and this works correctly:

```shell
$ docker-compose run -v /a-folder/perf:/scripts k6 run /scripts/k6sendEvent.js
```

And the `open` points to `/script/my-data.json`

I guess kind of hacky but I can live with it. Closing.

**Comment by nazad23** [comment]
Hi is there a better way to do this in 2022?

**Comment by mstoykov** [comment]
> Hi is there a better way to do this in 2022?

Given that docker makes it so you can't just access w/e - not if you are using docker. 

Please if you have questions, don't ask them in issues from 5 years ago we have a [community forum](https://community.k6.io/) and if you have an issue or feature request - just open a new one.
