### ISSUE TITLE
Unknown builtin module k6/encoding

### ISSUE THREAD

**Issue by sanderploegsma** [loadimpact/k6#364]
I installed k6 using Homebrew on a Macbook Pro running macos 10.13.1 High Sierra, but when I invoke the sample base64 script I get the following error:

```
ERRO[0000] GoError: unknown builtin module: k6/encoding
	at native
	at /Users/sander/Projects/k6/samples/base64.js:36:50(32)

GoError: unknown builtin module: k6/encoding
```

I'm assuming this should work out of the box.

**Comment by simonbcky** [comment]
same here, just wanted to post...

**Comment by liclac** [comment]
It's only available on master right now.

**Comment by sanderploegsma** [comment]
Okay, that makes sense. Considering there are almost 300 commits since the last release in september, when will the next release be available?

**Comment by liclac** [comment]
@sanderploegsma Sorry, missed this, but it's now available everywhere.
