### ISSUE TITLE
Add documentation for available env variable options

### ISSUE THREAD

**Issue by jonathon-l** [loadimpact/k6#373]
With v0.18.0, setting config values through environment variables was introduced.

The available options should be documented, perhaps in both the CLI and README.

**Comment by ppcano** [comment]
@jonathon-l 

This should be added to the [Options doc](https://docs.k6.io/docs/options) as well.

Suggesting documentation changes is straightforward if you [sign up](https://dash.readme.io/to/k6/signup).

**Comment by luizbafilho** [comment]
I made a few changes to reflect what are the environment variables available.

**Comment by na--** [comment]
Closing this, since it seems done for now. We can revisit the topic and restructure/expand the options documentation when we move the docs out of readme.io
