### ISSUE TITLE
In v0.18.0 reading script from STDIN doesn't work with Insights

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#375]
When running the v0.18.0 Docker image with results streaming to Insights (`-o cloud`) it stops and prints:
`time="2017-11-23T13:19:39Z" level=error msg="0 Validation error"----]   collector`

The error message comes from the cloud API (https://ingest.loadimpact.com/), but the communication with the cloud works with the pre-built binaries and earlier versions of the Docker image so points to some kind of issue with the Docker image.

**Comment by robingustafsson** [comment]
Both the `latest` and `0.18.0` tags are broken in this regard. The most recent version of the Docker image that works is `0.17.2`.

**Comment by robingustafsson** [comment]
It seems the problem is with reading the script from stdin via `-<`. Both v0.18.0 binary and Docker image fails when running with `-o cloud` and reading from stdin. They both work when passing the filename as last arg (using a volume for Docker).

**Comment by liclac** [comment]
As of df5a11f, the error now reads "Validation error: name (Shorter than minimum length 2.)".

I feel like the k6ingest side is the one that should set the default here.

**Comment by robingustafsson** [comment]
@liclac Ah, so the error is that the test name is empty when reading from stdin and that fails the validation in the ingest API. Got it, thanks for fixing the error message display. I think k6 should set the default name to "<stdin>" or something similar (maybe add a timestamp if we feel that all stdin based tests shouldn't be grouped together). I think the validation of the name in the ingest API is good, and if k6 knows the script comes from stdin why not use that to help the user with identifying that in the cloud service?

**Comment by liclac** [comment]
k6 is sending it a name of "", which is failing validation. If you fix that on the server side, you retroactively fix every old k6 version, and you could do things like grouping based on file contents if you wanted. The best k6 could do is push a new version that defaults to "unnamed" or something of the sort.

**Comment by robingustafsson** [comment]
No, this is a recent change (https://github.com/loadimpact/k6/commit/249f97f4a14bd01d91334e34c0b150c38dfb46ba). In v0.17.2 and below k6 sends "k6 test" as the default name of a test, see https://github.com/loadimpact/k6/blob/v0.17.2/stats/cloud/collector.go#L39 and https://github.com/loadimpact/k6/blob/v0.17.2/stats/cloud/collector.go#L291.

Yes, please add a default name back in, whether that is the old "k6 test" or "unnamed".
