### ISSUE TITLE
loader_test failing, test related pastebin resource has been removed

### ISSUE THREAD

**Issue by borjacampina** [loadimpact/k6#379]
https://pastebin.com/zngdRRDTk61 has been removed

I propose to use a gist (https://gist.github.com/loadimpact) (or a raw github file) with the same content: "export function fn() {\r\n    return 1234;\r\n}"

**Comment by StephenRadachy** [comment]
https://github.com/loadimpact/k6/blob/2bd00d6eb1f7855268ddffddda55e36261353700/loader/loader_test.go#L84-L114

Really, unit tests shouldn't have external dependencies - these should be stubbed out.

**Comment by borjacampina** [comment]
Same happens with the ws tests (ws://echo.websocket.org), the #377 PR is failing because of that

**Comment by borjacampina** [comment]
It looks like http://pastebin.com/raw/zngdRRDT is available again!

**Comment by liclac** [comment]
@StephenRadachy I agree 100%, we have a recurring problem of unit tests failing because of broken external resources, which is entirely on me for starting the trend of quickly stubbing unit tests with httpbin - the idea was always to move those in-process, then I never had time to actually do so…
