### ISSUE TITLE
Create Homebrew-core formula

### ISSUE THREAD

**Issue by StephenRadachy** [loadimpact/k6#380]
See: https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md

Grab the mac zip from here:
https://github.com/loadimpact/k6/releases/tag/v0.18.0

Also, update the readme since it will no longer be necessary to tap:
https://github.com/loadimpact/k6/blob/master/README.md

**Comment by liclac** [comment]
If anyone is willing to take this up, I'd be eternally grateful. I'm a little swamped right now to deal with packaging other than for bumping releases.

**Comment by andrewgy8** [comment]
Hey there! Id be willing to take this on. Ive got some free time today.

**Comment by andrewgy8** [comment]
@liclac I saw you committed [this](https://github.com/loadimpact/homebrew-k6/blob/master/k6.rb) 5 days ago.  I tried installing it with this script, and it seemed to work just fine.  Any reason you see, that it needs more work?

**Comment by na--** [comment]
Thanks to @chenrui333, we now have a homebrew-core package for k6 :tada: More info:
- https://github.com/loadimpact/homebrew-k6/issues/6
- https://github.com/Homebrew/homebrew-core/pull/40689
- https://github.com/loadimpact/homebrew-k6/pull/7

I'll close this issue after we update the k6 README and release notes.
