### ISSUE TITLE
Sending a binary file through POST API

### ISSUE THREAD

**Issue by Borisakov** [loadimpact/k6#386]
I am trying to open a file which located in the same folder where the script:
let fpost = open("./file.bin");

and I am getting :
time="2017-11-30T07:52:52Z" level=error msg="GoError: open /file.bin: no such file or directory"

the command using local docker-compose:
docker run -i loadimpact/k6 run --insecure-skip-tls-verify - <system_post 

Any ideas? I have tried all the combination of the path.. where should I put this file in my k6 project file?

**Comment by ppcano** [comment]
@Borisakov 2 things to mention:

1) If you use `docker`, you have to mount the filesystem volume to access local files from your script.

On the same way that is decribed at https://docs.k6.io/docs/modules#section-using-local-modules-with-docker


2) Currently, Binary file is not supported by the [open API](https://docs.k6.io/docs/open-filepath). The feature request is described at #269 and the WIP-Pull request at #370
