### ISSUE TITLE
Add "run" command option and/or REST API endpoint to specify blacklisted IPs

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#389]
In the cloud service (loadimpact.com) we need to stop requests being sent to a number of blacklisted IPs and IP blocks (CIDR).

I propose we add a `--ip-blacklist` option to the "run" command that would take a comma separated list of IPv4 and/or IPv6 CIDR blocks (or if a single IP is specified, consider it a /32 or /128 for IPv6). I also think it would be beneficial to have this implemented as a REST API endpoint (https://github.com/loadimpact/k6/tree/master/api/) so that one could communicate with the k6 REST API (we start k6 suspended in the cloud) to add blacklisted IPs/blocks.

Before trying to connect to a target system k6 should make sure that the IP is not in a blacklisted block. If it is, k6 should exit, with a non-zero exit code and log an error message with the following fields:

- Offending IP
- Blacklisted CIDR block that the offending IP is part of
- URL of HTTP/WebSocket request/connection in question
- Error message explaining the test termination

@martinfijal Please add to this issue if there's something I've overlooked.

**Comment by liclac** [comment]
Having k6 straight up exit would be weird, nigh untestable and needlessly complicated to implement. Having connection attempts aborted before they leave the system, on the other hand, is totally doable.

**Comment by liclac** [comment]
```
$ k6 run samples/localhost.js --blacklist-ip 127.0.0.1/0 --blacklist-ip ::1/0
...
WARN[0000] Request Failed                                error="Get http://localhost:8080/: IP (::1) is in a blacklisted range (::/0)"
WARN[0000] Request Failed                                error="Get http://localhost:8080/style.css: IP (::1) is in a blacklisted range (::/0)"
WARN[0000] Request Failed                                error="Get http://localhost:8080/teddy.jpg: IP (::1) is in a blacklisted range (::/0)"
...
```

**Comment by robingustafsson** [comment]
@martinfijal Could you please have a look at this and comment?

**Comment by martinfijal** [comment]
Looks good. This also works when dealing with redirects, right?
