### ISSUE TITLE
HTTP options

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#39]
Based on experience with current load generator scripting we know users have a need to customize the HTTP client behavior, this card details what options we need.

HTTP Options (set globally)
- [ ] TCP max connections per host
- [ ] TCP max connections per VU
- [ ] User agent string

HTTP options (local, request functions)
- [ ] ...

*Imported from https://trello.com/c/5ISLT75I/115-http-options*

**Comment by liclac** [comment]
I'm adding an user agent flag, but the TCP socket limits would be annoying to implement, do we still need them?

**Comment by liclac** [comment]
Alright, open another issue if we do want those limits.
