### ISSUE TITLE
Binary installation as default or recommended instructions

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#392]
**1 -**

When using `docker`, many users have troubles when the load script requires access to the filesystem, because you have to mount the filesystem from the host into the container as described [here](https://docs.k6.io/docs/modules#section-using-local-modules-with-docker). 

Given the simplicity of the binary file installation: unzip and drop the binary file into a folder in your `PATH`. I think we should recommend the binary installation as default.

IMO, the `docker` way is a good solution to get a workable version of the `master` branch or some predefined environment like the [grafana/k6 setup](https://docs.k6.io/docs/influxdb-grafana#section-using-our-docker-compose-setup).

**2 -**

"Additionally", we could prepare an `install.sh` shell script like other tools do:

```
curl -sfL https://raw.githubusercontent.com/loadimpact/k6/master/install.sh | sh
```

I already did a test https://github.com/ppcano/k6/commit/3d7b5d8c4c7732eabde40fd5978976e26e7db277, but the `checksum` file should be generated for every release.

Thoughts?

**Comment by liclac** [comment]
I completely agree. Docker is great *when you need its features*, not so much as something to point complete beginners to. One of the most common questions we get is "why isn't this import statement working??" from people who don't understand how docker works.

**Comment by robingustafsson** [comment]
We should also have a look at using a service like https://equinox.io/ for being able to offer a smooth update process (eg. `k6 update`) no matter how you installed the binary in the first place. Equinox could also be used for generating native installation packages for Linux and Windows.

**Comment by na--** [comment]
Closing this since we already have binary packages for all major platforms: https://github.com/loadimpact/k6#install
