### ISSUE TITLE
--no-color / -n missing after CLI refactor (v0.18.0)

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#397]
The CLI flag `--no-color` (`-n` for short) has gone missing as part of the refactoring work. See original commit adding it for reference: https://github.com/loadimpact/k6/commit/5f99db11ec9474cdf7803c47e367965f4aa619a9.

**Comment by borjacampina** [comment]
What about using `colorable.NewNonColorable` as stdout/stderr writer instead of evaluating the value of the noColor flag in every part of the code?

```
stdout    = consoleWriter{colorable.NewNonColorable(os.Stdout), stdoutTTY, outMutex}
stderr    = consoleWriter{colorable.NewNonColorable(os.Stderr), stderrTTY, outMutex}
```

**Comment by ppcano** [comment]
a8265cb1b20feeda9bf6d00e75d36dcbeeb36d9c closes this issue. Re-open if necessary.

**Comment by ppcano** [comment]
Re-open.

@martinfijal says that `--no-color` is necessary for `cloud execution`.

The [Options doc](https://docs.k6.io/docs/options) does not mention `--no-color`.  May you share why this is necessary so we can add it to the `docs`.

**Comment by liclac** [comment]
`--no-color` is back, not aliasing it to -n this time bc it's such a sparsely used option and global/command options are no longer positional.

**Comment by borjacampina** [comment]
I was trying to implement this when I commented about using "colorable.NewNonColorable" and I found two new issues.

1. PersistentPreRun doesn't work with the root command (help/usage info, no parameters): so `k6 --no-color`is shown with colors. For now the only thing that comes to mind is implementing the "Run" call in RootCmd command to show help/usage info directly.

2. Clear screen/buffer appropriately on TTY consoles. I think is the ui/progress_bar.go

```
$ k6 run --no-color script.js
          /\      |‾‾|  /‾‾/  /‾/
     /\  /  \     |  |_/  /  / /
    /  \/    \    |      |  /  ‾‾\
   /          \   |  |‾\  \ | (_) |
  / __________ \  |__|  \__\ \___/ .io

  execution: local--------------------------------------------------]   servertor <- garbage
     output: -
     script: script.js

    duration: -,  iterations: 1
         vus: 1, max: 1

    done [==========================================================] 1 / 1ing <- garbage
```
