### ISSUE TITLE
Run a set number of iterations

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#40]
*Imported from https://trello.com/c/0Q3eClL9/116-run-a-set-number-of-iterations*

**Comment by uppfinnarn** [comment]
With a `--count n` specified, each VU will do exactly `n` iterations - that means `-u 1 -c 10` will run 10 iterations total, `-u 2 -c 10` will run 20, etc.

**Comment by uppfinnarn** [comment]
To accompany this, we will start to default to 1 VU running 1 iteration; if `--duration` is specified, iterations will not be capped by default. This means we default to something more akin to a functional test, which can then make for a seamless transition to a load test, but will also work out of the box as a behavioral test.
