### ISSUE TITLE
Improve the way that metrics are pushed to the Load Impact cloud service

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#405]
If a test runs without any `sleep` time, the metrics will be pushed too frequently to the `cloud` and it may overload the service. 

I haven't reviewed the code but I think this is due that `metrics` are pushed after the VU iteration completion. It may be good if we explore a better alternative for pushing the metrics to the `cloud`.

This may be related #344 and the binary format discussion at #321

**Comment by liclac** [comment]
The problem is that you're making an HTTP request for every VU iteration, which can be done thousands of times per second. Batch 'em up like the InfluxDB collector does, or hell, use a websocket.

(Not using JSON would certainly help :T)

**Comment by micsjo** [comment]
How about using a queue? There are queue-services for all the big cloud operators (AWS, Azure, Google) that can handle that. No need to roll your own. Or even add-on one of the streaming data services? Way more capacity than what is needed.

**Comment by ppcano** [comment]
@liclac 

> The problem is that you're making an HTTP request for every VU iteration

I reviewed the code and the metrics are pushed every 1 second. Sorry for the wrong initial assumption.

The problem happens there are many VUs, with many metrics per VUs and the VUs completion is too fast. In some of these circumstances, too much info/metrics are pushed to the server and it fails.

We will figure out soon how to solve this situation.

**Comment by ppcano** [comment]
Closing. #496 and the `gzip compression` have reduced the data size.
