### ISSUE TITLE
Disk config file no longer works

### ISSUE THREAD

**Issue by yzhang-myob** [loadimpact/k6#413]
Hi there,

Looks like my json configuration no longer works after I upgrade to v0.18.2. I used to have:

```json
{
  "userAgent": "k6-client-credentials-endurance-testing",
  "vusMax": 5,
  "stages": [
    { "duration": "1h", "target": 1 },
    { "duration": "1h", "target": 2 },
    { "duration": "1h", "target": 4 },
    { "duration": "1h", "target": 5 },
    { "duration": "1h", "target": 6 },
    { "duration": "1h", "target": 7 }
  ],
  "thresholds": {
    "Round trip time": ["p(95)<500", "avg<350", "min<300"],
    "None 200 response": ["count=0"]
  }
}
```

The above works fine in v0.17.2 when running `k6 run -c <config> <script>`

Is the config option changed?

Thanks

**Comment by liclac** [comment]
Ah, the `-c` flag seems to have been lost in the CLI refactor (`0.8.0`), which also changed the default filename of the config file (same place as before, but now called `config.json`). The latter was intentional, the former not so much - fixing.
