### ISSUE TITLE
get request query parameter suffix & translated to unicode

### ISSUE THREAD

**Issue by ttraenkler** [loadimpact/k6#418]
When requesting a URL with `const res = http.get(url, params);` using a URL containing query parameters like `http://example.com?a=1&b=1` to an URL, the result is `http://example.com?a=1\u0026b=1` - the & it seems is translated to its unicode value. Is this a bug?

**Comment by liclac** [comment]
Hm. That certainly sounds like a bug.

**Comment by luizbafilho** [comment]
Hi, @ttraenkler I'm taking a look at this issue, but I'm not sure what are you referring. Are talking about the `url` attribute in the `response`?

**Comment by ttraenkler** [comment]
Hi @luizbafilho. It is a bit too long ago to be sure, but I think the problem was not the response, but that I cannot make requests that contain parameters

**Comment by luizbafilho** [comment]
Just for the record if there were errors when making requests with query parameters, they are not happening anymore.
