### ISSUE TITLE
Support for writing tests in TypeScript

### ISSUE THREAD

**Issue by cyberw** [loadimpact/k6#422]
It would be really nice to be able to write test cases in TypeScript instead of plain javascript. I miss static typing/compile time checks.

I think this could be accomplished by just creating TS declaration files for the k6 functions that are exposed to the test and publishing them to  https://github.com/DefinitelyTyped/DefinitelyTyped

Some more context: We’re looking at being able to use code for API calls based on code generated from a Swagger API definition, so the test case can call something like:

`customer.addOrder(“pizza”, 1) `

instead of 

`http.post(“http://some-api-endpoint/customer/orders“, { “name”: “pizza”, “quantity”: 1 })`

We could of course generate pure javascript but then that doesn't give us type checks or anything like that, so we wouldnt get IDE support & it would be easier to make mistakes.

**Comment by liclac** [comment]
I'm definitely open to this, but someone would have to PR a change to `js/compiler` that would allow it to handle `.ts` files.

**Comment by dstpierre** [comment]
I think this should be pre-processed via the installed TypeScript compiler on the host instead of bundling the TS compiler inside k6.

A first check to detect if the script passed is `.ts` than `tsc <script>.ts` and the transpiled `<script>.js` would be used as normal in k6.

The TypeScript definition file would simply help the experience writing the tests in code editors.

I'd like to have a look at this.

**Comment by cyberw** [comment]
I've spent some time on it (using tsc as a preprocessor). I'll describe what I've done, in case you are interested:

In my case, merchant-api.ts is a library generated from a Swagger api definition using a code gen (or at least will be, because right now it is just a placeholder that exports a type and a class, later I will tweak it so that the library is the one actually calling k6)

I got it working, but the import statement is a little messed up, so I need to manually replace "./merchant-api" with "./merchant-api.js" in the js before k6 accepts it (otherwise I get ERRO[0000] GoError: open /Users/lars.holmberg/git/k6/merchant-api: no such file or directory)

```
var k6 = require("k6");
var http = require("k6/http");

import {address, MerchantAPI} from "./merchant-api";

export default function() {
// this fails at compile time - type safety :)
//    var v = new MerchantAPI(45);
    var v = new MerchantAPI("http://www.google.com/");

    console.log(v.createOrderMerchantURL({body: <address>({ organization_name: "Foo Corp" })}));
    var payload = ''
    var params =  { headers: { "Content-Type": "application/json" } }

    let res = http.post(v.getDomain(), payload, params);
    k6.check(res, {
        "is status 200": (r) => r.status === 200
    });
};
```

I run it this way (you also need a tsconfig.json and lots of other stuff, probably also `npm install @types/node --save-dev`)
```
tsc && sed -i '.bak' 's/merchant-api"/merchant-api.js"/' typescript.js && k6 run -v typescript.js
```

**Comment by liclac** [comment]
The import change is on purpose, because otherwise we open for a distinction between how relative imports work locally vs remotely (you can `import` straight from URLs). Having to add `.js` felt like a small price to pay for that.

**Comment by cyberw** [comment]
Makes sense. I'm actually quite ok with the way it works now. 

Type info would still be nice (and higher prio than adding ts support in js/compiler imho), but because I can force TS to accept the un-typed calls, this is not blocking me any more (I have two full days of TS experience now :) )

**Comment by aaronmell** [comment]
So one thing that I could not get to work was making my main test file a ts file. The imports for k6 and http won't work in TS unless you disregard the TSC failure, as it still emits the js files. 

I ended up making my main test file a js file to get around this. and additional modules I created to support testing were ts files.

**Comment by grahamyork** [comment]
Can I just add my voice to the others who are asking for this feature. Great idea!

**Comment by Toub** [comment]
A `k6-typescript` template based on https://github.com/k6io/k6-es6 would be awesome.

**Comment by Toub** [comment]
Looks like there is a good example of typescript integration here: https://github.com/go-automate/k6-typescript-framework

**Comment by ppcano** [comment]
> A `k6-typescript` template based on https://github.com/k6io/k6-es6 would be awesome.

There is a project template at https://github.com/k6io/template-typescript

And the TypeScript definition  https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/k6

@MStoykov I think this issue can be closed. If anyone wants any specifics, I suggest creating a new issue.

**Comment by Toub** [comment]
Looks good!

What about adding pointer to this template to the documentation?

**Comment by ppcano** [comment]
> What about adding a link to this template from the documentation?

Yes!, It is on [Examples page](https://k6.io/docs/examples ) and soon on the Modules page -> https://github.com/loadimpact/k6-docs/pull/123

Hopefully, users can find the project template. I will figure out if there are other places to add it.

**Comment by MStoykov** [comment]
I am closing this as well then. Thanks @ppcano

**Comment by ShradhaKhard** [comment]
I am just wondering, how do I run the K6 tests without using webpack? After running `tsc` I can see the transpiled .JS files. but when I run the test.js that I have (which imports functions from other files) It fails to run with `GoError: The moduleSpecifier "../K6LoadTest/actions/actions" couldn't be found on local disk.`
