### ISSUE TITLE
Add examples on creating requests from forms

### ISSUE THREAD

**Issue by marklagendijk** [loadimpact/k6#423]
A common use case with load testing is creating subsequent requests based on a form rendered in a response.
This is useful for scenarios like these:
- You need to post a form with all data as it was already filled in by the server. E.g. the server is using a form as redirect mechanism. Javascript is usually used to autosubmit such forms.
- You need to post a form with certain fields as it was filled by the server. E.g. the server renders a hidden input with a value that is needed to be able to post the request.

As a developer you want functionality to be able to easily create such requests. It would be nice to add examples for these use cases. Additionally we could consider adding this natively to k6, or releasing such functionality as a separate module.

I'm currently working on implementing this. The following is work in progress.
``` javascript 
import cheerio from '../bundle/cheerio.js';

export function createFormRequestFromHtml(html) {
    const form = parseForm(html);
    return {
        method: form.attr('method') ? form.attr('method').toUpperCase(): 'GET',
        url: form.attr('action'),
        body: parseFormDataFromHtml(form)
    };
}

export function parseFormDataFromHtml(html) {
    return parseFormDataArrayFromHtml(html)
        .reduce((result, item) => {
            result[item.name] = item.value;
            return result;
        }, {});
}

export function parseFormDataUrlFromHtml(html) {
    const form = parseForm(html);
    return form.serialize();
}

function parseFormDataArrayFromHtml(html) {
    const form = parseForm(html);
    return form.serializeArray();
}

function parseForm(html) {
    if(typeof html === 'string'){
        const $ = cheerio.load(html);
        return $('form');
    }
    else{
        return html;
    }
}
```

**Comment by marklagendijk** [comment]
Note: my proposed example uses Cheerio for the implementation. I think we should add `serialize` and `serializeArray` on the Selection API. See #424.

**Comment by liclac** [comment]
👍 

If `serialize`/`serializeArray` alone isn't enough, I'd like some discussion around how to design an API that makes sense, so that we can implement it Go-side for performance.

**Comment by marklagendijk** [comment]
@liclac I would suggest that we also implement `http.requestFromResponseForm`.
It would work like this (but then be implemented in Go):
``` js
function requestFromResponseForm(response, formData){
    const document = html.parseHTML(response.body);
    const form = document.find('form');
    const request = {
        method: form.attr('method') ? form.attr('method').toUpperCase(): 'GET',
        url: form.attr('action'), // Note: if it is a relative url, it should resolve based on response.url
        body: _.assign(form.serializeObject(), formData)
    };
    return http.request(request.method, request.url, request.body);
}
```
With this we would have the following:

- `requestFromResponseForm` for creating requests based on a single form in the response. If needed, fields can be overridden by passing them in formData. This would support at least 95% of the scenarios.
- `serialize` / `serializeObject` / `serializeArray` for other, custom scenarios.

**Comment by liclac** [comment]
I like this a lot, actually, though what about making the API something like:

```js
let res = http.get("http://example.com/page/with/form");
let res2 = res.submitForm("#form-id", { field1: "hi", field2: "world" });
```

**Comment by marklagendijk** [comment]
Yes! I like that!

**Comment by marklagendijk** [comment]
This is now clearly documented.
