### ISSUE TITLE
Implement 'Selection.serialize' and 'Selection.serializeArray'

### ISSUE THREAD

**Issue by marklagendijk** [loadimpact/k6#424]
A common use case with load testing is creating subsequent requests based on a form rendered in a response (see #423).

To make it possible to easily implement such use case, without having to use an external library, we should add two methods to the Selection API (mimicking jQuery):
- [serialize](https://api.jquery.com/serialize/)
- [serializeArray](https://api.jquery.com/serializeArray/)

Also see jQuery's implementation: [serialize.js](https://github.com/jquery/jquery/blob/master/src/serialize.js).

**Comment by liclac** [comment]
I'd very much welcome a PR that adds this!

**Comment by marklagendijk** [comment]
Has been implemented by #435, and is merged.
