### ISSUE TITLE
Med value in output is incorrect if the number of iterations is even

### ISSUE THREAD

**Issue by tmcgannon** [loadimpact/k6#426]
Example output (notice med value is less than min value):

ws_session_duration...: avg=40.55ms  **min=17.47ms  med=11.66ms**  max=107.39ms p(90)=107.39ms p(95)=107.39ms
ws_sessions...........: 10

I found the following line which is causing the problem:

https://github.com/loadimpact/k6/blob/3ffe18cd10d8494c47a6c6c303019d1913cb7145/stats/sink.go#L139

t.Med has no value at this line so the resultant t.Med value will be half of one of the first middle values.  It should be half of the sum of the two middle values.

`t.Med = ( t.Values[(t.Count/2) - 1] + t.Values[(t.Count/2)]) / 2 `

**Comment by liclac** [comment]
wHOOPS. Could you send a PR with a fix? ^^;;

**Comment by tmcgannon** [comment]
I don't have a golang environment.  I did provide the one line change though.

**Comment by liclac** [comment]
You can make it through the GitHub web editor if you want! CI will make sure the code is correct.

I just want you getting proper attribution, but if you don't care about that, I can just change it myself.
