### ISSUE TITLE
Hosted k6 documentation

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#44]
Along with launch of k6.io marketing site, we want to plug in a developer-friendly, inviting and useful documentation framework.

Let's start by discussing our options in terms of good and potential frameworks to leverage. What other open source projects or public documentation will be useful as reference to model our site from? 

**Checklist**
- [ ] decide on documentation framework
- [ ] write/merge documentation
- [ ] merge/integrate with k6.io

*Imported from https://trello.com/c/GKPwLLr1/120-hosted-k6-documentation*

**Comment by adr0sen** [comment]
Custom domain http://docs.k6.io is now enabled. 
I'm unsuccessful in getting http://k6.io and http://www.k6.io to properly redirect to http://docs.k6.io, per [this](https://cl.ly/0I1J2A0S1y2P) configuration. 

I will continue debug this, to see if I can figure out the problem.

**Comment by robingustafsson** [comment]
@adr0sen The k6.io and www.k6.io redirects to docs.k6.io have now been set up.

**Comment by ragnarlonn** [comment]
@adr0sen @robingustafsson @uppfinnarn Is it possible to close this issue now?  If there is some automation lacking maybe we can just create a new issue for that?
