### ISSUE TITLE
Add `response.clickLink` method

### ISSUE THREAD

**Issue by marklagendijk** [loadimpact/k6#456]
We use k6 to test flows. These flows usually go like this:

1. Start by doing a request: `response = http.get(someUrl)`
2. Do `response = response.submitForm()` a couple of times. Sometimes provide some custom data.

The nice thing about this is that the test follows the real flow: each step is based on the result of the previous step.

However, sometimes in these flows a user would click a link instead of submit a form (the idea is the same, but the technical implementation slightly different.
This breaks with that principle. In the test you suddenly get an `http.get` call again. Not using anything from the response.

A solution for this would be to add a `response.clickLink()` method:
- `selector` the selector for the link which will be 'clicked'. Optional, default: 'a'.
- `params` custom request paramaters. Optional.

**Comment by robingustafsson** [comment]
@marklagendijk Spontaneously, I think that would be a nice addition to the API.

**Comment by micsjo** [comment]
It deviates from the original design pattern since it reflects UI actions. That being said - so does implementing a HAR file converter _inside_ k6. So I don't know how "religious" LI will be on the design pattern :-)

**Comment by marklagendijk** [comment]
I think that in the context of k6 there are only 2 'ui actions' that can be implemented / are relevant:

1. Submitting forms (already implemented as `response.submitForm`
2. Following links (resolving the url from the link and doing a GET request to it).

So I would say that it would make sense to also add the second one. I'll create a pull request for it (it's quite simple to implement).

**Comment by robingustafsson** [comment]
@micsjo Deviation from what we did in rload/Lua perhaps ;) Sure, there's always the risk of users being fooled by such an API in a (server) load testing tool, thinking k6 will execute client-side JS and wonder why things don't work if the page rendering depends on client-side JS being run, but I think the tradeoff between a more hardline network-only API vs some potential confusion (which I know from experience with our previous generation tools will be there anyhow) can be dealt with through documentation and a helpful community :)
