### ISSUE TITLE
HAR converter should output to stdout

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#471]
I think the user flow would be better if the HAR converter by default sent the converted JS script to stdout instead of to "har-script.js". As it is, a common new user flow is likely to be:

1. `k6 convert myfile.har`
2. `ls`  (to see what file k6 created)
3. `k6 help convert` (to see how you change the file name)
4. `k6 convert -O myfile.js myfile.har`

If instead k6 sent output to stdout, the most common flow would probably be:

1. `k6 convert myfile.har`  --> lots of data printed on screen -> user understands what to do
2. `k6 convert myfile.har >myfile.js`

The -O option is still good to have, but for most people it will not be necessary to learn about it.

This proposed behaviour is more in tune with how common Unix tools work, which means it is also more intuitive to many.

**Comment by robingustafsson** [comment]
Agree, outputting to stdout is a better default.
