### ISSUE TITLE
Add option to override DNS lookup with specific IP

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#474]
When resolving hostnames to IPs k6, through the Go runtime, honors entries in `/etc/hosts` if you're on Linux/Mac and `C:\Windows\System32\drivers\etc\hosts` if you're on Windows. This is a mechanism that works to override DNS resolution for local execution of k6.

To provide a solution that works across local, cloud and clustered execution modes we could add a new option to allow overriding DNS resolution, something like this:

```js
import http from "k6/http";

export let options = {
    hosts: {
        "loadimpact.com": "1.2.3.4",
        "test.loadimpact.com": "5.6.7.8"
    }
};

export default function() {
    let res = http.get("https://loadimpact.com/");
    check(res, {
        "is correct IP": (r) => r.remote_ip === "1.2.3.4"
    });
}
```

Implementation pointers:
- https://github.com/loadimpact/k6/blob/master/lib/netext/dialer.go
- https://github.com/loadimpact/k6/blob/master/lib/options.go

**Comment by markingman** [comment]
Yes this would be perfect — but perhaps consider how `hosts` in `options` (above) could have same domain name for different IPs (i.e. hostname can't be a key), i.e:
`"example.com": "1.2.3.4"`
`"example.com": "5.6.7.8"`

Not crucial but great if can run in the one test.

Real world example: have website running on "1.2.3.4", and set up new server at "5.6.7.8" with same hostname etc, ready to go live, and wish to load test with everything in-situ before re-pointing DNS.

**Comment by robingustafsson** [comment]
@markingman Ah good point, so we'd need to do a round-robin or random selection of the IP to use then when making a connection to the hostname with multiple IP mappings. We could make it so that the value/IP part of `hosts` would allow both a string for the case of one IP and an array for cases of multiple IPs per hostname.

For your example with switching DNS between two IPs you could perhaps make use of env vars? Something like:
```js
import http from "k6/http";

export let options = {
    hosts: {
        "example.com": __ENV.MY_HOST_IP
    }
};

export default function() {
    let res = http.get("https://loadimpact.com/");
    check(res, {
        "is correct IP": (r) => r.remote_ip === __ENV.MY_HOST_IP
    });
}
``` 
that you run with: `MY_HOST_IP=1.2.3.4 k6 run script.js` (or `k6 run -e MY_HOST_IP=1.2.3.4 script.js` when https://github.com/loadimpact/k6/issues/467 is implemented)

**Comment by markingman** [comment]
Sounds perfect again for both points — many thanks! :)
