### ISSUE TITLE
Reduce cardinality of data sent to InfluxDB

### ISSUE THREAD

**Issue by dterei** [loadimpact/k6#485]
K6 appears to generate very high cardinality data.

```
> show tag keys from "http_req_duration";
name: http_req_duration
tagKey
------
group
iter
method
name
ocsp_status
perf_type
proto
status
tls_version
url
vu
```

This is a lot of tags! And a few of them have very high cardinality (largely `iter`, but `vu` is not great either). This very quickly leads to a lot of series:

```
> show series from "http_req_duration" limit 20;
key
---
http_req_duration,group=::basic\ test\ 1,iter=0,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=1
http_req_duration,group=::basic\ test\ 1,iter=0,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=2
http_req_duration,group=::basic\ test\ 1,iter=0,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=3
http_req_duration,group=::basic\ test\ 1,iter=0,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=4
http_req_duration,group=::basic\ test\ 1,iter=0,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=5
http_req_duration,group=::basic\ test\ 1,iter=0,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=6
http_req_duration,group=::basic\ test\ 1,iter=0,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=7
http_req_duration,group=::basic\ test\ 1,iter=0,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=8
http_req_duration,group=::basic\ test\ 1,iter=0,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=9
http_req_duration,group=::basic\ test\ 1,iter=1,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=1
http_req_duration,group=::basic\ test\ 1,iter=1,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=2
http_req_duration,group=::basic\ test\ 1,iter=1,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=3
http_req_duration,group=::basic\ test\ 1,iter=1,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=4
http_req_duration,group=::basic\ test\ 1,iter=1,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=5
http_req_duration,group=::basic\ test\ 1,iter=1,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=6
http_req_duration,group=::basic\ test\ 1,iter=1,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=7
http_req_duration,group=::basic\ test\ 1,iter=1,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=8
http_req_duration,group=::basic\ test\ 1,iter=1,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=9
http_req_duration,group=::basic\ test\ 1,iter=10,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=1
http_req_duration,group=::basic\ test\ 1,iter=10,method=GET,name=Ex2-Basic1,proto=HTTP/1.1,status=200,url=http://test.loadimpact.com,vu=2
```

I was testing out k6 and very quickly hit my InfluxDB max series limit after about 10 minutes of benchmarking.

Currently I'm looking to use telegraf to exclude some of these fields, but it would be great if k6 supported choosing a few options:

1. Which of the default key-value pairs are fields vs tags.
2. Which default key-value pairs are used at all.
3. Which default metrics are used.

(1) alone will solve my actual issue, but the others would be nice :) Other than this issue have been very impressed with k6!

**Comment by robingustafsson** [comment]
Thanks for pointing this out @dterei!

As a first step I suggest we remove the `vu` and `iter` tags by default (they were added for a Load Impact specific use case), and add a CLI option to whitelist the HTTP tags that should be included for HTTP metrics (point 2 in your list). So something like `--http-tags method,status,vu,iter` if you'd want to include just those four tags.

Point 1 and 3 also sound like good (future) additions to me.

**Comment by mnordsletten** [comment]
A fix for this would be very nice. I also hit the max limit of 1,000,000 series within 15 minutes when testing k6 today.

**Comment by ppcano** [comment]
`iter` and `vu` are also included in system metrics like `data_received`, `data_sent` and `iteration_duration`.

I wonder if the option should be renamed to `--tags method,status,vu,iter`

**Comment by robingustafsson** [comment]
Yes, it's also included in those metrics. I've a PR on the way for this (see https://github.com/loadimpact/k6/tree/feature/default-tags-option for WIP). I call the CLI option `--default-tags` and you select which ones to include with a namespace (`--default-tags "vu:id, http:method"` etc.).

**Comment by ppcano** [comment]
@robingustafsson 

Shouldn't it be more intuitive naming the tag with the same than they will be reported?

`--default-tags "vu,method"`

**Comment by robingustafsson** [comment]
@ppcano Hm, true, don't remember why I went with the namespaced approach. Will change that and create a PR so we can get this into master and ready for a new release.
