### ISSUE TITLE
Support for NTLM Authentication

### ISSUE THREAD

**Issue by FournierAlexandre** [loadimpact/k6#493]
Hello,

We have windows web server which are NTLM base authenticated.

Is it supported on K6 or are you planning to support it?

Thanks!

**Comment by FournierAlexandre** [comment]
There is a GO library that support NTLM ; https://github.com/ThomsonReutersEikon/go-ntlm

Not sure if it's easy to integrate.

**Comment by robingustafsson** [comment]
Thanks @FournierAlexandre, will have a look at the lib. Yes, NTLM is something we plan to support as it's something we (Load Impact) have in our current Lua based cloud offering.
