### ISSUE TITLE
Adding tags automatically to all metrics.

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#501]
It is useful to have an option (CLI and in code) to add tags to all metrics.

`--tags=mytag1:value1,mytag2:value2`

```
export let options = {
  vus: 20,
  duration: '30s',
  tags: {mytag1: "value1", mytag2: "value2"}
}
```

This is useful for the Cloud Collector and it could also be a good addition when reporting to other Collectors (InfluxDB, prometheus...), for example, to differentiate different tests or environments.

The API syntax is related to #485

**Comment by robingustafsson** [comment]
@ppcano This is a duplicate of https://github.com/loadimpact/k6/issues/461

**Comment by ppcano** [comment]
Closing in favour of #461
