### ISSUE TITLE
Global and per-request option to discard incoming data on arrival

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#504]
Saving HTTP response body data by default is arguably a good default in the name of user experience. But, in many cases it makes little to no sense to spend memory on saving response body data. One such case, where in most cases it makes little sense, is when requesting static website assets (JS, CSS, images etc.).

For cases like that it'd make sense to have an option to discard incoming data on arrival to save CPU cycles (copying data) and memory.

I propose we add a global as well as a per-request option for this. Something along the lines of:

```js
export let options = {
    discardResponseBody: true|false
};

export default function() {
    let res = http.get("https://example.com/", {
        discardResponseBody: true|false
    });
    // res.body would now be null if discardResponseBody==true
}
```

Code references:
- Options: https://github.com/loadimpact/k6/blob/master/lib/options.go
- Per-request options: https://github.com/loadimpact/k6/blob/master/js/modules/k6/http/http_request.go#L164
- Response body handling: https://github.com/loadimpact/k6/blob/master/js/modules/k6/http/http_request.go#L311 (for discarding body: https://coderwall.com/p/3t9ljq/discard-response-body-in-go-http-request)

Related to https://github.com/loadimpact/k6/issues/477

**Comment by ppcano** [comment]
Look a good idea. Should the HAR converter by default discard body response?

`discardResponseBody ` looks too long. Can we figure out a different option name? One idea could be to use `responseBody=false` to discard the body.

**Comment by robingustafsson** [comment]
For the HAR recorder we could perhaps discard response bodies for non-text content-types by default?

Yeah, naming suggestions are welcome. Agree, `responseBody=true|false` would work for the per-request option but feels a bit too non-descriptive for the global option.

**Comment by ofauchon** [comment]
Hi Robin, 

This is my first contribution for the project. 

https://github.com/ofauchon/k6/tree/feature/504_HttpDiscardResponse

It's not fully tested yet, but can you already have a look to the implementation ?

Note I keeped the 'discardResponseBody' parameter name because I find it more clear. 

Olivier

**Comment by na--** [comment]
Thanks @ofauchon! I had a quick look at the changes in your branch and they look very good to me, so go ahead and make a pull request. The only thing that I think is missing right now is a simple unit test or two that verify that the new options work as expected. Thanks again for implementing this!

**Comment by ofauchon** [comment]
Hi na--

Thanks for your quick review.
I added a simple unit test as suggested and i made the pull request..

Olivier

**Comment by na--** [comment]
Closed by https://github.com/loadimpact/k6/pull/742, thanks again @ofauchon!
