### ISSUE TITLE
Add remote address information to metrics

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#509]
It could be useful to add the remote address information as an optional `tag` for `http` metrics.

[net.http.Request.RemoteAddr](https://golang.org/pkg/net/http/#Request)

To avoid adding more tags, it could be implemented after #485

**Comment by robingustafsson** [comment]
Through https://github.com/loadimpact/k6/issues/485 this is related to https://github.com/loadimpact/k6/pull/525
