### ISSUE TITLE
Shared state/memory between VUs

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#532]
We should evaluate possible ways to share larger blobs of data between VUs. The use case being that one might want to declare (or load from file on disk) a large data structure in the init context that is than used to parameterize data in the test.

Some ideas:
1. Share parts of the init context between VUs (not certain if this is at all doable in a clean way)
2. Create an API that is writable in the init context but only readable when running the test (executing the `export default function()`)

An API for 2) could perhaps be something like:
```js
import share from "k6/share";

// Parse data in to format specifc JS objects (CSV, JSON etc.)
let csvShare = share.load("./data.csv");
let jsonShare = share.load("./data.json");

export default function() {
    // Read data from the shared data blobs
    let row = csvShare.row();
    let randomRow = csvShare.random();
    let itemTitle = jsonShare.q("0.properties.title");
}
```

**Comment by Globegitter** [comment]
Is it possible to have any shared state at the moment? We are interested in sharing a counter between the requests, to know the how many number of requests it took until a certain condition a has been met.

**Comment by na--** [comment]
At the moment you can use a custom `Counter` metric (docs [here](https://docs.k6.io/docs/result-metrics#section-custom-metrics) and [here](https://docs.k6.io/docs/counter-k6metrics)) to track that at the end of the test, but there's no shared counter that you can use and check inside of the script, sorry. Depending on your use case, [thresholds](https://docs.k6.io/docs/thresholds) may be able to do the job, but if not, follow this issue for updates on any new shared state features.

**Comment by na--** [comment]
This was resolved by https://github.com/loadimpact/k6/pull/1739. As described in the [release notes](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.30.0.md#share-memory-between-vus-using-read-only-arrays-1739) (we don't quite have the docs updated yet), k6 now has a way to use a huge read-only array without the need to have a copy in every VU. We could do something similar for a map in the future, if needs be, but that would be a separate issue. And data segmentation (i.e. VUs independently iterating over non-overlapping elements of the array) falls under https://github.com/loadimpact/k6/issues/1539. So, I think this can be closed :tada:
