### ISSUE TITLE
Setup and teardown for cloud execution

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#539]
https://github.com/loadimpact/k6/pull/457 implements setup & teardown lifecycle hooks for tests. However, it doesn't implement the necessary hooks for the feature to work with cloud/distributed execution, namely:

- We need to be able to run *only* the setup function (and pause) and then distribute the result/return of the setup function to all nodes' `export default function`:

    ```js
    export default function(setupData) {
        http.get(`https://${setupData.featureBranchSubdomain}.example.com/`);
    }
    ```

- We need to be able to extract the data returned by the `setup()` call from the node where it was run, and pass it to all other nodes' `export default function`. Maybe through the REST API? So, you could start k6 with something like:
    1. run `k6 cloud --run-setup-then-pause script.js`
    2. extract the `setupData`
    3. pass it to all nodes (k6 run --setup-data "..." or via REST API), and then unpause all nodes to begin execution

The intent is to merge https://github.com/loadimpact/k6/pull/457 first to make it available in k6 for local execution and then implement what's outlined in this issue to gain the necessary cloud/distributed execution support.

**Comment by robingustafsson** [comment]
Also, as noted by @na-- in https://github.com/loadimpact/k6/pull/457 the setup and teardown function timeouts (hardcoded to 10s for now) should be made configurable.

**Comment by na--** [comment]
Closing this because https://github.com/loadimpact/k6/pull/629 should be sufficient to implement the rest of the changes outside of k6 itself.
