### ISSUE TITLE
Make sure we run CI tests against all supported Go versions

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#541]
We currently run tests against Go 1.10 only (`circleci/golang:latest` in https://github.com/loadimpact/k6/blob/master/.circleci/config.yml#L5). We say in the README and CONTRIBUTING.md that we support Go 1.8+, so we should either make sure the test suite passes on 1.8 and 1.9 as well or up the required Go version.

**Comment by na--** [comment]
I think this could probably be much easier to do with Travis than with CircleCI:
- https://docs.travis-ci.com/user/build-stages/
- https://docs.travis-ci.com/user/build-stages/matrix-expansion/
I don't think CircleCI supports this natively, it looks like you have to copy-paste the whole stage script to make it work, and it's more complicated to test in parallel as well.

**Comment by na--** [comment]
Just for completeness, GitLab CI added support for GitHub projects recently: https://about.gitlab.com/features/github/
Another thing worth looking into if we switch CI systems is whether they support testing the result of a pull request before actually merging it, since we can't do that in CircleCI easily.

**Comment by luizbafilho** [comment]
I'm not sure if this is necessary, we are building a tool that is used as a binary, there is no need to guarantee that we can build against past versions of Go. 

That guarantee is usually related when building a library that can be used by many projects that we have no control of. So, the support for multiple versions of Go makes sense.

**Comment by robingustafsson** [comment]
@luizbafilho True, I guess we could require the latest version when building from source or contributing. Building from source might also be less of concern if we start providing nightly builds or similar of the binaries.
