### ISSUE TITLE
Run tests on Windows using AppVeyor

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#542]
As Windows is one of the platforms we support and build releases for we should run the tests on Windows as well. As CircleCI doesn't have Windows support, let's have a look at [AppVeyor](https://www.appveyor.com/) as an additional CI service for Windows.

**Comment by robingustafsson** [comment]
See example config here: https://github.com/mholt/caddy/blob/master/appveyor.yml

**Comment by MStoykov** [comment]
Fixed with #756
