### ISSUE TITLE
Document what archives are and how they work

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#546]
Add documentation describing archives:
- What an archive is (basically a tar file with all `import`ed JS modules and `open()`'d files inlcluded and `export let options` extracted into a metadata.json)
- What `k6 archive script.js` does
- The structure of an archive
- How it works with cloud execution (an archive is implicitly created as part of the invocation of `k6 cloud script.js`)

**Comment by robingustafsson** [comment]
Have a first draft of this done at: https://docs.k6.io/v1.0/docs/test-archives-for-bundling-sharing

**Comment by na--** [comment]
LGTM
