### ISSUE TITLE
Warning for "no iterations could be completed" doesn't detect a specific case

### ISSUE THREAD

**Issue by fredmenez** [loadimpact/k6#547]
Instead of stopping and displaying an error message the stage setup runs indefinitely:

`stages: [ , ]`

Although the following stage setup does end immediately: 
`stages: []`

and displays a message : 

`WARN[0001] No data generated, because no script iterations finished, consider making the test duration longer`

**Comment by na--** [comment]
Thanks for reporting this. Can confirm that `export let options = { stages: [] };` exits immediately, while `export let options = { stages: [,] };` hangs indefinitely.
