### ISSUE TITLE
Document how tests are executed (closed vs open system model, VUs etc.)

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#551]
We need to do a better job of explaining how k6 tests are executed, the difference between closed and open system models [1], and how VUs, duration and iterations relate to each other.

We have a start in [2], but we can improve it. Also, this relates to https://github.com/loadimpact/k6/issues/550.

[1] - http://users.cms.caltech.edu/~adamw/publications-openclosed.html
[2] - https://docs.k6.io/docs/running-k6#section-adding-more-vus

**Comment by na--** [comment]
This was done in https://github.com/loadimpact/k6-docs/pull/49
