### ISSUE TITLE
Fix archive code to handle Windows path separators

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#560]
When k6 creates an archive using `k6 archive script.js` (or implicitly when executing `k6 cloud script.js`) the path separator used for the files inside of the tar file + metadata.json entries `pwd` and `filename` will be whatever the local system is using, so on Linux/Unix it'll be `/` and on Windows `\`.

This will cause trouble in two ways:
1. Archives created on Windows won't be digested correctly by k6 as k6 internally assumes `/` as a path separator when loading files.
2. When untar'ing archives created on Windows on a Linux/Unix machine the`\` path separator will mess up paths of the extracted directories and files.

We need to patch both as 1) will enable reading of archives created by older versions of k6 and 2) for better cross platform support.

Fixing 1) looks to be trivial, a matter of converting `\` to `/` in [ReadArchive()](https://github.com/loadimpact/k6/blob/master/lib/archive.go#L68) (for `hdr.Name` and `arc.Filename` and `arcPwd` when unmarshaling metadata.json).

Fixing 2) also looks straightforward, normalize all paths to use `/` as the path separator when creating the archive.

**Comment by luizbafilho** [comment]
fixed by #566
