### ISSUE TITLE
Wrong metrics collection when there are redirects

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#562]
At the moment, metrics collection can return wrong results when there are HTTP redirects. Mostly because we're using Go's [`httptrace.ClientTrace`](https://golang.org/pkg/net/http/httptrace/#ClientTrace) (via [`netext.Tracer`](https://github.com/loadimpact/k6/blob/master/lib/netext/tracer.go)) incorrectly. From the docs:
> ClientTrace currently traces a single HTTP request & response during a single round trip and has no hooks that span a series of redirected requests. 

Unfortunately, currently we don't use a new `Tracer` for each [`RoundTrip()`](https://golang.org/pkg/net/http/#RoundTripper) ("single HTTP transaction"), rather [we use a singe `Tracer` for a whole `Client` request](https://github.com/loadimpact/k6/blob/4e50dea30d783778ed8216014d41b2c2a8641fc4/js/modules/k6/http/http_request.go#L402), which may include a whole lot of redirects, since the [`http.Client` "handles HTTP details such as cookies and redirects"](https://golang.org/pkg/net/http/#Client). For a more correct approach, we can emulate the example on the bottom of the [blog post that introduced HTTP tracing](https://blog.golang.org/http-tracing).

I think that the bigger issue here is that we don't actually have any special treatment of redirects. We only allow users to specify what's the maximum number of redirects allowed, otherwise we pretend they don't exist. At the moment if a script requests an http site that redirects to an https site, the mess will be especially big :)...  If we run `http.get("http://httpbin.org/redirect-to?url=https://www.httpbin.org/delay/3");`, we'll get `http_req_tls_handshaking` information, but if I run it with `-o json`, the `URL` tag will be the plain http one. The `http_req_connecting` stat will also be for the http url, not the https one...

I think the only correct approach here is to basically measure and tag each request of the redirect chain separately. We should probably use the same `name` tag for all of the redirect requests that the original had, but the other http-related tags could be different.

**Comment by luizbafilho** [comment]
Hi @na-- not good news on this. I tried my best to trace the redirects but there is a lot of coupling on the data we need to expose that is only available in the client context.

The approach I choose was the one you pointed, I created a new RoundTripper and I was creating one tracer for every RoundTrip call, and we need to set some tags, but some of them info is only available in the client level, like `TLS` info and errors for example.

I pushed the work I did, so you can take a look, it is totally ugly, but that is me trying to make something work, it would be nice if you could take a look so we can discuss alternatives.

https://github.com/loadimpact/k6/compare/fix/trace-redirect-requests?expand=1

**Comment by na--** [comment]
Hmm I'll take a more thorough look sometime this week, but the [`Transport`](https://golang.org/pkg/net/http/#Transport) (i.e. the `RoundTripper` implementation) should be the place that deals with TLS and thus has the necessary information. The `Client` is supposed to deal only with higher-level stuff like cookie and redirects. 

Quickly skimming your code I don't see any issues - it's a bit ugly, but I wouldn't call the current state of the HTTP request code pretty either, so it may actually be a slight improvement... :grin: Not sure what the problem with the TLS is, since you're just wrapping the `Transport`, can't you just use the `Response.TLS` from it?

**Comment by na--** [comment]
This was fixed by #753
