### ISSUE TITLE
Add an option to filter the emitted metrics to outputs

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#570]
We currently output quite a lot of data and it'd [probably](https://k6io.slack.com/archives/C3E688J8Z/p1521461932000225) be useful if there was a way to filter/limit the emitted metrics directly from k6.

**Comment by danron** [comment]
I will take a look at implementing this as a metric whitelist.

**Comment by na--** [comment]
Closing this in favor of https://github.com/loadimpact/k6/issues/1321
