### ISSUE TITLE
Prevent execution with mutually exclusive options

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#571]
We should probably show an error or warning when users try to run k6 with mutually exclusive options. [Properly documenting](https://github.com/loadimpact/k6/issues/551) this is very important as well, but we probably shouldn't allow users to specify `--iterations` and `--duration` at the same time. Or any of `--iterations`/`--duration`/`--vus` and `--stage` at the same time. 

This restriction should only be valid for a single "level" of the [options "hierarchy"](https://github.com/loadimpact/k6/issues/538#issuecomment-378857270), for example it should be possible for the exported script `options` to specify `stages` and for the user to override it with `iterations` from the CLI options.

There's probably also a bug with the current handling when you specify both duration and VUs directly and also stages: https://k6io.slack.com/archives/C3E688J8Z/p1522883206000246

**Comment by luizbafilho** [comment]
I see no problems with specifying `--interactions` and `--duration` at the same time. The test will just exit whichever comes first, a valid use case in my opinion.

I also found that the bug reported in slack isn't actually a bug, it just not clear in the documentation [here](https://k6.readme.io/docs/execution-context-variables#section-__vu-and-__iter) when it says:

> Current VU number. The value is assigned incrementally for each new VU instance. One-based.

it is talking about an ID given to a VU to identify it. At least for me and I guess for the one who reported, it looks like a number of current VUs running at the time. Which is not true according to: https://github.com/loadimpact/k6/blob/master/core/local/local.go#L340

**Comment by na--** [comment]
:+1:, agree that there should be no issues with specifying both interactions duration, as long as the behaviour is officially supported and properly documented. Closing this issue since it seems that's covered by https://github.com/loadimpact/k6/issues/551
