### ISSUE TITLE
Allow `login cloud` to set an empty token.

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#575]
At this moment, there is not an option to set an empty cloud token. If the user has previously configured a cloud token, he cannot reset it to upload results as an anonymous user.

To reset my token, I had to modify it manually in the configuration file `~/Library/Application\ Support/LoadImpact/k6/config.json` 

An option like `login cloud --anonymous` or `login cloud --reset` is desired to support this case.

**Comment by na--** [comment]
Hmm, I'm not sure, but I think I've inadvertently partially fixed this with the cloud config refactoring in https://github.com/loadimpact/k6/pull/600.
Right now you could login with a valid token or username and password and then override that by setting an empty token with an environment variable:
```sh
k6 login cloud -t some_valid_token
export K6_CLOUD_TOKEN=""
k6 run -o cloud some_script.js
```
and the results would be uploaded as `anonymous`.

I think it's still worth it to add something like `login cloud --anonymous` or `login cloud --reset`, just for a better user experience, but at least we'll have a workaround when we merge the aggregation changes.
