### ISSUE TITLE
Running example in docker no longer works

### ISSUE THREAD

**Issue by slolife** [loadimpact/k6#579]
Running this:
`docker run -i loadimpact/k6 run -<test.js`

I get this:
`time="2018-04-11T19:43:04Z" level=error msg="script must export a default function"`

And this test.js code looks like this:

    import { http } from "k6/http";
    import { sleep } from "k6";

    export default function() {
      http.get("http://test.loadimpact.com");
      sleep(1);
    };

Notice I am specifying the `-i` parameter mentioned in #444

**Comment by sri85** [comment]
Not sure if its valid , i see that the URL you are loading is not valid `http://test` , is this intended?

**Comment by slolife** [comment]
That could be a valid url, right? Just trying to hit a machine on my network.  But in reality I just put something there to replace the full internal url I was really trying to access.  I'll fix it to look just like the example with http://test.loadimpact.com

**Comment by na--** [comment]
The `import http` statement is wrong, it should be like this:
```js
import http from "k6/http";
import { sleep } from "k6";

export default function() {
  http.get("http://test.loadimpact.com");
  sleep(1);
};
```
Also I got a different error (`TypeError: Cannot read property 'get' of undefined`) when running your code, so maybe also try running `docker pull loadimpact/k6:latest` to get the latest docker image.

**Comment by slolife** [comment]
Thank you @na-- .  That fixed it in the script I posted.
As a side note, your fix did not initially fix it in the console I was running the docker command in. I use [ConEmu ](https://conemu.github.io/) and that still shows `"script must export a default function"` when I run the docker command with the _fixed_ script. I suspect there is something strange that ConEmu does with stdin that is breaking it.
