### ISSUE TITLE
Logging does not respect --no-color

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#580]
Running `k6 run --no-color samples/logging.js` produces this:
![screenshot_2018-04-12_11-19-38](https://user-images.githubusercontent.com/3336773/38664840-69f5dfd2-3e43-11e8-9081-a18731ee5a49.png)

The k6 logo and summary respect `--no-color`, but logging does not. This will cause problems if users want to post-process or parse the output logs, which may be a common debug workflow, since k6 lacks support for directly writing information in files. It will be less of an issue when https://github.com/loadimpact/k6/issues/529 is implemented, but it's still a bug. 

Also, generally the default value of the `no-color` property should probably be dependent on whether the stdout is an interactive terminal or not: https://rosettacode.org/wiki/Check_output_device_is_a_terminal#Go

Edit: [this](https://github.com/loadimpact/k6/blob/50a8f42ab245910bb36a66489d749532a0f16d05/cmd/root.go#L70-L71) seems to be the place where loggers are set up without regard to the `noColor` option

**Comment by luizbafilho** [comment]
closed via #634
