### ISSUE TITLE
Document the k6 REST API

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#589]
We should mention that there's a k6 REST API and how the `pause`, `resume`, etc. commands can be used.

**Comment by luizbafilho** [comment]
Just add some documentation on https://docs.k6.io/v1.0/docs/rest-api, feel free to edit as you wish.

**Comment by na--** [comment]
Expanded the landing page a bit and fixed a few minor typos, but otherwise LGTM, closing the issue for now. Like with everything else, we can probably add more docs when we get out of readme.io...
