### ISSUE TITLE
Add `error` tag when the request IP is blacklisted.

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#597]
When a request is not performed because the IP is blacklisted, it sets the `status` tag to 0.
It's desirable to use the `error` tag to describe a proper error message.

**Comment by THoelzel** [comment]
This looks to have been fixed by https://github.com/loadimpact/k6/pull/907

Currently I'm getting the following tags:
```
"error":"ip is blacklisted"
"error_code":"1110"
```

**Comment by na--** [comment]
You're right, seems like we forgot to close this issue. Thanks!
