### ISSUE TITLE
NTLM with no-connection-reuse

### ISSUE THREAD

**Issue by MarianBusila** [loadimpact/k6#599]
When using NTLM auth with no-connection-reuse, the first request is authenticated and handled ok. The next requests, are created on different TCP connections, but are failing with 401. More details are provided at [https://stackoverflow.com/questions/49866978/ntlm-requests-in-k6](url)

**Comment by luizbafilho** [comment]
thanks, @MarianBusila, you are right. It is supposed to work. I'll take a look what is happening.

**Comment by luizbafilho** [comment]
Hi @MarianBusila I created a PR ( #603 ) with a fix for this. But I would like merge only after you test it, to make sure it is working. 

You can build yourself the binary from the branch `fix/ntlm-no-conn-reuse` or I could do that and give you one. Let me know if you need help.

**Comment by MarianBusila** [comment]
I tested and it is working ok. I could see in wireshark the NTLM requests for each HTTP Request I was doing.

As a side note, I did a test with 120 VUS and I got 2 times more requests when reusing the connection vs no connection reuse, which is what I would expect. But when I tested with 30 VUS I got the same number of requests per second whether I was using or not connection reuse, which I cannot explain. I also expected 2 times more requests when reusing connection.

You can go ahead and merge the PR.
