### ISSUE TITLE
Ability to run multiple Collectors

### ISSUE THREAD

**Issue by jmccann** [loadimpact/k6#620]
I would like the ability to run multiple collectors on a `run`.

From a CLI perspective this could look like some of the following:

* `k6 run --out json=test.json --out influxdb=http://localhost:8086/k6 ...` - which would write a `test.json` report as well as ship logs to an influxdb instance.
* `k6 run --out influxdb=http://localhost:8086/k6 --out influxdb=http://remote.server:8086/k6 ...` - ship logs to two separate influxdb servers

Not sure how this would look from an `K6_OUT` envvar perspective.

This would probably mean a slight breaking change to the config file format to allow passing an array of collectors.

**Comment by na--** [comment]
As I mentioned [in slack](https://k6io.slack.com/archives/C3EDLHPTR/p1525981419000113), I'm not sure if there's an easy and user-friendly way to achieve this flexible configuration with environment variables, probably not. @luizbafilho, @robingustafsson: any ideas?

Regarding the in-script exported `options` and `config.json`, the collector configuration there is [somewhat inconsistent](https://github.com/loadimpact/k6/issues/587) at the moment and we would have done a slightly breaking change there anyways. So having the collectors as an array there wouldn't be a huge problem and we may as well kill 2 birds with one stone with this.

**Comment by luizbafilho** [comment]
I'm not sure if there is a good way to express this, env variables should be as simple as possible. But I'm ok with not having the option of configuring multiples collectors via env variables.

**Comment by na--** [comment]
Yeah, but I'm not sure if even specifying a single collector via environment variables is easily compatible with supporting multiple collectors in the other configuration methods. Also, at the moment you can specify `K6_INFLUXDB_USERNAME` or some other collector option, but in the context of multiple collectors, is specifying that globally a bug or a feature?

**Comment by jmccann** [comment]
Not sure if this can be closed with #624 or if there is more work to be done?

**Comment by na--** [comment]
It can be closed :smile: Thanks! The only remaining work is to update the [release notes](https://github.com/loadimpact/k6/blob/master/release%20notes/upcoming.md) for the next release, but I'll do another PR later today for that.
