### ISSUE TITLE
Unique node Ids or synchronised VU Ids across multiple nodes in Cloud execution mode

### ISSUE THREAD

**Issue by letsrokk** [loadimpact/k6#631]
[Context]

For some test scenarios we need to have an ability to generate unique IDs which we can in HTTP requests - e.g. for client registration APIs

For local executions we are using `__VU` and `__ITER` to generate IDs like `001000004` where `001` is VU number and `000004` is iteration number.

But when tests are executed in Cloud mode in multiple availability zones `__VU` can overlap because VU are individually tracked for each load generator node.

It would be nice to either track VUs across nodes (ideally) or get unique node Id or number so we can generate values like `01001000004` (`${node}${vu}${iter}`)

**Comment by markjmeier** [comment]
@na-- The Load Impact cloud execution variables should solve this: https://support.loadimpact.com/4.0/test-running/cloud-execution/#load-impact-environment-variables specifically LI_INSTANCE_ID.

**Comment by MStoykov** [comment]
I do think that this should be closed given @markjmeier comment ?

**Comment by na--** [comment]
I agree, anything more than that should probably fall under https://github.com/loadimpact/k6/issues/1320
