### ISSUE TITLE
Way to give custom metrics a context

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#65]
I'm missing a way to connect a custom metric to a context, like a group. Could we in some way add a `group` or `context` option like `counter.add(1, { group: "add item to cart" });` alternatively adding a `group` tag automatically to custom metric data points?

**Comment by caalle** [comment]
Not sure this is working as expected. Im running the following test script:

```javascript
import { check, group } from "k6";
import { Trend } from "k6/metrics";

const trend = new Trend("My trend");


export default function() {
  trend.add(1, {outside_group: true});

  group("First group", () => {
    trend.add(2, {outside_group: false});
  });
};
```

And it produces the following output with the JSON collector:

´´´
{"type":"Metric","data":{"type":"gauge","contains":"default","tainted":null,"sample":null},"metric":"vus"}
{"type":"Point","data":{"time":"2017-04-06T12:59:35.478336538+02:00","value":1,"tags":null},"metric":"vus"}
{"type":"Metric","data":{"type":"gauge","contains":"default","tainted":null,"sample":null},"metric":"vus_max"}
{"type":"Point","data":{"time":"2017-04-06T12:59:35.478336538+02:00","value":1,"tags":null},"metric":"vus_max"}
{"type":"Metric","data":{"type":"trend","contains":"default","tainted":null,"sample":null},"metric":"My trend"}
{"type":"Point","data":{"time":"2017-04-06T12:59:35.477964992+02:00","value":1,"tags":{"outside_group":"true"}},"metric":"My trend"}
{"type":"Point","data":{"time":"2017-04-06T12:59:35.478129118+02:00","value":2,"tags":{"outside_group":"false"}},"metric":"My trend"}
{"type":"Metric","data":{"type":"counter","contains":"default","tainted":null,"sample":null},"metric":"iterations"}
{"type":"Point","data":{"time":"2017-04-06T12:59:35.478138733+02:00","value":1,"tags":null},"metric":"iterations"}
´´´

Tags seems to be added as they should, but the Point is missing the `group_id`.

**Comment by liclac** [comment]
I'll hotfix in the current code, js2 will have proper unit test coverage for this

**Comment by liclac** [comment]
Fixed in js2
