### ISSUE TITLE
Ability for HAR convert to filter by substrings from the entire URL

### ISSUE THREAD

**Issue by SaberStrat** [loadimpact/k6#650]
According to the source of convert.go, the HAR converter currently supports the filters `only` and `skip` that only accept a domain string.

It would be cool if the converter could also filter by substrings (maybe regex even) from the entire URL - i.e. parsing the domain, the path and the query. JMeter, for instance, supports this in its Script Recorder.

For example, something like:
`k6 convert --only .*.jsp.* --skip .*ads\..*,.*analysics.js.* myfile.har` with regex or
`k6 convert --only .jsp --skip ads.,analysics.js myfile.har` for substring matches.

**Comment by na--** [comment]
I think having a regex filter would be more useful, even if it's a bit more complex for users.

**Comment by ppcano** [comment]
`k6` deprecated the k6 convert support at https://github.com/loadimpact/k6/issues/1124. We built a [har-to-k6 converter](https://github.com/loadimpact/har-to-k6) to make `k6` independent from this type of logic.


To filter the content of the recorded session, you can use a regex on the Browser Developer Tools to skip domains from the recorded HAR file. 

You can read how to filter domains on the `Remove third-party content` section of the [Session recording guide](https://k6.io/docs/using-k6/session-recording-har-support#modify-the-auto-generated-k6-script). Please, let us know if there is something we should improve.

Closing the issue.

**Comment by MStoykov** [comment]
For the record, we then reverted the deprecation in https://github.com/loadimpact/k6/pull/1268 because har-to-k6 converter still didn't have full feature parity with the current converter, specifically it still doesn't support [creating http.batch requests](https://github.com/loadimpact/har-to-k6/issues/17).

**Comment by na--** [comment]
@ppcano, browsers are not the only tools that generate HAR files, and it's not always easy to filter out domains or URLs. So, I think a feature in the HAR converter to do it would be a good idea, albeit one with a relatively low priority. So, I created https://github.com/loadimpact/har-to-k6/issues/39...

**Comment by timkrins** [comment]
Because HAR files are just JSON, it is fairly easy to create a script to pre-filter the HAR based on regex.
Here is a gist I wrote that I use with Chrome exported HARs.
https://gist.github.com/timkrins/229bb64598797b41beb70f43381ad6de
