### ISSUE TITLE
Results http_req_duration definition

### ISSUE THREAD

**Issue by vkatsikaros** [loadimpact/k6#655]
Hi

I read in https://docs.k6.io/docs/results-output 

> http_req_duration Total time for request, excluding time spent blocked (http_req_blocked), DNS lookup (http_req_looking_up) and TCP connect (http_req_connecting) time.

and in https://docs.k6.io/docs/response-k6http I read

> Response.timings.duration   float    Containing total time (ms) for request, excluding blocked time.

I don't have a specific opinion about whether these 2 definitions should be the same or not. However, I would like to ask, if they should be excluding a different number of times ( block VS block + DNS lookup + TCP connect).

If they are _not_ supposed to be different this is a documentation bug. If they are supposed to be different, maybe a note could be added to avoid confusion and/or reason for the decision.

**Comment by na--** [comment]
Thanks for reporting this! The values are the same and the `http_req_duration` description is the correct one, so I'll fix the docs. It may be even clearer to specify that in both cases `duration` is simply the sum of `sending` + `waiting` + `receiving`. It's simply a shorthand for "once connected, how long did the remote server take to process and respond to my request".

**Comment by na--** [comment]
Updated the documentation in both places, thanks again @vkatsikaros for reporting the discrepancy.
