### ISSUE TITLE
Issues with k6 when using different precision on InfluxDB

### ISSUE THREAD

**Issue by gboston** [loadimpact/k6#668]
We're experiencing issues when we set the precision of InfluxDB to milliseconds or seconds. This is done with env. variables:
      - INFLUXDB_PRECISION=ms
      - INFLUXDB_UDP_PRECISION=ms

``
time="2018-06-07T12:40:00Z" level=error msg="InfluxDB: Couldn't write stats" error="{\"error\":\"Request Entity Too Large\"}\n
``

Seems like k6 is trying to send objects that are too large to process? Can we adjust this is in any way?

**Comment by na--** [comment]
We use the [official Go library](https://github.com/influxdata/influxdb/tree/master/client/v2) to connect to influxdb, so I'm quite surprised by this error. In any case, you can try increasing the influxdb `max-body-size` like this: https://github.com/influxdata/docs.influxdata.com/blob/master/content/influxdb/v1.5/administration/config.md#max-body-size--25000000

**Comment by na--** [comment]
I assume that increasing the body sized worked, so I'll close this issue for now, feel free to reopen if not.

**Comment by SebastianStehle** [comment]
I got the same issue with the default precision, perhaps this should be changed in the official docker-compose file?

**Comment by adoublef** [comment]
I am currently getting this same error, using the default settings found with the compose file. I am seeing if there may be a workaround

**Comment by adoublef** [comment]
Seems the adjustments that look to have resulted in a new warning `WARN[0019] The flush operation took higher than the expected set push interval. If you see this message multiple times then the setup or configuration need to be adjusted to achieve a sustainable rate.  output=InfluxDBv1 t=2.835083585s`.

```
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_MAX_BODY_SIZE=0
```

some progress but unsure how much an issue that warning will be, should I be using xk6 with influxdbv2 instead?
