### ISSUE TITLE
Debug `setup/teardown` functions for cloud execution

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#670]
I have been using the `setup/teardown` function in cloud execution and I could not find a way to debug these functions.

When running locally `k6 run`, the console output shows the `console.log` statements, but this is not working when using `k6 cloud`.

We discussed in Slack that a possible solution could be to report [custom metrics](https://docs.k6.io/docs/result-metrics#section-custom-metrics) in the `setup/teardown` functions.

**Comment by na--** [comment]
This was closed by https://github.com/loadimpact/k6/pull/678
