### ISSUE TITLE
In Summary the checkNames and groupNames are being sorted, so cli-summary is not same as execution order

### ISSUE THREAD

**Issue by mohanprasaths** [loadimpact/k6#673]
On executing a testcase.js using k6 with multiple groups and numerous checks inside them , it executes in proper order but before printing in summary (CLI) , they are being sorted . So the summary test cases output order is not in execution order

Steps to reproduce
1.) Wirte a test case ```test.js``` file with multiple groups and checks
2.) Execute it using K6 and compare order of execution and summary

eg: 
```
export default function () {
	// VU cookie jar
	group("c", function () {
		var res = {
			"a": 1
		}
		check(res, {
			"check a": (r) => true
		})
		group("a", function () {
			var res = {
				"a": 1
			}
			check(res, {
				"check a": (r) => true
			})
		});
		group("f", function () {
			var res = {
				"a": 1
			}
			check(res, {
				"check a": (r) => true
			})
		});
		group("e", function () {
			var res = {
				"a": 1
			}
			check(res, {
				"check a": (r) => true
			})
		});
		group("b", function () {
			var res = {
				"a": 1
			}
			check(res, {
				"check a": (r) => true
			})
		});
	});

	group("d", function () {
		var res = {
			"a": 1
		}
		check(res, {
			"check a": (r) => true
		})
	});

	group("a", function () {
		var res = {
			"a": 1
		}
		check(res, {
			"check a": (r) => true
		})
	});


}

```

On executing this file , the summary in output should be same as the execution order but the names are being sorted 
![summaryoutput](https://user-images.githubusercontent.com/12637959/41388952-ec20fbb0-6fab-11e8-964b-b105fbe7885a.PNG)

**Comment by na--** [comment]
Closed by https://github.com/loadimpact/k6/pull/674
