### ISSUE TITLE
Easier access to cookies

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#68]
When trying to create a simple script to test the cookie support I realized that setting cookies is a header manipulation affair right now. I think we should create a simpler way to access cookies from HTTP responses and specify them on HTTP requests (when one opts for manual cookie handling).

Maybe something akin to how the Python requests library does it, see http://docs.python-requests.org/en/master/user/quickstart/#cookies. Exposing the response cookies using `response.cookies` and exposing a simple `http.get("...", null, { "cookies": {"my_cookie": ["value1", "value2"]} })` as well as the full cookie jar kind of API:

```js
let jar = new CookieJar();
jar.set('tasty_cookie', 'yum', domain='httpbin.org', path='/cookies')
http.get("...", null, { "cookies": jar })
```

Note that it's allowed for multiple cookies with the same name (hence why the "my_cookie" value is a list), see https://tools.ietf.org/html/rfc6265#section-4.2.2. Maybe that use case should be deferred to header manipulation though since I think we can pretty safely classify it as uncommon.

**Comment by ragnarlonn** [comment]
@liclac @robingustafsson Putting out a bounty on this one. 

Bountyhunters: We want an implementation similar to the one Robin started on in https://github.com/loadimpact/k6/pull/173 but have since then switched to a new JavaScript runner and we want this solution to be based on that (i.e. based on current master branch).

**Comment by robingustafsson** [comment]
To clarify one thing: the API design in https://github.com/loadimpact/k6/pull/173 is not ideal in terms of how the `CookieJar` works.

The JS API makes it seem as if it is possible to have several separate cookie jars that can be set and used per request. This is not true. In Go land there's just one CookieJar (per VU) shared between all requests in a VU iteration.

This should be updated and reflected in the JS API. I'm thinking we should change the API to look as follows:

```js
let jar = http.getCookieJar();
jar.set("name", "value", { domain: "example.org", path: "/a-path" });
```

and on the request level, there's no need anymore to pass in the jar (it's there in the background and interacted with through the get-singleton function above). You could still pass in a JS object with "simple" cookies that will be added to the VU cookie jar:

```js
let cookies = {
    name: "value1",
    name2: "value2"
};
let res = http.get("http://httpbin.org/cookies", { cookies: cookies });
```

**Comment by liclac** [comment]
Wouldn't it make more sense to have a `res.cookies()` function on responses + the suggested `http.get(url, { cookies: … })` function?

Having `http.setCookie()` and friends would work too (and we could have them too if there's a case for it?), but while this will be global state manipulations either way (the manipulating the state of the VU's HTTP client), the request/response association is a lot cleaner.

**Comment by robingustafsson** [comment]
@liclac Yes, I agree that `res.cookies` should still be there together with `http.get(url, { cookies: … })` (as they were in the PR). My comment was more concerning the CookieJar part of the proposed API in the PR, which turned out bad.

I see `http.getCookieJar()` as an advanced use case, when you need to set cookie parameters beyond key and value or when you want to set cookies in one go rather than per request.

**Comment by zoek1** [comment]
I'm working on this but i don't have clear if will be permitted set the cookie jar directly.

```
let a_name = {
    value: "a",
    domain: "example.org", 
    path: "/a-path"
}

let b_name = {
    value: "b",
    domain: "example.org", 
    path: "/b-path"
}

http.setCookieJar({a_name, b_name})
```

or just the cookies

```
http.setCookieJar({a_name: "a", b_name: "b"})
```

**Comment by edgardoalz** [comment]
@zoek1 Are you still working on this? I'd like to do it

**Comment by zoek1** [comment]
@edgardoalz currently not, my implementation is incomplete, please go ahead.

**Comment by robingustafsson** [comment]
@zoek1 Still working on this?

**Comment by robingustafsson** [comment]
@edgardoalz Interested in taking this on?

**Comment by asifmallik** [comment]
@robingustafsson is this complete?

**Comment by robingustafsson** [comment]
@asifmallik Yes, this was implemented in https://github.com/loadimpact/k6/pull/323. Forgot to close the issue :)

**Comment by asifmallik** [comment]
@robingustafsson  there's a 100 USD bounty on bountysource, you might want to claim that

**Comment by robingustafsson** [comment]
@asifmallik I work for Load Impact, and I'm the one that put up that bounty :) Will put the bounty money towards some other k6 issue instead.
