### ISSUE TITLE
Option to set vertical axis maximum for Insights comparison charts

### ISSUE THREAD

**Issue by SteveLeach-Keytree** [loadimpact/k6#686]
At the moment the Insights comparison chart automatically calculates the Y axis scale and maximum value, based on the data points in the series.

This is often fine, but can make visual comparisons difficult: comparing two response time metrics in the same load test, or comparing the same metric across different load tests.

It would be very handy to have the ability to override the Y-axis maximum for each chart in the Breakdown Tree Analysis Comparison chart.

**Comment by na--** [comment]
Thank you for the feedback! I've copied it [here](https://loadimpact.ideas.aha.io/ideas/LI-I-30) and I'll close this issue, since the [Load Impact Product ideas](https://loadimpact.ideas.aha.io/) page is a much better fit than the k6 github page for Insights-related feedback.
