### ISSUE TITLE
Add CONTRIBUTING.md with guidelines for contributors

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#70]
Stuff to answer:
- What is the process to contribute code? Fork, make changes and PR against what branch? 
- Do we have special purpose branches, do we follow a specific branching standard?
- What about small typos and doc changes? Push directly to `develop` if one has commit access?
- Do we require test cases?
- Should AUTHORS or some other file be updated as part of contribution?
- Make it clear what license you contribute under
etc.

**Comment by uppfinnarn** [comment]
See: #116
