### ISSUE TITLE
Better error messages for setup and teardown timeouts

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#702]
Currently when the `setup()` or `teardown()` function times out, users see a very uninformative error message, something like:
```
ERRO[0010] Engine error                                  error="setup: context cancelled at setup (script.js:11:224(6))"
```

We should explicitly state that this error is because of a timeout and we should probably mention the `setupTimeout` or `teardownTimeout` option that would allow users to increase the allowed execution time for the particular function that timed out.

**Comment by MStoykov** [comment]
is a1df7bf91666c9fe367ba9932be37158f39de684 enough? or do you want to change the messages as well ?

**Comment by na--** [comment]
It's definitely much better than before! Though there are still some issues... Here's what I currently see when there's a timeout during `setup()`:
```
ERRO[0010] Setup timeout                                 error="setup: Timeout during setup"
ERRO[0010] Setup timeout
```

It's... both bit much and not enough at the same time :smile: We say setup timeout 3 times for some reason, and even though that's much better than the previous`setup: context cancelled at setup`, here's what I would improve with the above picture:
- Don't repeat the same thing 3 times :grin: I hadn't noticed those `log.WithError(err).Error(basicallySameErr)` statements in the error handling code before...
- The message `setup: Timeout during setup` could be rephrased as `Timeout during setup() execution`
- Even better, `setup() execution timed out after X seconds`

Here's a proposal how the above scenario could look like:
```
ERRO[0010] setup() execution timed out after 10 seconds         hint="You can increase the time limit via the setupTimeout option"
```

**Comment by na--** [comment]
Hmm not sure this is fully fixed. k6 v0.25.1 produced this output:
```
ERRO[0002] Setup timeout                                 error="setup: Timeout during setup"
ERRO[0002] Setup timeout   
```

the latest k6 `master` again produced 2 separate error messages for the same timeout, though I admit the first message is much, much better :heart: :
```
ERRO[0002] setup: setup execution timed out after 2 seconds  hint="You can increase the time limit via the setupTimeout option"
ERRO[0002] Setup timeout
```

**Comment by cuonglm** [comment]
@na-- We can't prevent the second `Setup timeout`, it' from https://github.com/loadimpact/k6/blob/19c6796b3f4f9d7d96a3c7ef88ee7b651eba3bb3/cmd/run.go#L412

**Comment by na--** [comment]
You should have linked the broader context, since I'm not sure there isn't any room for improvement in this code :smile: https://github.com/loadimpact/k6/blob/19c6796b3f4f9d7d96a3c7ef88ee7b651eba3bb3/cmd/run.go#L408-L422**

**Comment by na--** [comment]
Maybe we should extend the `ExitCode` struct so that when k6 aborts with an `ExitCode`, it can also give hints? Not sure if that's the best way to handle this, but for sure we should be able to have something better and fully solve this (and other similar issue), even though this isn't a `high prio` issue...

**Comment by na--** [comment]
I've set `lower prio` and `refactoring` labels here, since even though we can slightly improve the code and UX here, the current state is more than good enough for now, given what we started with. We can come back and fix the remaining details at some future point, even after 0.26.0.
