### ISSUE TITLE
Access to group hierarchy information in output plugins

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#71]
Output plugins should get access to group hierarchy information such as group names and group parent IDs.

**Comment by caalle** [comment]
The group information for checks and metrics are available as `path` in the tags in the JSON-output. The hierarchy looks something like `::Group name 1::Group name 2::Group name 3`, which represents:

```
Group name 1
    Group name 2
        Group name 3
```

**Comment by uppfinnarn** [comment]
It's now `group` on both checks and HTTP requests, with checks now having both `group` (`::group1::group2`) and `name` (`mycheck`).
