### ISSUE TITLE
The docker-compose can't build the grafana image

### ISSUE THREAD

**Issue by piotrkedzia** [loadimpact/k6#717]
It's not possible to build the grafana image.

Steps to reproduce:
1) `git clone 'https://github.com/loadimpact/k6'`
2) `cd k6`
3) `git submodule update --init`
4) `docker-compose up -d influxdb grafana`

Grafana image won't be built
Output:
```
Building grafana
Step 1/6 : FROM grafana/grafana
 ---> 1bfead9ff707
Step 2/6 : RUN apt-get update && apt-get -y install curl
 ---> Running in 3e89ad9d7a9c
Reading package lists...
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
ERROR: Service 'grafana' failed to build: The command '/bin/sh -c apt-get update && apt-get -y install curl' returned a non-zero code: 100
```

Hint: The build will pass when we change the `Dockerfile.grafana` to use basic grafana/grafana image < v5.1.0
https://github.com/loadimpact/k6/blob/master/Dockerfile.grafana#L1
e.g. `FROM grafana/grafana:5.0.4`

It looks like there were major changes in grafana docker image v5.1.0 which prevents the build process to finish.

**Comment by mariolopjr** [comment]
Hi @piotrkedzia,

Another way to keep the image version the same, is to do the following:

Under the FROM grafana/grafana line, before the RUN apt-get line in the Dockerfile.grafana, add the following: ```USER root```

I think in the latest images for grafana, they are using a new grafana user which breaks this build. Do NOT switch back to ```USER grafana``` later on in the Dockerfile, it will not work and break the linking between grafana and indexdb.

Entire Dockerfile below:
```Dockerfile
FROM grafana/grafana
USER root
RUN apt-get update && apt-get -y install curl

# Change the default data directory (otherwise grafana.db won't persist)
RUN mkdir /var/lib/grafanadb
ENV GF_PATHS_DATA /var/lib/grafanadb

# Init Grafana sqlite db and preconfigure our data source to be our influxdb k6 db
RUN bash -c '/run.sh & sleep 15 && curl -s -H "Content-Type: application/json" -X POST \
    --data '"'"'{"name": "myinfluxdb", "type": "influxdb", "access": "proxy", "url": "http://influxdb:8086", "database": "k6", "isDefault": true}'"'"' \
    http://admin:admin@localhost:3000/api/datasources \
    && kill -SIGINT %%'


CMD ["/run.sh"]
```

***NOTE***: There _may_ be security implications with this change, I really don't know. Use at your own risk. 😈

**Comment by piotrkedzia** [comment]
Hi @mariolopjr,
thx for info :)

**Comment by na--** [comment]
Closed by https://github.com/loadimpact/k6/pull/783
