### ISSUE TITLE
Add possibility to batch HTTP requests in JS API

### ISSUE THREAD

**Issue by robingustafsson** [loadimpact/k6#72]
In an earlier life k6, at that time known as speedboat, used to support batching of HTTP requests [1] [2].

Something along the lines of:

```js
let responses = http.batch([
    "http://example.com/",
    {
        "method": "GET",
        "url": "http://example.com/search",
        "params": { "q": "what's the meaning of life?" }
    }
])
```

Can we have that back plz?

[1] - https://github.com/loadimpact/k6/commit/c4238a1ccb892ce3dde3afbc2230f831093e1e9a
[2] - https://github.com/loadimpact/k6/commit/74f22e82ee77c433f5d0fda0e6054e3dc2c50d4f

**Comment by ragnarlonn** [comment]
So, this issue is not closed because there is currently no way to limit the concurrency when using http.batch() ?    Should we close this and create a new issue about implementing "max connections and max connections per host for http.batch()" ?

**Comment by uppfinnarn** [comment]
I actually forgot to close it, but that's a good point. We should limit the concurrency to something configurable; I'm not against this being a commandline flag, as the corresponding browser behavior is already out of the script's hands. Do we want to do it per-host or globally though?

**Comment by ragnarlonn** [comment]
We currently have both a global limit and a per-host limit and that has been modeled on how the browsers work, so I think it is reasonable for k6 to have both too. See http://www.browserscope.org/?category=network&v=top
