### ISSUE TITLE
K6 and IP spoofing

### ISSUE THREAD

**Issue by ofauchon** [loadimpact/k6#721]
Hi, 

Anyone thought about IP spoofing in k6 ?

Basic idea would be to pass an IP subnet/range at runtime, and allow each k6 virtual user to pick an IP
within the range (forever or per iteration) 

At the condition golang network stack can deal with IP spoofing. 

Any idea about the implementation welcome.

Olivier

**Comment by na--** [comment]
This is somewhat related to https://github.com/loadimpact/k6/issues/476

**Comment by na--** [comment]
I think this was finally resolved by https://github.com/loadimpact/k6/pull/1682, and "VUs picking their IP per iteration" is covered under https://github.com/loadimpact/k6/issues/1724
