### ISSUE TITLE
In summary show the failed cases in a block with groupID (useful while loadtesting)

### ISSUE THREAD

**Issue by openmohan** [loadimpact/k6#724]
When load testing(multiple iterations), user have to check summary to find all the failed test cases. I would be nice to have a section to display all errors encountered while executing test cases.

**Comment by na--** [comment]
I don't completely understand the requirements here, but the new `handleSummary()` function [introduced in the recently released k6 v0.30.0](https://github.com/loadimpact/k6/blob/master/release%20notes/v0.30.0.md#support-a-handlesummary-callback-at-the-end-of-the-test-1768) (https://github.com/loadimpact/k6/pull/1768) should allow great flexibility in formatting the k6 results however you like. If that's not sufficient, please open a new issue describing your use case and requirements in more details.
