### ISSUE TITLE
Extra semicolon in user agent string

### ISSUE THREAD

**Issue by chipironcin** [loadimpact/k6#727]
While executing the K6 tool version `k6 v0.22.0`
Executing the K6 tool version `k6 v0.22.0` against a .NET service listening to HTTP requests I always get 500 Internal Server Error.

Server logs are a bit more specific:
```
System.FormatException: The format of value '(https://k6.io/);' is invalid.
```
https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Net.Http/src/System/Net/Http/Headers/ProductInfoHeaderParser.cs

The default user agent this version of K6 (and master branch) is using is `k6/0.22.0 (https://k6.io/);` and seems that the semicolon is causing .NET to throw a parsing exception. 
https://github.com/loadimpact/k6/blob/dff69657733bfff8d1b8db68bbd4b91d5d35bd70/cmd/options.go#L58

Removing the semicolon fixes the issue. Moving the semicolon to inside the parenthesis also fixes the issue.

After reading the RFC for User Agent String formatting (https://tools.ietf.org/html/rfc2616#page-145 and https://tools.ietf.org/html/rfc2616#section-3.8), it is not clear whether the comment part of the string should be enclosed in parenthesis or not.

Using the offending user agent against other HTTP servers return no errors.

Suggestion to update the default user agent from `k6/0.22.0 (https://k6.io/);` to `k6/0.22.0 (https://k6.io/)`.

**Comment by na--** [comment]
Thanks for reporting this. It is easy enough to fix, though I find it very strange that an http server throws an exception just because it can't parse such an unimportant header like `user-agent`... You can always overwrite the default user agent with the `--user-agent` CLI flag, but I see no reason not to remove the semicolon at the end, so I'll fix it in a bit.

**Comment by chipironcin** [comment]
Thanks for the quick fix @na-- !
I was using a custom user agent string in the meanwhile. It is great the tool supports that option 👏🏼

Yes, this is the only server I have seen rejecting to answer because it can't parse the user agent string, but the code is there to prove it.

In any case, I was unable to spot any user agent that uses semicolons outside the comment section so it makes sense to comply with what seems to be the standard 😛 

Cheers!
