### ISSUE TITLE
Stabilize latest docker image

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#740]
Currently the `latest` docker tag is built from the latest git commit in `master`, which may introduce some bugs like [this](https://github.com/loadimpact/k6/pull/739)... It would probably be better if the `latest` docker tag is just an alias to the latest stable k6 release tag, like most other docker images. We can add another docker tag `master` or `unstable` or something that tracks the latest git `master`.

**Comment by MStoykov** [comment]
fixed in 19901f0d5e4b8b7ef2d1c780f393038844aaaed9
