### ISSUE TITLE
K6 test runs twice when using ramp parameters through command line

### ISSUE THREAD

**Issue by peNC** [loadimpact/k6#758]
Hey everyone,

As the title states, I'm running into an issue where my test will run twice when I pass in the ramping parameters in command line:

`k6 run --stage 1m:1,1m:2,1m:3,1m:4,1m:5,5m:5,2m:0 k6_NewUser.js`

Is anyone else running into this issue? 
I've copied the command from [https://docs.k6.io/docs/options](https://docs.k6.io/docs/options)
Using version v0.22.1

Thank you in advance!

**Comment by na--** [comment]
Thanks @peNC for reporting this bug, it was due to an unfortunate regression we'd made when fixing a [corner-case](https://github.com/loadimpact/k6/issues/547) in the handled JS stages a while ago...

**Comment by peNC** [comment]
Hey @na-- is there an ETA of when a new version of k6 with this bug fix will be released?
Thanks!

**Comment by na--** [comment]
Hi @peNC, I can only give you a rough estimate, but this fix should be officially released as part of k6 1.0, hopefully sometime in the next several weeks. You can use it earlier than that if you use the `latest` k6 docker image (docs [here](https://github.com/loadimpact/k6#running-k6) and [here](https://docs.k6.io/docs/running-k6)) or if you build k6 from source yourself (it's pretty easy, info [here](https://github.com/loadimpact/k6#build-from-source)).

Also, as you might have seen in the linked issue above, yesterday I found another (much smaller) problem with the handling of `stages`, that we'll also soon fix before 1.0: https://github.com/loadimpact/k6/issues/775
