### ISSUE TITLE
Rare inconsistency in /v1/groups

### ISSUE THREAD

**Issue by liclac** [loadimpact/k6#76]
Now and then, the tests for `/v1/groups` will fail with the result:

```
--- FAIL: TestGetGroups (0.00s)
    --- FAIL: TestGetGroups/list (0.00s)
        --- FAIL: TestGetGroups/list/groups (0.00s)
	Error Trace:	group_routes_test.go:83
	Error:      	"[]" should have 1 item(s), but has 0
	Error Trace:	group_routes_test.go:84
	Error:      	"[]" does not contain "%!!(MISSING)s(int64=1)"
```

No race conditions, at least according to `go test -race`. I'm completely at a loss as to what is going on here.

**Comment by ragnarlonn** [comment]
@uppfinnarn I have only seen this happen in CI test runs. Have you seen it when running tests locally?

**Comment by liclac** [comment]
Doesn't seem to happen anymore.
