### ISSUE TITLE
Better error message for JSON decoding errors

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#773]
This script:
```js
import http from "k6/http";

export default function () {
    let respJSON = http.get("https://test.loadimpact.com/").json();
}
```
will currently fail with a very uninformative error like this:
```
ERRO[0001] GoError: invalid character '<' looking for beginning of value
	at native
	at /path/to/script.js:4:38(8)
```

It's especially challenging to understand what the issue is when the `.json()` call is nested deep in a `check()` somewhere, as was the case in https://github.com/loadimpact/k6/issues/772

**Comment by MStoykov** [comment]
fixed by #905
