### ISSUE TITLE
Internal k6 objects aren't properly encoded to JSON

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#803]
Most of the internal Go objects that are passed to the script like `http.Response` aren't marshalled to JSON properly, the Go `struct`s simply [lack the appropriate `js` tags](https://github.com/loadimpact/k6/blob/bb6e97542c63b1282126c650f6b757c5ecf9d2b1/js/modules/k6/http/response.go#L52-L65). This is especially problematic when they are returned as part of a `setup()` result, since it is passed through JSON before the VUs and `teardown()` receive it. I've briefly mentioned about this in the comments of https://github.com/loadimpact/k6/issues/558 and https://github.com/loadimpact/k6/issues/693, but since they've been mostly closed by https://github.com/loadimpact/k6/pull/799, I'm creating this separate issue just for this bug.

To demonstrate, this script:

```js
import http from "k6/http";

export function setup() {
   return http.get("https://test.loadimpact.com");
}

export default function (data) {
   let resp = http.get("https://test.loadimpact.com");

   console.log(Object.keys(data))
   console.log(Object.keys(resp))
}
```

will output something like this:

```
INFO[0002] Headers,OCSP,Body,TLSVersion,Request,RemoteIP,RemotePort,TLSCipherSuite,Error,Proto,Cookies,Timings,URL,Status 
INFO[0002] remote_ip,remote_port,url,status,proto,headers,cookies,body,timings,tls_version,tls_cipher_suite,ocsp,error,request,clickLink,html,json,submitForm
```

**Comment by MStoykov** [comment]
fixed by #804
