### ISSUE TITLE
No Such Host

### ISSUE THREAD

**Issue by pawansinha0612** [loadimpact/k6#809]
WARN[0002] Request Failed                                error="Get https://onlineappspnv.dev.anz/cola/assets/anz-icons.baadb1e5.woff: lookup onlineappspnv.dev.anz: no such host"

I have only done launch transaction of my application, I am trying to run and getting above error.

**Comment by na--** [comment]
I don't think this is a k6 issue, that domain either doesn't exist or isn't public. Running `host onlineappspnv.dev.anz` gives me `Host onlineappspnv.dev.anz not found: 2(SERVFAIL)` and `curl` also fails.

If you want, you can use the `hosts` [option](https://docs.k6.io/docs/options) in k6 to manually provide an IP address for that domain. Closing this issue for now, but feel free to reopen or comment if you think that this is actually a bug in k6.
