### ISSUE TITLE
Using core nodejs libraries

### ISSUE THREAD

**Issue by Stono** [loadimpact/k6#830]
Hey folks,
I need to shell out in the setup and teardown to execute some commands to prep the environment for the tests.

I was wanting to do that in the setup() function (with `const { spawnSync } = require('child_process');`); however I get the following error:

```
ERRO[0000] GoError: The file "child_process" couldn't be found on local disk, and trying to retrieve it from https://child_process failed as well. Make sure that you've specified the right path to the file. If you're running k6 using the Docker image make sure you have mounted the local directory (-v /local/path/:/inside/docker/path) containing your script and modules so that they're accessible by k6 from inside of the container, see https://docs.k6.io/v1.0/docs/modules#section-using-local-modules-with-docker.
```

I'm running this with the brew installed version on macosx.

Is what I'm trying to do even possible?

**Comment by MStoykov** [comment]
k6 is not nodejs compliant - that will be very difficult and mostly out of the scope of the project. 
While some things are possible, k6 is designed to be called in distributed manner and as such running any shell command you can think of is generally not a good idea.

I would recommend going to the k6 [slack channel](https://k6io.slack.com/messages) and asking in the #support channel with some explanation about what you want to do - maybe it is possible without spawning shell scripts.

I'm closing this as supporting all core nodejs libraries or specifically child_process is out of the scope of k6.
