### ISSUE TITLE
Make http.request less confusing

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#832]
Currently calling http.request(or http.pull ...) so on take at least the method a url and than body and params where neither is required. The way it's implemented though makes it possible to actually call it with more arguments like
```
http.request("GET", "http://example.com", null, {headers: ...}, {tags: ....})
```

This does not give error but will not actually look at the tags which makes it strange.

Ideally we would like this syntax to mean that both headers and tags are params, but this will require a lot reworking of the code. Alternatively we should give error that too many the function was called with too many parameters.

**Comment by na--** [comment]
I honestly don't think we should support that, and even emitting an error would be strange in the JavaScript world, and probably the dynamic language world in general. If I have this pretty simple JS code:
```js
function f(p1,p2) {
  console.log(p1, p2);
}
f(1,2,3);
```
No JS interpreter will actually have a problem with that code, they'll just happily print `1 2` and ignore the third argument. Returning an error in k6 in a similar situation will be very unusual...
