### ISSUE TITLE
certificate is not valid or is not yet valid

### ISSUE THREAD

**Issue by mohanrajramalingam** [loadimpact/k6#836]
Hello Team,
I am trying to do my load testing on my microservices using K6.

I wrote a helloworld code to test it, but im getting the below error.

> WARN[0001] Request Failed                                error="Get https://url/test1/test2/: x509: certificate has expired or is not yet valid"
> ERRO[0001] ReferenceError: k6 is not defined
>         at C:\path\script.js:7:2(9)

Below is my code snippet
```js
import http from "k6/http";

export default function() {
        let response = http.get("https://url/test1/test2");
	k6.post("https://url/test1/test2", {
		"username":"user",
		"password":"pass",
		"client_id":"client",
		"client_secret":"secret",
		"scope":"abc"
	});
};
```

----------------------------------------------------------------------------------------------------------------
I am sure this is because it doesn't have the cert file imported and its https not http. Is there any forum or place where i can find code or example for these kind of requests.

Thanks in advance.

**Comment by MStoykov** [comment]
You can try using `k6 run --insecure-skip-tls-verify path/to/script.js`. This will skip testing your certificates. Also you should use `http.post` not `k6.post`. 

It's better if you ask questions like that in our [slack](https://join.slack.com/t/k6io/shared_invite/enQtNDYwNDQyMjU1MDc2LTEwN2JhYmRhYzU1ZTVlYTI0NzZhZTRiZjQxZmY0ZTIzMzQxNjA0ZjcyOWIwY2NkMmZlMWE1ZmJjZDA3NjY0MDA) for example in the support channel. You can also take a look at [documentation](https://docs.k6.io/docs)
