### ISSUE TITLE
getting sessionid from http request and share same session

### ISSUE THREAD

**Issue by klase1337** [loadimpact/k6#839]
Is there any way to keep http request in same session, and getting sessinid from cookie?

I can do that in python request module, but I can't find any information on k6 doc site.

**Comment by na--** [comment]
Not sure I fully understand your questions, but I think the answer is yes. Take a look at these docs pages:
- https://docs.k6.io/docs/k6http
- https://docs.k6.io/docs/cookies
- https://docs.k6.io/docs/params-k6http
- https://docs.k6.io/docs/response-k6http

In any case, github issues aren't the best place for these types of questions, so I'm closing this issue. As [mentioned in the README](https://github.com/loadimpact/k6#need-help-or-want-to-contribute), StackOverflow or the k6 Slack chat are much more appropriate, so if you have any other questions, please post them there.
