### ISSUE TITLE
Error with the command docker-compose up -d influxdb grafana

### ISSUE THREAD

**Issue by Julianhm9612** [loadimpact/k6#850]
![image](https://user-images.githubusercontent.com/24255842/48959033-c527f900-ef30-11e8-9760-83e5fdd88fa6.png)

O.S Windows 10

**Comment by Julianhm9612** [comment]
Sure!

I'm following the documentation for visulalizate the results with **InfluxDB + Grafana**

![image](https://user-images.githubusercontent.com/24255842/49252876-2e0ce680-f3f3-11e8-8b65-a9aaeb0752bb.png)

When I execute the following command: **docker-compose up -d influxdb grafana**

It generates an error when executing this command that is in the file Dockerfile.grafana.

**My temporary solution was:**

 I commented the following lines:

![image](https://user-images.githubusercontent.com/24255842/49253250-2bf75780-f3f4-11e8-98e6-6a490d6a8e79.png)

After I execute the following command: **docker-compose up -d influxdb**

And then through postman the following:

![image](https://user-images.githubusercontent.com/24255842/49253364-7d9fe200-f3f4-11e8-9587-cdc0ef6def23.png)

And finally i run again: **docker-compose up -d influxdb grafana**

And it worked!

**Comment by na--** [comment]
Very strange :confused: So you're basically doing the same `curl` request from the Dockerfile, only with postman instead, and it's working?
Maybe that `sleep 15` there is insufficient? Can you try increasing it to 30 or even 60 seconds, just to see if that fixes the issue?

**Comment by Julianhm9612** [comment]
@na-- Thank you very much for your excellent support!!!!!!

you are right, the time was insufficient, I increased it to 60 to test and it worked:

![image](https://user-images.githubusercontent.com/24255842/49828737-9bf1d000-fd5a-11e8-9130-a060b6377d75.png)
