### ISSUE TITLE
Time metric inconsistencies

### ISSUE THREAD

**Issue by caalle** [loadimpact/k6#87]
I'm creating my own metric to track login request durations.

When setting up the `Trend` I'm using `isTime=true` to get the data points marked as times(and they will be treated as microseconds?).

Eg.

`const loginDuration = new Trend('login_duration, true);`

When copying a `response.timing.duration` from a request response the values are returned as `ms` which prevents me from just copying the values before insert.

Working around in by doing something like:

```
const response = http.post(/*login url with params*/);
loginDuration.add(response.timings.duration * 1000);
```

Any thoughts on this?

**Comment by ragnarlonn** [comment]
To me, it feels somewhat crippling to not be able to make an HTTP request and then access detailed response metrics from that particular request. It is a basic building block that allows people to shoot themselves in the foot but also provides a ton of flexibility. Does it really matter if people CAN shoot themselves in the foot, if we promote "best practise" methods that are safe?  What if a POST is made to the same URL twice, with different POST data, and the user wants to compare the response times for POST #1 and POST #2. Tagging with URL is not going to help there. I am sure there are tons of use cases we haven't thought about that we effectively prevent by assuming too much about how people are going to use the tool.

As for timings, I personally like milliseconds expressed as floats, or microseconds as integers. I think nanoseconds is ridiculous to use in our use case. But we should go with whatever people are used to, of course. Whatever is most idiomatic.

**Comment by caalle** [comment]
1. I guess this is a question for the more experienced load testers :)
2. The resolution of a Date object in Javascript goes down to milliseconds. Not sure if anything more granular than that is supported, except for `Performance.now()` which gives you microseconds from page load(or something like that).

**Comment by micsjo** [comment]
I have to weigh in here - not being able to access the metrics is simply
bad. People will shoot themselves not only in their feet but also do it
repeatedly. Remember - it's people and we make mistakes. Providing good
best practice is important and will cover the important basics.

And as far as use cases go, here's another one. Really big tests for
several 100' vu will not want more than just a few simple metric samples.
That you would control in script and then need metric access.

/Michael



Den 26 jan. 2017 9:55 fm skrev "ragnarlonn" <notifications@github.com>:

**Comment by ragnarlonn** [comment]
Milliseconds is OK, but not great, IMHO. Many existing tools support 1ms resolution only. I just think that a *performance* testing tool released today should have a little more precision than that. Measuring response times of e.g. HTTP transactions between microservices running in the same environment and getting very low network response times can mean that a highest resolution of 1ms leaves out important information.

**Comment by caalle** [comment]
I don't think the resolution of Date objects in javascript matters though. The metrics will never be converted or displayed as dates.

As long as it's clear what is being stored and what is being returned when I access it I don't see any issues with using eg microseconds.

**Comment by aidylewis** [comment]
Most load testers will deal in milliseconds and that's what our aspirational perf requirements are dealt in, but I also understand the need for microseconds for applications in the same sub network as the load generator for example. I'd side towards milliseconds though and use a switch (config) for more granularity.

**Comment by uppfinnarn** [comment]
What about milliseconds as floats with nanosecond precision? (or, as close approximation as a `float64` gets you, usual floating point imprecision disclaimer applies)

I'd actually be for changing everything to that (including emitted metrics to InfluxDB, et.al.), if we can keep the format consistent I can avoid some needless float multiplications and give API users something actually human-readable.

**Comment by adr0sen** [comment]
@uppfinnarn - ms as floats with ns precision sounds reasonable to me. And 👍 for consistent metric precision across the board!
