### ISSUE TITLE
Push functest capability more in README and project desc?

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#88]
Project description should maybe be updated. Right now it is "Gotta go fast", which is not bad at all from a coolness standpoint :) but it doesn't help people quickly understand what our software actually does.

Also, should we stop saying k6 is a "load testing tool" and instead label it as a tool for both functional and load testing?  If so, the project desc should say something like that, and the start of the README should also be updated to reflect that. Right now the README says "Load Impact's next-generation load generator", which is even more limited than "load testing tool". k6 doesn't just generate load, it also takes measurements.

**Comment by uppfinnarn** [comment]
I'm gonna have a go at the README and documentation right away.

("gotta go fast" is an in-joke and isn't meant to actually be used anywhere lol)

**Comment by pnn** [comment]
it's good though

**Comment by uppfinnarn** [comment]
I'm so tempted to change it to "nyoom"

**Comment by pnn** [comment]
Please

**Comment by ragnarlonn** [comment]
Maybe we can change the whole README to "nyoom" on e.g. sundays at 4pm CET, and then revert to the boring but useful text an hour later?

Here is an article by a developer about writing, btw: https://www.robinwieruch.de/lessons-learned-on-writing-well/   The author is obviously a fantastically brilliant person because he agrees with me on the importance of using simple language (and yes, "nyoom" is simple!)

**Comment by uppfinnarn** [comment]
Do I sense disapproval of my excessive verbosity? Perhaps even animosity towards my lexical compositions?

(I'll see myself out.)

**Comment by ragnarlonn** [comment]
when inditing it is paramount to eschew intricate words, because incremented intricacy betokens decremented information dissemination
