### ISSUE TITLE
Broken links in getting started guide

### ISSUE THREAD

**Issue by martinfijal** [loadimpact/k6#90]
We have several broken links in the getting started guide.

https://github.com/loadimpact/k6/blob/master/tutorials/getting-started.md

**Comment by adr0sen** [comment]
@martinfijal , I clicked through all visible (3) links in the getting started guide, all worked for me. Can you shed some more light?

**Comment by martinfijal** [comment]
Search for "{@link" in the document and you'll find three that are not in the markdown format.

**Comment by uppfinnarn** [comment]
Ah, yeah, that's jsdoc syntax. Once we have hosted docs up (#44), we should add a README.md in that directory linking to it.
