### ISSUE TITLE
InfluxDB: Couldn't write stats

### ISSUE THREAD

**Issue by sampadrout** [loadimpact/k6#906]
I have installed grafana and influxdb using docker. K6 also running using the docker. I have a the following command running from my mac terminal. Its giving error that "InfluxDB: Couldn't write stats"
docker run -i loadimpact/k6 run --out influxdb=http://influxdb:8086/myinfluxdb - <checks.js

Please let me know if i typing the correct command. Thanks

**Comment by sri85** [comment]
Can we please check whether `http://influxdb:8086/myinfluxdb ` is reachable?

**Comment by sampadrout** [comment]
I have tried that and it's not accessible. But I did a docker-compose earlier.

**Comment by sri85** [comment]
I believe the URL should be `http://localhost:8086/myinfluxdb`, can we try this ?

**Comment by sri85** [comment]
Sorry i meant `docker run -i loadimpact/k6 run --out influxdb=http://localhost:8086/myinfluxdb - <checks.js`

**Comment by sampadrout** [comment]
Hi, it did work. Earlier it did throw some error while doing the docker-compose run. The alpine source was giving error and i have failed to notice that. Thanks @sri85 for such a quick help, Closing the issue
