### ISSUE TITLE
k6 output on Gitlab console

### ISSUE THREAD

**Issue by stanislavsobolev** [loadimpact/k6#912]
Hi guys,

I've faced next problem while running load tests on Gitlab using k6:
Test status is not being shown as progress bar, but each request sent to console output.

https://prnt.sc/mdonc8

This happens even if i don't use --out json=...
Is there any way not to show this verbose output in Gitlab console? 
I'm using version k6-v0.23.1

Thank you in advance

**Comment by MStoykov** [comment]
Hi, Have you tried the `--quiet` flag ? it still has some problems #782 but I am pretty sure it should work for you.

**Comment by stanislavsobolev** [comment]
@MStoykov thank you a lot for the help, that worked for me
