### ISSUE TITLE
Refactor collector registration

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#917]
Currently every adding of collector means that we need to touch https://github.com/loadimpact/k6/blob/9af59bc1ca2eee2f065a544c9400c08875c5d268/cmd/collectors.go#L58-L99 . This should probably be instead be done in the same way the standard sql package works.

**Comment by na--** [comment]
This is important, since it's probably the main issue preventing us from offering output plugins, now that xk6 is a thing.
