### ISSUE TITLE
Try golangci-lint

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#918]
There is an alternative to gometalinter - [golangci-lint](https://github.com/golangci/golangci-lint) which supposedly is much better in all aspect imaginable, we should probably try and see what the difference is

**Comment by na--** [comment]
gometalinter is actually deprecated, so we don't have a lot of choice but to switch to golangci-lint  https://github.com/alecthomas/gometalinter/issues/590

**Comment by na--** [comment]
Closed by https://github.com/loadimpact/k6/pull/943
I think we should leave gometalinter running in the circleci job for the next few weeks, just to see if there are any discrepancies between the two linters
