### ISSUE TITLE
User-friendly error when test name is not set in cloud execution

### ISSUE THREAD

**Issue by na--** [loadimpact/k6#923]
Cloud execution of tests via `k6 cloud` requires that the test's `name` is set. That can be done via the `ext.loadimpact.name` property in the script's exported `options` (or global JSON config), or via the `K6_CLOUD_NAME` environment variable. If none of those values are set, the script filename is used instead. 

But when passing test scripts via `stdin` (which is very common when using docker: `docker run -e K6_CLOUD_TOKEN="<my-cloud-token>" -i loadimpact/k6 cloud - <script.js`), k6 doesn't know the filename, and this results in confusing errors like `Unexpected HTTP error from https://ingest.loadimpact.com/v1/archive-upload: 422 Unprocessable Entity`.

We should validate that the script's `name` property is set in k6, before sending the archive bundle to the cloud, and emit a user-friendly error that suggests that users should set `K6_CLOUD_NAME` or `ext.loadimpact.name`

**Comment by robingustafsson** [comment]
We've fixed this issue at least two times in the past (https://github.com/loadimpact/k6/pull/214,  https://github.com/loadimpact/k6/pull/510), it's time for a test case 😄

I think we should have a default name when the script comes from stdin (if not we default to the filename), as we've had in the past, and at most warn/inform the user with a friendly message that they can set their own name by setting it in the JS options or using the env var (we can detect it in Insights and hint there as well).
