### ISSUE TITLE
Update README!

### ISSUE THREAD

**Issue by ragnarlonn** [loadimpact/k6#93]
...and in general we want a best-practise way of using images in the README (might be nice with e.g. a GIF animation in it, showing command-line usage of k6)

**Comment by pnn** [comment]
https://asciinema.org/ maybe?

**Comment by uppfinnarn** [comment]
Opinions on this? https://asciinema.org/a/5lpa1ik4bnquwh53igj7tp1e8

**Comment by ragnarlonn** [comment]
Animations are great, makes a repo look much more interesting.

**Comment by pnn** [comment]
some more points:
- the logo should be replacing the `k6` header
- a clear and concise description should follow (even people who are not familiar with load testing should understand it)
- the `install` section should be first up
- the general hierarchy should be like this:

```
k6
(ci badges?)
(description)
(small usage example)
-> installation
-> usage
->-> scripting etc.
->-> cli usage etc.
-> contributing
```

**Comment by pnn** [comment]
[some](https://github.com/sindresorhus/pageres) [inspiration](https://github.com/karan/joe)

**Comment by uppfinnarn** [comment]
#130

**Comment by ragnarlonn** [comment]
The only thing I don't like is that it promises new things we don't currently have (brew and apt packages). Introducing new, unfilled dependencies is something that complicates an issue and slows down the release process for new things or updates substantially. I would have updated the README with the current installation methods and then created two new issues for creating brew and apt packages. Each issue can then stand on its own feet, is easy to resolve, and there are no dependencies.

**Comment by uppfinnarn** [comment]
I'm gonna get on at least homebrew packaging before the presentations next week, gonna have a shot at Debian and Ubuntu too and see how much I remember from my days maintaining KCT packages for both.

**Comment by pnn** [comment]
from my experience creating a homebrew tap and a formula is a 20-minute effort, so it shouldn't be a problem

**Comment by uppfinnarn** [comment]
You can now do:

```bash
brew tap loadimpact/k6
brew install k6
```

Working on Ubuntu packages.

**Comment by ragnarlonn** [comment]
Suggest removing the reference to Debian packages (but adding a new issue about it), adding the build instructions again, at the end of the file, and then merging this (or add the build instructions in a separate BUILD.md or similar, and just point to it in the README).

**Comment by uppfinnarn** [comment]
Merged!
