### ISSUE TITLE
response.body string pick out and compare

### ISSUE THREAD

**Issue by xinxinzhao1212** [loadimpact/k6#931]
Hi,
  Now i can get the string of response.body , and now  i want to
1. Filter some string out 
2. compare the filtered string with a string.
How can i realize this feature ?

**Comment by xinxinzhao1212** [comment]
This is the response 
Response:
HTTP/1.1 200 OK
Content-Length: 52
Content-Type: application/json
Date: Thu, 28 Feb 2019 09:51:25 GMT
X-Devbind-Build: development
X-Devbind-Flavor: development
X-Devbind-Region: local
X-Devbind-Server: localhost
X-Devbind-Start-Time: 26 Feb 19 11:24 UTC

{
        "errCode": "000",
        "errMsg": "",
        "devices": []
}
and the body can get is 
{
        "errCode": "000",
        "errMsg": "",
        "devices": []
}
how can i get some of the string in the res.body ?
Thanks for your help.

**Comment by na--** [comment]
Take a look at the [`http.Response` k6 documentation](https://docs.k6.io/docs/response-k6http) about methods for handling the response. Specifically, the `resp.json()` method that will parse the response body as a JSON and return the result to you. And you can always use regular JavaScript to deal with the body, like string operations or regular expressions, or in your case, something like `JSON.parse(resp.body)` to parse the response JSON will also work.

The k6 github issues aren't the most appropriate place to ask k6 usage questions, they're mostly intended for bug reports or feature requests. You can instead ask for help in the community forums here: https://community.k6.io/
