### ISSUE TITLE
Change CI to run with 1.12 

### ISSUE THREAD

**Issue by MStoykov** [loadimpact/k6#938]
Maybe just add 1.12 for now as 1.10 is currently added and update the build after a week or two when 1.12 doesn't turn up to have any big issues ;)

**Comment by MStoykov** [comment]
Also update versions of 1.11.x and 1.10.x

**Comment by na--** [comment]
Closed by https://github.com/loadimpact/k6/pull/944? Or leave this open until the "main" tests are ran with 1.12?

**Comment by MStoykov** [comment]
let's leave it
