### ISSUE TITLE
Require Abort if no data found

### ISSUE THREAD

**Issue by RushDoshi** [loadimpact/k6#939]
Hi,

I would like to Abort the script execution.

For example:
```js
If ( testObjects.totalCount===0) {
//1. .......
//2. abort("No Data Found") ; 
//3. ...........
}
```

If i use abort in this case then it should abort the script Immediately regardless of duration whatever i have specified.

Currently i'm using fail but the script is getting executed till i specified the duration (which doesn't serve my purpose).

Could someone please get this implemented ?

Thanks,
Rushabh

**Comment by na--** [comment]
Closing this issue in favor of https://github.com/loadimpact/k6/issues/1001, since the new one is a bit more detailed and expanded.
