### ISSUE TITLE
Proposal to modify the `group` tag syntax.

### ISSUE THREAD

**Issue by ppcano** [loadimpact/k6#948]
The current syntax of the [system tag](https://docs.k6.io/docs/tags-and-groups#section-system-tags) `group` is not fully documented and its syntax may not be intuitive.

Given the following script:

```js
import http from "k6/http";
import { check, group } from "k6";


export default function() {
 group("mainGroup", function() {
   http.get("https://loadimpact.com");

   group("nestedGroup", function() {
     http.get("https://test.loadimpact.com");
   });
 });
};
```

It will generate tags like:
```json
{"type":"Point","tags":{"group":"::mainGroup"}},"metric":"http_reqs"...}
{"type":"Point","tags":{"group":"::mainGroup::nestedGroup"}},"metric":"http_reqs"...}

{"type":"Point", "tags":{"group":"::mainGroup"}},"metric":"group_duration"...}
{"type":"Point", "tags":{"group":"::mainGroup::nestedGroup"}},"metric":"group_duration"...}

```

The current syntax is that `group tags` are always prepended with `::`. A `threshold` on a non-nested group must be configured: 

```js
export let options = {
  thresholds: {
    "group_duration{group:::mainGroup}": ["p(95)<1000"],
  }
}
```
The syntax of 👆 is not intuitive. I think `::` is a good symbol for referencing a nested group, but the first group may not be perceived as a nested group.

My proposal is to remove `::` from non-nested groups, then users could define thresholds as:

```js
export let options = {
  thresholds: {
    "group_duration{group:mainGroup}": ["p(95)<1000"],
    "group_duration{group:mainGroup::nestedGroup}": ["p(95)<1000"],
  }
}
```

**Comment by na--** [comment]
Hmm while I don't like the `::` separator, I don't think we can change it now, it would be a major breaking change. Besides, we can fix the issue from the other side, by changing the threshold syntax so it's not depending on the colon for equality, i.e. get rid of `key:value` expressions. 

We want to do that for other reasons as well, the current submetric definition is quite inflexible. See https://github.com/loadimpact/k6/issues/1443 and https://github.com/loadimpact/k6/issues/1313 for more details. And whatever that syntax ends up being, if we have something like `group === "::mainGroup::nestedGroup"`, it looks much better than the current `:::` mess. So, I'll make a note in https://github.com/loadimpact/k6/issues/1443 about this, and I think we should close this issue and https://github.com/loadimpact/k6/pull/1119. @imiric @MStoykov, thoughts?

**Comment by MStoykov** [comment]
Yeah ... I don't think breaking this is good idea. So I guess at least making less strange in the thresholds is better

**Comment by na--** [comment]
Ok, closing this and the PR then.
