### ISSUE TITLE
Checks in setup() and teardown() are reported partially

### ISSUE THREAD

**Issue by idoberko2** [loadimpact/k6#949]
General background
===
I own a service which was designed for optimal write operations. Read operations are trickier, especially if there were many write operations since the last read operation. I try to test such a scenario using k6, as follows:
1. `POST` 100 commands using 10 vus and 100 iterations, check the response status for each (group `POST requests`)
2. `GET` once *after all `POST`s are done (group `GET request`)

Issue description
===
To accomplish the second part, I'm making the request in the `teardown` function and check the response status.

Expected result
===
1. Result set should be compiled of two groups:
1.1. `POST requests`: 100 checks
1.2. `GET requests`: 1 check
2. Total amount should be 101 checks

Actual results
===
1. Result set contains only the first group, 100 checks
2. Total amount is 101 checks (correct)
![image](https://user-images.githubusercontent.com/6158608/54217830-0569b200-44f5-11e9-8118-1a2a0294839d.png)

**Comment by na--** [comment]
Thanks for reporting this, I confirmed that this is an issue for both `setup()` and `teardown()` with this script:
```js
import { group, check } from "k6";

export function setup() {
    group("setup-code", () => {
        console.log(`setup()`);
        check(true, {
            "setup-condition": (t) => t,
        });
    })
}

export default function () {
    group("default-code", () => {
        console.log(`${__VU}-${__ITER}-default`);
        check(true, {
            "default-condition": (t) => t,
        });
    })
}

export function teardown() {
    group("teardown-code", () => {
        console.log(`teardown()`);
        check(true, {
            "teardown-condition": (t) => t,
        });
    })
}
```

The summary at the end of the test shows:
```
   █ default-code

      ✓ default-condition

    checks...............: 100.00% ✓ 3   ✗ 0  

```

I think the reason may be because we tack on a `setup` and `teardown` group tag to all metrics emitted in `setup()` and `teardown()` respectively. If I filter the relevant metrics from running the above script with `--output json`, I get:
```
{"type":"Point","data":{"time":"...","value":1,"tags":{"check":"setup-condition","group":"::setup::setup-code"}},"metric":"checks"}
{"type":"Point","data":{"time":"...","value":0.069066,"tags":{"group":"::setup::setup-code"}},"metric":"group_duration"}
{"type":"Point","data":{"time":"...","value":1,"tags":{"check":"default-condition","group":"::default-code"}},"metric":"checks"}
{"type":"Point","data":{"time":"...","value":1,"tags":{"check":"teardown-condition","group":"::teardown::teardown-code"}},"metric":"checks"}
{"type":"Point","data":{"time":"...","value":0.186506,"tags":{"group":"::teardown::teardown-code"}},"metric":"group_duration"}
{"type":"Point","data":{"time":"...","value":0.082601,"tags":{"group":"::default-code"}},"metric":"group_duration"}

```
