### ISSUE TITLE
Can not write results to an output file

### ISSUE THREAD

**Issue by yolinas** [loadimpact/k6#98]
Ran k6 with the output option: ```-o json=test/performance/report2.json```

Got an error that it can not write to the file:
![screenshot from 2017-02-01 15-37-41](https://cloud.githubusercontent.com/assets/4997360/22513727/ff6cb208-e894-11e6-9cf3-52df047e45d8.png)

A read-only file was created. Here is a copy of the file:

[report2.json.txt](https://github.com/loadimpact/k6/files/745327/report2.json.txt)

Am I missing something?
Thanks!

**Comment by ragnarlonn** [comment]
I think it is the deferred shutdown function in engine.Run() that causes this:// Process any leftover samples.
		e.processSamples(e.collect()...)
		collectorcancel()
		<-collectorch

		// Emit final metrics.
		e.emitMetrics()

**Comment by uppfinnarn** [comment]
I said so in person earlier, but please submit a PR!
