### ISSUE TITLE
Installation failure in Ubuntu 18.04.2

### ISSUE THREAD

**Issue by kkeranen** [loadimpact/k6#983]
This step fails:
`sudo apt-get install k6`
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package k6

The previous step was already  suspicious:
` sudo apt-get update`
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [560 kB]
Ign:6 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [747 kB]
Err:6 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
  File has unexpected size (746892 != 746900). Mirror sync in progress? [IP: 91.189.88.162 80]
  Hashes of expected file:
   - Filesize:746900 [weak]
   - SHA256:cf734a6c7f3bb76a843b8bf6aa9c7baf6a6b5976fda48e4e662a807cef17b6fa
   - SHA1:08d6ec30929444ef48fff6b68ea634d11b2db32a [weak]
   - MD5Sum:0a25596a554256ec294bae1ff75de068 [weak]
  Release file created at: Fri, 29 Mar 2019 07:54:22 +0000
Fetched 812 kB in 12s (67.8 kB/s)
Reading package lists... Done
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/universe/binary-amd64/Packages.xz  File has unexpected size (746892 != 746900). Mirror sync in progress? [IP: 91.189.88.162 80]
   Hashes of expected file:
    - Filesize:746900 [weak]
    - SHA256:cf734a6c7f3bb76a843b8bf6aa9c7baf6a6b5976fda48e4e662a807cef17b6fa
    - SHA1:08d6ec30929444ef48fff6b68ea634d11b2db32a [weak]
    - MD5Sum:0a25596a554256ec294bae1ff75de068 [weak]
   Release file created at: Fri, 29 Mar 2019 07:54:22 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by kkeranen** [comment]
Retrying to steps doesn't help:

`sudo apt-get update`
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [560 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [747 kB]
Fetched 836 kB in 6s (148 kB/s)
Reading package lists... Done

`sudo apt-get install k6`
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package k6

**Comment by MStoykov** [comment]
I just tried it in docker and after I install ca-certificates it worked 
```
root@d9534989cece:/# apt-get install k6
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package k6
root@d9534989cece:/# apt-get update
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Ign:4 https://dl.bintray.com/loadimpact/deb stable InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Get:6 https://dl.bintray.com/loadimpact/deb stable Release [1840 B]
Get:7 https://dl.bintray.com/loadimpact/deb stable Release.gpg [821 B]
Get:8 https://dl.bintray.com/loadimpact/deb stable/main amd64 Packages [747 B]
Fetched 3408 B in 1s (5505 B/s)
Reading package lists... Done
root@d9534989cece:/# apt-get install k6
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  k6
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 5388 kB of archives.
After this operation, 21.5 kB of additional disk space will be used.
Get:1 https://dl.bintray.com/loadimpact/deb stable/main amd64 k6 amd64 0.24.0 [5388 kB]
Fetched 5388 kB in 1s (4143 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package k6.
(Reading database ... 4685 files and directories currently installed.)
Preparing to unpack .../archives/k6_0.24.0_amd64.deb ...
Unpacking k6 (0.24.0) ...
Setting up k6 (0.24.0) ...
root@d9534989cece:/# k6 version
k6 v0.24.0
```
But I think you haven't added the k6 repo as per [the readme](https://github.com/loadimpact/k6#linux)

**Comment by kkeranen** [comment]
Yes, that was the problem. Thank you.
