### ISSUE TITLE
Har converter missing some requests

### ISSUE THREAD

**Issue by neerolyte** [loadimpact/k6#984]
I've been trying to convert a har file to a script. It's leaving out some requests and I'm not sure why.

I'm using the docker version of k6:

```
$ docker run -it --rm loadimpact/k6 version
k6 v0.24.0
```

Converting a saved har with:

```
$ docker run -it --rm -v "$PWD:/code" -w "/code" loadimpact/k6 convert matrix.labs.squiz.test.har > create-folder.js
```

it seems to mostly run ok, but the only critical `POST` request is missing.

In the har file the 4th request is a `POST` to `http://matrix.labs.squiz.test/_admin/?SQ_BACKEND_PAGE=main&backend_section=am&am_section=add_asset&parent_assetid=1&pos=-1&type_code=folder&link_type=1&asset_ei_screen=details&sq_link_path=&sq_asset_path=`, in the `create-folder.js` script that request doesn't exist.

Files (as gzip because GitHub didn't allow the native extensions):
 * [matrix.labs.squiz.test.har.gz](https://github.com/loadimpact/k6/files/3027488/matrix.labs.squiz.test.har.gz)
 * [create-folder.js.gz](https://github.com/loadimpact/k6/files/3027489/create-folder.js.gz)

**Comment by na--** [comment]
I think this is a duplicate of https://github.com/loadimpact/k6/issues/747 - we need to fix both the HAR converter, and the `multipart/form-data` handling in k6...

**Comment by neerolyte** [comment]
Ah I missed:

> Also, when I decided to see how the HAR converter deals with multipart/form-data, I saw that it just skips them, so we should fix that as well...

You're right, this is definitely a duplicate.

**Comment by na--** [comment]
Yes, that seems to be the case. Thank you for reporting this, and sorry that we haven't fixed the issue already... I've increased the priority of the old issue and we'll get to it very soon.
